% Produced by CVXGEN, 2013-04-23 22:25:31 -0400.
% CVXGEN is Copyright (C) 2006-2012 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2012 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
C = params.C;
Js = params.Js;
Lambda = params.Lambda;
N = params.N;
Q = params.Q;
Ws = params.Ws;
b = params.b;
c = params.c;
ps = params.ps;
rhoMin = params.rhoMin;
wRho = params.wRho;
z = params.z;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable vd(34, 1);
  variable rho(48, 1);

  minimize(quad_form(A*vd - b, C) + quad_form(Js*vd - ps, Ws) + wRho*quad_form(rho, eye(48)) + quad_form(vd, Lambda));
  subject to
    Q*rho == A*vd + c;
    N'*vd == z;
    rho >= rhoMin;
cvx_end
vars.rho = rho;
vars.vd = vd;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
