#ifndef __perception_msgs__msg__BlackFlyParameterPacket__idl__
#define __perception_msgs__msg__BlackFlyParameterPacket__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * Atlas specific message
       */
      @TypeCode(type="perception_msgs::msg::dds_::BlackFlyParameterPacket_")
      struct BlackFlyParameterPacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        boolean auto_exposure;
        boolean auto_gain;
        boolean auto_shutter;
        double exposure;
        double frame_rate;
        boolean from_ui;
        double gain;
        double shutter;
        @defaultValue(value=255)
        octet robot_side;
      };
    };
  };
};

#endif
