#ifndef __perception_msgs__msg__CenterposeNodeMessage__idl__
#define __perception_msgs__msg__CenterposeNodeMessage__idl__

#include "perception_msgs/msg/./DetectableSceneNodeMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * An perception scene node for an ArUco marker
       * The topic name identifies the node.
       */
      @TypeCode(type="perception_msgs::msg::dds_::CenterposeNodeMessage_")
      struct CenterposeNodeMessage
      {
        /**
         * The detectable scene node information
         */
        perception_msgs::msg::dds::DetectableSceneNodeMessage detectable_scene_node;
        boolean enable_tracking;
      };
    };
  };
};

#endif
