#ifndef __perception_msgs__msg__ChunkedMapMessage__idl__
#define __perception_msgs__msg__ChunkedMapMessage__idl__

#include "perception_msgs/msg/./ChunkMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::ChunkedMapMessage_")
      struct ChunkedMapMessage
      {
        /**
         * Contains all the chunks to created the map (chunked map)
         */
        sequence<perception_msgs::msg::dds::ChunkMessage> chunks;
      };
    };
  };
};

#endif
