#ifndef __perception_msgs__msg__ChunkMessage__idl__
#define __perception_msgs__msg__ChunkMessage__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::ChunkMessage_")
      struct ChunkMessage
      {
        /**
         * We have a hash to keep each chunk unique
         */
        long hash_code_of_chunk;
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * X coordinate of the center of the height map
         */
        float origin_x;
        /**
         * Y coordinate of the center of the height map
         */
        float origin_y;
        /**
         * Width of the height map in meters
         */
        float width_in_meters;
        /**
         * Cell size in meters of an individual cell
         */
        float cell_size_in_meters;
        /**
         * Cells per axis
         */
        long cells_per_axis;
        /**
         * List of heights, which correspond to the list of keys
         */
        sequence<octet, 20000> heights;
      };
    };
  };
};

#endif
