#ifndef __perception_msgs__msg__DetectableSceneObjectMessage__idl__
#define __perception_msgs__msg__DetectableSceneObjectMessage__idl__

#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A detectable perception scene object
       * The topic name identifies the object.
       */
      @TypeCode(type="perception_msgs::msg::dds_::DetectableSceneObjectMessage_")
      struct DetectableSceneObjectMessage
      {
        /**
         * The name of the scene object
         */
        string name;
        /**
         * Whether or not the object is currently detected
         */
        boolean detected;
        /**
         * Transform of the object's frame to world frame
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage transform_to_world;
      };
    };
  };
};

#endif
