#ifndef __perception_msgs__msg__DetectedDoorListMessage__idl__
#define __perception_msgs__msg__DetectedDoorListMessage__idl__

#include "perception_msgs/msg/./DetectedDoorMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::DetectedDoorListMessage_")
      struct DetectedDoorListMessage
      {
        /**
         * List of detected doors
         */
        sequence<perception_msgs::msg::dds::DetectedDoorMessage, 16> detected_doors;
      };
    };
  };
};

#endif
