#ifndef __perception_msgs__msg__DetectableSceneNodeMessage__idl__
#define __perception_msgs__msg__DetectableSceneNodeMessage__idl__

#include "perception_msgs/msg/./InstantDetectionMessage_.idl"
#include "perception_msgs/msg/./SceneNodeMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A detectable perception scene node
       * The topic name identifies the node.
       */
      @TypeCode(type="perception_msgs::msg::dds_::DetectableSceneNodeMessage_")
      struct DetectableSceneNodeMessage
      {
        /**
         * The base scene node information
         */
        perception_msgs::msg::dds::SceneNodeMessage scene_node;
        /**
         * Instant detection information
         */
        sequence<perception_msgs::msg::dds::InstantDetectionMessage, 15> latest_detections;
        /**
         * Whether or not the node is currently detected
         */
        boolean currently_detected;
      };
    };
  };
};

#endif
