#ifndef __perception_msgs__msg__DetectableSceneNodesMessage__idl__
#define __perception_msgs__msg__DetectableSceneNodesMessage__idl__

#include "perception_msgs/msg/./DetectableSceneNodeMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Gives the current state of the complete collection of detectable scene nodes.
       * Publishing all scene nodes in one messages can simplify synchronization and
       * reduce the complexity of logic in figuring out when nodes are currently under
       * consideration.
       */
      @TypeCode(type="perception_msgs::msg::dds_::DetectableSceneNodesMessage_")
      struct DetectableSceneNodesMessage
      {
        /**
         * The current state of the complete collection of detectable scene nodes
         */
        sequence<perception_msgs::msg::dds::DetectableSceneNodeMessage, 5000> detectable_scene_nodes;
      };
    };
  };
};

#endif
