#ifndef __perception_msgs__msg__DoorNodeMessage__idl__
#define __perception_msgs__msg__DoorNodeMessage__idl__

#include "geometry_msgs/msg/./Transform_.idl"
#include "perception_msgs/msg/./DetectableSceneNodeMessage_.idl"
#include "perception_msgs/msg/./DoorOpeningMechanismMessage_.idl"
#include "perception_msgs/msg/./DoorPanelMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::DoorNodeMessage_")
      struct DoorNodeMessage
      {
        /**
         * The base scene node information
         */
        perception_msgs::msg::dds::DetectableSceneNodeMessage detectable_scene_node;
        /**
         * The transform of the frame of the door corner (X points in the direction the door opens)
         */
        geometry_msgs::msg::dds::Transform door_corner_transform_to_world;
        /**
         * Whether the pose of the door frame is locked
         */
        boolean pose_locked;
        /**
         * The door panel
         */
        perception_msgs::msg::dds::DoorPanelMessage door_panel;
        /**
         * The door opening mechanisms
         */
        sequence<perception_msgs::msg::dds::DoorOpeningMechanismMessage> opening_mechanisms;
      };
    };
  };
};

#endif
