#ifndef __perception_msgs__msg__FisheyePacket__idl__
#define __perception_msgs__msg__FisheyePacket__idl__

#include "perception_msgs/msg/./VideoPacket_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::FisheyePacket_")
      struct FisheyePacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        perception_msgs::msg::dds::VideoPacket video_packet;
      };
    };
  };
};

#endif
