#ifndef __perception_msgs__msg__Float32MultiArrayHack__idl__
#define __perception_msgs__msg__Float32MultiArrayHack__idl__

#include "std_msgs/msg/./MultiArrayLayout_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This is a stupid copy of the Float32MultiArray message to get enough array elements
       * because ihmc-ros2-library defaults unbounded arrays to 100 elements.
       * TODO: jros2 Remove this message when we transition to jros2
       */
      @TypeCode(type="perception_msgs::msg::dds_::Float32MultiArrayHack_")
      struct Float32MultiArrayHack
      {
        /**
         * specification of data layout
         */
        std_msgs::msg::dds::MultiArrayLayout layout;
        /**
         * array of data
         */
        sequence<float, 512> data;
      };
    };
  };
};

#endif
