#ifndef __perception_msgs__msg__FoundationPoseResult__idl__
#define __perception_msgs__msg__FoundationPoseResult__idl__

#include "geometry_msgs/msg/./Pose_.idl"
#include "ihmc_common_msgs/msg/./InstantMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::FoundationPoseResult_")
      struct FoundationPoseResult
      {
        /**
         * Detection timestamp. Should be the acquisition time of the image used for detection
         */
        ihmc_common_msgs::msg::dds::InstantMessage timestamp;
        /**
         * ID of the detected object
         */
        string object_id;
        /**
         * Mesh file name of the object (to identify it's class)
         */
        string mesh_file;
        /**
         * Pose of the object
         */
        geometry_msgs::msg::dds::Pose object_pose;
      };
    };
  };
};

#endif
