#ifndef __perception_msgs__msg__FoundationPoseRequest__idl__
#define __perception_msgs__msg__FoundationPoseRequest__idl__

#include "sensor_msgs/msg/./Image_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::FoundationPoseRequest_")
      struct FoundationPoseRequest
      {
        /**
         * ID that will be assigned to the object
         */
        string object_id;
        /**
         * Name of the mesh file for the object
         */
        string mesh_file;
        /**
         * Color image containing the object
         */
        sensor_msgs::msg::dds::Image color;
        /**
         * Depth image containing the object
         */
        sensor_msgs::msg::dds::Image depth;
        /**
         * Mask of the object in the image
         */
        sensor_msgs::msg::dds::Image object_mask;
      };
    };
  };
};

#endif
