#ifndef __perception_msgs__msg__FoundationPoseNodeMessage__idl__
#define __perception_msgs__msg__FoundationPoseNodeMessage__idl__

#include "geometry_msgs/msg/./Pose_.idl"
#include "perception_msgs/msg/./DetectableSceneNodeMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * DetectableSceneNode for FoundationPose tracked objects
       */
      @TypeCode(type="perception_msgs::msg::dds_::FoundationPoseNodeMessage_")
      struct FoundationPoseNodeMessage
      {
        /**
         * DetectableSceneNode information
         */
        perception_msgs::msg::dds::DetectableSceneNodeMessage detectable_scene_node;
        /**
         * Object's pose estimated by FoundationPose
         */
        geometry_msgs::msg::dds::Pose object_pose;
      };
    };
  };
};

#endif
