#ifndef __perception_msgs__msg__GlobalMapCellEntry__idl__
#define __perception_msgs__msg__GlobalMapCellEntry__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::GlobalMapCellEntry_")
      struct GlobalMapCellEntry
      {
        long key;
        long x_index;
        long y_index;
        double cell_height;
        double resolution;
      };
    };
  };
};

#endif
