#ifndef __perception_msgs__msg__GlobalMapCellMap__idl__
#define __perception_msgs__msg__GlobalMapCellMap__idl__

#include "perception_msgs/msg/./GlobalMapCellEntry_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::GlobalMapCellMap_")
      struct GlobalMapCellMap
      {
        sequence<perception_msgs::msg::dds::GlobalMapCellEntry> global_map_cells;
      };
    };
  };
};

#endif
