#ifndef __perception_msgs__msg__HeatMapPacket__idl__
#define __perception_msgs__msg__HeatMapPacket__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::HeatMapPacket_")
      struct HeatMapPacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        sequence<float> data;
        long width;
        long height;
        string name;
      };
    };
  };
};

#endif
