#ifndef __perception_msgs__msg__HeightMapMessage__idl__
#define __perception_msgs__msg__HeightMapMessage__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height map module
       */
      @TypeCode(type="perception_msgs::msg::dds_::HeightMapMessage_")
      struct HeightMapMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long long sequence_id;
        /**
         * X coordinate of the center of the height map
         */
        double grid_center_x;
        /**
         * Y coordinate of the center of the height map
         */
        double grid_center_y;
        /**
         * Width of the height map in meters
         */
        double width_in_meters;
        /**
         * Cell size in meters of an individual cell
         */
        double cell_size_in_meters;
        /**
         * Cells per axis
         */
        long cells_per_axis;
        /**
         * List of heights, which correspond to the list of keys
         */
        sequence<octet, 255000> heights;
      };
    };
  };
};

#endif
