#ifndef __perception_msgs__msg__InstantDetectionMessage__idl__
#define __perception_msgs__msg__InstantDetectionMessage__idl__

#include "geometry_msgs/msg/./Point32_.idl"
#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Pose_.idl"
#include "ihmc_common_msgs/msg/./InstantMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Message representing an InstantDetection of any type.
       */
      @TypeCode(type="perception_msgs::msg::dds_::InstantDetectionMessage_")
      struct InstantDetectionMessage
      {
        /**
         * Standard InstantDetection fields:
         */
        string detected_object_class;
        string detected_object_name;
        double confidence;
        geometry_msgs::msg::dds::Pose object_pose;
        ihmc_common_msgs::msg::dds::InstantMessage detection_time;
        /**
         * YOLOv8InstantDetection fields:
         */
        sequence<geometry_msgs::msg::dds::Point32, 255> yolo_object_point_cloud;
        /**
         * CenterPoseInstantDetection fields:
         */
        geometry_msgs::msg::dds::Point center_pose_bounding_box_2d_vertices[8];
        geometry_msgs::msg::dds::Point center_pose_bounding_box_vertices[8];
      };
    };
  };
};

#endif
