#ifndef __perception_msgs__msg__MeshSelectorBatchResult__idl__
#define __perception_msgs__msg__MeshSelectorBatchResult__idl__

#include "perception_msgs/msg/./MeshSelectorBatchResultItem_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::MeshSelectorBatchResult_")
      struct MeshSelectorBatchResult
      {
        /**
         * Frame ID of the image
         */
        long long frame_id;
        /**
         * Array of Mesh Selector Batch Items
         */
        sequence<perception_msgs::msg::dds::MeshSelectorBatchResultItem> items;
      };
    };
  };
};

#endif
