#ifndef __perception_msgs__msg__MeshSelectorBatchItem__idl__
#define __perception_msgs__msg__MeshSelectorBatchItem__idl__

#include "sensor_msgs/msg/./Image_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::MeshSelectorBatchItem_")
      struct MeshSelectorBatchItem
      {
        /**
         * Category / class label from the detector
         */
        string category;
        /**
         * Tracking ID assigned by the detection tracker
         */
        long track_id;
        /**
         * Segmented RGB image corresponding to the detection
         */
        sensor_msgs::msg::dds::Image segmented_rgb;
      };
    };
  };
};

#endif
