#ifndef __perception_msgs__msg__NormalEstimationParametersMessage__idl__
#define __perception_msgs__msg__NormalEstimationParametersMessage__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC Robot Environment Awareness (REA) module.
       */
      @TypeCode(type="perception_msgs::msg::dds_::NormalEstimationParametersMessage_")
      struct NormalEstimationParametersMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=0.08)
        double search_radius;
        @defaultValue(value=0.02)
        double max_distance_from_plane;
        @defaultValue(value=0.5)
        double min_consensus_ratio;
        @defaultValue(value=0.75)
        double max_average_deviation_ratio;
        @defaultValue(value=1)
        long number_of_iterations;
        @defaultValue(value=True)
        boolean enable_least_squares_estimation;
        @defaultValue(value=True)
        boolean weight_by_number_of_hits;
      };
    };
  };
};

#endif
