#ifndef __perception_msgs__msg__PersistentDetectionMessage__idl__
#define __perception_msgs__msg__PersistentDetectionMessage__idl__

#include "ihmc_common_msgs/msg/./DurationMessage_.idl"
#include "perception_msgs/msg/./InstantDetectionMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::PersistentDetectionMessage_")
      struct PersistentDetectionMessage
      {
        /**
         * History
         */
        sequence<perception_msgs::msg::dds::InstantDetectionMessage, 31> detection_history;
        ihmc_common_msgs::msg::dds::DurationMessage history_duration;
        /**
         * First detections
         */
        perception_msgs::msg::dds::InstantDetectionMessage first_detection;
        /**
         * Stability thresholds
         */
        double stability_confidence_threshold;
        double stability_detection_frequency;
        boolean ready_for_destruction;
      };
    };
  };
};

#endif
