#ifndef __perception_msgs__msg__PointCloudWorldPacket__idl__
#define __perception_msgs__msg__PointCloudWorldPacket__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is obsolete
       */
      @TypeCode(type="perception_msgs::msg::dds_::PointCloudWorldPacket_")
      struct PointCloudWorldPacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        long long timestamp;
        sequence<float> ground_quad_tree_support;
        sequence<float> decaying_world_scan;
        float default_ground_height;
      };
    };
  };
};

#endif
