#ifndef __perception_msgs__msg__Point2DArray__idl__
#define __perception_msgs__msg__Point2DArray__idl__

#include "vision_msgs/msg/./Point2D_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::Point2DArray_")
      struct Point2DArray
      {
        /**
         * Array of 2D points
         */
        sequence<vision_msgs::msg::dds::Point2D> points;
      };
    };
  };
};

#endif
