#ifndef __perception_msgs__msg__RequestPlanarRegionsListMessage__idl__
#define __perception_msgs__msg__RequestPlanarRegionsListMessage__idl__

#include "ihmc_common_msgs/msg/./BoundingBox3DMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {
      const octet SINGLE_UPDATE =
      0;

      const octet CONTINUOUS_UPDATE =
      1;

      const octet STOP_UPDATE =
      2;

      const octet CLEAR =
      3;


      /**
       * This message is obsolete and will be removed in the near future.
       * This message is part of the IHMC robot environment awareness (REA) module.
       * Use this message to request new planar regions
       * @deprecated REA always publishes planar regions when running. To request REA to clear its internal state, see REAStateRequestMessage.
       */
      @TypeCode(type="perception_msgs::msg::dds_::RequestPlanarRegionsListMessage_")
      struct RequestPlanarRegionsListMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        octet planar_regions_request_type;
        ihmc_common_msgs::msg::dds::BoundingBox3DMessage bounding_box_in_world_for_request;
      };
    };
  };
};

#endif
