#ifndef __perception_msgs__msg__StreamData__idl__
#define __perception_msgs__msg__StreamData__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Quaternion_.idl"
#include "ihmc_common_msgs/msg/./InstantMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * THIS MESSAGE IS SENT OVER VIDEO STREAMS WITH SRT.
       * MAX SIZE IS 881 BYTES. DO NO EXCEED THAT SIZE
       */
      @TypeCode(type="perception_msgs::msg::dds_::StreamData_")
      struct StreamData
      {
        /**
         * Camera intrinsics
         */
        unsigned short image_width;
        unsigned short image_height;
        float fx;
        float fy;
        float cx;
        float cy;
        float depth_discretization;
        /**
         * Frame acquisition time
         */
        ihmc_common_msgs::msg::dds::InstantMessage acquisition_time;
        /**
         * Sensor pose
         */
        geometry_msgs::msg::dds::Point position;
        geometry_msgs::msg::dds::Quaternion orientation;
      };
    };
  };
};

#endif
