#ifndef __perception_msgs__msg__TerrainMapMessage__idl__
#define __perception_msgs__msg__TerrainMapMessage__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height map module
       */
      @TypeCode(type="perception_msgs::msg::dds_::TerrainMapMessage_")
      struct TerrainMapMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long long sequence_id;
        /**
         * X coordinate of the center of the height map
         */
        double grid_center_x;
        /**
         * Y coordinate of the center of the height map
         */
        double grid_center_y;
        /**
         * Width of the height map in meters
         */
        double width_in_meters;
        /**
         * Cell size in meters of an individual cell
         */
        double cell_size_in_meters;
        /**
         * Cells per axis
         */
        long cells_per_axis;
        /**
         * Height map in metric values
         */
        sequence<float, 255000> height_map;
        /**
         * Obstacle clearance score, on a 0 to 1 scale
         */
        sequence<float, 255000> obstacle_clearance_score;
        /**
         * Traversability score, on a 0 to 1 scale
         */
        sequence<float, 255000> traversability_score;
        /**
         * Classifying traversability according to SnapResult
         */
        sequence<octet, 255000> traversability_class;
        /**
         * The raw data for the snap normal x value, which are stored as chars.
         */
        sequence<octet, 255000> snapped_normal_x_data;
        /**
         * The raw data for the snap normal y value, which are stored as chars.
         */
        sequence<octet, 255000> snapped_normal_y_data;
        /**
         * The raw data for the snap normal z value, which are stored as chars.
         */
        sequence<octet, 255000> snapped_normal_z_data;
      };
    };
  };
};

#endif
