#ifndef __perception_msgs__msg__TerrainMapMessage__idl__
#define __perception_msgs__msg__TerrainMapMessage__idl__

#include "perception_msgs/msg/./HeightMapMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height map module
       */
      @TypeCode(type="perception_msgs::msg::dds_::TerrainMapMessage_")
      struct TerrainMapMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long long sequence_id;
        /**
         * Height map message
         */
        perception_msgs::msg::dds::HeightMapMessage height_map;
        /**
         * Traversability score, on a 0 to 1 scale
         */
        sequence<float, 255000> traversability_score;
        /**
         * Classifying traversability according to SnapResult
         */
        sequence<octet, 255000> traversability_class;
        /**
         * The raw data for the snap normal x value, which are stored as chars.
         */
        sequence<octet, 255000> snapped_normal_x_data;
        /**
         * The raw data for the snap normal y value, which are stored as chars.
         */
        sequence<octet, 255000> snapped_normal_y_data;
        /**
         * The raw data for the snap normal z value, which are stored as chars.
         */
        sequence<octet, 255000> snapped_normal_z_data;
      };
    };
  };
};

#endif
