#ifndef __perception_msgs__msg__YOLOv8ExecutorParameters__idl__
#define __perception_msgs__msg__YOLOv8ExecutorParameters__idl__

#include "ihmc_common_msgs/msg/./LatestModificationMessage_.idl"
#include "perception_msgs/msg/./YOLOv8ModelInfo_.idl"
#include "perception_msgs/msg/./YOLOv8ModelParameters_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Settings for the YOLOv8DetectionExecutor class
       */
      @TypeCode(type="perception_msgs::msg::dds_::YOLOv8ExecutorParameters_")
      struct YOLOv8ExecutorParameters
      {
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_timestamp_modifiable;
        /**
         * List of the available models
         */
        sequence<perception_msgs::msg::dds::YOLOv8ModelInfo, 16> available_yolo_models;
        /**
         * List of models to run
         */
        string model_to_run;
        /**
         * Settings for each model
         */
        perception_msgs::msg::dds::YOLOv8ModelParameters model_settings;
      };
    };
  };
};

#endif
