#ifndef __perception_msgs__msg__YOLOv8ModelParameters__idl__
#define __perception_msgs__msg__YOLOv8ModelParameters__idl__

#include "ihmc_common_msgs/msg/./LatestModificationMessage_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Settings for an individual YOLOv8 Model
       * Below are parameters not used directly by the YOLOv8Model class,
       * but related to the way we use the YOLO output.
       */
      @TypeCode(type="perception_msgs::msg::dds_::YOLOv8ModelParameters_")
      struct YOLOv8ModelParameters
      {
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_timestamp_modifiable;
        string model_name;
        /**
         * A boolean for each object class, whether its detections should be ignored
         */
        sequence<boolean, 96> ignored_object_classes;
        /**
         * Confidence thresholds, corresponding to each detectable object class
         */
        sequence<float, 96> confidence_thresholds;
        /**
         * Mask thresholds, corresponding to each detectable object class
         */
        sequence<float, 96> mask_thresholds;
        /**
         * Non-maximum suppression threshold
         */
        float non_maximum_suppression_threshold;
        /**
         * Radii used for mask erosion, corresponding to each detectable object class
         */
        sequence<unsigned short, 96> erosion_kernel_radii;
        /**
         * Thresholds for removing outlier points of segmented point cloud
         */
        sequence<float, 96> outlier_thresholds;
      };
    };
  };
};

#endif
