#ifndef __perception_msgs__msg__YOLOv8ModelInfo__idl__
#define __perception_msgs__msg__YOLOv8ModelInfo__idl__

module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Information about a YOLO model
       */
      @TypeCode(type="perception_msgs::msg::dds_::YOLOv8ModelInfo_")
      struct YOLOv8ModelInfo
      {
        /**
         * Model's name
         */
        string model_name;
        /**
         * Names of object classes the model can detect
         */
        sequence<string, 96> detectable_object_classes;
      };
    };
  };
};

#endif
