#ifndef __perception_msgs__msg__YOLOv8DetectionAnnotationInfo__idl__
#define __perception_msgs__msg__YOLOv8DetectionAnnotationInfo__idl__

#include "ihmc_common_msgs/msg/./InstantMessage_.idl"
#include "perception_msgs/msg/./Point2DArray_.idl"
#include "vision_msgs/msg/./BoundingBox2D_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Information used for annotating a single YOLOv8 detection
       */
      @TypeCode(type="perception_msgs::msg::dds_::YOLOv8DetectionAnnotationInfo_")
      struct YOLOv8DetectionAnnotationInfo
      {
        /**
         * Time the detection was made
         */
        ihmc_common_msgs::msg::dds::InstantMessage detection_instant;
        /**
         * Class of the detected object
         */
        string object_class;
        /**
         * Bounding box of the detection
         */
        vision_msgs::msg::dds::BoundingBox2D bounding_box;
        sequence<perception_msgs::msg::dds::Point2DArray> mask_polygons;
      };
    };
  };
};

#endif
