#ifndef __perception_msgs__msg__YOLOv8DoorNodeMessage__idl__
#define __perception_msgs__msg__YOLOv8DoorNodeMessage__idl__

#include "geometry_msgs/msg/./Point32_.idl"
module perception_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="perception_msgs::msg::dds_::YOLOv8DoorNodeMessage_")
      struct YOLOv8DoorNodeMessage
      {
        /**
         * TODO: Add door stuff
         */
        sequence<geometry_msgs::msg::dds::Point32, 5000> presumed_door_point_cloud;
      };
    };
  };
};

#endif
