package actionlib_tutorials;

public interface AveragingActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib_tutorials/AveragingActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nAveragingResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  actionlib_tutorials.AveragingResult getResult();
  void setResult(actionlib_tutorials.AveragingResult value);
}
