
uint8[] head

uint8 level_flag

uint8 frame_reserve

uint32[] sn

uint32[] version

uint16 bandwidth

unitree_go_msgs/IMUState imu_state

unitree_go_msgs/MotorState[] motor_state

unitree_go_msgs/BmsState bms_state

int16[] foot_force

int16[] foot_force_est

uint32 tick

uint8[] wireless_remote

uint8 bit_flag

float32 adc_reel

int8 temperature_ntc1

int8 temperature_ntc2

float32 power_v

float32 power_a

uint16[] fan_frequency

uint32 reserve

uint32 crc


