#ifndef __vision_msgs__msg__BoundingBox2DArray__idl__
#define __vision_msgs__msg__BoundingBox2DArray__idl__

#include "std_msgs/msg/./Header_.idl"
#include "vision_msgs/msg/./BoundingBox2D_.idl"
module vision_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="vision_msgs::msg::dds_::BoundingBox2DArray_")
      struct BoundingBox2DArray
      {
        std_msgs::msg::dds::Header header;
        sequence<vision_msgs::msg::dds::BoundingBox2D> boxes;
      };
    };
  };
};

#endif
