#ifndef __vision_msgs__msg__BoundingBox2D__idl__
#define __vision_msgs__msg__BoundingBox2D__idl__

#include "vision_msgs/msg/./Pose2D_.idl"
module vision_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A 2D bounding box that can be rotated about its center.
       * All dimensions are in pixels, but represented using floating-point
       * values to allow sub-pixel precision. If an exact pixel crop is required
       * for a rotated bounding box, it can be calculated using Bresenham's line
       * algorithm.
       */
      @TypeCode(type="vision_msgs::msg::dds_::BoundingBox2D_")
      struct BoundingBox2D
      {
        /**
         * The 2D position (in pixels) and orientation of the bounding box center.
         */
        vision_msgs::msg::dds::Pose2D center;
        /**
         * The total size (in pixels) of the bounding box surrounding the object relative
         * to the pose of its center.
         */
        double size_x;
        double size_y;
      };
    };
  };
};

#endif
