#ifndef __vision_msgs__msg__Detection2D__idl__
#define __vision_msgs__msg__Detection2D__idl__

#include "std_msgs/msg/./Header_.idl"
#include "vision_msgs/msg/./BoundingBox2D_.idl"
#include "vision_msgs/msg/./ObjectHypothesisWithPose_.idl"
module vision_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Defines a 2D detection result.
       * 
       * This is similar to a 2D classification, but includes position information,
       * allowing a classification result for a specific crop or image point to
       * to be located in the larger image.
       */
      @TypeCode(type="vision_msgs::msg::dds_::Detection2D_")
      struct Detection2D
      {
        std_msgs::msg::dds::Header header;
        /**
         * Class probabilities
         */
        sequence<vision_msgs::msg::dds::ObjectHypothesisWithPose> results;
        /**
         * 2D bounding box surrounding the object.
         */
        vision_msgs::msg::dds::BoundingBox2D bbox;
        /**
         * ID used for consistency across multiple detection messages. Detections
         * of the same object in different detection messages should have the same id.
         * This field may be empty.
         */
        string id;
      };
    };
  };
};

#endif
