#ifndef __vision_msgs__msg__Pose2D__idl__
#define __vision_msgs__msg__Pose2D__idl__

#include "vision_msgs/msg/./Point2D_.idl"
module vision_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Represents a 2D pose (coordinates and a radian rotation). Rotation is positive counterclockwise.
       */
      @TypeCode(type="vision_msgs::msg::dds_::Pose2D_")
      struct Pose2D
      {
        vision_msgs::msg::dds::Point2D position;
        double theta;
      };
    };
  };
};

#endif
