#ifndef __vision_msgs__msg__VisionClass__idl__
#define __vision_msgs__msg__VisionClass__idl__

module vision_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A key value pair that maps an integer class_id to a string class label
       * in computer vision systems.
       */
      @TypeCode(type="vision_msgs::msg::dds_::VisionClass_")
      struct VisionClass
      {
        /**
         * The int value that identifies the class.
         * Elements identified with 65535, the maximum uint16 value are assumed
         * to belong to the "UNLABELED" class. For vision pipelines using less
         * than 255 classes the "UNLABELED" is the maximum value in the uint8
         * range.
         */
        unsigned short class_id;
        /**
         * The name of the class represented by the class_id
         */
        string class_name;
      };
    };
  };
};

#endif
