package us.ihmc.exampleSimulations.agileHexapod;

import java.util.ArrayList;

import us.ihmc.yoVariables.variable.YoBoolean;
import us.ihmc.yoVariables.variable.YoDouble;

public class AgileHexapodControllerBase
{
   protected AgileHexapodRobot rob;

   // These are the variables that are automatically created when the robot is created:
   YoDouble t;
   
   YoBoolean gc_body1_slip, gc_body2_slip, gc_body3_slip, gc_body4_slip, gc_foot1_slip, gc_foot2_slip, gc_foot3_slip, gc_foot4_slip;
   YoBoolean gc_foot5_slip, gc_foot6_slip, gc_pend_end_slip;
   
   YoDouble q_x, q_y, q_z, qd_x, qd_y, qd_z, qdd_x, qdd_y, qdd_z, q_qs;
   YoDouble q_qx, q_qy, q_qz, qd_wx, qd_wy, qd_wz, qdd_wx, qdd_wy, qdd_wz;
   YoDouble gc_body1_x, gc_body1_y, gc_body1_z, gc_body1_dx, gc_body1_dy, gc_body1_dz, gc_body1_fx, gc_body1_fy, gc_body1_fz, gc_body1_px;
   YoDouble gc_body1_py, gc_body1_pz, gc_body1_tdx, gc_body1_tdy, gc_body1_tdz, gc_body1_fs;
   YoDouble gc_body2_x, gc_body2_y, gc_body2_z, gc_body2_dx, gc_body2_dy, gc_body2_dz, gc_body2_fx, gc_body2_fy, gc_body2_fz, gc_body2_px;
   YoDouble gc_body2_py, gc_body2_pz, gc_body2_tdx, gc_body2_tdy, gc_body2_tdz, gc_body2_fs;
   YoDouble gc_body3_x, gc_body3_y, gc_body3_z, gc_body3_dx, gc_body3_dy, gc_body3_dz, gc_body3_fx, gc_body3_fy, gc_body3_fz, gc_body3_px;
   YoDouble gc_body3_py, gc_body3_pz, gc_body3_tdx, gc_body3_tdy, gc_body3_tdz, gc_body3_fs;
   YoDouble gc_body4_x, gc_body4_y, gc_body4_z, gc_body4_dx, gc_body4_dy, gc_body4_dz, gc_body4_fx, gc_body4_fy, gc_body4_fz, gc_body4_px;
   YoDouble gc_body4_py, gc_body4_pz, gc_body4_tdx, gc_body4_tdy, gc_body4_tdz, gc_body4_fs;
   YoDouble q_hip1_z, qd_hip1_z, qdd_hip1_z, tau_hip1_z, tau_damp_hip1_z;
   YoDouble q_hip1_x, qd_hip1_x, qdd_hip1_x, tau_hip1_x, tau_damp_hip1_x;
   YoDouble q_knee1, qd_knee1, qdd_knee1, tau_knee1, tau_damp_knee1;
   YoDouble gc_foot1_x, gc_foot1_y, gc_foot1_z, gc_foot1_dx, gc_foot1_dy, gc_foot1_dz, gc_foot1_fx, gc_foot1_fy, gc_foot1_fz, gc_foot1_px;
   YoDouble gc_foot1_py, gc_foot1_pz, gc_foot1_tdx, gc_foot1_tdy, gc_foot1_tdz, gc_foot1_fs;
   YoDouble q_hip2_z, qd_hip2_z, qdd_hip2_z, tau_hip2_z, tau_damp_hip2_z;
   YoDouble q_hip2_x, qd_hip2_x, qdd_hip2_x, tau_hip2_x, tau_damp_hip2_x;
   YoDouble q_knee2, qd_knee2, qdd_knee2, tau_knee2, tau_damp_knee2;
   YoDouble gc_foot2_x, gc_foot2_y, gc_foot2_z, gc_foot2_dx, gc_foot2_dy, gc_foot2_dz, gc_foot2_fx, gc_foot2_fy, gc_foot2_fz, gc_foot2_px;
   YoDouble gc_foot2_py, gc_foot2_pz, gc_foot2_tdx, gc_foot2_tdy, gc_foot2_tdz, gc_foot2_fs;
   YoDouble q_hip3_z, qd_hip3_z, qdd_hip3_z, tau_hip3_z, tau_damp_hip3_z;
   YoDouble q_hip3_x, qd_hip3_x, qdd_hip3_x, tau_hip3_x, tau_damp_hip3_x;
   YoDouble q_knee3, qd_knee3, qdd_knee3, tau_knee3, tau_damp_knee3;
   YoDouble gc_foot3_x, gc_foot3_y, gc_foot3_z, gc_foot3_dx, gc_foot3_dy, gc_foot3_dz, gc_foot3_fx, gc_foot3_fy, gc_foot3_fz, gc_foot3_px;
   YoDouble gc_foot3_py, gc_foot3_pz, gc_foot3_tdx, gc_foot3_tdy, gc_foot3_tdz, gc_foot3_fs;
   YoDouble q_hip4_z, qd_hip4_z, qdd_hip4_z, tau_hip4_z, tau_damp_hip4_z;
   YoDouble q_hip4_x, qd_hip4_x, qdd_hip4_x, tau_hip4_x, tau_damp_hip4_x;
   YoDouble q_knee4, qd_knee4, qdd_knee4, tau_knee4, tau_damp_knee4;
   YoDouble gc_foot4_x, gc_foot4_y, gc_foot4_z, gc_foot4_dx, gc_foot4_dy, gc_foot4_dz, gc_foot4_fx, gc_foot4_fy, gc_foot4_fz, gc_foot4_px;
   YoDouble gc_foot4_py, gc_foot4_pz, gc_foot4_tdx, gc_foot4_tdy, gc_foot4_tdz, gc_foot4_fs;
   YoDouble q_hip5_z, qd_hip5_z, qdd_hip5_z, tau_hip5_z, tau_damp_hip5_z;
   YoDouble q_hip5_x, qd_hip5_x, qdd_hip5_x, tau_hip5_x, tau_damp_hip5_x;
   YoDouble q_knee5, qd_knee5, qdd_knee5, tau_knee5, tau_damp_knee5;
   YoDouble gc_foot5_x, gc_foot5_y, gc_foot5_z, gc_foot5_dx, gc_foot5_dy, gc_foot5_dz, gc_foot5_fx, gc_foot5_fy, gc_foot5_fz, gc_foot5_px;
   YoDouble gc_foot5_py, gc_foot5_pz, gc_foot5_tdx, gc_foot5_tdy, gc_foot5_tdz, gc_foot5_fs;
   YoDouble q_hip6_z, qd_hip6_z, qdd_hip6_z, tau_hip6_z, tau_damp_hip6_z;
   YoDouble q_hip6_x, qd_hip6_x, qdd_hip6_x, tau_hip6_x, tau_damp_hip6_x;
   YoDouble q_knee6, qd_knee6, qdd_knee6, tau_knee6, tau_damp_knee6;
   YoDouble gc_foot6_x, gc_foot6_y, gc_foot6_z, gc_foot6_dx, gc_foot6_dy, gc_foot6_dz, gc_foot6_fx, gc_foot6_fy, gc_foot6_fz, gc_foot6_px;
   YoDouble gc_foot6_py, gc_foot6_pz, gc_foot6_tdx, gc_foot6_tdy, gc_foot6_tdz, gc_foot6_fs;
   YoDouble q_pend1, qd_pend1, qdd_pend1, tau_pend1;
   YoDouble q_pend2, qd_pend2, qdd_pend2, tau_pend2;
   YoDouble gc_pend_end_x, gc_pend_end_y, gc_pend_end_z, gc_pend_end_dx, gc_pend_end_dy, gc_pend_end_dz, gc_pend_end_fx, gc_pend_end_fy, gc_pend_end_fz,
              gc_pend_end_px;
   YoDouble gc_pend_end_py, gc_pend_end_pz, gc_pend_end_tdx, gc_pend_end_tdy, gc_pend_end_tdz, gc_pend_end_fs;

   // User defined control variables will be placed in this ArrayList when they are registered:
   ArrayList<YoDouble> controlVars;

   public AgileHexapodControllerBase(AgileHexapodRobot rob)
   {
      this.rob = rob;

      // Get the variables that are stored with the robot:

      t = (YoDouble)rob.getVariable("t");

      q_x = (YoDouble)rob.getVariable("q_x");
      q_y = (YoDouble)rob.getVariable("q_y");
      q_z = (YoDouble)rob.getVariable("q_z");
      qd_x = (YoDouble)rob.getVariable("qd_x");
      qd_y = (YoDouble)rob.getVariable("qd_y");
      qd_z = (YoDouble)rob.getVariable("qd_z");
      qdd_x = (YoDouble)rob.getVariable("qdd_x");
      qdd_y = (YoDouble)rob.getVariable("qdd_y");
      qdd_z = (YoDouble)rob.getVariable("qdd_z");
      q_qs = (YoDouble)rob.getVariable("q_qs");
      q_qx = (YoDouble)rob.getVariable("q_qx");
      q_qy = (YoDouble)rob.getVariable("q_qy");
      q_qz = (YoDouble)rob.getVariable("q_qz");
      qd_wx = (YoDouble)rob.getVariable("qd_wx");
      qd_wy = (YoDouble)rob.getVariable("qd_wy");
      qd_wz = (YoDouble)rob.getVariable("qd_wz");
      qdd_wx = (YoDouble)rob.getVariable("qdd_wx");
      qdd_wy = (YoDouble)rob.getVariable("qdd_wy");
      qdd_wz = (YoDouble)rob.getVariable("qdd_wz");
      gc_body1_x = (YoDouble)rob.getVariable("gc_body1_x");
      gc_body1_y = (YoDouble)rob.getVariable("gc_body1_y");
      gc_body1_z = (YoDouble)rob.getVariable("gc_body1_z");
      gc_body1_dx = (YoDouble)rob.getVariable("gc_body1_dx");
      gc_body1_dy = (YoDouble)rob.getVariable("gc_body1_dy");
      gc_body1_dz = (YoDouble)rob.getVariable("gc_body1_dz");
      gc_body1_fx = (YoDouble)rob.getVariable("gc_body1_fx");
      gc_body1_fy = (YoDouble)rob.getVariable("gc_body1_fy");
      gc_body1_fz = (YoDouble)rob.getVariable("gc_body1_fz");
      gc_body1_px = (YoDouble)rob.getVariable("gc_body1_px");
      gc_body1_py = (YoDouble)rob.getVariable("gc_body1_py");
      gc_body1_pz = (YoDouble)rob.getVariable("gc_body1_pz");
      gc_body1_tdx = (YoDouble)rob.getVariable("gc_body1_tdx");
      gc_body1_tdy = (YoDouble)rob.getVariable("gc_body1_tdy");
      gc_body1_tdz = (YoDouble)rob.getVariable("gc_body1_tdz");
      gc_body1_fs = (YoDouble)rob.getVariable("gc_body1_fs");
      gc_body1_slip = (YoBoolean)rob.getVariable("gc_body1_slip");
      gc_body2_x = (YoDouble)rob.getVariable("gc_body2_x");
      gc_body2_y = (YoDouble)rob.getVariable("gc_body2_y");
      gc_body2_z = (YoDouble)rob.getVariable("gc_body2_z");
      gc_body2_dx = (YoDouble)rob.getVariable("gc_body2_dx");
      gc_body2_dy = (YoDouble)rob.getVariable("gc_body2_dy");
      gc_body2_dz = (YoDouble)rob.getVariable("gc_body2_dz");
      gc_body2_fx = (YoDouble)rob.getVariable("gc_body2_fx");
      gc_body2_fy = (YoDouble)rob.getVariable("gc_body2_fy");
      gc_body2_fz = (YoDouble)rob.getVariable("gc_body2_fz");
      gc_body2_px = (YoDouble)rob.getVariable("gc_body2_px");
      gc_body2_py = (YoDouble)rob.getVariable("gc_body2_py");
      gc_body2_pz = (YoDouble)rob.getVariable("gc_body2_pz");
      gc_body2_tdx = (YoDouble)rob.getVariable("gc_body2_tdx");
      gc_body2_tdy = (YoDouble)rob.getVariable("gc_body2_tdy");
      gc_body2_tdz = (YoDouble)rob.getVariable("gc_body2_tdz");
      gc_body2_fs = (YoDouble)rob.getVariable("gc_body2_fs");
      gc_body2_slip = (YoBoolean)rob.getVariable("gc_body2_slip");
      gc_body3_x = (YoDouble)rob.getVariable("gc_body3_x");
      gc_body3_y = (YoDouble)rob.getVariable("gc_body3_y");
      gc_body3_z = (YoDouble)rob.getVariable("gc_body3_z");
      gc_body3_dx = (YoDouble)rob.getVariable("gc_body3_dx");
      gc_body3_dy = (YoDouble)rob.getVariable("gc_body3_dy");
      gc_body3_dz = (YoDouble)rob.getVariable("gc_body3_dz");
      gc_body3_fx = (YoDouble)rob.getVariable("gc_body3_fx");
      gc_body3_fy = (YoDouble)rob.getVariable("gc_body3_fy");
      gc_body3_fz = (YoDouble)rob.getVariable("gc_body3_fz");
      gc_body3_px = (YoDouble)rob.getVariable("gc_body3_px");
      gc_body3_py = (YoDouble)rob.getVariable("gc_body3_py");
      gc_body3_pz = (YoDouble)rob.getVariable("gc_body3_pz");
      gc_body3_tdx = (YoDouble)rob.getVariable("gc_body3_tdx");
      gc_body3_tdy = (YoDouble)rob.getVariable("gc_body3_tdy");
      gc_body3_tdz = (YoDouble)rob.getVariable("gc_body3_tdz");
      gc_body3_fs = (YoDouble)rob.getVariable("gc_body3_fs");
      gc_body3_slip = (YoBoolean)rob.getVariable("gc_body3_slip");
      gc_body4_x = (YoDouble)rob.getVariable("gc_body4_x");
      gc_body4_y = (YoDouble)rob.getVariable("gc_body4_y");
      gc_body4_z = (YoDouble)rob.getVariable("gc_body4_z");
      gc_body4_dx = (YoDouble)rob.getVariable("gc_body4_dx");
      gc_body4_dy = (YoDouble)rob.getVariable("gc_body4_dy");
      gc_body4_dz = (YoDouble)rob.getVariable("gc_body4_dz");
      gc_body4_fx = (YoDouble)rob.getVariable("gc_body4_fx");
      gc_body4_fy = (YoDouble)rob.getVariable("gc_body4_fy");
      gc_body4_fz = (YoDouble)rob.getVariable("gc_body4_fz");
      gc_body4_px = (YoDouble)rob.getVariable("gc_body4_px");
      gc_body4_py = (YoDouble)rob.getVariable("gc_body4_py");
      gc_body4_pz = (YoDouble)rob.getVariable("gc_body4_pz");
      gc_body4_tdx = (YoDouble)rob.getVariable("gc_body4_tdx");
      gc_body4_tdy = (YoDouble)rob.getVariable("gc_body4_tdy");
      gc_body4_tdz = (YoDouble)rob.getVariable("gc_body4_tdz");
      gc_body4_fs = (YoDouble)rob.getVariable("gc_body4_fs");
      gc_body4_slip = (YoBoolean)rob.getVariable("gc_body4_slip");
      q_hip1_z = (YoDouble)rob.getVariable("q_hip1_z");
      qd_hip1_z = (YoDouble)rob.getVariable("qd_hip1_z");
      qdd_hip1_z = (YoDouble)rob.getVariable("qdd_hip1_z");
      tau_hip1_z = (YoDouble)rob.getVariable("tau_hip1_z");
      tau_damp_hip1_z = (YoDouble)rob.getVariable("tau_damp_hip1_z");
      q_hip1_x = (YoDouble)rob.getVariable("q_hip1_x");
      qd_hip1_x = (YoDouble)rob.getVariable("qd_hip1_x");
      qdd_hip1_x = (YoDouble)rob.getVariable("qdd_hip1_x");
      tau_hip1_x = (YoDouble)rob.getVariable("tau_hip1_x");
      tau_damp_hip1_x = (YoDouble)rob.getVariable("tau_damp_hip1_x");
      q_knee1 = (YoDouble)rob.getVariable("q_knee1");
      qd_knee1 = (YoDouble)rob.getVariable("qd_knee1");
      qdd_knee1 = (YoDouble)rob.getVariable("qdd_knee1");
      tau_knee1 = (YoDouble)rob.getVariable("tau_knee1");
      tau_damp_knee1 = (YoDouble)rob.getVariable("tau_damp_knee1");
      gc_foot1_x = (YoDouble)rob.getVariable("gc_foot1_x");
      gc_foot1_y = (YoDouble)rob.getVariable("gc_foot1_y");
      gc_foot1_z = (YoDouble)rob.getVariable("gc_foot1_z");
      gc_foot1_dx = (YoDouble)rob.getVariable("gc_foot1_dx");
      gc_foot1_dy = (YoDouble)rob.getVariable("gc_foot1_dy");
      gc_foot1_dz = (YoDouble)rob.getVariable("gc_foot1_dz");
      gc_foot1_fx = (YoDouble)rob.getVariable("gc_foot1_fx");
      gc_foot1_fy = (YoDouble)rob.getVariable("gc_foot1_fy");
      gc_foot1_fz = (YoDouble)rob.getVariable("gc_foot1_fz");
      gc_foot1_px = (YoDouble)rob.getVariable("gc_foot1_px");
      gc_foot1_py = (YoDouble)rob.getVariable("gc_foot1_py");
      gc_foot1_pz = (YoDouble)rob.getVariable("gc_foot1_pz");
      gc_foot1_tdx = (YoDouble)rob.getVariable("gc_foot1_tdx");
      gc_foot1_tdy = (YoDouble)rob.getVariable("gc_foot1_tdy");
      gc_foot1_tdz = (YoDouble)rob.getVariable("gc_foot1_tdz");
      gc_foot1_fs = (YoDouble)rob.getVariable("gc_foot1_fs");
      gc_foot1_slip = (YoBoolean)rob.getVariable("gc_foot1_slip");
      q_hip2_z = (YoDouble)rob.getVariable("q_hip2_z");
      qd_hip2_z = (YoDouble)rob.getVariable("qd_hip2_z");
      qdd_hip2_z = (YoDouble)rob.getVariable("qdd_hip2_z");
      tau_hip2_z = (YoDouble)rob.getVariable("tau_hip2_z");
      tau_damp_hip2_z = (YoDouble)rob.getVariable("tau_damp_hip2_z");
      q_hip2_x = (YoDouble)rob.getVariable("q_hip2_x");
      qd_hip2_x = (YoDouble)rob.getVariable("qd_hip2_x");
      qdd_hip2_x = (YoDouble)rob.getVariable("qdd_hip2_x");
      tau_hip2_x = (YoDouble)rob.getVariable("tau_hip2_x");
      tau_damp_hip2_x = (YoDouble)rob.getVariable("tau_damp_hip2_x");
      q_knee2 = (YoDouble)rob.getVariable("q_knee2");
      qd_knee2 = (YoDouble)rob.getVariable("qd_knee2");
      qdd_knee2 = (YoDouble)rob.getVariable("qdd_knee2");
      tau_knee2 = (YoDouble)rob.getVariable("tau_knee2");
      tau_damp_knee2 = (YoDouble)rob.getVariable("tau_damp_knee2");
      gc_foot2_x = (YoDouble)rob.getVariable("gc_foot2_x");
      gc_foot2_y = (YoDouble)rob.getVariable("gc_foot2_y");
      gc_foot2_z = (YoDouble)rob.getVariable("gc_foot2_z");
      gc_foot2_dx = (YoDouble)rob.getVariable("gc_foot2_dx");
      gc_foot2_dy = (YoDouble)rob.getVariable("gc_foot2_dy");
      gc_foot2_dz = (YoDouble)rob.getVariable("gc_foot2_dz");
      gc_foot2_fx = (YoDouble)rob.getVariable("gc_foot2_fx");
      gc_foot2_fy = (YoDouble)rob.getVariable("gc_foot2_fy");
      gc_foot2_fz = (YoDouble)rob.getVariable("gc_foot2_fz");
      gc_foot2_px = (YoDouble)rob.getVariable("gc_foot2_px");
      gc_foot2_py = (YoDouble)rob.getVariable("gc_foot2_py");
      gc_foot2_pz = (YoDouble)rob.getVariable("gc_foot2_pz");
      gc_foot2_tdx = (YoDouble)rob.getVariable("gc_foot2_tdx");
      gc_foot2_tdy = (YoDouble)rob.getVariable("gc_foot2_tdy");
      gc_foot2_tdz = (YoDouble)rob.getVariable("gc_foot2_tdz");
      gc_foot2_fs = (YoDouble)rob.getVariable("gc_foot2_fs");
      gc_foot2_slip = (YoBoolean)rob.getVariable("gc_foot2_slip");
      q_hip3_z = (YoDouble)rob.getVariable("q_hip3_z");
      qd_hip3_z = (YoDouble)rob.getVariable("qd_hip3_z");
      qdd_hip3_z = (YoDouble)rob.getVariable("qdd_hip3_z");
      tau_hip3_z = (YoDouble)rob.getVariable("tau_hip3_z");
      tau_damp_hip3_z = (YoDouble)rob.getVariable("tau_damp_hip3_z");
      q_hip3_x = (YoDouble)rob.getVariable("q_hip3_x");
      qd_hip3_x = (YoDouble)rob.getVariable("qd_hip3_x");
      qdd_hip3_x = (YoDouble)rob.getVariable("qdd_hip3_x");
      tau_hip3_x = (YoDouble)rob.getVariable("tau_hip3_x");
      tau_damp_hip3_x = (YoDouble)rob.getVariable("tau_damp_hip3_x");
      q_knee3 = (YoDouble)rob.getVariable("q_knee3");
      qd_knee3 = (YoDouble)rob.getVariable("qd_knee3");
      qdd_knee3 = (YoDouble)rob.getVariable("qdd_knee3");
      tau_knee3 = (YoDouble)rob.getVariable("tau_knee3");
      tau_damp_knee3 = (YoDouble)rob.getVariable("tau_damp_knee3");
      gc_foot3_x = (YoDouble)rob.getVariable("gc_foot3_x");
      gc_foot3_y = (YoDouble)rob.getVariable("gc_foot3_y");
      gc_foot3_z = (YoDouble)rob.getVariable("gc_foot3_z");
      gc_foot3_dx = (YoDouble)rob.getVariable("gc_foot3_dx");
      gc_foot3_dy = (YoDouble)rob.getVariable("gc_foot3_dy");
      gc_foot3_dz = (YoDouble)rob.getVariable("gc_foot3_dz");
      gc_foot3_fx = (YoDouble)rob.getVariable("gc_foot3_fx");
      gc_foot3_fy = (YoDouble)rob.getVariable("gc_foot3_fy");
      gc_foot3_fz = (YoDouble)rob.getVariable("gc_foot3_fz");
      gc_foot3_px = (YoDouble)rob.getVariable("gc_foot3_px");
      gc_foot3_py = (YoDouble)rob.getVariable("gc_foot3_py");
      gc_foot3_pz = (YoDouble)rob.getVariable("gc_foot3_pz");
      gc_foot3_tdx = (YoDouble)rob.getVariable("gc_foot3_tdx");
      gc_foot3_tdy = (YoDouble)rob.getVariable("gc_foot3_tdy");
      gc_foot3_tdz = (YoDouble)rob.getVariable("gc_foot3_tdz");
      gc_foot3_fs = (YoDouble)rob.getVariable("gc_foot3_fs");
      gc_foot3_slip = (YoBoolean)rob.getVariable("gc_foot3_slip");
      q_hip4_z = (YoDouble)rob.getVariable("q_hip4_z");
      qd_hip4_z = (YoDouble)rob.getVariable("qd_hip4_z");
      qdd_hip4_z = (YoDouble)rob.getVariable("qdd_hip4_z");
      tau_hip4_z = (YoDouble)rob.getVariable("tau_hip4_z");
      tau_damp_hip4_z = (YoDouble)rob.getVariable("tau_damp_hip4_z");
      q_hip4_x = (YoDouble)rob.getVariable("q_hip4_x");
      qd_hip4_x = (YoDouble)rob.getVariable("qd_hip4_x");
      qdd_hip4_x = (YoDouble)rob.getVariable("qdd_hip4_x");
      tau_hip4_x = (YoDouble)rob.getVariable("tau_hip4_x");
      tau_damp_hip4_x = (YoDouble)rob.getVariable("tau_damp_hip4_x");
      q_knee4 = (YoDouble)rob.getVariable("q_knee4");
      qd_knee4 = (YoDouble)rob.getVariable("qd_knee4");
      qdd_knee4 = (YoDouble)rob.getVariable("qdd_knee4");
      tau_knee4 = (YoDouble)rob.getVariable("tau_knee4");
      tau_damp_knee4 = (YoDouble)rob.getVariable("tau_damp_knee4");
      gc_foot4_x = (YoDouble)rob.getVariable("gc_foot4_x");
      gc_foot4_y = (YoDouble)rob.getVariable("gc_foot4_y");
      gc_foot4_z = (YoDouble)rob.getVariable("gc_foot4_z");
      gc_foot4_dx = (YoDouble)rob.getVariable("gc_foot4_dx");
      gc_foot4_dy = (YoDouble)rob.getVariable("gc_foot4_dy");
      gc_foot4_dz = (YoDouble)rob.getVariable("gc_foot4_dz");
      gc_foot4_fx = (YoDouble)rob.getVariable("gc_foot4_fx");
      gc_foot4_fy = (YoDouble)rob.getVariable("gc_foot4_fy");
      gc_foot4_fz = (YoDouble)rob.getVariable("gc_foot4_fz");
      gc_foot4_px = (YoDouble)rob.getVariable("gc_foot4_px");
      gc_foot4_py = (YoDouble)rob.getVariable("gc_foot4_py");
      gc_foot4_pz = (YoDouble)rob.getVariable("gc_foot4_pz");
      gc_foot4_tdx = (YoDouble)rob.getVariable("gc_foot4_tdx");
      gc_foot4_tdy = (YoDouble)rob.getVariable("gc_foot4_tdy");
      gc_foot4_tdz = (YoDouble)rob.getVariable("gc_foot4_tdz");
      gc_foot4_fs = (YoDouble)rob.getVariable("gc_foot4_fs");
      gc_foot4_slip = (YoBoolean)rob.getVariable("gc_foot4_slip");
      q_hip5_z = (YoDouble)rob.getVariable("q_hip5_z");
      qd_hip5_z = (YoDouble)rob.getVariable("qd_hip5_z");
      qdd_hip5_z = (YoDouble)rob.getVariable("qdd_hip5_z");
      tau_hip5_z = (YoDouble)rob.getVariable("tau_hip5_z");
      tau_damp_hip5_z = (YoDouble)rob.getVariable("tau_damp_hip5_z");
      q_hip5_x = (YoDouble)rob.getVariable("q_hip5_x");
      qd_hip5_x = (YoDouble)rob.getVariable("qd_hip5_x");
      qdd_hip5_x = (YoDouble)rob.getVariable("qdd_hip5_x");
      tau_hip5_x = (YoDouble)rob.getVariable("tau_hip5_x");
      tau_damp_hip5_x = (YoDouble)rob.getVariable("tau_damp_hip5_x");
      q_knee5 = (YoDouble)rob.getVariable("q_knee5");
      qd_knee5 = (YoDouble)rob.getVariable("qd_knee5");
      qdd_knee5 = (YoDouble)rob.getVariable("qdd_knee5");
      tau_knee5 = (YoDouble)rob.getVariable("tau_knee5");
      tau_damp_knee5 = (YoDouble)rob.getVariable("tau_damp_knee5");
      gc_foot5_x = (YoDouble)rob.getVariable("gc_foot5_x");
      gc_foot5_y = (YoDouble)rob.getVariable("gc_foot5_y");
      gc_foot5_z = (YoDouble)rob.getVariable("gc_foot5_z");
      gc_foot5_dx = (YoDouble)rob.getVariable("gc_foot5_dx");
      gc_foot5_dy = (YoDouble)rob.getVariable("gc_foot5_dy");
      gc_foot5_dz = (YoDouble)rob.getVariable("gc_foot5_dz");
      gc_foot5_fx = (YoDouble)rob.getVariable("gc_foot5_fx");
      gc_foot5_fy = (YoDouble)rob.getVariable("gc_foot5_fy");
      gc_foot5_fz = (YoDouble)rob.getVariable("gc_foot5_fz");
      gc_foot5_px = (YoDouble)rob.getVariable("gc_foot5_px");
      gc_foot5_py = (YoDouble)rob.getVariable("gc_foot5_py");
      gc_foot5_pz = (YoDouble)rob.getVariable("gc_foot5_pz");
      gc_foot5_tdx = (YoDouble)rob.getVariable("gc_foot5_tdx");
      gc_foot5_tdy = (YoDouble)rob.getVariable("gc_foot5_tdy");
      gc_foot5_tdz = (YoDouble)rob.getVariable("gc_foot5_tdz");
      gc_foot5_fs = (YoDouble)rob.getVariable("gc_foot5_fs");
      gc_foot5_slip = (YoBoolean)rob.getVariable("gc_foot5_slip");
      q_hip6_z = (YoDouble)rob.getVariable("q_hip6_z");
      qd_hip6_z = (YoDouble)rob.getVariable("qd_hip6_z");
      qdd_hip6_z = (YoDouble)rob.getVariable("qdd_hip6_z");
      tau_hip6_z = (YoDouble)rob.getVariable("tau_hip6_z");
      tau_damp_hip6_z = (YoDouble)rob.getVariable("tau_damp_hip6_z");
      q_hip6_x = (YoDouble)rob.getVariable("q_hip6_x");
      qd_hip6_x = (YoDouble)rob.getVariable("qd_hip6_x");
      qdd_hip6_x = (YoDouble)rob.getVariable("qdd_hip6_x");
      tau_hip6_x = (YoDouble)rob.getVariable("tau_hip6_x");
      tau_damp_hip6_x = (YoDouble)rob.getVariable("tau_damp_hip6_x");
      q_knee6 = (YoDouble)rob.getVariable("q_knee6");
      qd_knee6 = (YoDouble)rob.getVariable("qd_knee6");
      qdd_knee6 = (YoDouble)rob.getVariable("qdd_knee6");
      tau_knee6 = (YoDouble)rob.getVariable("tau_knee6");
      tau_damp_knee6 = (YoDouble)rob.getVariable("tau_damp_knee6");
      gc_foot6_x = (YoDouble)rob.getVariable("gc_foot6_x");
      gc_foot6_y = (YoDouble)rob.getVariable("gc_foot6_y");
      gc_foot6_z = (YoDouble)rob.getVariable("gc_foot6_z");
      gc_foot6_dx = (YoDouble)rob.getVariable("gc_foot6_dx");
      gc_foot6_dy = (YoDouble)rob.getVariable("gc_foot6_dy");
      gc_foot6_dz = (YoDouble)rob.getVariable("gc_foot6_dz");
      gc_foot6_fx = (YoDouble)rob.getVariable("gc_foot6_fx");
      gc_foot6_fy = (YoDouble)rob.getVariable("gc_foot6_fy");
      gc_foot6_fz = (YoDouble)rob.getVariable("gc_foot6_fz");
      gc_foot6_px = (YoDouble)rob.getVariable("gc_foot6_px");
      gc_foot6_py = (YoDouble)rob.getVariable("gc_foot6_py");
      gc_foot6_pz = (YoDouble)rob.getVariable("gc_foot6_pz");
      gc_foot6_tdx = (YoDouble)rob.getVariable("gc_foot6_tdx");
      gc_foot6_tdy = (YoDouble)rob.getVariable("gc_foot6_tdy");
      gc_foot6_tdz = (YoDouble)rob.getVariable("gc_foot6_tdz");
      gc_foot6_fs = (YoDouble)rob.getVariable("gc_foot6_fs");
      gc_foot6_slip = (YoBoolean)rob.getVariable("gc_foot6_slip");
      q_pend1 = (YoDouble)rob.getVariable("q_pend1");
      qd_pend1 = (YoDouble)rob.getVariable("qd_pend1");
      qdd_pend1 = (YoDouble)rob.getVariable("qdd_pend1");
      tau_pend1 = (YoDouble)rob.getVariable("tau_pend1");
      q_pend2 = (YoDouble)rob.getVariable("q_pend2");
      qd_pend2 = (YoDouble)rob.getVariable("qd_pend2");
      qdd_pend2 = (YoDouble)rob.getVariable("qdd_pend2");
      tau_pend2 = (YoDouble)rob.getVariable("tau_pend2");
      gc_pend_end_x = (YoDouble)rob.getVariable("gc_pend_end_x");
      gc_pend_end_y = (YoDouble)rob.getVariable("gc_pend_end_y");
      gc_pend_end_z = (YoDouble)rob.getVariable("gc_pend_end_z");
      gc_pend_end_dx = (YoDouble)rob.getVariable("gc_pend_end_dx");
      gc_pend_end_dy = (YoDouble)rob.getVariable("gc_pend_end_dy");
      gc_pend_end_dz = (YoDouble)rob.getVariable("gc_pend_end_dz");
      gc_pend_end_fx = (YoDouble)rob.getVariable("gc_pend_end_fx");
      gc_pend_end_fy = (YoDouble)rob.getVariable("gc_pend_end_fy");
      gc_pend_end_fz = (YoDouble)rob.getVariable("gc_pend_end_fz");
      gc_pend_end_px = (YoDouble)rob.getVariable("gc_pend_end_px");
      gc_pend_end_py = (YoDouble)rob.getVariable("gc_pend_end_py");
      gc_pend_end_pz = (YoDouble)rob.getVariable("gc_pend_end_pz");
      gc_pend_end_tdx = (YoDouble)rob.getVariable("gc_pend_end_tdx");
      gc_pend_end_tdy = (YoDouble)rob.getVariable("gc_pend_end_tdy");
      gc_pend_end_tdz = (YoDouble)rob.getVariable("gc_pend_end_tdz");
      gc_pend_end_fs = (YoDouble)rob.getVariable("gc_pend_end_fs");
      gc_pend_end_slip = (YoBoolean)rob.getVariable("gc_pend_end_slip");

   }
}
