/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body controller API.
This message commands the controller to move an arm in jointspace to the desired joint angles while going through the specified trajectory points.
<p>Source (controller_msgs/ArmTrajectoryMessage):
<pre>{@code
# This message is part of the IHMC whole-body controller API.
# This message commands the controller to move an arm in jointspace to the desired joint angles while going through the specified trajectory points.

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# When the robot is walking, restrictions on upper-body motion may be applied.
# To by-pass the safety check and force the execution of this message, set this field to true.
bool force_execution false

# Specifies the side of the robot that will execute the trajectory.
byte robot_side 255
# Trajectories for each joint.
# The indexing for the joints goes increasingly from the first shoulder joint to the last arm joint.
JointspaceTrajectoryMessage jointspace_trajectory}</pre>
*/
public class ArmTrajectoryMessage implements ROS2Message<ArmTrajectoryMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ArmTrajectoryMessage_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      When the robot is walking, restrictions on upper-body motion may be applied.
      To by-pass the safety check and force the execution of this message, set this field to true.
   */
   private boolean force_execution_;
   /**
      Specifies the side of the robot that will execute the trajectory.
   */
   private byte robot_side_;
   /**
      Trajectories for each joint.
      The indexing for the joints goes increasingly from the first shoulder joint to the last arm joint.
   */
   private final controller_msgs.JointspaceTrajectoryMessage jointspace_trajectory_;

   public ArmTrajectoryMessage()
   {
      force_execution_ = (boolean) false;
      robot_side_ = (byte) 255;
      jointspace_trajectory_ = new controller_msgs.JointspaceTrajectoryMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // force_execution_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += jointspace_trajectory_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(force_execution_);
      buffer.writeByte(robot_side_);
      jointspace_trajectory_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      force_execution_ = buffer.readBoolean();
      robot_side_ = buffer.readByte();
      jointspace_trajectory_.deserialize(buffer);

   }

   @Override
   public void set(ArmTrajectoryMessage from)
   {
      sequence_id_ = from.sequence_id_;
      force_execution_ = from.force_execution_;
      robot_side_ = from.robot_side_;
      jointspace_trajectory_.set(from.jointspace_trajectory_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getForceExecution()
   {
      return force_execution_;
   }

   public void setForceExecution(boolean force_execution_)
   {
      this.force_execution_ = force_execution_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public controller_msgs.JointspaceTrajectoryMessage getJointspaceTrajectory()
   {
      return jointspace_trajectory_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ArmTrajectoryMessage {");
      builder.append("ROBOT_SIDE_LEFT=");
      builder.append(ROBOT_SIDE_LEFT);
      builder.append("ROBOT_SIDE_RIGHT=");
      builder.append(ROBOT_SIDE_RIGHT);
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("force_execution_=");
      builder.append(force_execution_);
      builder.append("robot_side_=");
      builder.append(robot_side_);
      builder.append("jointspace_trajectory_=");
      builder.append(jointspace_trajectory_);

      builder.append("}");
      return builder.toString();
   }
}