/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (controller_msgs/BipedTimedStepMessage):
<pre>{@code
int8 ROBOT_SIDE_LEFT=0
int8 ROBOT_SIDE_RIGHT=1


uint32 sequence_id

float64 start_time
float64 end_time
float64 swing_height -1.0
# Specifies which foot will swing to reach the footstep.
byte robot_side 255
# Specifies the position of the footstep (sole frame) in world frame.
geometry_msgs/Point location
# Specifies the orientation of the footstep (sole frame) in world frame.
geometry_msgs/Quaternion orientation}</pre>
*/
public class BipedTimedStepMessage implements ROS2Message<BipedTimedStepMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::BipedTimedStepMessage_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   private int sequence_id_;
   private double start_time_;
   private double end_time_;
   private double swing_height_;
   /**
      Specifies which foot will swing to reach the footstep.
   */
   private byte robot_side_;
   /**
      Specifies the position of the footstep (sole frame) in world frame.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage location_;
   /**
      Specifies the orientation of the footstep (sole frame) in world frame.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage orientation_;

   public BipedTimedStepMessage()
   {
      swing_height_ = (double) -1.0;
      robot_side_ = (byte) 255;
      location_ = new us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage();
      orientation_ = new us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage();

   }

   public BipedTimedStepMessage(BipedTimedStepMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // start_time_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // end_time_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // swing_height_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += location_.calculateSizeBytes(currentAlignment);
      currentAlignment += orientation_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeInt(sequence_id_);
      buffer.writeDouble(start_time_);
      buffer.writeDouble(end_time_);
      buffer.writeDouble(swing_height_);
      buffer.writeByte(robot_side_);
      location_.serialize(buffer);
      orientation_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readInt();
      start_time_ = buffer.readDouble();
      end_time_ = buffer.readDouble();
      swing_height_ = buffer.readDouble();
      robot_side_ = buffer.readByte();
      location_.deserialize(buffer);
      orientation_.deserialize(buffer);

   }

   @Override
   public void set(BipedTimedStepMessage from)
   {
      sequence_id_ = from.sequence_id_;
      start_time_ = from.start_time_;
      end_time_ = from.end_time_;
      swing_height_ = from.swing_height_;
      robot_side_ = from.robot_side_;
      location_.set(from.location_);
      orientation_.set(from.orientation_);

   }

   public int getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(int sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getStartTime()
   {
      return start_time_;
   }

   public void setStartTime(double start_time_)
   {
      this.start_time_ = start_time_;
   }

   public double getEndTime()
   {
      return end_time_;
   }

   public void setEndTime(double end_time_)
   {
      this.end_time_ = end_time_;
   }

   public double getSwingHeight()
   {
      return swing_height_;
   }

   public void setSwingHeight(double swing_height_)
   {
      this.swing_height_ = swing_height_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage getLocation()
   {
      return location_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage getOrientation()
   {
      return orientation_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("BipedTimedStepMessage {");
      builder.append("ROBOT_SIDE_LEFT=");
      builder.append(ROBOT_SIDE_LEFT);
      builder.append("ROBOT_SIDE_RIGHT=");
      builder.append(ROBOT_SIDE_RIGHT);
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("start_time_=");
      builder.append(start_time_);
      builder.append("end_time_=");
      builder.append(end_time_);
      builder.append("swing_height_=");
      builder.append(swing_height_);
      builder.append("robot_side_=");
      builder.append(robot_side_);
      builder.append("location_=");
      builder.append(location_);
      builder.append("orientation_=");
      builder.append(orientation_);

      builder.append("}");
      return builder.toString();
   }
}