/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Input message to queue a sequence of goals for the PDVelocityBasedGoalReacher.
Each waypoint is consumed in order; the hold_position flag of the last waypoint
determines whether the robot holds position at the final goal.
<p>Source (controller_msgs/ControllerWaypointGoalListMessage):
<pre>{@code
# Input message to queue a sequence of goals for the PDVelocityBasedGoalReacher.
# Each waypoint is consumed in order; the hold_position flag of the last waypoint
# determines whether the robot holds position at the final goal.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Ordered list of goals to execute in sequence.
ControllerWaypointGoalMessage[<=50] waypoints
}</pre>
*/
public class ControllerWaypointGoalListMessage implements ROS2Message<ControllerWaypointGoalListMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ControllerWaypointGoalListMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Ordered list of goals to execute in sequence.
   */
   private final IDLObjectSequence<controller_msgs.ControllerWaypointGoalMessage> waypoints_;

   public ControllerWaypointGoalListMessage()
   {
      waypoints_ = new IDLObjectSequence<controller_msgs.ControllerWaypointGoalMessage>(0, 50, controller_msgs.ControllerWaypointGoalMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += waypoints_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      waypoints_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      waypoints_.deserialize(buffer);

   }

   @Override
   public void set(ControllerWaypointGoalListMessage from)
   {
      sequence_id_ = from.sequence_id_;
      waypoints_.set(from.waypoints_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLObjectSequence<controller_msgs.ControllerWaypointGoalMessage> getWaypoints()
   {
      return waypoints_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ControllerWaypointGoalListMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("waypoints_=");
      builder.append(waypoints_);

      builder.append("}");
      return builder.toString();
   }
}