/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Published by the PDVelocityBasedGoalReacher when it begins walking toward a waypoint
or when it reaches a waypoint.
<p>Source (controller_msgs/ControllerWaypointChangeStatusMessage):
<pre>{@code
# Published by the PDVelocityBasedGoalReacher when it begins walking toward a waypoint
# or when it reaches a waypoint.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# The waypoint goal pose associated with this event.
ControllerWaypointStatusMessage waypoint

# Number of waypoints remaining in the queue after this event (not counting the waypoint
# described by this message).
int32 waypoints_remaining

# True if the robot just started walking toward this waypoint.
# False if the robot just reached this waypoint.
bool is_started false
}</pre>
*/
public class ControllerWaypointChangeStatusMessage implements ROS2Message<ControllerWaypointChangeStatusMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::ControllerWaypointChangeStatusMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      The waypoint goal pose associated with this event.
   */
   private final controller_msgs.ControllerWaypointStatusMessage waypoint_;
   /**
      Number of waypoints remaining in the queue after this event (not counting the waypoint
      described by this message).
   */
   private int waypoints_remaining_;
   /**
      True if the robot just started walking toward this waypoint.
      False if the robot just reached this waypoint.
   */
   private boolean is_started_;

   public ControllerWaypointChangeStatusMessage()
   {
      waypoint_ = new controller_msgs.ControllerWaypointStatusMessage();
      is_started_ = (boolean) false;

   }

   public ControllerWaypointChangeStatusMessage(ControllerWaypointChangeStatusMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += waypoint_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // waypoints_remaining_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_started_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      waypoint_.serialize(buffer);
      buffer.writeInt(waypoints_remaining_);
      buffer.writeBoolean(is_started_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      waypoint_.deserialize(buffer);
      waypoints_remaining_ = buffer.readInt();
      is_started_ = buffer.readBoolean();

   }

   @Override
   public void set(ControllerWaypointChangeStatusMessage from)
   {
      sequence_id_ = from.sequence_id_;
      waypoint_.set(from.waypoint_);
      waypoints_remaining_ = from.waypoints_remaining_;
      is_started_ = from.is_started_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public controller_msgs.ControllerWaypointStatusMessage getWaypoint()
   {
      return waypoint_;
   }

   public int getWaypointsRemaining()
   {
      return waypoints_remaining_;
   }

   public void setWaypointsRemaining(int waypoints_remaining_)
   {
      this.waypoints_remaining_ = waypoints_remaining_;
   }

   public boolean getIsStarted()
   {
      return is_started_;
   }

   public void setIsStarted(boolean is_started_)
   {
      this.is_started_ = is_started_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ControllerWaypointChangeStatusMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("waypoint_=");
      builder.append(waypoint_);
      builder.append("waypoints_remaining_=");
      builder.append(waypoints_remaining_);
      builder.append("is_started_=");
      builder.append(is_started_);

      builder.append("}");
      return builder.toString();
   }
}