/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message contains the control behavior for Directional Control.
<p>Source (controller_msgs/DirectionalControlConfigurationMessage):
<pre>{@code
# This message contains the control behavior for Directional Control.

uint64 sequence_id

# Set to true to cause the robot to walk. Setting this to false will cause the robot to stop walking. 
# However, the robot will still finish the current step.
bool enable_walking false

# Specify the profile name to use. Profiles contain definitions of walking and stepping
# parameters that modify how aggressive or conservative steps will be.
# Assuming it exists, directional control will be initialized with the "default" profile.
# If this field is left empty, no alteration will be made to the profile.
# By default, profiles are stored in the directory ~/.ihmc/joystick_step_app and are
# in .ini format. 
# For more details, see UserProfileManager and JoystickStepParameters.  
string profile_name ""}</pre>
*/
public class DirectionalControlConfigurationMessage implements ROS2Message<DirectionalControlConfigurationMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::DirectionalControlConfigurationMessage_";

   private long sequence_id_;
   /**
      Set to true to cause the robot to walk. Setting this to false will cause the robot to stop walking.
      However, the robot will still finish the current step.
   */
   private boolean enable_walking_;
   /**
      Specify the profile name to use. Profiles contain definitions of walking and stepping
      parameters that modify how aggressive or conservative steps will be.
      Assuming it exists, directional control will be initialized with the "default" profile.
      If this field is left empty, no alteration will be made to the profile.
      By default, profiles are stored in the directory ~/.ihmc/joystick_step_app and are
      in .ini format.
      For more details, see UserProfileManager and JoystickStepParameters.
   */
   private final StringBuilder profile_name_;

   public DirectionalControlConfigurationMessage()
   {
      enable_walking_ = (boolean) false;
      profile_name_ = new StringBuilder("");

   }

   public DirectionalControlConfigurationMessage(DirectionalControlConfigurationMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // enable_walking_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * profile_name_.length()) + 1; // profile_name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(enable_walking_);
      buffer.writeString(profile_name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      enable_walking_ = buffer.readBoolean();
      buffer.readString(profile_name_);

   }

   @Override
   public void set(DirectionalControlConfigurationMessage from)
   {
      sequence_id_ = from.sequence_id_;
      enable_walking_ = from.enable_walking_;
      profile_name_.delete(0, profile_name_.length());
      profile_name_.insert(0, from.profile_name_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getEnableWalking()
   {
      return enable_walking_;
   }

   public void setEnableWalking(boolean enable_walking_)
   {
      this.enable_walking_ = enable_walking_;
   }

   public StringBuilder getProfileName()
   {
      return profile_name_;
   }

   public java.lang.String getProfileNameAsString()
   {
      return profile_name_.toString();
   }

   public void setProfileName(java.lang.String s)
   {
      this.profile_name_.delete(0, this.profile_name_.length());
      this.profile_name_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("DirectionalControlConfigurationMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("enable_walking_=");
      builder.append(enable_walking_);
      builder.append("profile_name_=");
      builder.append(profile_name_.toString());

      builder.append("}");
      return builder.toString();
   }
}