/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A message for allowing operator to observe the status of various startup/shutdown variables often required for robot operation
<p>Source (controller_msgs/EStopMasterGainStatusMessage):
<pre>{@code
# A message for allowing operator to observe the status of various startup/shutdown variables often required for robot operation

# Current startup status
bool startup_complete
bool shutdown_complete

# Current SOFT-E-STOP value
bool is_estopped

# Is robot faulted
bool robot_is_faulted

# Is robot servod
bool robot_is_servod

# Is robot calibrated
bool robot_is_calibrated

# Is publishing ROS commands to robot enabled
bool publishing_to_robot_is_enabled

# Are the actuators enabled
bool actuators_are_enabled

# The current master gain
float64 current_master_gain
}</pre>
*/
public class EStopMasterGainStatusMessage implements ROS2Message<EStopMasterGainStatusMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::EStopMasterGainStatusMessage_";

   /**
      Current startup status
   */
   private boolean startup_complete_;
   private boolean shutdown_complete_;
   /**
      Current SOFT-E-STOP value
   */
   private boolean is_estopped_;
   /**
      Is robot faulted
   */
   private boolean robot_is_faulted_;
   /**
      Is robot servod
   */
   private boolean robot_is_servod_;
   /**
      Is robot calibrated
   */
   private boolean robot_is_calibrated_;
   /**
      Is publishing ROS commands to robot enabled
   */
   private boolean publishing_to_robot_is_enabled_;
   /**
      Are the actuators enabled
   */
   private boolean actuators_are_enabled_;
   /**
      The current master gain
   */
   private double current_master_gain_;

   public EStopMasterGainStatusMessage()
   {
      startup_complete_ = (boolean) false;
      shutdown_complete_ = (boolean) false;
      is_estopped_ = (boolean) false;
      robot_is_faulted_ = (boolean) false;
      robot_is_servod_ = (boolean) false;
      robot_is_calibrated_ = (boolean) false;
      publishing_to_robot_is_enabled_ = (boolean) false;
      actuators_are_enabled_ = (boolean) false;

   }

   public EStopMasterGainStatusMessage(EStopMasterGainStatusMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // startup_complete_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // shutdown_complete_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_estopped_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_is_faulted_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_is_servod_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_is_calibrated_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // publishing_to_robot_is_enabled_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // actuators_are_enabled_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // current_master_gain_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeBoolean(startup_complete_);
      buffer.writeBoolean(shutdown_complete_);
      buffer.writeBoolean(is_estopped_);
      buffer.writeBoolean(robot_is_faulted_);
      buffer.writeBoolean(robot_is_servod_);
      buffer.writeBoolean(robot_is_calibrated_);
      buffer.writeBoolean(publishing_to_robot_is_enabled_);
      buffer.writeBoolean(actuators_are_enabled_);
      buffer.writeDouble(current_master_gain_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      startup_complete_ = buffer.readBoolean();
      shutdown_complete_ = buffer.readBoolean();
      is_estopped_ = buffer.readBoolean();
      robot_is_faulted_ = buffer.readBoolean();
      robot_is_servod_ = buffer.readBoolean();
      robot_is_calibrated_ = buffer.readBoolean();
      publishing_to_robot_is_enabled_ = buffer.readBoolean();
      actuators_are_enabled_ = buffer.readBoolean();
      current_master_gain_ = buffer.readDouble();

   }

   @Override
   public void set(EStopMasterGainStatusMessage from)
   {
      startup_complete_ = from.startup_complete_;
      shutdown_complete_ = from.shutdown_complete_;
      is_estopped_ = from.is_estopped_;
      robot_is_faulted_ = from.robot_is_faulted_;
      robot_is_servod_ = from.robot_is_servod_;
      robot_is_calibrated_ = from.robot_is_calibrated_;
      publishing_to_robot_is_enabled_ = from.publishing_to_robot_is_enabled_;
      actuators_are_enabled_ = from.actuators_are_enabled_;
      current_master_gain_ = from.current_master_gain_;

   }

   public boolean getStartupComplete()
   {
      return startup_complete_;
   }

   public void setStartupComplete(boolean startup_complete_)
   {
      this.startup_complete_ = startup_complete_;
   }

   public boolean getShutdownComplete()
   {
      return shutdown_complete_;
   }

   public void setShutdownComplete(boolean shutdown_complete_)
   {
      this.shutdown_complete_ = shutdown_complete_;
   }

   public boolean getIsEstopped()
   {
      return is_estopped_;
   }

   public void setIsEstopped(boolean is_estopped_)
   {
      this.is_estopped_ = is_estopped_;
   }

   public boolean getRobotIsFaulted()
   {
      return robot_is_faulted_;
   }

   public void setRobotIsFaulted(boolean robot_is_faulted_)
   {
      this.robot_is_faulted_ = robot_is_faulted_;
   }

   public boolean getRobotIsServod()
   {
      return robot_is_servod_;
   }

   public void setRobotIsServod(boolean robot_is_servod_)
   {
      this.robot_is_servod_ = robot_is_servod_;
   }

   public boolean getRobotIsCalibrated()
   {
      return robot_is_calibrated_;
   }

   public void setRobotIsCalibrated(boolean robot_is_calibrated_)
   {
      this.robot_is_calibrated_ = robot_is_calibrated_;
   }

   public boolean getPublishingToRobotIsEnabled()
   {
      return publishing_to_robot_is_enabled_;
   }

   public void setPublishingToRobotIsEnabled(boolean publishing_to_robot_is_enabled_)
   {
      this.publishing_to_robot_is_enabled_ = publishing_to_robot_is_enabled_;
   }

   public boolean getActuatorsAreEnabled()
   {
      return actuators_are_enabled_;
   }

   public void setActuatorsAreEnabled(boolean actuators_are_enabled_)
   {
      this.actuators_are_enabled_ = actuators_are_enabled_;
   }

   public double getCurrentMasterGain()
   {
      return current_master_gain_;
   }

   public void setCurrentMasterGain(double current_master_gain_)
   {
      this.current_master_gain_ = current_master_gain_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("EStopMasterGainStatusMessage {");
      builder.append("startup_complete_=");
      builder.append(startup_complete_);
      builder.append("shutdown_complete_=");
      builder.append(shutdown_complete_);
      builder.append("is_estopped_=");
      builder.append(is_estopped_);
      builder.append("robot_is_faulted_=");
      builder.append(robot_is_faulted_);
      builder.append("robot_is_servod_=");
      builder.append(robot_is_servod_);
      builder.append("robot_is_calibrated_=");
      builder.append(robot_is_calibrated_);
      builder.append("publishing_to_robot_is_enabled_=");
      builder.append(publishing_to_robot_is_enabled_);
      builder.append("actuators_are_enabled_=");
      builder.append(actuators_are_enabled_);
      builder.append("current_master_gain_=");
      builder.append(current_master_gain_);

      builder.append("}");
      return builder.toString();
   }
}