/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body controller API.
This message gives the status of the current footstep from the controller as well as the position and orientation of the footstep in world coordinates.
<p>Source (controller_msgs/FootstepStatusMessage):
<pre>{@code
# This message is part of the IHMC whole-body controller API.
# This message gives the status of the current footstep from the controller as well as the position and orientation of the footstep in world coordinates.

byte FOOTSTEP_STATUS_STARTED = 0
byte FOOTSTEP_STATUS_COMPLETED = 1

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# The current footstep status enum value.
byte footstep_status 255
# footstep_index starts at 0 and monotonically increases with each completed footstep in a given FootstepDataListMessage.
int32 footstep_index
# The robot side (left or right) that this footstep status correlates to.
byte robot_side 255
# Specifies the desired position of the foot sent to the controller as opposed to where the foot actually landed.
geometry_msgs/Point desired_foot_position_in_world
# Specifies the desired orientation of the foot sent to the controller as opposed to where the foot actually landed.
geometry_msgs/Quaternion desired_foot_orientation_in_world
# Specifies the position of where the foot actually landed.
geometry_msgs/Point actual_foot_position_in_world
# Specifies the orientation of where the foot actually landed.
geometry_msgs/Quaternion actual_foot_orientation_in_world
# This is the swing duration of the step.
float64 swing_duration}</pre>
*/
public class FootstepStatusMessage implements ROS2Message<FootstepStatusMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::FootstepStatusMessage_";

   public static final byte FOOTSTEP_STATUS_STARTED = 0;
   public static final byte FOOTSTEP_STATUS_COMPLETED = 1;
   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      The current footstep status enum value.
   */
   private byte footstep_status_;
   /**
      footstep_index starts at 0 and monotonically increases with each completed footstep in a given FootstepDataListMessage.
   */
   private int footstep_index_;
   /**
      The robot side (left or right) that this footstep status correlates to.
   */
   private byte robot_side_;
   /**
      Specifies the desired position of the foot sent to the controller as opposed to where the foot actually landed.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage desired_foot_position_in_world_;
   /**
      Specifies the desired orientation of the foot sent to the controller as opposed to where the foot actually landed.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage desired_foot_orientation_in_world_;
   /**
      Specifies the position of where the foot actually landed.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage actual_foot_position_in_world_;
   /**
      Specifies the orientation of where the foot actually landed.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage actual_foot_orientation_in_world_;
   /**
      This is the swing duration of the step.
   */
   private double swing_duration_;

   public FootstepStatusMessage()
   {
      footstep_status_ = (byte) 255;
      robot_side_ = (byte) 255;
      desired_foot_position_in_world_ = new us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage();
      desired_foot_orientation_in_world_ = new us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage();
      actual_foot_position_in_world_ = new us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage();
      actual_foot_orientation_in_world_ = new us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage();

   }

   public FootstepStatusMessage(FootstepStatusMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // footstep_status_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // footstep_index_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += desired_foot_position_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_foot_orientation_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += actual_foot_position_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += actual_foot_orientation_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // swing_duration_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(footstep_status_);
      buffer.writeInt(footstep_index_);
      buffer.writeByte(robot_side_);
      desired_foot_position_in_world_.serialize(buffer);
      desired_foot_orientation_in_world_.serialize(buffer);
      actual_foot_position_in_world_.serialize(buffer);
      actual_foot_orientation_in_world_.serialize(buffer);
      buffer.writeDouble(swing_duration_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      footstep_status_ = buffer.readByte();
      footstep_index_ = buffer.readInt();
      robot_side_ = buffer.readByte();
      desired_foot_position_in_world_.deserialize(buffer);
      desired_foot_orientation_in_world_.deserialize(buffer);
      actual_foot_position_in_world_.deserialize(buffer);
      actual_foot_orientation_in_world_.deserialize(buffer);
      swing_duration_ = buffer.readDouble();

   }

   @Override
   public void set(FootstepStatusMessage from)
   {
      sequence_id_ = from.sequence_id_;
      footstep_status_ = from.footstep_status_;
      footstep_index_ = from.footstep_index_;
      robot_side_ = from.robot_side_;
      desired_foot_position_in_world_.set(from.desired_foot_position_in_world_);
      desired_foot_orientation_in_world_.set(from.desired_foot_orientation_in_world_);
      actual_foot_position_in_world_.set(from.actual_foot_position_in_world_);
      actual_foot_orientation_in_world_.set(from.actual_foot_orientation_in_world_);
      swing_duration_ = from.swing_duration_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getFootstepStatus()
   {
      return footstep_status_;
   }

   public void setFootstepStatus(byte footstep_status_)
   {
      this.footstep_status_ = footstep_status_;
   }

   public int getFootstepIndex()
   {
      return footstep_index_;
   }

   public void setFootstepIndex(int footstep_index_)
   {
      this.footstep_index_ = footstep_index_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage getDesiredFootPositionInWorld()
   {
      return desired_foot_position_in_world_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage getDesiredFootOrientationInWorld()
   {
      return desired_foot_orientation_in_world_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage getActualFootPositionInWorld()
   {
      return actual_foot_position_in_world_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage getActualFootOrientationInWorld()
   {
      return actual_foot_orientation_in_world_;
   }

   public double getSwingDuration()
   {
      return swing_duration_;
   }

   public void setSwingDuration(double swing_duration_)
   {
      this.swing_duration_ = swing_duration_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("FootstepStatusMessage {");
      builder.append("FOOTSTEP_STATUS_STARTED=");
      builder.append(FOOTSTEP_STATUS_STARTED);
      builder.append("FOOTSTEP_STATUS_COMPLETED=");
      builder.append(FOOTSTEP_STATUS_COMPLETED);
      builder.append("ROBOT_SIDE_LEFT=");
      builder.append(ROBOT_SIDE_LEFT);
      builder.append("ROBOT_SIDE_RIGHT=");
      builder.append(ROBOT_SIDE_RIGHT);
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("footstep_status_=");
      builder.append(footstep_status_);
      builder.append("footstep_index_=");
      builder.append(footstep_index_);
      builder.append("robot_side_=");
      builder.append(robot_side_);
      builder.append("desired_foot_position_in_world_=");
      builder.append(desired_foot_position_in_world_);
      builder.append("desired_foot_orientation_in_world_=");
      builder.append(desired_foot_orientation_in_world_);
      builder.append("actual_foot_position_in_world_=");
      builder.append(actual_foot_position_in_world_);
      builder.append("actual_foot_orientation_in_world_=");
      builder.append(actual_foot_orientation_in_world_);
      builder.append("swing_duration_=");
      builder.append(swing_duration_);

      builder.append("}");
      return builder.toString();
   }
}