/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Operator request to run an AvatarMimic recording on the robot controller.
The UI only sends this button command; replay itself runs on the robot.
<p>Source (controller_msgs/MimicManeuverCommandMessage):
<pre>{@code
# Operator request to run an AvatarMimic recording on the robot controller.
# The UI only sends this button command; replay itself runs on the robot.

byte ACTION_NONE = 0
byte ACTION_STAND_UP = 1
byte ACTION_LIE_DOWN = 2
byte ACTION_COVER = 3
byte ACTION_RECEIVE_TROWEL = 4
byte ACTION_DIG = 5
byte ACTION_DIG_MORE = 6
byte ACTION_GET_UP = 7
byte ACTION_CANCEL = 8
byte ACTION_PICKUP_BUCKET = 9
byte ACTION_DROP_BUCKET = 10

byte requested_action
bool execute
}</pre>
*/
public class MimicManeuverCommandMessage implements ROS2Message<MimicManeuverCommandMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MimicManeuverCommandMessage_";

   public static final byte ACTION_NONE = 0;
   public static final byte ACTION_STAND_UP = 1;
   public static final byte ACTION_LIE_DOWN = 2;
   public static final byte ACTION_COVER = 3;
   public static final byte ACTION_RECEIVE_TROWEL = 4;
   public static final byte ACTION_DIG = 5;
   public static final byte ACTION_DIG_MORE = 6;
   public static final byte ACTION_GET_UP = 7;
   public static final byte ACTION_CANCEL = 8;
   public static final byte ACTION_PICKUP_BUCKET = 9;
   public static final byte ACTION_DROP_BUCKET = 10;
   private byte requested_action_;
   private boolean execute_;

   public MimicManeuverCommandMessage()
   {
      execute_ = (boolean) false;

   }

   public MimicManeuverCommandMessage(MimicManeuverCommandMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // requested_action_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // execute_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(requested_action_);
      buffer.writeBoolean(execute_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      requested_action_ = buffer.readByte();
      execute_ = buffer.readBoolean();

   }

   @Override
   public void set(MimicManeuverCommandMessage from)
   {
      requested_action_ = from.requested_action_;
      execute_ = from.execute_;

   }

   public byte getRequestedAction()
   {
      return requested_action_;
   }

   public void setRequestedAction(byte requested_action_)
   {
      this.requested_action_ = requested_action_;
   }

   public boolean getExecute()
   {
      return execute_;
   }

   public void setExecute(boolean execute_)
   {
      this.execute_ = execute_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MimicManeuverCommandMessage {");
      builder.append("ACTION_NONE=");
      builder.append(ACTION_NONE);
      builder.append("ACTION_STAND_UP=");
      builder.append(ACTION_STAND_UP);
      builder.append("ACTION_LIE_DOWN=");
      builder.append(ACTION_LIE_DOWN);
      builder.append("ACTION_COVER=");
      builder.append(ACTION_COVER);
      builder.append("ACTION_RECEIVE_TROWEL=");
      builder.append(ACTION_RECEIVE_TROWEL);
      builder.append("ACTION_DIG=");
      builder.append(ACTION_DIG);
      builder.append("ACTION_DIG_MORE=");
      builder.append(ACTION_DIG_MORE);
      builder.append("ACTION_GET_UP=");
      builder.append(ACTION_GET_UP);
      builder.append("ACTION_CANCEL=");
      builder.append(ACTION_CANCEL);
      builder.append("ACTION_PICKUP_BUCKET=");
      builder.append(ACTION_PICKUP_BUCKET);
      builder.append("ACTION_DROP_BUCKET=");
      builder.append(ACTION_DROP_BUCKET);
      builder.append("requested_action_=");
      builder.append(requested_action_);
      builder.append("execute_=");
      builder.append(execute_);

      builder.append("}");
      return builder.toString();
   }
}