/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC multi-contact controller API.
Published by the IHMC controller, this message carries minimal information relative
to the balance status of the robot.
All the information here is expressed in the world frame.
<p>Source (controller_msgs/MultiContactBalanceStatus):
<pre>{@code
# This message is part of the IHMC multi-contact controller API.
# Published by the IHMC controller, this message carries minimal information relative
# to the balance status of the robot.
# All the information here is expressed in the world frame.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# This is the measured position in world of the robot's capture point. Only x and y coordinates are relevant.
geometry_msgs/Point capture_point_2d
# This is the measured position in world of the robot's center of mass.
geometry_msgs/Point center_of_mass_3d
# List of contact points in world-frame.
geometry_msgs/Point[<=16] contact_points_in_world
# (Optional) List of the contact surface normals in world frame. If provided these are used to solve generalized support region.
geometry_msgs/Vector3[<=16] surface_normals_in_world
# List of the rigid-bodies in contact. This list's size and ordering corresponds to contact_point_in_world and surface_normals_in_world.
int32[<=16] support_rigid_body_ids}</pre>
*/
public class MultiContactBalanceStatus implements ROS2Message<MultiContactBalanceStatus>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MultiContactBalanceStatus_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      This is the measured position in world of the robot's capture point. Only x and y coordinates are relevant.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage capture_point_2d_;
   /**
      This is the measured position in world of the robot's center of mass.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage center_of_mass_3d_;
   /**
      List of contact points in world-frame.
   */
   private final IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> contact_points_in_world_;
   /**
      (Optional) List of the contact surface normals in world frame. If provided these are used to solve generalized support region.
   */
   private final IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidVector3DMessage> surface_normals_in_world_;
   /**
      List of the rigid-bodies in contact. This list's size and ordering corresponds to contact_point_in_world and surface_normals_in_world.
   */
   private final IDLIntSequence support_rigid_body_ids_;

   public MultiContactBalanceStatus()
   {
      capture_point_2d_ = new us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage();
      center_of_mass_3d_ = new us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage();
      contact_points_in_world_ = new IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage>(0, 16, us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage.class);
      surface_normals_in_world_ = new IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidVector3DMessage>(0, 16, us.ihmc.euclid.jros2.messages.EuclidVector3DMessage.class);
      support_rigid_body_ids_ = new IDLIntSequence(0, 16);

   }

   public MultiContactBalanceStatus(MultiContactBalanceStatus from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += capture_point_2d_.calculateSizeBytes(currentAlignment);
      currentAlignment += center_of_mass_3d_.calculateSizeBytes(currentAlignment);
      currentAlignment += contact_points_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += surface_normals_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += support_rigid_body_ids_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      capture_point_2d_.serialize(buffer);
      center_of_mass_3d_.serialize(buffer);
      contact_points_in_world_.serialize(buffer);
      surface_normals_in_world_.serialize(buffer);
      support_rigid_body_ids_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      capture_point_2d_.deserialize(buffer);
      center_of_mass_3d_.deserialize(buffer);
      contact_points_in_world_.deserialize(buffer);
      surface_normals_in_world_.deserialize(buffer);
      support_rigid_body_ids_.deserialize(buffer);

   }

   @Override
   public void set(MultiContactBalanceStatus from)
   {
      sequence_id_ = from.sequence_id_;
      capture_point_2d_.set(from.capture_point_2d_);
      center_of_mass_3d_.set(from.center_of_mass_3d_);
      contact_points_in_world_.set(from.contact_points_in_world_);
      surface_normals_in_world_.set(from.surface_normals_in_world_);
      support_rigid_body_ids_.set(from.support_rigid_body_ids_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage getCapturePoint2d()
   {
      return capture_point_2d_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage getCenterOfMass3d()
   {
      return center_of_mass_3d_;
   }

   public IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> getContactPointsInWorld()
   {
      return contact_points_in_world_;
   }

   public IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidVector3DMessage> getSurfaceNormalsInWorld()
   {
      return surface_normals_in_world_;
   }

   public IDLIntSequence getSupportRigidBodyIds()
   {
      return support_rigid_body_ids_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MultiContactBalanceStatus {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("capture_point_2d_=");
      builder.append(capture_point_2d_);
      builder.append("center_of_mass_3d_=");
      builder.append(center_of_mass_3d_);
      builder.append("contact_points_in_world_=");
      builder.append(contact_points_in_world_);
      builder.append("surface_normals_in_world_=");
      builder.append(surface_normals_in_world_);
      builder.append("support_rigid_body_ids_=");
      builder.append(support_rigid_body_ids_);

      builder.append("}");
      return builder.toString();
   }
}