/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC multi-contact controller API.
<p>Source (controller_msgs/MultiContactTrajectoryStatus):
<pre>{@code
# This message is part of the IHMC multi-contact controller API.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte TRAJECTORY_STATUS_STARTED = 0
byte TRAJECTORY_STATUS_COMPLETED = 1

# Reports the status of the trajectory
byte trajectory_status 255
}</pre>
*/
public class MultiContactTrajectoryStatus implements ROS2Message<MultiContactTrajectoryStatus>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::MultiContactTrajectoryStatus_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   public static final byte TRAJECTORY_STATUS_STARTED = 0;
   public static final byte TRAJECTORY_STATUS_COMPLETED = 1;
   /**
      Reports the status of the trajectory
   */
   private byte trajectory_status_;

   public MultiContactTrajectoryStatus()
   {
      trajectory_status_ = (byte) 255;

   }

   public MultiContactTrajectoryStatus(MultiContactTrajectoryStatus from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // trajectory_status_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(trajectory_status_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      trajectory_status_ = buffer.readByte();

   }

   @Override
   public void set(MultiContactTrajectoryStatus from)
   {
      sequence_id_ = from.sequence_id_;
      trajectory_status_ = from.trajectory_status_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getTrajectoryStatus()
   {
      return trajectory_status_;
   }

   public void setTrajectoryStatus(byte trajectory_status_)
   {
      this.trajectory_status_ = trajectory_status_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MultiContactTrajectoryStatus {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("TRAJECTORY_STATUS_STARTED=");
      builder.append(TRAJECTORY_STATUS_STARTED);
      builder.append("TRAJECTORY_STATUS_COMPLETED=");
      builder.append(TRAJECTORY_STATUS_COMPLETED);
      builder.append("trajectory_status_=");
      builder.append(trajectory_status_);

      builder.append("}");
      return builder.toString();
   }
}