/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body controller API.
This message commands the controller to move in taskspace the pelvis to the desired pose (position & orientation) while going through the specified trajectory points.
A third order polynomial function is used to interpolate positions and a Hermite based curve (third order) is used to interpolate the orientations.
To excute a single straight line trajectory to reach a desired pelvis pose, set only one trajectory point with zero velocity and its time to be equal to the desired trajectory time.
Note that the pelvis position is limited keep the robot's balance (center of mass has to remain inside the support polygon).
<p>Source (controller_msgs/PelvisTrajectoryMessage):
<pre>{@code
# This message is part of the IHMC whole-body controller API.
# This message commands the controller to move in taskspace the pelvis to the desired pose (position & orientation) while going through the specified trajectory points.
# A third order polynomial function is used to interpolate positions and a Hermite based curve (third order) is used to interpolate the orientations.
# To excute a single straight line trajectory to reach a desired pelvis pose, set only one trajectory point with zero velocity and its time to be equal to the desired trajectory time.
# Note that the pelvis position is limited keep the robot's balance (center of mass has to remain inside the support polygon).

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# When the robot is walking, restrictions on upper-body motion may be applied.
# To by-pass the safety check and force the execution of this message, set this field to true.
bool force_execution false

# Execute this trajectory in user mode. User mode tries to achieve the desired regardless of the leg kinematics.
bool enable_user_pelvis_control false
# If enable_user_pelvis_control is true then enable_user_pelvis_control_during_walking
# will keep the manager in user mode while walking.
# If this is false the manager will switch back to controller mode when walking.
bool enable_user_pelvis_control_during_walking false
# The position/orientation trajectory information.
ihmc_common_msgs/SE3TrajectoryMessage se3_trajectory}</pre>
*/
public class PelvisTrajectoryMessage implements ROS2Message<PelvisTrajectoryMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::PelvisTrajectoryMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      When the robot is walking, restrictions on upper-body motion may be applied.
      To by-pass the safety check and force the execution of this message, set this field to true.
   */
   private boolean force_execution_;
   /**
      Execute this trajectory in user mode. User mode tries to achieve the desired regardless of the leg kinematics.
   */
   private boolean enable_user_pelvis_control_;
   /**
      If enable_user_pelvis_control is true then enable_user_pelvis_control_during_walking
      will keep the manager in user mode while walking.
      If this is false the manager will switch back to controller mode when walking.
   */
   private boolean enable_user_pelvis_control_during_walking_;
   /**
      The position/orientation trajectory information.
   */
   private final ihmc_common_msgs.SE3TrajectoryMessage se3_trajectory_;

   public PelvisTrajectoryMessage()
   {
      force_execution_ = (boolean) false;
      enable_user_pelvis_control_ = (boolean) false;
      enable_user_pelvis_control_during_walking_ = (boolean) false;
      se3_trajectory_ = new ihmc_common_msgs.SE3TrajectoryMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // force_execution_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // enable_user_pelvis_control_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // enable_user_pelvis_control_during_walking_
      currentAlignment += se3_trajectory_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(force_execution_);
      buffer.writeBoolean(enable_user_pelvis_control_);
      buffer.writeBoolean(enable_user_pelvis_control_during_walking_);
      se3_trajectory_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      force_execution_ = buffer.readBoolean();
      enable_user_pelvis_control_ = buffer.readBoolean();
      enable_user_pelvis_control_during_walking_ = buffer.readBoolean();
      se3_trajectory_.deserialize(buffer);

   }

   @Override
   public void set(PelvisTrajectoryMessage from)
   {
      sequence_id_ = from.sequence_id_;
      force_execution_ = from.force_execution_;
      enable_user_pelvis_control_ = from.enable_user_pelvis_control_;
      enable_user_pelvis_control_during_walking_ = from.enable_user_pelvis_control_during_walking_;
      se3_trajectory_.set(from.se3_trajectory_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getForceExecution()
   {
      return force_execution_;
   }

   public void setForceExecution(boolean force_execution_)
   {
      this.force_execution_ = force_execution_;
   }

   public boolean getEnableUserPelvisControl()
   {
      return enable_user_pelvis_control_;
   }

   public void setEnableUserPelvisControl(boolean enable_user_pelvis_control_)
   {
      this.enable_user_pelvis_control_ = enable_user_pelvis_control_;
   }

   public boolean getEnableUserPelvisControlDuringWalking()
   {
      return enable_user_pelvis_control_during_walking_;
   }

   public void setEnableUserPelvisControlDuringWalking(boolean enable_user_pelvis_control_during_walking_)
   {
      this.enable_user_pelvis_control_during_walking_ = enable_user_pelvis_control_during_walking_;
   }

   public ihmc_common_msgs.SE3TrajectoryMessage getSe3Trajectory()
   {
      return se3_trajectory_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("PelvisTrajectoryMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("force_execution_=");
      builder.append(force_execution_);
      builder.append("enable_user_pelvis_control_=");
      builder.append(enable_user_pelvis_control_);
      builder.append("enable_user_pelvis_control_during_walking_=");
      builder.append(enable_user_pelvis_control_during_walking_);
      builder.append("se3_trajectory_=");
      builder.append(se3_trajectory_);

      builder.append("}");
      return builder.toString();
   }
}