/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message used to report the current joint angles for the fingers of the sake gripper.
<p>Source (controller_msgs/SakeHandStatusMessage):
<pre>{@code
# Message used to report the current joint angles for the fingers of the sake gripper.

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

# Specifies the side of the robot of the hand being referred to
byte robot_side 255

# Angle at which the hand is closed, in radians
float64 position_upper_limit

# Angle at which the hand is fully open, in radians
float64 position_lower_limit

# Temperature of the Dynamixel in Celsius
int32 temperature

# The current dynamixel position, in radians
float64 current_position

# The current dynamixel torque
# 0: dynamixel will not apply any force and will not achieve desired position
# 300: A reasonable normal value
# 1023: dynamixel max torque which will quickly overheat the motor
int32 raw_current_torque

# The position the Dynamixel is trying to achieve, in radians
float64 desired_position_status

# Torque limit set on the Dynamixel
float64 raw_torque_limit_status

bool torque_on_status

# Rotation velocity of the Dynamixel, in rad/s
# Positive = opening hand (CCW rotation)
# Negative = closing hand (CW rotation)
float64 current_velocity

# Dynamixel's error codes
# See: https://emanual.robotis.com/docs/en/dxl/protocol1/#error
int32 error_codes

# Realtime tick of the Dynamixel
# If this value isn't changing, communication with the hand is broken
int32 realtime_tick

bool is_calibrated

bool needs_reset

bool is_calibrating

bool is_cooling_down

bool automatic_cooldown_enabled
}</pre>
*/
public class SakeHandStatusMessage implements ROS2Message<SakeHandStatusMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::SakeHandStatusMessage_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   /**
      Specifies the side of the robot of the hand being referred to
   */
   private byte robot_side_;
   /**
      Angle at which the hand is closed, in radians
   */
   private double position_upper_limit_;
   /**
      Angle at which the hand is fully open, in radians
   */
   private double position_lower_limit_;
   /**
      Temperature of the Dynamixel in Celsius
   */
   private int temperature_;
   /**
      The current dynamixel position, in radians
   */
   private double current_position_;
   /**
      The current dynamixel torque
      0: dynamixel will not apply any force and will not achieve desired position
      300: A reasonable normal value
      1023: dynamixel max torque which will quickly overheat the motor
   */
   private int raw_current_torque_;
   /**
      The position the Dynamixel is trying to achieve, in radians
   */
   private double desired_position_status_;
   /**
      Torque limit set on the Dynamixel
   */
   private double raw_torque_limit_status_;
   private boolean torque_on_status_;
   /**
      Rotation velocity of the Dynamixel, in rad/s
      Positive = opening hand (CCW rotation)
      Negative = closing hand (CW rotation)
   */
   private double current_velocity_;
   /**
      Dynamixel's error codes
      See: https://emanual.robotis.com/docs/en/dxl/protocol1/#error
   */
   private int error_codes_;
   /**
      Realtime tick of the Dynamixel
      If this value isn't changing, communication with the hand is broken
   */
   private int realtime_tick_;
   private boolean is_calibrated_;
   private boolean needs_reset_;
   private boolean is_calibrating_;
   private boolean is_cooling_down_;
   private boolean automatic_cooldown_enabled_;

   public SakeHandStatusMessage()
   {
      robot_side_ = (byte) 255;
      torque_on_status_ = (boolean) false;
      is_calibrated_ = (boolean) false;
      needs_reset_ = (boolean) false;
      is_calibrating_ = (boolean) false;
      is_cooling_down_ = (boolean) false;
      automatic_cooldown_enabled_ = (boolean) false;

   }

   public SakeHandStatusMessage(SakeHandStatusMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // position_upper_limit_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // position_lower_limit_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // temperature_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // current_position_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // raw_current_torque_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // desired_position_status_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // raw_torque_limit_status_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // torque_on_status_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // current_velocity_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // error_codes_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // realtime_tick_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_calibrated_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // needs_reset_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_calibrating_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // is_cooling_down_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // automatic_cooldown_enabled_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(robot_side_);
      buffer.writeDouble(position_upper_limit_);
      buffer.writeDouble(position_lower_limit_);
      buffer.writeInt(temperature_);
      buffer.writeDouble(current_position_);
      buffer.writeInt(raw_current_torque_);
      buffer.writeDouble(desired_position_status_);
      buffer.writeDouble(raw_torque_limit_status_);
      buffer.writeBoolean(torque_on_status_);
      buffer.writeDouble(current_velocity_);
      buffer.writeInt(error_codes_);
      buffer.writeInt(realtime_tick_);
      buffer.writeBoolean(is_calibrated_);
      buffer.writeBoolean(needs_reset_);
      buffer.writeBoolean(is_calibrating_);
      buffer.writeBoolean(is_cooling_down_);
      buffer.writeBoolean(automatic_cooldown_enabled_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      robot_side_ = buffer.readByte();
      position_upper_limit_ = buffer.readDouble();
      position_lower_limit_ = buffer.readDouble();
      temperature_ = buffer.readInt();
      current_position_ = buffer.readDouble();
      raw_current_torque_ = buffer.readInt();
      desired_position_status_ = buffer.readDouble();
      raw_torque_limit_status_ = buffer.readDouble();
      torque_on_status_ = buffer.readBoolean();
      current_velocity_ = buffer.readDouble();
      error_codes_ = buffer.readInt();
      realtime_tick_ = buffer.readInt();
      is_calibrated_ = buffer.readBoolean();
      needs_reset_ = buffer.readBoolean();
      is_calibrating_ = buffer.readBoolean();
      is_cooling_down_ = buffer.readBoolean();
      automatic_cooldown_enabled_ = buffer.readBoolean();

   }

   @Override
   public void set(SakeHandStatusMessage from)
   {
      robot_side_ = from.robot_side_;
      position_upper_limit_ = from.position_upper_limit_;
      position_lower_limit_ = from.position_lower_limit_;
      temperature_ = from.temperature_;
      current_position_ = from.current_position_;
      raw_current_torque_ = from.raw_current_torque_;
      desired_position_status_ = from.desired_position_status_;
      raw_torque_limit_status_ = from.raw_torque_limit_status_;
      torque_on_status_ = from.torque_on_status_;
      current_velocity_ = from.current_velocity_;
      error_codes_ = from.error_codes_;
      realtime_tick_ = from.realtime_tick_;
      is_calibrated_ = from.is_calibrated_;
      needs_reset_ = from.needs_reset_;
      is_calibrating_ = from.is_calibrating_;
      is_cooling_down_ = from.is_cooling_down_;
      automatic_cooldown_enabled_ = from.automatic_cooldown_enabled_;

   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public double getPositionUpperLimit()
   {
      return position_upper_limit_;
   }

   public void setPositionUpperLimit(double position_upper_limit_)
   {
      this.position_upper_limit_ = position_upper_limit_;
   }

   public double getPositionLowerLimit()
   {
      return position_lower_limit_;
   }

   public void setPositionLowerLimit(double position_lower_limit_)
   {
      this.position_lower_limit_ = position_lower_limit_;
   }

   public int getTemperature()
   {
      return temperature_;
   }

   public void setTemperature(int temperature_)
   {
      this.temperature_ = temperature_;
   }

   public double getCurrentPosition()
   {
      return current_position_;
   }

   public void setCurrentPosition(double current_position_)
   {
      this.current_position_ = current_position_;
   }

   public int getRawCurrentTorque()
   {
      return raw_current_torque_;
   }

   public void setRawCurrentTorque(int raw_current_torque_)
   {
      this.raw_current_torque_ = raw_current_torque_;
   }

   public double getDesiredPositionStatus()
   {
      return desired_position_status_;
   }

   public void setDesiredPositionStatus(double desired_position_status_)
   {
      this.desired_position_status_ = desired_position_status_;
   }

   public double getRawTorqueLimitStatus()
   {
      return raw_torque_limit_status_;
   }

   public void setRawTorqueLimitStatus(double raw_torque_limit_status_)
   {
      this.raw_torque_limit_status_ = raw_torque_limit_status_;
   }

   public boolean getTorqueOnStatus()
   {
      return torque_on_status_;
   }

   public void setTorqueOnStatus(boolean torque_on_status_)
   {
      this.torque_on_status_ = torque_on_status_;
   }

   public double getCurrentVelocity()
   {
      return current_velocity_;
   }

   public void setCurrentVelocity(double current_velocity_)
   {
      this.current_velocity_ = current_velocity_;
   }

   public int getErrorCodes()
   {
      return error_codes_;
   }

   public void setErrorCodes(int error_codes_)
   {
      this.error_codes_ = error_codes_;
   }

   public int getRealtimeTick()
   {
      return realtime_tick_;
   }

   public void setRealtimeTick(int realtime_tick_)
   {
      this.realtime_tick_ = realtime_tick_;
   }

   public boolean getIsCalibrated()
   {
      return is_calibrated_;
   }

   public void setIsCalibrated(boolean is_calibrated_)
   {
      this.is_calibrated_ = is_calibrated_;
   }

   public boolean getNeedsReset()
   {
      return needs_reset_;
   }

   public void setNeedsReset(boolean needs_reset_)
   {
      this.needs_reset_ = needs_reset_;
   }

   public boolean getIsCalibrating()
   {
      return is_calibrating_;
   }

   public void setIsCalibrating(boolean is_calibrating_)
   {
      this.is_calibrating_ = is_calibrating_;
   }

   public boolean getIsCoolingDown()
   {
      return is_cooling_down_;
   }

   public void setIsCoolingDown(boolean is_cooling_down_)
   {
      this.is_cooling_down_ = is_cooling_down_;
   }

   public boolean getAutomaticCooldownEnabled()
   {
      return automatic_cooldown_enabled_;
   }

   public void setAutomaticCooldownEnabled(boolean automatic_cooldown_enabled_)
   {
      this.automatic_cooldown_enabled_ = automatic_cooldown_enabled_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SakeHandStatusMessage {");
      builder.append("ROBOT_SIDE_LEFT=");
      builder.append(ROBOT_SIDE_LEFT);
      builder.append("ROBOT_SIDE_RIGHT=");
      builder.append(ROBOT_SIDE_RIGHT);
      builder.append("robot_side_=");
      builder.append(robot_side_);
      builder.append("position_upper_limit_=");
      builder.append(position_upper_limit_);
      builder.append("position_lower_limit_=");
      builder.append(position_lower_limit_);
      builder.append("temperature_=");
      builder.append(temperature_);
      builder.append("current_position_=");
      builder.append(current_position_);
      builder.append("raw_current_torque_=");
      builder.append(raw_current_torque_);
      builder.append("desired_position_status_=");
      builder.append(desired_position_status_);
      builder.append("raw_torque_limit_status_=");
      builder.append(raw_torque_limit_status_);
      builder.append("torque_on_status_=");
      builder.append(torque_on_status_);
      builder.append("current_velocity_=");
      builder.append(current_velocity_);
      builder.append("error_codes_=");
      builder.append(error_codes_);
      builder.append("realtime_tick_=");
      builder.append(realtime_tick_);
      builder.append("is_calibrated_=");
      builder.append(is_calibrated_);
      builder.append("needs_reset_=");
      builder.append(needs_reset_);
      builder.append("is_calibrating_=");
      builder.append(is_calibrating_);
      builder.append("is_cooling_down_=");
      builder.append(is_cooling_down_);
      builder.append("automatic_cooldown_enabled_=");
      builder.append(automatic_cooldown_enabled_);

      builder.append("}");
      return builder.toString();
   }
}