/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message for commanding the Sake hands to perform various predefined grasps.
Also allows for custom grasps with set positions/torques
<p>Source (controller_msgs/SakeHandDesiredCommandMessage):
<pre>{@code
# Message for commanding the Sake hands to perform various predefined grasps.
# Also allows for custom grasps with set positions/torques

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

# Specifies the side of the robot of the hand being referred to
byte robot_side 255

# Request the gripper to perform a calibration sequence
bool request_calibration

# Request to reset the gripper error state after overheating
bool request_reset_errors

# Set to true to enable automatic cooldown
bool enable_automatic_cooldown

# Set to true to disable automatic cooldown
bool disable_automatic_cooldown

# Set to true to override the cooldown
bool override_cooldown

# The desired dynamixel position, in radians
float64 gripper_desired_position

# The dynamixel torque limit setting in achieving the desired position
# 0: dynamixel will not apply any force and will not achieve desired position
# 300: A reasonable normal value
# 1023: dynamixel max torque which will quickly overheat the motor
int32 raw_gripper_torque_limit

# Keeping the torque off when not needed can help keep the hand's temperature down
bool torque_on
}</pre>
*/
public class SakeHandDesiredCommandMessage implements ROS2Message<SakeHandDesiredCommandMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::SakeHandDesiredCommandMessage_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   /**
      Specifies the side of the robot of the hand being referred to
   */
   private byte robot_side_;
   /**
      Request the gripper to perform a calibration sequence
   */
   private boolean request_calibration_;
   /**
      Request to reset the gripper error state after overheating
   */
   private boolean request_reset_errors_;
   /**
      Set to true to enable automatic cooldown
   */
   private boolean enable_automatic_cooldown_;
   /**
      Set to true to disable automatic cooldown
   */
   private boolean disable_automatic_cooldown_;
   /**
      Set to true to override the cooldown
   */
   private boolean override_cooldown_;
   /**
      The desired dynamixel position, in radians
   */
   private double gripper_desired_position_;
   /**
      The dynamixel torque limit setting in achieving the desired position
      0: dynamixel will not apply any force and will not achieve desired position
      300: A reasonable normal value
      1023: dynamixel max torque which will quickly overheat the motor
   */
   private int raw_gripper_torque_limit_;
   /**
      Keeping the torque off when not needed can help keep the hand's temperature down
   */
   private boolean torque_on_;

   public SakeHandDesiredCommandMessage()
   {
      robot_side_ = (byte) 255;
      request_calibration_ = (boolean) false;
      request_reset_errors_ = (boolean) false;
      enable_automatic_cooldown_ = (boolean) false;
      disable_automatic_cooldown_ = (boolean) false;
      override_cooldown_ = (boolean) false;
      torque_on_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_calibration_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // request_reset_errors_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // enable_automatic_cooldown_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // disable_automatic_cooldown_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // override_cooldown_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // gripper_desired_position_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // raw_gripper_torque_limit_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // torque_on_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(robot_side_);
      buffer.writeBoolean(request_calibration_);
      buffer.writeBoolean(request_reset_errors_);
      buffer.writeBoolean(enable_automatic_cooldown_);
      buffer.writeBoolean(disable_automatic_cooldown_);
      buffer.writeBoolean(override_cooldown_);
      buffer.writeDouble(gripper_desired_position_);
      buffer.writeInt(raw_gripper_torque_limit_);
      buffer.writeBoolean(torque_on_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      robot_side_ = buffer.readByte();
      request_calibration_ = buffer.readBoolean();
      request_reset_errors_ = buffer.readBoolean();
      enable_automatic_cooldown_ = buffer.readBoolean();
      disable_automatic_cooldown_ = buffer.readBoolean();
      override_cooldown_ = buffer.readBoolean();
      gripper_desired_position_ = buffer.readDouble();
      raw_gripper_torque_limit_ = buffer.readInt();
      torque_on_ = buffer.readBoolean();

   }

   @Override
   public void set(SakeHandDesiredCommandMessage from)
   {
      robot_side_ = from.robot_side_;
      request_calibration_ = from.request_calibration_;
      request_reset_errors_ = from.request_reset_errors_;
      enable_automatic_cooldown_ = from.enable_automatic_cooldown_;
      disable_automatic_cooldown_ = from.disable_automatic_cooldown_;
      override_cooldown_ = from.override_cooldown_;
      gripper_desired_position_ = from.gripper_desired_position_;
      raw_gripper_torque_limit_ = from.raw_gripper_torque_limit_;
      torque_on_ = from.torque_on_;

   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public boolean getRequestCalibration()
   {
      return request_calibration_;
   }

   public void setRequestCalibration(boolean request_calibration_)
   {
      this.request_calibration_ = request_calibration_;
   }

   public boolean getRequestResetErrors()
   {
      return request_reset_errors_;
   }

   public void setRequestResetErrors(boolean request_reset_errors_)
   {
      this.request_reset_errors_ = request_reset_errors_;
   }

   public boolean getEnableAutomaticCooldown()
   {
      return enable_automatic_cooldown_;
   }

   public void setEnableAutomaticCooldown(boolean enable_automatic_cooldown_)
   {
      this.enable_automatic_cooldown_ = enable_automatic_cooldown_;
   }

   public boolean getDisableAutomaticCooldown()
   {
      return disable_automatic_cooldown_;
   }

   public void setDisableAutomaticCooldown(boolean disable_automatic_cooldown_)
   {
      this.disable_automatic_cooldown_ = disable_automatic_cooldown_;
   }

   public boolean getOverrideCooldown()
   {
      return override_cooldown_;
   }

   public void setOverrideCooldown(boolean override_cooldown_)
   {
      this.override_cooldown_ = override_cooldown_;
   }

   public double getGripperDesiredPosition()
   {
      return gripper_desired_position_;
   }

   public void setGripperDesiredPosition(double gripper_desired_position_)
   {
      this.gripper_desired_position_ = gripper_desired_position_;
   }

   public int getRawGripperTorqueLimit()
   {
      return raw_gripper_torque_limit_;
   }

   public void setRawGripperTorqueLimit(int raw_gripper_torque_limit_)
   {
      this.raw_gripper_torque_limit_ = raw_gripper_torque_limit_;
   }

   public boolean getTorqueOn()
   {
      return torque_on_;
   }

   public void setTorqueOn(boolean torque_on_)
   {
      this.torque_on_ = torque_on_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SakeHandDesiredCommandMessage {");
      builder.append("ROBOT_SIDE_LEFT=");
      builder.append(ROBOT_SIDE_LEFT);
      builder.append("ROBOT_SIDE_RIGHT=");
      builder.append(ROBOT_SIDE_RIGHT);
      builder.append("robot_side_=");
      builder.append(robot_side_);
      builder.append("request_calibration_=");
      builder.append(request_calibration_);
      builder.append("request_reset_errors_=");
      builder.append(request_reset_errors_);
      builder.append("enable_automatic_cooldown_=");
      builder.append(enable_automatic_cooldown_);
      builder.append("disable_automatic_cooldown_=");
      builder.append(disable_automatic_cooldown_);
      builder.append("override_cooldown_=");
      builder.append(override_cooldown_);
      builder.append("gripper_desired_position_=");
      builder.append(gripper_desired_position_);
      builder.append("raw_gripper_torque_limit_=");
      builder.append(raw_gripper_torque_limit_);
      builder.append("torque_on_=");
      builder.append(torque_on_);

      builder.append("}");
      return builder.toString();
   }
}