/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body controller API.
This message gives the user the option to bypass IHMC feedback controllers for the spine joints by sending desired spine joint accelerations.
One needs experience in control when activating the bypass as it can result in unexpected behaviors for unreasonable accelerations.
<p>Source (controller_msgs/SpineDesiredAccelerationsMessage):
<pre>{@code
# This message is part of the IHMC whole-body controller API.
# This message gives the user the option to bypass IHMC feedback controllers for the spine joints by sending desired spine joint accelerations.
# One needs experience in control when activating the bypass as it can result in unexpected behaviors for unreasonable accelerations.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# The desired joint acceleration information.
DesiredAccelerationsMessage desired_accelerations}</pre>
*/
public class SpineDesiredAccelerationsMessage implements ROS2Message<SpineDesiredAccelerationsMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::SpineDesiredAccelerationsMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      The desired joint acceleration information.
   */
   private final controller_msgs.DesiredAccelerationsMessage desired_accelerations_;

   public SpineDesiredAccelerationsMessage()
   {
      desired_accelerations_ = new controller_msgs.DesiredAccelerationsMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += desired_accelerations_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      desired_accelerations_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      desired_accelerations_.deserialize(buffer);

   }

   @Override
   public void set(SpineDesiredAccelerationsMessage from)
   {
      sequence_id_ = from.sequence_id_;
      desired_accelerations_.set(from.desired_accelerations_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public controller_msgs.DesiredAccelerationsMessage getDesiredAccelerations()
   {
      return desired_accelerations_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SpineDesiredAccelerationsMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("desired_accelerations_=");
      builder.append(desired_accelerations_);

      builder.append("}");
      return builder.toString();
   }
}