/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package controller_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body controller API.
This class is used to build a wrench (force & moment) profile over time.
It holds the necessary information for one trajectory point.
<p>Source (controller_msgs/WrenchTrajectoryPointMessage):
<pre>{@code
# This message is part of the IHMC whole-body controller API.
# This class is used to build a wrench (force & moment) profile over time.
# It holds the necessary information for one trajectory point.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Time at which the trajectory point has to be reached. The time is relative to when the trajectory starts.
float64 time
# Define the desired wrench (force & moment) to be achieved at this trajectory point.
geometry_msgs/Wrench wrench}</pre>
*/
public class WrenchTrajectoryPointMessage implements ROS2Message<WrenchTrajectoryPointMessage>
{
   public static final java.lang.String name = "controller_msgs::msg::dds_::WrenchTrajectoryPointMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Time at which the trajectory point has to be reached. The time is relative to when the trajectory starts.
   */
   private double time_;
   /**
      Define the desired wrench (force & moment) to be achieved at this trajectory point.
   */
   private final geometry_msgs.Wrench wrench_;

   public WrenchTrajectoryPointMessage()
   {
      wrench_ = new geometry_msgs.Wrench();

   }

   public WrenchTrajectoryPointMessage(WrenchTrajectoryPointMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // time_
      currentAlignment += wrench_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(time_);
      wrench_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      time_ = buffer.readDouble();
      wrench_.deserialize(buffer);

   }

   @Override
   public void set(WrenchTrajectoryPointMessage from)
   {
      sequence_id_ = from.sequence_id_;
      time_ = from.time_;
      wrench_.set(from.wrench_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getTime()
   {
      return time_;
   }

   public void setTime(double time_)
   {
      this.time_ = time_;
   }

   public geometry_msgs.Wrench getWrench()
   {
      return wrench_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("WrenchTrajectoryPointMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("time_=");
      builder.append(time_);
      builder.append("wrench_=");
      builder.append(wrench_);

      builder.append("}");
      return builder.toString();
   }
}