# A service call to carry out an inverse kinematics computation
# The inverse kinematics request
kinematics_msgs/PositionIKRequest ik_request
# Maximum allowed time for IK calculation
duration timeout
---
# The returned solution 
# (in the same order as the list of joints specified in the IKRequest message)
arm_navigation_msgs/RobotState solution

arm_navigation_msgs/ArmNavigationErrorCodes error_code

