//convex_plane_decomposition_msgs/PlanarRegion[] planarRegions
//        geometry_msgs/Pose plane_parameters
//        geometry_msgs/Point position
//        float64 x
//        float64 y
//        float64 z
//        geometry_msgs/Quaternion orientation
//        float64 x
//        float64 y
//        float64 z
//        float64 w
//        convex_plane_decomposition_msgs/BoundingBox2d bbox2d
//        float32 min_x
//        float32 min_y
//        float32 max_x
//        float32 max_y
//        convex_plane_decomposition_msgs/PolygonWithHoles2d boundary
//        convex_plane_decomposition_msgs/Polygon2d outer_boundary
//        convex_plane_decomposition_msgs/Point2d[] points
//        float32 x
//        float32 y
//        convex_plane_decomposition_msgs/Polygon2d[] holes
//        convex_plane_decomposition_msgs/Point2d[] points
//        float32 x
//        float32 y
//        convex_plane_decomposition_msgs/PolygonWithHoles2d[] insets
//        convex_plane_decomposition_msgs/Polygon2d outer_boundary
//        convex_plane_decomposition_msgs/Point2d[] points
//        float32 x
//        float32 y
//        convex_plane_decomposition_msgs/Polygon2d[] holes
//        convex_plane_decomposition_msgs/Point2d[] points
//        float32 x
//        float32 y
//        grid_map_msgs/GridMap gridmap
//        grid_map_msgs/GridMapInfo info
//        std_msgs/Header header
//        uint32 seq
//        time stamp
//        string frame_id
//        float64 resolution
//        float64 length_x
//        float64 length_y
//        geometry_msgs/Pose pose
//        geometry_msgs/Point position
//        float64 x
//        float64 y
//        float64 z
//        geometry_msgs/Quaternion orientation
//        float64 x
//        float64 y
//        float64 z
//        float64 w
//        string[] layers
//        string[] basic_layers
//        std_msgs/Float32MultiArray[] data
//        std_msgs/MultiArrayLayout layout
//        std_msgs/MultiArrayDimension[] dim
//        string label
//        uint32 size
//        uint32 stride
//        uint32 data_offset
//        float32[] data
//        uint16 outer_start_index
//        uint16 inner_start_index
