# Array of string names for the links for which cost information is desired
string[] links

# The state of the robot represented as an array of Kinematic states which
# include the joint name and joint value
arm_navigation_msgs/RobotState state

---

# Returns an array of costs for the links (in the same order as the input)
float64[] costs

# Each element of this array is a num_joints x 1 array that represents the
# joint velocity that will move the link down the gradient of the distance
# field (away from collisions)
JointVelocityArray[] gradient

# A boolean value which indicates whether the configuration is in collision
uint8 in_collision
