# A service call to get the cost for a given state of the robot (specified in the form of a RobotState message)

# A list of link names for which the cost should be computed
string[] link_names
# The robot state for which the cost should be computed
arm_navigation_msgs/RobotState robot_state
----
# True if the cost computation was valid
bool valid
# The cost corresponding to each link
float64[] costs
