int8 L_ARM_WRY=0

int8 L_ARM_WRX=1

int8 L_ARM_WRY2=2

int8 R_ARM_WRY=3

int8 R_ARM_WRX=4

int8 R_ARM_WRY2=5

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint32 sequence_id

# The Enum value of the motor to enable
# Field default value 255
int8 atlas_electric_motor_packet_enum_enable

# Boolean for enable state; true for enable, false for disable.
bool enable


