float64 NO_VALUE_DOUBLE=-11.1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint32 sequence_id

# Field default value -11.1
float64 maximum_front_step_reach

# Field default value -11.1
float64 maximum_front_step_length

# Field default value -11.1
float64 minimum_front_step_length

# Field default value -11.1
float64 maximum_hind_step_reach

# Field default value -11.1
float64 maximum_hind_step_length

# Field default value -11.1
float64 minimum_hind_step_length

# Field default value -11.1
float64 maximum_front_step_length_when_stepping_up

# Field default value -11.1
float64 minimum_front_step_length_when_stepping_up

# Field default value -11.1
float64 maximum_hind_step_length_when_stepping_up

# Field default value -11.1
float64 minimum_hind_step_length_when_stepping_up

# Field default value -11.1
float64 step_z_for_stepping_up

# Field default value -11.1
float64 maximum_front_step_length_when_stepping_down

# Field default value -11.1
float64 minimum_front_step_length_when_stepping_down

# Field default value -11.1
float64 maximum_hind_step_length_when_stepping_down

# Field default value -11.1
float64 minimum_hind_step_length_when_stepping_down

# Field default value -11.1
float64 step_z_for_stepping_down

# Field default value -11.1
float64 maximum_step_outward

# Field default value -11.1
float64 maximum_step_inward

# Field default value -11.1
float64 maximum_step_yaw_outward

# Field default value -11.1
float64 maximum_step_yaw_inward

# Field default value -11.1
float64 maximum_step_change_z

# Field default value -11.1
float64 body_ground_clearance

# Field default value -11.1
float64 distance_weight

# Field default value -11.1
float64 yaw_weight

# Field default value -11.1
float64 x_gait_weight

# Field default value -11.1
float64 desired_velocity_weight

# Field default value -11.1
float64 cost_per_step

# Field default value -11.1
float64 step_up_weight

# Field default value -11.1
float64 step_down_weight

# Field default value -11.1
float64 heuristics_weight

# Field default value -11.1
float64 min_x_clearance_from_paw

# Field default value -11.1
float64 min_y_clearance_from_paw

# Field default value -11.1
float64 max_walking_speed_multiplier

bool project_inside_using_convex_hull

# Field default value -11.1
float64 projection_inside_distance

# Field default value -11.1
float64 minimum_projection_inside_distance

# Field default value -11.1
float64 maximum_xy_wiggle_distance

# Field default value -11.1
float64 minimum_surface_incline_radians

# Field default value -11.1
float64 cliff_height_to_avoid

# Field default value -11.1
float64 minimum_front_end_forward_distance_from_cliff_bottoms

# Field default value -11.1
float64 minimum_front_end_backward_distance_from_cliff_bottoms

# Field default value -11.1
float64 minimum_hind_end_forward_distance_from_cliff_bottoms

# Field default value -11.1
float64 minimum_hind_end_backward_distance_from_cliff_bottoms

# Field default value -11.1
float64 minimum_lateral_distance_from_cliff_bottoms

# Field default value -11.1
float64 final_turn_proximity

# Field default value -11.1
float64 final_slow_down_proximity

# Field default value -11.1
float64 maximum_deviation_from_x_gait_during_expansion

bool return_best_effort_plan

# Field default value 4
uint32 minimum_steps_for_best_effort_plan

bool perform_graph_repairing_step

# Field default value -11.1
float64 repairing_heuristic_weight_scaling

# Field default value -11.1
float64 minimum_heuristic_weight_reduction


