float64 NO_VALUE_DOUBLE=-11.1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint32 sequence_id

# Field default value -11.1
float64 maximum_step_reach

# Field default value -11.1
float64 maximum_step_length

# Field default value -11.1
float64 minimum_step_length

# Field default value -11.1
float64 maximum_step_width

# Field default value -11.1
float64 minimum_step_width

# Field default value -11.1
float64 minimum_step_yaw

# Field default value -11.1
float64 maximum_step_yaw

# Field default value -11.1
float64 maximum_step_change_z

# Field default value -11.1
float64 body_ground_clearance

# Field default value -11.1
float64 distance_heuristic_weight

# Field default value -11.1
float64 yaw_weight

# Field default value -11.1
float64 x_gait_weight

# Field default value -11.1
float64 cost_per_step

# Field default value -11.1
float64 step_up_weight

# Field default value -11.1
float64 step_down_weight

# Field default value -11.1
float64 heuristics_weight

# Field default value -11.1
float64 min_x_clearance_from_foot

# Field default value -11.1
float64 min_y_clearance_from_foot

# Field default value -11.1
float64 crawl_speed

# Field default value -11.1
float64 trot_speed

# Field default value -11.1
float64 pace_speed

# Field default value -11.1
float64 projection_inside_distance

# Field default value -11.1
float64 minimum_surface_incline_radians

# Field default value -11.1
float64 cliff_height_to_avoid

# Field default value -11.1
float64 minimum_distance_from_cliff_bottoms

# Field default value -11.1
float64 minimum_distance_from_cliff_tops


