#ifndef __atlas_msgs__msg__AtlasWristSensorCalibrationRequestPacket__idl__
#define __atlas_msgs__msg__AtlasWristSensorCalibrationRequestPacket__idl__

module atlas_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * Atlas specific message: request taring of the wrist force/torque sensors.
       */
      @TypeCode(type="atlas_msgs::msg::dds_::AtlasWristSensorCalibrationRequestPacket_")
      struct AtlasWristSensorCalibrationRequestPacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * The robot side (left or right) for the wrist sensor you would like to request calibration for.
         */
        @defaultValue(value=255)
        octet robot_side;
      };
    };
  };
};

#endif
