## AtlasElectricMotorEnablePacketMessage
# Specifies a specific electric motor in the Atlas forearm to power on or off.

# Options for motorEnableEnum
uint8 L_ARM_WRY=0 # left upper wrist pitch
uint8 L_ARM_WRX=1 # left wrist roll
uint8 L_ARM_WRY2=2 # left lower wrist pitch
uint8 R_ARM_WRY=3 # right upper wrist pitch
uint8 R_ARM_WRX=4 # right wrist roll
uint8 R_ARM_WRY2=5 # right lower wrist pitch
uint8 motor_enable_enum

bool enable


