#ifndef __toolbox_msgs__msg__BehaviorControlModePacket__idl__
#define __toolbox_msgs__msg__BehaviorControlModePacket__idl__

module toolbox_msgs
{
  module msg
  {
    module dds
    {
      const octet STOP =
      0;

      const octet PAUSE =
      1;

      const octet RESUME =
      2;


      /**
       * This message is part of the IHMC humanoid behavior module.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::BehaviorControlModePacket_")
      struct BehaviorControlModePacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=255)
        octet behavior_control_mode_enum_request;
      };
    };
  };
};

#endif
