#ifndef __toolbox_msgs__msg__FootstepPlannerStatusMessage__idl__
#define __toolbox_msgs__msg__FootstepPlannerStatusMessage__idl__

module toolbox_msgs
{
  module msg
  {
    module dds
    {
      const octet FOOTSTEP_PLANNER_STATUS_IDLE =
      0;

      const octet FOOTSTEP_PLANNER_STATUS_PLANNING_PATH =
      1;

      const octet FOOTSTEP_PLANNER_STATUS_PLANNING_STEPS =
      2;


      /**
       * This message is part of the IHMC footstep planner API.
       * The footstep planner sends this message to notify the user of the status of planning.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::FootstepPlannerStatusMessage_")
      struct FootstepPlannerStatusMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=255)
        octet footstep_planner_status;
      };
    };
  };
};

#endif
