#ifndef __toolbox_msgs__msg__FootstepStreamingToolboxInputMessage__idl__
#define __toolbox_msgs__msg__FootstepStreamingToolboxInputMessage__idl__

#include "toolbox_msgs/msg/./FootstepStreamingToolboxSideMessage_.idl"
module toolbox_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the FootstepStreamingToolbox API
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::FootstepStreamingToolboxInputMessage_")
      struct FootstepStreamingToolboxInputMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing
         */
        unsigned long long sequence_id;
        /**
         * Current robot step duration
         */
        double robot_step_duration;
        /**
         * Time elapsed since the robot has initiated this last step
         */
        double robot_step_elapsed_time;
        /**
         * The list of sides used as input for the toolbox to estimate footsteps for the robot
         */
        sequence<toolbox_msgs::msg::dds::FootstepStreamingToolboxSideMessage, 2> side;
      };
    };
  };
};

#endif
