#ifndef __toolbox_msgs__msg__KinematicsToolboxInputCollectionMessage__idl__
#define __toolbox_msgs__msg__KinematicsToolboxInputCollectionMessage__idl__

#include "toolbox_msgs/msg/./KinematicsToolboxCenterOfMassMessage_.idl"
#include "toolbox_msgs/msg/./KinematicsToolboxOneDoFJointMessage_.idl"
#include "toolbox_msgs/msg/./KinematicsToolboxRigidBodyMessage_.idl"
#include "toolbox_msgs/msg/./KinematicsToolboxSupportRegionMessage_.idl"
module toolbox_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body inverse kinematics module.
       * This message allows to pack and send as a single message a collection of inputs for the kinematics toolbox.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::KinematicsToolboxInputCollectionMessage_")
      struct KinematicsToolboxInputCollectionMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Inputs for controlling the center of mass position.
         */
        sequence<toolbox_msgs::msg::dds::KinematicsToolboxCenterOfMassMessage, 3> center_of_mass_inputs;
        /**
         * Inputs for controlling rigid-bodies.
         */
        sequence<toolbox_msgs::msg::dds::KinematicsToolboxRigidBodyMessage, 20> rigid_body_inputs;
        /**
         * Inputs for controlling 1-DoF joints.
         */
        sequence<toolbox_msgs::msg::dds::KinematicsToolboxOneDoFJointMessage, 20> joint_inputs;
        /**
         * Input for overriding the default support polygon with a custom one.
         */
        sequence<toolbox_msgs::msg::dds::KinematicsToolboxSupportRegionMessage, 1> contact_state_input;
      };
    };
  };
};

#endif
