#ifndef __toolbox_msgs__msg__KinematicsStreamingToolboxContactConfigurationMessage__idl__
#define __toolbox_msgs__msg__KinematicsStreamingToolboxContactConfigurationMessage__idl__

module toolbox_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC Kinematics Streaming Toolbox module.
       * It contains auxiliary information that allows to customize the contact configuration based on user input.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::KinematicsStreamingToolboxContactConfigurationMessage_")
      struct KinematicsStreamingToolboxContactConfigurationMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long long sequence_id;
        /**
         * The contact configuration of the left foot
         */
        boolean left_foot_in_contact;
        /**
         * The contact configuration of the right foot
         */
        boolean right_foot_in_contact;
      };
    };
  };
};

#endif
