#ifndef __toolbox_msgs__msg__KinematicsToolboxOneDoFJointMessage__idl__
#define __toolbox_msgs__msg__KinematicsToolboxOneDoFJointMessage__idl__

module toolbox_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body inverse kinematics module.
       * This message contains all the information needed to configure the objectives/constraints to apply on
       * a given 1-DoF joint in the solver.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::KinematicsToolboxOneDoFJointMessage_")
      struct KinematicsToolboxOneDoFJointMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * The is the unique hash code of the joint to be solved for.
         * It is used on the solver side to retrieve the desired joint to be controlled.
         * See Joint.hashCode() for the computation of a joint hash code.
         */
        long joint_hash_code;
        /**
         * The is the desired joint position.
         */
        double desired_position;
        /**
         * Weight used to define the priority for reaching the desired position.
         */
        double weight;
      };
    };
  };
};

#endif
