#ifndef __toolbox_msgs__msg__ROS2LogMessage__idl__
#define __toolbox_msgs__msg__ROS2LogMessage__idl__

module toolbox_msgs
{
  module msg
  {
    module dds
    {
      const octet ROS2_LOG_REQUESTED_STATE_START =
      0;

      const octet ROS2_LOG_REQUESTED_STATE_FINISH =
      1;


      /**
       * This message is used to start and stop recording ROS logs.
       * This is used both for recording and replaying, see ROS2LogRecord and ROS2LogReplay for more information.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::ROS2LogMessage_")
      struct ROS2LogMessage
      {
        /**
         * Requested state for the ROS 2 log recorder
         */
        @defaultValue(value=255)
        octet requested_state;
      };
    };
  };
};

#endif
