#ifndef __toolbox_msgs__msg__SwingPlanningRequestPacket__idl__
#define __toolbox_msgs__msg__SwingPlanningRequestPacket__idl__

module toolbox_msgs
{
  module msg
  {
    module dds
    {
      const octet SWING_PLANNER_TYPE_NONE =
      0;

      const octet SWING_PLANNER_TYPE_POSITION =
      1;

      const octet SWING_PLANNER_TYPE_PROPORTION =
      2;


      /**
       * This message is part of the IHMC footstep planning module.
       * The planner recomputes swing waypoints for the last planned path if it receives this message.
       * If no path was previously planned, it's ignored.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::SwingPlanningRequestPacket_")
      struct SwingPlanningRequestPacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Specifies swing planner to use. See the above enumeration
         */
        octet requested_swing_planner;
        /**
         * Generate log of this plan. Logs are written to ~/.ihmc/logs by default, set the environment variable IHMC_FOOTSTEP_PLANNER_LOG_DIR to override this directory.
         * For example, export IHMC_FOOTSTEP_PLANNER_LOG_DIR=/home/user/myLogs/
         */
        boolean generate_log;
      };
    };
  };
};

#endif
