#ifndef __toolbox_msgs__msg__WalkingControllerPreviewInputMessage__idl__
#define __toolbox_msgs__msg__WalkingControllerPreviewInputMessage__idl__

#include "controller_msgs/msg/./FootstepDataListMessage_.idl"
module toolbox_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC walking controller preview module: WalkingControllerPreviewToolbox.
       * Configure only the fields to be previewed.
       * New fields will be added to this message as the module supports them.
       */
      @TypeCode(type="toolbox_msgs::msg::dds_::WalkingControllerPreviewInputMessage_")
      struct WalkingControllerPreviewInputMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Set this field to request a preview of the corresponding walking sequence.
         */
        controller_msgs::msg::dds::FootstepDataListMessage footsteps;
      };
    };
  };
};

#endif
