/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package test_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (test_msgs/LongString):
<pre>{@code
# String as multiple ASCII bytes because of our 255 string length constraint
int8[<=2048] long_string
}</pre>
*/
public class LongString implements ROS2Message<LongString>
{
   public static final java.lang.String name = "test_msgs::msg::dds_::LongString_";

   /**
      String as multiple ASCII bytes because of our 255 string length constraint
   */
   private final IDLByteSequence long_string_;

   public LongString()
   {
      long_string_ = new IDLByteSequence(2048);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += long_string_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      long_string_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      long_string_.deserialize(buffer);

   }

   @Override
   public void set(LongString from)
   {
      long_string_.set(from.long_string_);

   }

   public IDLByteSequence getLongString()
   {
      return long_string_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("LongString {");
      builder.append("long_string_=");
      builder.append(long_string_);

      builder.append("}");
      return builder.toString();
   }
}