package object_manipulation_msgs;

public interface PlaceFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "object_manipulation_msgs/PlaceFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\n# The number of the place location currently being attempted\nint32 current_location\n\n# The total number of locations that will be attempted\nint32 total_locations\n\n";
  int getCurrentLocation();
  void setCurrentLocation(int value);
  int getTotalLocations();
  void setTotalLocations(int value);
}
