package pr2_controllers_msgs;

public interface JointTrajectoryGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "pr2_controllers_msgs/JointTrajectoryGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\ntrajectory_msgs/JointTrajectory trajectory\n";
  trajectory_msgs.JointTrajectory getTrajectory();
  void setTrajectory(trajectory_msgs.JointTrajectory value);
}
