package pr2_controllers_msgs;

public interface PointHeadAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "pr2_controllers_msgs/PointHeadAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nPointHeadActionGoal action_goal\nPointHeadActionResult action_result\nPointHeadActionFeedback action_feedback\n";
  pr2_controllers_msgs.PointHeadActionGoal getActionGoal();
  void setActionGoal(pr2_controllers_msgs.PointHeadActionGoal value);
  pr2_controllers_msgs.PointHeadActionResult getActionResult();
  void setActionResult(pr2_controllers_msgs.PointHeadActionResult value);
  pr2_controllers_msgs.PointHeadActionFeedback getActionFeedback();
  void setActionFeedback(pr2_controllers_msgs.PointHeadActionFeedback value);
}
