package arm_navigation_msgs;

public interface MoveArmActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "arm_navigation_msgs/MoveArmActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nMoveArmFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  arm_navigation_msgs.MoveArmFeedback getFeedback();
  void setFeedback(arm_navigation_msgs.MoveArmFeedback value);
}
