package arm_navigation_msgs;

public interface SyncPlanningSceneActionResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "arm_navigation_msgs/SyncPlanningSceneActionResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nSyncPlanningSceneResult result\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  arm_navigation_msgs.SyncPlanningSceneResult getResult();
  void setResult(arm_navigation_msgs.SyncPlanningSceneResult value);
}
