#ifndef __ihmc_common_msgs__msg__DistributedClockMessage__idl__
#define __ihmc_common_msgs__msg__DistributedClockMessage__idl__

#include "ihmc_common_msgs/msg/./GuidMessage_.idl"
#include "ihmc_common_msgs/msg/./InstantMessage_.idl"
module ihmc_common_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is a request-reply ping used to estimate the clock offset
       * of another node to be used by data synchronization algorithms.
       */
      @TypeCode(type="ihmc_common_msgs::msg::dds_::DistributedClockMessage_")
      struct DistributedClockMessage
      {
        /**
         * The guid of the publisher that's expected to send back a reply
         */
        ihmc_common_msgs::msg::dds::GuidMessage request_target;
        /**
         * The guid of the publisher associated with the requester
         */
        ihmc_common_msgs::msg::dds::GuidMessage reply_target;
        /**
         * The time at which the request is sent
         */
        ihmc_common_msgs::msg::dds::InstantMessage request_send_time;
        /**
         * The time at which the reply is sent
         */
        ihmc_common_msgs::msg::dds::InstantMessage reply_send_time;
      };
    };
  };
};

#endif
