#ifndef __ihmc_common_msgs__msg__GroundPlaneMessage__idl__
#define __ihmc_common_msgs__msg__GroundPlaneMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Vector3_.idl"
module ihmc_common_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This is part of the IHMC Common message package.
       * This message contains a model of the ground plane.
       * It is defined by an origin and a normal
       */
      @TypeCode(type="ihmc_common_msgs::msg::dds_::GroundPlaneMessage_")
      struct GroundPlaneMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        geometry_msgs::msg::dds::Point region_origin;
        geometry_msgs::msg::dds::Vector3 region_normal;
      };
    };
  };
};

#endif
