#ifndef __ihmc_common_msgs__msg__GuidMessage__idl__
#define __ihmc_common_msgs__msg__GuidMessage__idl__

module ihmc_common_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Represents a DDS-RTPS Guid
       */
      @TypeCode(type="ihmc_common_msgs::msg::dds_::GuidMessage_")
      struct GuidMessage
      {
        /**
         * Prefix
         */
        octet prefix[12];
        /**
         * Entity
         */
        octet entity[4];
      };
    };
  };
};

#endif
