#ifndef __ihmc_common_msgs__msg__LatestModificationMessage__idl__
#define __ihmc_common_msgs__msg__LatestModificationMessage__idl__

#include "ihmc_common_msgs/msg/./GuidMessage_.idl"
#include "ihmc_common_msgs/msg/./InstantMessage_.idl"
module ihmc_common_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A message to hold onto the most recent modification timestamp
       * on the data this message is associated with.
       */
      @TypeCode(type="ihmc_common_msgs::msg::dds_::LatestModificationMessage_")
      struct LatestModificationMessage
      {
        /**
         * The guid of the peer that made the most recent modification
         */
        ihmc_common_msgs::msg::dds::GuidMessage latest_modifier_id;
        /**
         * The time the latest modification was made in peer frame
         */
        ihmc_common_msgs::msg::dds::InstantMessage latest_modification_time_in_modifier_frame;
        /**
         * Modification number used to order the modifications across all peers
         * This allows us to workaround peer clock offset drift.
         */
        unsigned long long latest_modification_number;
        /**
         * Human readable name of the latest modifier
         */
        string latest_modifier_name;
      };
    };
  };
};

#endif
