#ifndef __ihmc_common_msgs__msg__RobotFrameData__idl__
#define __ihmc_common_msgs__msg__RobotFrameData__idl__

#include "geometry_msgs/msg/./Pose_.idl"
module ihmc_common_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message carries robot's joints, IMU, and force sensors' reference frame information.
       * It is published frequently from the IHMC state estimator along with robot configuration data.
       */
      @TypeCode(type="ihmc_common_msgs::msg::dds_::RobotFrameData_")
      struct RobotFrameData
      {
        /**
         * Platform dependent.
         * Time signal in nanoseconds that can be used to synchronize two time sources.
         */
        long long timestamp;
        /**
         * Hash code of this frame.
         */
        long frame_name_hash;
        /**
         * Pose3D of this frame in the world frame.
         */
        geometry_msgs::msg::dds::Pose frame_pose_in_world;
        /**
         * Name of this frame.
         */
        string frame_name;
      };
    };
  };
};

#endif
