#ifndef __ihmc_common_msgs__msg__TimeIntervalMessage__idl__
#define __ihmc_common_msgs__msg__TimeIntervalMessage__idl__

module ihmc_common_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="ihmc_common_msgs::msg::dds_::TimeIntervalMessage_")
      struct TimeIntervalMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        double start_time;
        double end_time;
      };
    };
  };
};

#endif
