package atlas_msgs;

public interface WalkDemoActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "atlas_msgs/WalkDemoActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nWalkDemoFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  atlas_msgs.WalkDemoFeedback getFeedback();
  void setFeedback(atlas_msgs.WalkDemoFeedback value);
}
