package atlas_msgs;

public interface WalkDemoAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "atlas_msgs/WalkDemoAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nWalkDemoActionGoal action_goal\nWalkDemoActionResult action_result\nWalkDemoActionFeedback action_feedback\n";
  atlas_msgs.WalkDemoActionGoal getActionGoal();
  void setActionGoal(atlas_msgs.WalkDemoActionGoal value);
  atlas_msgs.WalkDemoActionResult getActionResult();
  void setActionResult(atlas_msgs.WalkDemoActionResult value);
  atlas_msgs.WalkDemoActionFeedback getActionFeedback();
  void setActionFeedback(atlas_msgs.WalkDemoActionFeedback value);
}
