int32 NUMBER_OF_CIRCUITS = 3
#
# Select which circuit to command
#
int32 circuit
#
# Defined circuits
#
int32 BASE      = 0
int32 RIGHT_ARM = 1
int32 LEFT_ARM  = 2
#
# Command to send to circuit:
# command = start, stop, reset, disable, none
#
string command  
#
# reset the latched voltage and current statistics
bool reset_stats
#
# reset the latched stats for each circuit
bool reset_circuits
---
# return if the command was successfully sent
bool success
