package object_manipulation_msgs;

public interface ReactiveGraspResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "object_manipulation_msgs/ReactiveGraspResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\n# the result of the reactive grasp attempt\n\nManipulationResult manipulation_result\n\n";
  object_manipulation_msgs.ManipulationResult getManipulationResult();
  void setManipulationResult(object_manipulation_msgs.ManipulationResult value);
}
