package object_manipulation_msgs;

public interface PlaceAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "object_manipulation_msgs/PlaceAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nPlaceActionGoal action_goal\nPlaceActionResult action_result\nPlaceActionFeedback action_feedback\n";
  object_manipulation_msgs.PlaceActionGoal getActionGoal();
  void setActionGoal(object_manipulation_msgs.PlaceActionGoal value);
  object_manipulation_msgs.PlaceActionResult getActionResult();
  void setActionResult(object_manipulation_msgs.PlaceActionResult value);
  object_manipulation_msgs.PlaceActionFeedback getActionFeedback();
  void setActionFeedback(object_manipulation_msgs.PlaceActionFeedback value);
}
