package us.ihmc.robotics.generatedTestSuites;

import org.junit.runner.RunWith;
import org.junit.runners.Suite.SuiteClasses;

import us.ihmc.tools.testing.TestPlanSuite;
import us.ihmc.tools.testing.TestPlanSuite.TestSuiteTarget;
import us.ihmc.tools.testing.TestPlanTarget;

/** WARNING: AUTO-GENERATED FILE. DO NOT MAKE MANUAL CHANGES TO THIS FILE. **/
@RunWith(TestPlanSuite.class)
@TestSuiteTarget(TestPlanTarget.Fast)
@SuiteClasses
({
   us.ihmc.robotics.alphaToAlpha.StretchedSlowInMiddleAlphaToAlphaFunctionTest.class,
   us.ihmc.robotics.controllers.CylindricalPDGainsTest.class,
   us.ihmc.robotics.controllers.GainCalculatorTest.class,
   us.ihmc.robotics.controllers.PDControllerTest.class,
   us.ihmc.robotics.controllers.PIDControllerTest.class,
   us.ihmc.robotics.controllers.YoPDGainsTest.class,
   us.ihmc.robotics.controllers.YoPIDGainsTest.class,
   us.ihmc.robotics.dataStructures.ComplexNumberTest.class,
   us.ihmc.robotics.dataStructures.DoubleHashHeightMapTest.class,
   us.ihmc.robotics.dataStructures.PolynomialTest.class,
   us.ihmc.robotics.dataStructures.registry.NameSpaceTest.class,
   us.ihmc.robotics.dataStructures.registry.YoVariableRegistryTest.class,
   us.ihmc.robotics.dataStructures.variable.BooleanYoVariableTest.class,
   us.ihmc.robotics.dataStructures.variable.DoubleYoVariableTest.class,
   us.ihmc.robotics.dataStructures.variable.EnumYoVariableTest.class,
   us.ihmc.robotics.dataStructures.variable.IntegerYoVariableTest.class,
   us.ihmc.robotics.dataStructures.variable.LongYoVariableTest.class,
   us.ihmc.robotics.dataStructures.variable.YoVariableListTest.class,
   us.ihmc.robotics.dataStructures.variable.YoVariableTest.class,
   us.ihmc.robotics.filters.GlitchFilterForDataSetTest.class,
   us.ihmc.robotics.filters.ZeroLagLowPassFilterTest.class,
   us.ihmc.robotics.functionApproximation.LinearMappingTest.class,
   us.ihmc.robotics.functionApproximation.LinearRegressionTest.class,
   us.ihmc.robotics.functionApproximation.OnlineLinearRegressionTest.class,
   us.ihmc.robotics.geometry.AngleToolsTest.class,
   us.ihmc.robotics.geometry.BoundingBox2dTest.class,
   us.ihmc.robotics.geometry.BoundingBox3dTest.class,
   us.ihmc.robotics.geometry.CapsuleTest.class,
   us.ihmc.robotics.geometry.ConvexHullCalculator2dTest.class,
   us.ihmc.robotics.geometry.ConvexPolygon2dTest.class,
   us.ihmc.robotics.geometry.ConvexPolygonShrinkerTest.class,
   us.ihmc.robotics.geometry.ConvexPolygonToolsTest.class,
   us.ihmc.robotics.geometry.DirectionTest.class,
   us.ihmc.robotics.geometry.FrameConvexPolygon2dTest.class,
   us.ihmc.robotics.geometry.FrameLine2dTest.class,
   us.ihmc.robotics.geometry.FrameLineTest.class,
   us.ihmc.robotics.geometry.FrameMatrix3DTest.class,
   us.ihmc.robotics.geometry.FrameOrientationTest.class,
   us.ihmc.robotics.geometry.FramePoint2dTest.class,
   us.ihmc.robotics.geometry.FramePointTest.class,
   us.ihmc.robotics.geometry.FramePoseTest.class,
   us.ihmc.robotics.geometry.FrameVector2dTest.class,
   us.ihmc.robotics.geometry.FrameVectorTest.class,
   us.ihmc.robotics.geometry.GeometryToolsTest.class,
   us.ihmc.robotics.geometry.GeoregressionConversionToolsTest.class,
   us.ihmc.robotics.geometry.HumanEvaluationLine2dTest.class,
   us.ihmc.robotics.geometry.InertiaToolsTest.class,
   us.ihmc.robotics.geometry.InPlaceConvexHullCalculator2dTest.class,
   us.ihmc.robotics.geometry.LeastSquaresZPlaneFitterTest.class,
   us.ihmc.robotics.geometry.Line2dTest.class,
   us.ihmc.robotics.geometry.LineSegment2dTest.class,
   us.ihmc.robotics.geometry.LineSegment3dTest.class,
   us.ihmc.robotics.geometry.PointToLineUnProjectorTest.class,
   us.ihmc.robotics.geometry.QuaternionRotationRelationshipTest.class,
   us.ihmc.robotics.geometry.RigidBodyTransformTest.class,
   us.ihmc.robotics.geometry.RotationalInertiaCalculatorTest.class,
   us.ihmc.robotics.geometry.RotationToolsTest.class,
   us.ihmc.robotics.geometry.shapes.BestFitPlaneCalculatorTest.class,
   us.ihmc.robotics.geometry.shapes.Box3dTest.class,
   us.ihmc.robotics.geometry.shapes.Cylinder3dTest.class,
   us.ihmc.robotics.geometry.shapes.Ellipsoid3dTest.class,
   us.ihmc.robotics.geometry.shapes.FrameBox3dTest.class,
   us.ihmc.robotics.geometry.shapes.FramePlane3dTest.class,
   us.ihmc.robotics.geometry.shapes.Plane3dTest.class,
   us.ihmc.robotics.geometry.shapes.QuickHull3DWrapperTest.class,
   us.ihmc.robotics.geometry.shapes.Ramp3dTest.class,
   us.ihmc.robotics.geometry.shapes.Sphere3dTest.class,
   us.ihmc.robotics.geometry.shapes.Torus3dTest.class,
   us.ihmc.robotics.geometry.SmallAngleRotationDerivativeTest.class,
   us.ihmc.robotics.geometry.SmallQuaternionRelationshipTest.class,
   us.ihmc.robotics.geometry.StringStretcher2dTest.class,
   us.ihmc.robotics.geometry.Transform3dTest.class,
   us.ihmc.robotics.geometry.TransformToolsTest.class,
   us.ihmc.robotics.hyperCubeTree.HyperCubeNodeTest.class,
   us.ihmc.robotics.hyperCubeTree.HyperCubeTreeTest.class,
   us.ihmc.robotics.hyperCubeTree.OctreeTest.class,
   us.ihmc.robotics.hyperCubeTree.OneDimensionalBoundsTest.class,
   us.ihmc.robotics.hyperCubeTree.SphericalLinearResolutionProviderTest.class,
   us.ihmc.robotics.kinematics.AverageQuaternionCalculatorTest.class,
   us.ihmc.robotics.kinematics.DdoglegInverseKinematicsCalculatorTest.class,
   us.ihmc.robotics.kinematics.fourbar.FourBarCalculatorsComparisonTest.class,
   us.ihmc.robotics.kinematics.fourbar.FourBarCalculatorTest.class,
   us.ihmc.robotics.kinematics.fourbar.FourBarCalculatorWithDerivativesTest.class,
   us.ihmc.robotics.kinematics.NumericalInverseKinematicsCalculatorTest.class,
   us.ihmc.robotics.kinematics.TimeStampedTransform3DTest.class,
   us.ihmc.robotics.kinematics.TransformInterpolationCalculatorTest.class,
   us.ihmc.robotics.lidar.AbstractLidarScanTest.class,
   us.ihmc.robotics.lidar.LidarScanParametersTest.class,
   us.ihmc.robotics.lidar.LidarScanTest.class,
   us.ihmc.robotics.linearAlgebra.MatrixExponentialCalculatorTest.class,
   us.ihmc.robotics.linearAlgebra.MatrixOfCofactorsCalculatorInefficientTest.class,
   us.ihmc.robotics.linearAlgebra.MatrixStatisticsTest.class,
   us.ihmc.robotics.linearAlgebra.MatrixToolsTest.class,
   us.ihmc.robotics.linearAlgebra.NullspaceCalculatorTest.class,
   us.ihmc.robotics.linearAlgebra.PrincipalComponentAnalysis3DTest.class,
   us.ihmc.robotics.linearDynamicSystems.BodeUnitsConverterTest.class,
   us.ihmc.robotics.linearDynamicSystems.ComplexConjugateModeTest.class,
   us.ihmc.robotics.linearDynamicSystems.ComplexMatrixTest.class,
   us.ihmc.robotics.linearDynamicSystems.EigenvalueDecomposerTest.class,
   us.ihmc.robotics.linearDynamicSystems.LinearDynamicSystemTest.class,
   us.ihmc.robotics.linearDynamicSystems.MassSpringDamperTest.class,
   us.ihmc.robotics.linearDynamicSystems.PolynomialMatrixTest.class,
   us.ihmc.robotics.linearDynamicSystems.SingleRealModeTest.class,
   us.ihmc.robotics.linearDynamicSystems.StateSpaceSystemDiscretizerTest.class,
   us.ihmc.robotics.linearDynamicSystems.TransferFunctionMatrixTest.class,
   us.ihmc.robotics.linearDynamicSystems.TransferFunctionTest.class,
   us.ihmc.robotics.lists.RecyclingArrayListTest.class,
   us.ihmc.robotics.math.corruptors.NoisyDoubleYoVariableTest.class
})

public class IHMCRoboticsToolkitAFastTestSuite
{
   public static void main(String[] args)
   {

   }
}
