#ifndef __unitree_go_msgs__msg__Error__idl__
#define __unitree_go_msgs__msg__Error__idl__

module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::Error_")
      struct Error
      {
        unsigned long error_source;
        unsigned long error_state;
      };
    };
  };
};

#endif
