#ifndef __unitree_go_msgs__msg__Go2FrontVideoData__idl__
#define __unitree_go_msgs__msg__Go2FrontVideoData__idl__

module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::Go2FrontVideoData_")
      struct Go2FrontVideoData
      {
        unsigned long long time_frame;
        sequence<octet> video720p;
        sequence<octet> video360p;
        sequence<octet> video180p;
      };
    };
  };
};

#endif
