#ifndef __unitree_go_msgs__msg__IMUState__idl__
#define __unitree_go_msgs__msg__IMUState__idl__

module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::IMUState_")
      struct IMUState
      {
        float quaternion[4];
        float gyroscope[3];
        float accelerometer[3];
        float rpy[3];
        octet temperature;
      };
    };
  };
};

#endif
