#ifndef __unitree_go_msgs__msg__LowCmd__idl__
#define __unitree_go_msgs__msg__LowCmd__idl__

#include "unitree_go_msgs/msg/./BmsCmd_.idl"
#include "unitree_go_msgs/msg/./MotorCmd_.idl"
module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::LowCmd_")
      struct LowCmd
      {
        octet head[2];
        octet level_flag;
        octet frame_reserve;
        unsigned_long sn[2];
        unsigned_long version[2];
        unsigned short bandwidth;
        unitree_go_msgs::msg::dds::MotorCmd motor_cmd[20];
        unitree_go_msgs::msg::dds::BmsCmd bms_cmd;
        octet wireless_remote[40];
        octet led[12];
        octet fan[2];
        octet gpio;
        unsigned long reserve;
        unsigned long crc;
      };
    };
  };
};

#endif
