#ifndef __unitree_go_msgs__msg__LowState__idl__
#define __unitree_go_msgs__msg__LowState__idl__

#include "unitree_go_msgs/msg/./BmsState_.idl"
#include "unitree_go_msgs/msg/./IMUState_.idl"
#include "unitree_go_msgs/msg/./MotorState_.idl"
module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::LowState_")
      struct LowState
      {
        octet head[2];
        octet level_flag;
        octet frame_reserve;
        unsigned_long sn[2];
        unsigned_long version[2];
        unsigned short bandwidth;
        unitree_go_msgs::msg::dds::IMUState imu_state;
        unitree_go_msgs::msg::dds::MotorState motor_state[20];
        unitree_go_msgs::msg::dds::BmsState bms_state;
        short foot_force[4];
        short foot_force_est[4];
        unsigned long tick;
        octet wireless_remote[40];
        octet bit_flag;
        float adc_reel;
        octet temperature_ntc1;
        octet temperature_ntc2;
        float power_v;
        float power_a;
        unsigned_short fan_frequency[4];
        unsigned long reserve;
        unsigned long crc;
      };
    };
  };
};

#endif
