#ifndef __unitree_go_msgs__msg__MotorStates__idl__
#define __unitree_go_msgs__msg__MotorStates__idl__

#include "unitree_go_msgs/msg/./MotorState_.idl"
module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::MotorStates_")
      struct MotorStates
      {
        sequence<unitree_go_msgs::msg::dds::MotorState> states;
      };
    };
  };
};

#endif
