#ifndef __unitree_go_msgs__msg__PathPoint__idl__
#define __unitree_go_msgs__msg__PathPoint__idl__

module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::PathPoint_")
      struct PathPoint
      {
        float t_from_start;
        float x;
        float y;
        float yaw;
        float vx;
        float vy;
        float vyaw;
      };
    };
  };
};

#endif
