#ifndef __unitree_go_msgs__msg__SportModeState__idl__
#define __unitree_go_msgs__msg__SportModeState__idl__

#include "unitree_go_msgs/msg/./IMUState_.idl"
#include "unitree_go_msgs/msg/./TimeSpec_.idl"
module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::SportModeState_")
      struct SportModeState
      {
        unitree_go_msgs::msg::dds::TimeSpec stamp;
        unsigned long error_code;
        unitree_go_msgs::msg::dds::IMUState imu_state;
        octet mode;
        float progress;
        octet gait_type;
        float foot_raise_height;
        float position[3];
        float body_height;
        float velocity[3];
        float yaw_speed;
        float range_obstacle[4];
        short foot_force[4];
        float foot_position_body[12];
        float foot_speed_body[12];
      };
    };
  };
};

#endif
