#ifndef __unitree_go_msgs__msg__TimeSpec__idl__
#define __unitree_go_msgs__msg__TimeSpec__idl__

module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::TimeSpec_")
      struct TimeSpec
      {
        /**
         * Time indicates a specific point in time, relative to a clock's 0 point.
         * The seconds component, valid over all int32 values.
         */
        long sec;
        /**
         * The nanoseconds component, valid in the range [0, 10e9).
         */
        unsigned long nanosec;
      };
    };
  };
};

#endif
