#ifndef __unitree_go_msgs__msg__UwbState__idl__
#define __unitree_go_msgs__msg__UwbState__idl__

module unitree_go_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_go_msgs::msg::dds_::UwbState_")
      struct UwbState
      {
        octet version[2];
        octet channel;
        octet joy_mode;
        float orientation_est;
        float pitch_est;
        float distance_est;
        float yaw_est;
        float tag_roll;
        float tag_pitch;
        float tag_yaw;
        float base_roll;
        float base_pitch;
        float base_yaw;
        float joystick[2];
        octet error_state;
        octet buttons;
        octet enabled_from_app;
      };
    };
  };
};

#endif
