# minimum corner point of axis-aligned bounding box in global frame
geometry_msgs/Point min
# maximum corner point of axis-aligned bounding box in global frame
geometry_msgs/Point max
---
# centers of all occupied voxels
geometry_msgs/Point[] occupied

# centers of all free voxels
geometry_msgs/Point[] free

# resolution of the octree = side length of all returned voxels
float64 resolution
