package us.ihmc.FrictionID.frictionModels;

public enum FrictionModel
{
   OFF, PRESSURE_BASED, ASYMMETRIC_COULOMB_VISCOUS, ASYMMETRIC_HYPERBOLIC_COULOMB_VISCOUS, ASYMMETRIC_COULOMB_VISCOUS_STRIBECK
}