package us.ihmc.commonWalkingControlModules.highLevelHumanoidControl.plugin;

import us.ihmc.commonWalkingControlModules.highLevelHumanoidControl.HighLevelMPCControllerFactoryHelper;

public interface HighLevelHumanoidMPCControllerPluginFactory
{
   HighLevelHumanoidMPCControllerPlugin buildPlugin(HighLevelMPCControllerFactoryHelper controllerFactoryHelper);
}
