# The UnloadController service allows you to unload a single controller 
# that is loaded in pr2_controller_manager. 

# To unload a controller, specify the "name" of the controller. 
# The return value "ok" indicates if the controller was unloaded or not.
# There are three cases when unloadinng a controller will fail:
#  * No controller with the specified name exists
#  * The controller is still running
#  * Another controller depends on the specified controller

string name
---
bool ok
