/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC external force estimation module.
It specifies where an expected external force will be applied.
<p>Source (toolbox_msgs/ExternalForceEstimationConfigurationMessage):
<pre>{@code
# This message is part of the IHMC external force estimation module.
# It specifies where an expected external force will be applied.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Estimator gain, usually in the range of 0.25 - 5.0. If the system is noisy or prone to oscillation, a lower gain is suggested.
float64 estimator_gain 0.5

# Specifies the alpha value used by the damped least-squares solver, usually in the range (1e-6 - 1e-2). For long joint paths, smaller alphas are recommended.
float64 solver_alpha 0.005

# Indicates whether the wrench at the root joint should be included in the solver
bool calculate_root_joint_wrench true

# List of unique hash codes corresponding to the rigid bodies at which the solver will calculate external forces.
# See RigidBody.hashCode() for calculation of the hash code
int32[<=10] rigid_body_hash_codes

# List of contact positions for each rigid body, expressed in RigidBody.getParentJoint().getFrameAfterJoint()
geometry_msgs/Point[<=10] contact_point_positions

# (in beta) Estimates the location of the contact point at a single rigid body (the first provided). The root joint wrench is not estimated.
bool estimate_contact_location}</pre>
*/
public class ExternalForceEstimationConfigurationMessage implements ROS2Message<ExternalForceEstimationConfigurationMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::ExternalForceEstimationConfigurationMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Estimator gain, usually in the range of 0.25 - 5.0. If the system is noisy or prone to oscillation, a lower gain is suggested.
   */
   private double estimator_gain_;
   /**
      Specifies the alpha value used by the damped least-squares solver, usually in the range (1e-6 - 1e-2). For long joint paths, smaller alphas are recommended.
   */
   private double solver_alpha_;
   /**
      Indicates whether the wrench at the root joint should be included in the solver
   */
   private boolean calculate_root_joint_wrench_;
   /**
      List of unique hash codes corresponding to the rigid bodies at which the solver will calculate external forces.
      See RigidBody.hashCode() for calculation of the hash code
   */
   private final IDLIntSequence rigid_body_hash_codes_;
   /**
      List of contact positions for each rigid body, expressed in RigidBody.getParentJoint().getFrameAfterJoint()
   */
   private final IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> contact_point_positions_;
   /**
      (in beta) Estimates the location of the contact point at a single rigid body (the first provided). The root joint wrench is not estimated.
   */
   private boolean estimate_contact_location_;

   public ExternalForceEstimationConfigurationMessage()
   {
      estimator_gain_ = (double) 0.5;
      solver_alpha_ = (double) 0.005;
      calculate_root_joint_wrench_ = (boolean) true;
      rigid_body_hash_codes_ = new IDLIntSequence(0, 10);
      contact_point_positions_ = new IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage>(0, 10, us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage.class);
      estimate_contact_location_ = (boolean) false;

   }

   public ExternalForceEstimationConfigurationMessage(ExternalForceEstimationConfigurationMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // estimator_gain_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // solver_alpha_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // calculate_root_joint_wrench_
      currentAlignment += rigid_body_hash_codes_.calculateSizeBytes(currentAlignment);
      currentAlignment += contact_point_positions_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // estimate_contact_location_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(estimator_gain_);
      buffer.writeDouble(solver_alpha_);
      buffer.writeBoolean(calculate_root_joint_wrench_);
      rigid_body_hash_codes_.serialize(buffer);
      contact_point_positions_.serialize(buffer);
      buffer.writeBoolean(estimate_contact_location_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      estimator_gain_ = buffer.readDouble();
      solver_alpha_ = buffer.readDouble();
      calculate_root_joint_wrench_ = buffer.readBoolean();
      rigid_body_hash_codes_.deserialize(buffer);
      contact_point_positions_.deserialize(buffer);
      estimate_contact_location_ = buffer.readBoolean();

   }

   @Override
   public void set(ExternalForceEstimationConfigurationMessage from)
   {
      sequence_id_ = from.sequence_id_;
      estimator_gain_ = from.estimator_gain_;
      solver_alpha_ = from.solver_alpha_;
      calculate_root_joint_wrench_ = from.calculate_root_joint_wrench_;
      rigid_body_hash_codes_.set(from.rigid_body_hash_codes_);
      contact_point_positions_.set(from.contact_point_positions_);
      estimate_contact_location_ = from.estimate_contact_location_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getEstimatorGain()
   {
      return estimator_gain_;
   }

   public void setEstimatorGain(double estimator_gain_)
   {
      this.estimator_gain_ = estimator_gain_;
   }

   public double getSolverAlpha()
   {
      return solver_alpha_;
   }

   public void setSolverAlpha(double solver_alpha_)
   {
      this.solver_alpha_ = solver_alpha_;
   }

   public boolean getCalculateRootJointWrench()
   {
      return calculate_root_joint_wrench_;
   }

   public void setCalculateRootJointWrench(boolean calculate_root_joint_wrench_)
   {
      this.calculate_root_joint_wrench_ = calculate_root_joint_wrench_;
   }

   public IDLIntSequence getRigidBodyHashCodes()
   {
      return rigid_body_hash_codes_;
   }

   public IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> getContactPointPositions()
   {
      return contact_point_positions_;
   }

   public boolean getEstimateContactLocation()
   {
      return estimate_contact_location_;
   }

   public void setEstimateContactLocation(boolean estimate_contact_location_)
   {
      this.estimate_contact_location_ = estimate_contact_location_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ExternalForceEstimationConfigurationMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("estimator_gain_=");
      builder.append(estimator_gain_);
      builder.append("solver_alpha_=");
      builder.append(solver_alpha_);
      builder.append("calculate_root_joint_wrench_=");
      builder.append(calculate_root_joint_wrench_);
      builder.append("rigid_body_hash_codes_=");
      builder.append(rigid_body_hash_codes_);
      builder.append("contact_point_positions_=");
      builder.append(contact_point_positions_);
      builder.append("estimate_contact_location_=");
      builder.append(estimate_contact_location_);

      builder.append("}");
      return builder.toString();
   }
}