/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC footstep planning module.
<p>Source (toolbox_msgs/FootstepPlanningTimingsMessage):
<pre>{@code
# This message is part of the IHMC footstep planning module.

# Total time measured in the planner process between receiving request message and publishing output message
float64 total_elapsed_seconds

# Elapsed time between receiving request message and starting to plan body path
float64 time_before_planning_seconds

# Elapsed time for planning body path
float64 time_planning_body_path_seconds

# Elapsed time for step planning
float64 time_planning_steps_seconds

# Number of iterations performed during path planning
int64 path_planning_iterations

# Number of iterations performed during step planning
int64 step_planning_iterations}</pre>
*/
public class FootstepPlanningTimingsMessage implements ROS2Message<FootstepPlanningTimingsMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::FootstepPlanningTimingsMessage_";

   /**
      Total time measured in the planner process between receiving request message and publishing output message
   */
   private double total_elapsed_seconds_;
   /**
      Elapsed time between receiving request message and starting to plan body path
   */
   private double time_before_planning_seconds_;
   /**
      Elapsed time for planning body path
   */
   private double time_planning_body_path_seconds_;
   /**
      Elapsed time for step planning
   */
   private double time_planning_steps_seconds_;
   /**
      Number of iterations performed during path planning
   */
   private long path_planning_iterations_;
   /**
      Number of iterations performed during step planning
   */
   private long step_planning_iterations_;

   public FootstepPlanningTimingsMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // total_elapsed_seconds_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // time_before_planning_seconds_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // time_planning_body_path_seconds_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // time_planning_steps_seconds_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // path_planning_iterations_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // step_planning_iterations_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(total_elapsed_seconds_);
      buffer.writeDouble(time_before_planning_seconds_);
      buffer.writeDouble(time_planning_body_path_seconds_);
      buffer.writeDouble(time_planning_steps_seconds_);
      buffer.writeLong(path_planning_iterations_);
      buffer.writeLong(step_planning_iterations_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      total_elapsed_seconds_ = buffer.readDouble();
      time_before_planning_seconds_ = buffer.readDouble();
      time_planning_body_path_seconds_ = buffer.readDouble();
      time_planning_steps_seconds_ = buffer.readDouble();
      path_planning_iterations_ = buffer.readLong();
      step_planning_iterations_ = buffer.readLong();

   }

   @Override
   public void set(FootstepPlanningTimingsMessage from)
   {
      total_elapsed_seconds_ = from.total_elapsed_seconds_;
      time_before_planning_seconds_ = from.time_before_planning_seconds_;
      time_planning_body_path_seconds_ = from.time_planning_body_path_seconds_;
      time_planning_steps_seconds_ = from.time_planning_steps_seconds_;
      path_planning_iterations_ = from.path_planning_iterations_;
      step_planning_iterations_ = from.step_planning_iterations_;

   }

   public double getTotalElapsedSeconds()
   {
      return total_elapsed_seconds_;
   }

   public void setTotalElapsedSeconds(double total_elapsed_seconds_)
   {
      this.total_elapsed_seconds_ = total_elapsed_seconds_;
   }

   public double getTimeBeforePlanningSeconds()
   {
      return time_before_planning_seconds_;
   }

   public void setTimeBeforePlanningSeconds(double time_before_planning_seconds_)
   {
      this.time_before_planning_seconds_ = time_before_planning_seconds_;
   }

   public double getTimePlanningBodyPathSeconds()
   {
      return time_planning_body_path_seconds_;
   }

   public void setTimePlanningBodyPathSeconds(double time_planning_body_path_seconds_)
   {
      this.time_planning_body_path_seconds_ = time_planning_body_path_seconds_;
   }

   public double getTimePlanningStepsSeconds()
   {
      return time_planning_steps_seconds_;
   }

   public void setTimePlanningStepsSeconds(double time_planning_steps_seconds_)
   {
      this.time_planning_steps_seconds_ = time_planning_steps_seconds_;
   }

   public long getPathPlanningIterations()
   {
      return path_planning_iterations_;
   }

   public void setPathPlanningIterations(long path_planning_iterations_)
   {
      this.path_planning_iterations_ = path_planning_iterations_;
   }

   public long getStepPlanningIterations()
   {
      return step_planning_iterations_;
   }

   public void setStepPlanningIterations(long step_planning_iterations_)
   {
      this.step_planning_iterations_ = step_planning_iterations_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("FootstepPlanningTimingsMessage {");
      builder.append("total_elapsed_seconds_=");
      builder.append(total_elapsed_seconds_);
      builder.append("time_before_planning_seconds_=");
      builder.append(time_before_planning_seconds_);
      builder.append("time_planning_body_path_seconds_=");
      builder.append(time_planning_body_path_seconds_);
      builder.append("time_planning_steps_seconds_=");
      builder.append(time_planning_steps_seconds_);
      builder.append("path_planning_iterations_=");
      builder.append(path_planning_iterations_);
      builder.append("step_planning_iterations_=");
      builder.append(step_planning_iterations_);

      builder.append("}");
      return builder.toString();
   }
}