/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC footstep planning module.
<p>Source (toolbox_msgs/FootstepPlanningToolboxOutputStatus):
<pre>{@code
# This message is part of the IHMC footstep planning module.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

byte BODY_PATH_PLANNING_RESULT_PLANNING = 0
byte BODY_PATH_PLANNING_RESULT_FOUND_SOLUTION = 1
byte BODY_PATH_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION = 2
byte BODY_PATH_PLANNING_RESULT_NO_PATH_EXISTS = 3
byte BODY_PATH_PLANNING_RESULT_INVALID_GOAL = 4
byte BODY_PATH_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED = 5
byte BODY_PATH_PLANNING_RESULT_EXCEPTION = 6
byte BODY_PATH_PLANNING_RESULT_HALTED = 7

byte FOOTSTEP_PLANNING_RESULT_PLANNING = 0
byte FOOTSTEP_PLANNING_RESULT_FOUND_SOLUTION = 1
byte FOOTSTEP_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION = 2
byte FOOTSTEP_PLANNING_RESULT_NO_PATH_EXISTS = 3
byte FOOTSTEP_PLANNING_RESULT_INVALID_GOAL = 4
byte FOOTSTEP_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED = 5
byte FOOTSTEP_PLANNING_RESULT_EXCEPTION = 6
byte FOOTSTEP_PLANNING_RESULT_HALTED = 7

int32 NO_PLAN_ID = -1

# ID of the request this output corresponds to
int32 plan_id -1

# Footstep plan, may be empty depending on the state of the planner, according to footstep_planning_result
controller_msgs/FootstepDataListMessage footstep_data_list

# Body path plan result. Null if no result is available
byte body_path_planning_result 255

# Footstep planner result. Null if no result is available
byte footstep_planning_result 255

# (deprecated) Height map that correspond to the request message. Originally used for debugging networking
perception_msgs/HeightMapMessage height_map_message

# Planned body path. Empty if planner failed
geometry_msgs/Pose[] body_path

# Planned body path before smoothing, used for debugging. Empty if planner failed
geometry_msgs/Point[] body_path_unsmoothed

# Goal pose used by the planner. This will be different from the requested goal pose if it's beyond the horizon length.
geometry_msgs/Pose goal_pose

# Object to record various planner timings, helpful for debugging
FootstepPlanningTimingsMessage planner_timings

# Contains planner stack trace if failure is due to an exception
string exception_message
string[<=20] stacktrace}</pre>
*/
public class FootstepPlanningToolboxOutputStatus implements ROS2Message<FootstepPlanningToolboxOutputStatus>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::FootstepPlanningToolboxOutputStatus_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   public static final byte BODY_PATH_PLANNING_RESULT_PLANNING = 0;
   public static final byte BODY_PATH_PLANNING_RESULT_FOUND_SOLUTION = 1;
   public static final byte BODY_PATH_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION = 2;
   public static final byte BODY_PATH_PLANNING_RESULT_NO_PATH_EXISTS = 3;
   public static final byte BODY_PATH_PLANNING_RESULT_INVALID_GOAL = 4;
   public static final byte BODY_PATH_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED = 5;
   public static final byte BODY_PATH_PLANNING_RESULT_EXCEPTION = 6;
   public static final byte BODY_PATH_PLANNING_RESULT_HALTED = 7;
   public static final byte FOOTSTEP_PLANNING_RESULT_PLANNING = 0;
   public static final byte FOOTSTEP_PLANNING_RESULT_FOUND_SOLUTION = 1;
   public static final byte FOOTSTEP_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION = 2;
   public static final byte FOOTSTEP_PLANNING_RESULT_NO_PATH_EXISTS = 3;
   public static final byte FOOTSTEP_PLANNING_RESULT_INVALID_GOAL = 4;
   public static final byte FOOTSTEP_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED = 5;
   public static final byte FOOTSTEP_PLANNING_RESULT_EXCEPTION = 6;
   public static final byte FOOTSTEP_PLANNING_RESULT_HALTED = 7;
   public static final int NO_PLAN_ID = -1;
   /**
      ID of the request this output corresponds to
   */
   private int plan_id_;
   /**
      Footstep plan, may be empty depending on the state of the planner, according to footstep_planning_result
   */
   private final controller_msgs.FootstepDataListMessage footstep_data_list_;
   /**
      Body path plan result. Null if no result is available
   */
   private byte body_path_planning_result_;
   /**
      Footstep planner result. Null if no result is available
   */
   private byte footstep_planning_result_;
   /**
      (deprecated) Height map that correspond to the request message. Originally used for debugging networking
   */
   private final perception_msgs.HeightMapMessage height_map_message_;
   /**
      Planned body path. Empty if planner failed
   */
   private final IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPose3DMessage> body_path_;
   /**
      Planned body path before smoothing, used for debugging. Empty if planner failed
   */
   private final IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> body_path_unsmoothed_;
   /**
      Goal pose used by the planner. This will be different from the requested goal pose if it's beyond the horizon length.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPose3DMessage goal_pose_;
   /**
      Object to record various planner timings, helpful for debugging
   */
   private final toolbox_msgs.FootstepPlanningTimingsMessage planner_timings_;
   /**
      Contains planner stack trace if failure is due to an exception
   */
   private final StringBuilder exception_message_;
   private final IDLStringSequence stacktrace_;

   public FootstepPlanningToolboxOutputStatus()
   {
      plan_id_ = (int) -1;
      footstep_data_list_ = new controller_msgs.FootstepDataListMessage();
      body_path_planning_result_ = (byte) 255;
      footstep_planning_result_ = (byte) 255;
      height_map_message_ = new perception_msgs.HeightMapMessage();
      body_path_ = new IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPose3DMessage>(us.ihmc.euclid.jros2.messages.EuclidPose3DMessage.class);
      body_path_unsmoothed_ = new IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage>(us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage.class);
      goal_pose_ = new us.ihmc.euclid.jros2.messages.EuclidPose3DMessage();
      planner_timings_ = new toolbox_msgs.FootstepPlanningTimingsMessage();
      exception_message_ = new StringBuilder();
      stacktrace_ = new IDLStringSequence(0);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // plan_id_
      currentAlignment += footstep_data_list_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // body_path_planning_result_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // footstep_planning_result_
      currentAlignment += height_map_message_.calculateSizeBytes(currentAlignment);
      currentAlignment += body_path_.calculateSizeBytes(currentAlignment);
      currentAlignment += body_path_unsmoothed_.calculateSizeBytes(currentAlignment);
      currentAlignment += goal_pose_.calculateSizeBytes(currentAlignment);
      currentAlignment += planner_timings_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * exception_message_.length()) + 1; // exception_message_
      currentAlignment += stacktrace_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeInt(plan_id_);
      footstep_data_list_.serialize(buffer);
      buffer.writeByte(body_path_planning_result_);
      buffer.writeByte(footstep_planning_result_);
      height_map_message_.serialize(buffer);
      body_path_.serialize(buffer);
      body_path_unsmoothed_.serialize(buffer);
      goal_pose_.serialize(buffer);
      planner_timings_.serialize(buffer);
      buffer.writeString(exception_message_);
      stacktrace_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      plan_id_ = buffer.readInt();
      footstep_data_list_.deserialize(buffer);
      body_path_planning_result_ = buffer.readByte();
      footstep_planning_result_ = buffer.readByte();
      height_map_message_.deserialize(buffer);
      body_path_.deserialize(buffer);
      body_path_unsmoothed_.deserialize(buffer);
      goal_pose_.deserialize(buffer);
      planner_timings_.deserialize(buffer);
      buffer.readString(exception_message_);
      stacktrace_.deserialize(buffer);

   }

   @Override
   public void set(FootstepPlanningToolboxOutputStatus from)
   {
      sequence_id_ = from.sequence_id_;
      plan_id_ = from.plan_id_;
      footstep_data_list_.set(from.footstep_data_list_);
      body_path_planning_result_ = from.body_path_planning_result_;
      footstep_planning_result_ = from.footstep_planning_result_;
      height_map_message_.set(from.height_map_message_);
      body_path_.set(from.body_path_);
      body_path_unsmoothed_.set(from.body_path_unsmoothed_);
      goal_pose_.set(from.goal_pose_);
      planner_timings_.set(from.planner_timings_);
      exception_message_.delete(0, exception_message_.length());
      exception_message_.insert(0, from.exception_message_);
      stacktrace_.set(from.stacktrace_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public int getPlanId()
   {
      return plan_id_;
   }

   public void setPlanId(int plan_id_)
   {
      this.plan_id_ = plan_id_;
   }

   public controller_msgs.FootstepDataListMessage getFootstepDataList()
   {
      return footstep_data_list_;
   }

   public byte getBodyPathPlanningResult()
   {
      return body_path_planning_result_;
   }

   public void setBodyPathPlanningResult(byte body_path_planning_result_)
   {
      this.body_path_planning_result_ = body_path_planning_result_;
   }

   public byte getFootstepPlanningResult()
   {
      return footstep_planning_result_;
   }

   public void setFootstepPlanningResult(byte footstep_planning_result_)
   {
      this.footstep_planning_result_ = footstep_planning_result_;
   }

   public perception_msgs.HeightMapMessage getHeightMapMessage()
   {
      return height_map_message_;
   }

   public IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPose3DMessage> getBodyPath()
   {
      return body_path_;
   }

   public IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> getBodyPathUnsmoothed()
   {
      return body_path_unsmoothed_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPose3DMessage getGoalPose()
   {
      return goal_pose_;
   }

   public toolbox_msgs.FootstepPlanningTimingsMessage getPlannerTimings()
   {
      return planner_timings_;
   }

   public StringBuilder getExceptionMessage()
   {
      return exception_message_;
   }

   public java.lang.String getExceptionMessageAsString()
   {
      return exception_message_.toString();
   }

   public void setExceptionMessage(java.lang.String s)
   {
      this.exception_message_.delete(0, this.exception_message_.length());
      this.exception_message_.insert(0, s);
   }
   public IDLStringSequence getStacktrace()
   {
      return stacktrace_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("FootstepPlanningToolboxOutputStatus {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("BODY_PATH_PLANNING_RESULT_PLANNING=");
      builder.append(BODY_PATH_PLANNING_RESULT_PLANNING);
      builder.append("BODY_PATH_PLANNING_RESULT_FOUND_SOLUTION=");
      builder.append(BODY_PATH_PLANNING_RESULT_FOUND_SOLUTION);
      builder.append("BODY_PATH_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION=");
      builder.append(BODY_PATH_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION);
      builder.append("BODY_PATH_PLANNING_RESULT_NO_PATH_EXISTS=");
      builder.append(BODY_PATH_PLANNING_RESULT_NO_PATH_EXISTS);
      builder.append("BODY_PATH_PLANNING_RESULT_INVALID_GOAL=");
      builder.append(BODY_PATH_PLANNING_RESULT_INVALID_GOAL);
      builder.append("BODY_PATH_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED=");
      builder.append(BODY_PATH_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED);
      builder.append("BODY_PATH_PLANNING_RESULT_EXCEPTION=");
      builder.append(BODY_PATH_PLANNING_RESULT_EXCEPTION);
      builder.append("BODY_PATH_PLANNING_RESULT_HALTED=");
      builder.append(BODY_PATH_PLANNING_RESULT_HALTED);
      builder.append("FOOTSTEP_PLANNING_RESULT_PLANNING=");
      builder.append(FOOTSTEP_PLANNING_RESULT_PLANNING);
      builder.append("FOOTSTEP_PLANNING_RESULT_FOUND_SOLUTION=");
      builder.append(FOOTSTEP_PLANNING_RESULT_FOUND_SOLUTION);
      builder.append("FOOTSTEP_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION=");
      builder.append(FOOTSTEP_PLANNING_RESULT_TIMED_OUT_BEFORE_SOLUTION);
      builder.append("FOOTSTEP_PLANNING_RESULT_NO_PATH_EXISTS=");
      builder.append(FOOTSTEP_PLANNING_RESULT_NO_PATH_EXISTS);
      builder.append("FOOTSTEP_PLANNING_RESULT_INVALID_GOAL=");
      builder.append(FOOTSTEP_PLANNING_RESULT_INVALID_GOAL);
      builder.append("FOOTSTEP_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED=");
      builder.append(FOOTSTEP_PLANNING_RESULT_MAXIMUM_ITERATIONS_REACHED);
      builder.append("FOOTSTEP_PLANNING_RESULT_EXCEPTION=");
      builder.append(FOOTSTEP_PLANNING_RESULT_EXCEPTION);
      builder.append("FOOTSTEP_PLANNING_RESULT_HALTED=");
      builder.append(FOOTSTEP_PLANNING_RESULT_HALTED);
      builder.append("NO_PLAN_ID=");
      builder.append(NO_PLAN_ID);
      builder.append("plan_id_=");
      builder.append(plan_id_);
      builder.append("footstep_data_list_=");
      builder.append(footstep_data_list_);
      builder.append("body_path_planning_result_=");
      builder.append(body_path_planning_result_);
      builder.append("footstep_planning_result_=");
      builder.append(footstep_planning_result_);
      builder.append("height_map_message_=");
      builder.append(height_map_message_);
      builder.append("body_path_=");
      builder.append(body_path_);
      builder.append("body_path_unsmoothed_=");
      builder.append(body_path_unsmoothed_);
      builder.append("goal_pose_=");
      builder.append(goal_pose_);
      builder.append("planner_timings_=");
      builder.append(planner_timings_);
      builder.append("exception_message_=");
      builder.append(exception_message_.toString());
      builder.append("stacktrace_=");
      builder.append(stacktrace_);

      builder.append("}");
      return builder.toString();
   }
}