/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message contains all the information needed to estimate footsteps for the robot based on VR trackers
<p>Source (toolbox_msgs/FootstepStreamingToolboxSideMessage):
<pre>{@code
# This message contains all the information needed to estimate footsteps for the robot based on VR trackers

byte ROBOT_SIDE_LEFT = 0
byte ROBOT_SIDE_RIGHT = 1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Specifies which foot/tracker
byte side 255

# The timestamp of the  last read from the tracker
int64 timestamp 0

# Current position of the robot foot frame's origin.
# The data is assumed to be expressed in world frame.
geometry_msgs/Point robot_foot_position_in_world
# Current orientation of the robot foot frame.
# The data is assumed to be expressed in world frame.
geometry_msgs/Quaternion robot_foot_orientation_in_world

# Current position of the tracker frame's origin.
# The data is assumed to be expressed in world frame.
geometry_msgs/Point current_position_in_world
# Current orientation of the tracker frame.
# The data is assumed to be expressed in world frame.
geometry_msgs/Quaternion current_orientation_in_world

# Whether the current linear velocity is defined.
bool has_current_velocity
# The current linear velocity of the tracker frame's origin.
geometry_msgs/Vector3 current_linear_velocity_in_world
# The current angular velocity of the tracker frame.
geometry_msgs/Vector3 current_angular_velocity_in_world}</pre>
*/
public class FootstepStreamingToolboxSideMessage implements ROS2Message<FootstepStreamingToolboxSideMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::FootstepStreamingToolboxSideMessage_";

   public static final byte ROBOT_SIDE_LEFT = 0;
   public static final byte ROBOT_SIDE_RIGHT = 1;
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Specifies which foot/tracker
   */
   private byte side_;
   /**
      The timestamp of the  last read from the tracker
   */
   private long timestamp_;
   /**
      Current position of the robot foot frame's origin.
      The data is assumed to be expressed in world frame.
   */
   private final geometry_msgs.Point robot_foot_position_in_world_;
   /**
      Current orientation of the robot foot frame.
      The data is assumed to be expressed in world frame.
   */
   private final geometry_msgs.Quaternion robot_foot_orientation_in_world_;
   /**
      Current position of the tracker frame's origin.
      The data is assumed to be expressed in world frame.
   */
   private final geometry_msgs.Point current_position_in_world_;
   /**
      Current orientation of the tracker frame.
      The data is assumed to be expressed in world frame.
   */
   private final geometry_msgs.Quaternion current_orientation_in_world_;
   /**
      Whether the current linear velocity is defined.
   */
   private boolean has_current_velocity_;
   /**
      The current linear velocity of the tracker frame's origin.
   */
   private final geometry_msgs.Vector3 current_linear_velocity_in_world_;
   /**
      The current angular velocity of the tracker frame.
   */
   private final geometry_msgs.Vector3 current_angular_velocity_in_world_;

   public FootstepStreamingToolboxSideMessage()
   {
      side_ = (byte) 255;
      timestamp_ = (long) 0;
      robot_foot_position_in_world_ = new geometry_msgs.Point();
      robot_foot_orientation_in_world_ = new geometry_msgs.Quaternion();
      current_position_in_world_ = new geometry_msgs.Point();
      current_orientation_in_world_ = new geometry_msgs.Quaternion();
      has_current_velocity_ = (boolean) false;
      current_linear_velocity_in_world_ = new geometry_msgs.Vector3();
      current_angular_velocity_in_world_ = new geometry_msgs.Vector3();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // side_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // timestamp_
      currentAlignment += robot_foot_position_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += robot_foot_orientation_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += current_position_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += current_orientation_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // has_current_velocity_
      currentAlignment += current_linear_velocity_in_world_.calculateSizeBytes(currentAlignment);
      currentAlignment += current_angular_velocity_in_world_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(side_);
      buffer.writeLong(timestamp_);
      robot_foot_position_in_world_.serialize(buffer);
      robot_foot_orientation_in_world_.serialize(buffer);
      current_position_in_world_.serialize(buffer);
      current_orientation_in_world_.serialize(buffer);
      buffer.writeBoolean(has_current_velocity_);
      current_linear_velocity_in_world_.serialize(buffer);
      current_angular_velocity_in_world_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      side_ = buffer.readByte();
      timestamp_ = buffer.readLong();
      robot_foot_position_in_world_.deserialize(buffer);
      robot_foot_orientation_in_world_.deserialize(buffer);
      current_position_in_world_.deserialize(buffer);
      current_orientation_in_world_.deserialize(buffer);
      has_current_velocity_ = buffer.readBoolean();
      current_linear_velocity_in_world_.deserialize(buffer);
      current_angular_velocity_in_world_.deserialize(buffer);

   }

   @Override
   public void set(FootstepStreamingToolboxSideMessage from)
   {
      sequence_id_ = from.sequence_id_;
      side_ = from.side_;
      timestamp_ = from.timestamp_;
      robot_foot_position_in_world_.set(from.robot_foot_position_in_world_);
      robot_foot_orientation_in_world_.set(from.robot_foot_orientation_in_world_);
      current_position_in_world_.set(from.current_position_in_world_);
      current_orientation_in_world_.set(from.current_orientation_in_world_);
      has_current_velocity_ = from.has_current_velocity_;
      current_linear_velocity_in_world_.set(from.current_linear_velocity_in_world_);
      current_angular_velocity_in_world_.set(from.current_angular_velocity_in_world_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getSide()
   {
      return side_;
   }

   public void setSide(byte side_)
   {
      this.side_ = side_;
   }

   public long getTimestamp()
   {
      return timestamp_;
   }

   public void setTimestamp(long timestamp_)
   {
      this.timestamp_ = timestamp_;
   }

   public geometry_msgs.Point getRobotFootPositionInWorld()
   {
      return robot_foot_position_in_world_;
   }

   public geometry_msgs.Quaternion getRobotFootOrientationInWorld()
   {
      return robot_foot_orientation_in_world_;
   }

   public geometry_msgs.Point getCurrentPositionInWorld()
   {
      return current_position_in_world_;
   }

   public geometry_msgs.Quaternion getCurrentOrientationInWorld()
   {
      return current_orientation_in_world_;
   }

   public boolean getHasCurrentVelocity()
   {
      return has_current_velocity_;
   }

   public void setHasCurrentVelocity(boolean has_current_velocity_)
   {
      this.has_current_velocity_ = has_current_velocity_;
   }

   public geometry_msgs.Vector3 getCurrentLinearVelocityInWorld()
   {
      return current_linear_velocity_in_world_;
   }

   public geometry_msgs.Vector3 getCurrentAngularVelocityInWorld()
   {
      return current_angular_velocity_in_world_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("FootstepStreamingToolboxSideMessage {");
      builder.append("ROBOT_SIDE_LEFT=");
      builder.append(ROBOT_SIDE_LEFT);
      builder.append("ROBOT_SIDE_RIGHT=");
      builder.append(ROBOT_SIDE_RIGHT);
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("side_=");
      builder.append(side_);
      builder.append("timestamp_=");
      builder.append(timestamp_);
      builder.append("robot_foot_position_in_world_=");
      builder.append(robot_foot_position_in_world_);
      builder.append("robot_foot_orientation_in_world_=");
      builder.append(robot_foot_orientation_in_world_);
      builder.append("current_position_in_world_=");
      builder.append(current_position_in_world_);
      builder.append("current_orientation_in_world_=");
      builder.append(current_orientation_in_world_);
      builder.append("has_current_velocity_=");
      builder.append(has_current_velocity_);
      builder.append("current_linear_velocity_in_world_=");
      builder.append(current_linear_velocity_in_world_);
      builder.append("current_angular_velocity_in_world_=");
      builder.append(current_angular_velocity_in_world_);

      builder.append("}");
      return builder.toString();
   }
}