/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
General purpose message normally used to report the solution of a whole-body inverse kinematics solver.
Main usage is for the IHMC KinematicsToolbox.
<p>Source (toolbox_msgs/KinematicsToolboxOutputStatus):
<pre>{@code
# General purpose message normally used to report the solution of a whole-body inverse kinematics solver.
# Main usage is for the IHMC KinematicsToolbox.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# Nothing reported by the toolbox.
byte CURRENT_TOOLBOX_STATE_NO_STATUS = 0
# The toolbox just initialized successfully and is about to start running.
byte CURRENT_TOOLBOX_STATE_INITIALIZE_SUCCESSFUL = 1
# The toolbox failed its initialization and cannot run until it succeeds.
# This failure specifies that the toolbox has not received RobotConfigurationData from the IHMC walking controller.
byte CURRENT_TOOLBOX_STATE_INITIALIZE_FAILURE_MISSING_RCD = 2
# The toolbox has been initialized properly and is running.
byte CURRENT_TOOLBOX_STATE_RUNNING = 3

# Provides insight about the current state of the toolbox, e.g. waiting for user input or waiting for controller input.
byte current_toolbox_state 0

int32 joint_name_hash

# Desired joint positions.
float32[] desired_joint_angles

# Desired root joint position in world frame.
geometry_msgs/Point desired_root_position
# Desired root joint orientation in world frame.
geometry_msgs/Quaternion desired_root_orientation

# Desired joint velocities.
float32[] desired_joint_velocities

# Desired linear velocity of the root joint expressed in local frame.
geometry_msgs/Vector3 desired_root_linear_velocity
# Desired angular velocity of the root joint expressed in local frame.
geometry_msgs/Vector3 desired_root_angular_velocity

# Support region used by the toolbox
geometry_msgs/Point[<=32] support_region

# Desired joint velocities derived from finite difference from positions at publishing period.
float32[] desired_joint_velocities_publishing_period
# Desired linear velocity of the root joint expressed in local frame, derived from finite difference from positions at publishing period.
geometry_msgs/Vector3 desired_root_linear_velocity_publishing_period
# Desired angular velocity of the root joint expressed in local frame, derived from finite difference from positions at publishing period.
geometry_msgs/Vector3 desired_root_angular_velocity_publishing_period

geometry_msgs/Point desired_torso_position
geometry_msgs/Quaternion desired_torso_orientation

float32 com_offset

# Legged robot-specific contact information (false if not a legged robot)
bool left_foot_in_contact
bool right_foot_in_contact

float64 solution_quality -1}</pre>
*/
public class KinematicsToolboxOutputStatus implements ROS2Message<KinematicsToolboxOutputStatus>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::KinematicsToolboxOutputStatus_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      Nothing reported by the toolbox.
   */
   public static final byte CURRENT_TOOLBOX_STATE_NO_STATUS = 0;
   /**
      The toolbox just initialized successfully and is about to start running.
   */
   public static final byte CURRENT_TOOLBOX_STATE_INITIALIZE_SUCCESSFUL = 1;
   /**
      The toolbox failed its initialization and cannot run until it succeeds.
      This failure specifies that the toolbox has not received RobotConfigurationData from the IHMC walking controller.
   */
   public static final byte CURRENT_TOOLBOX_STATE_INITIALIZE_FAILURE_MISSING_RCD = 2;
   /**
      The toolbox has been initialized properly and is running.
   */
   public static final byte CURRENT_TOOLBOX_STATE_RUNNING = 3;
   /**
      Provides insight about the current state of the toolbox, e.g. waiting for user input or waiting for controller input.
   */
   private byte current_toolbox_state_;
   private int joint_name_hash_;
   /**
      Desired joint positions.
   */
   private final IDLFloatSequence desired_joint_angles_;
   /**
      Desired root joint position in world frame.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage desired_root_position_;
   /**
      Desired root joint orientation in world frame.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage desired_root_orientation_;
   /**
      Desired joint velocities.
   */
   private final IDLFloatSequence desired_joint_velocities_;
   /**
      Desired linear velocity of the root joint expressed in local frame.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidVector3DMessage desired_root_linear_velocity_;
   /**
      Desired angular velocity of the root joint expressed in local frame.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidVector3DMessage desired_root_angular_velocity_;
   /**
      Support region used by the toolbox
   */
   private final IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> support_region_;
   /**
      Desired joint velocities derived from finite difference from positions at publishing period.
   */
   private final IDLFloatSequence desired_joint_velocities_publishing_period_;
   /**
      Desired linear velocity of the root joint expressed in local frame, derived from finite difference from positions at publishing period.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidVector3DMessage desired_root_linear_velocity_publishing_period_;
   /**
      Desired angular velocity of the root joint expressed in local frame, derived from finite difference from positions at publishing period.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidVector3DMessage desired_root_angular_velocity_publishing_period_;
   private final us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage desired_torso_position_;
   private final us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage desired_torso_orientation_;
   private float com_offset_;
   /**
      Legged robot-specific contact information (false if not a legged robot)
   */
   private boolean left_foot_in_contact_;
   private boolean right_foot_in_contact_;
   private double solution_quality_;

   public KinematicsToolboxOutputStatus()
   {
      current_toolbox_state_ = (byte) 0;
      desired_joint_angles_ = new IDLFloatSequence();
      desired_root_position_ = new us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage();
      desired_root_orientation_ = new us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage();
      desired_joint_velocities_ = new IDLFloatSequence();
      desired_root_linear_velocity_ = new us.ihmc.euclid.jros2.messages.EuclidVector3DMessage();
      desired_root_angular_velocity_ = new us.ihmc.euclid.jros2.messages.EuclidVector3DMessage();
      support_region_ = new IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage>(0, 32, us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage.class);
      desired_joint_velocities_publishing_period_ = new IDLFloatSequence();
      desired_root_linear_velocity_publishing_period_ = new us.ihmc.euclid.jros2.messages.EuclidVector3DMessage();
      desired_root_angular_velocity_publishing_period_ = new us.ihmc.euclid.jros2.messages.EuclidVector3DMessage();
      desired_torso_position_ = new us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage();
      desired_torso_orientation_ = new us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage();
      left_foot_in_contact_ = (boolean) false;
      right_foot_in_contact_ = (boolean) false;
      solution_quality_ = (double) -1;

   }

   public KinematicsToolboxOutputStatus(KinematicsToolboxOutputStatus from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // current_toolbox_state_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // joint_name_hash_
      currentAlignment += desired_joint_angles_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_root_position_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_root_orientation_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_joint_velocities_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_root_linear_velocity_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_root_angular_velocity_.calculateSizeBytes(currentAlignment);
      currentAlignment += support_region_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_joint_velocities_publishing_period_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_root_linear_velocity_publishing_period_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_root_angular_velocity_publishing_period_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_torso_position_.calculateSizeBytes(currentAlignment);
      currentAlignment += desired_torso_orientation_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // com_offset_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // left_foot_in_contact_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // right_foot_in_contact_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // solution_quality_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeByte(current_toolbox_state_);
      buffer.writeInt(joint_name_hash_);
      desired_joint_angles_.serialize(buffer);
      desired_root_position_.serialize(buffer);
      desired_root_orientation_.serialize(buffer);
      desired_joint_velocities_.serialize(buffer);
      desired_root_linear_velocity_.serialize(buffer);
      desired_root_angular_velocity_.serialize(buffer);
      support_region_.serialize(buffer);
      desired_joint_velocities_publishing_period_.serialize(buffer);
      desired_root_linear_velocity_publishing_period_.serialize(buffer);
      desired_root_angular_velocity_publishing_period_.serialize(buffer);
      desired_torso_position_.serialize(buffer);
      desired_torso_orientation_.serialize(buffer);
      buffer.writeFloat(com_offset_);
      buffer.writeBoolean(left_foot_in_contact_);
      buffer.writeBoolean(right_foot_in_contact_);
      buffer.writeDouble(solution_quality_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      current_toolbox_state_ = buffer.readByte();
      joint_name_hash_ = buffer.readInt();
      desired_joint_angles_.deserialize(buffer);
      desired_root_position_.deserialize(buffer);
      desired_root_orientation_.deserialize(buffer);
      desired_joint_velocities_.deserialize(buffer);
      desired_root_linear_velocity_.deserialize(buffer);
      desired_root_angular_velocity_.deserialize(buffer);
      support_region_.deserialize(buffer);
      desired_joint_velocities_publishing_period_.deserialize(buffer);
      desired_root_linear_velocity_publishing_period_.deserialize(buffer);
      desired_root_angular_velocity_publishing_period_.deserialize(buffer);
      desired_torso_position_.deserialize(buffer);
      desired_torso_orientation_.deserialize(buffer);
      com_offset_ = buffer.readFloat();
      left_foot_in_contact_ = buffer.readBoolean();
      right_foot_in_contact_ = buffer.readBoolean();
      solution_quality_ = buffer.readDouble();

   }

   @Override
   public void set(KinematicsToolboxOutputStatus from)
   {
      sequence_id_ = from.sequence_id_;
      current_toolbox_state_ = from.current_toolbox_state_;
      joint_name_hash_ = from.joint_name_hash_;
      desired_joint_angles_.set(from.desired_joint_angles_);
      desired_root_position_.set(from.desired_root_position_);
      desired_root_orientation_.set(from.desired_root_orientation_);
      desired_joint_velocities_.set(from.desired_joint_velocities_);
      desired_root_linear_velocity_.set(from.desired_root_linear_velocity_);
      desired_root_angular_velocity_.set(from.desired_root_angular_velocity_);
      support_region_.set(from.support_region_);
      desired_joint_velocities_publishing_period_.set(from.desired_joint_velocities_publishing_period_);
      desired_root_linear_velocity_publishing_period_.set(from.desired_root_linear_velocity_publishing_period_);
      desired_root_angular_velocity_publishing_period_.set(from.desired_root_angular_velocity_publishing_period_);
      desired_torso_position_.set(from.desired_torso_position_);
      desired_torso_orientation_.set(from.desired_torso_orientation_);
      com_offset_ = from.com_offset_;
      left_foot_in_contact_ = from.left_foot_in_contact_;
      right_foot_in_contact_ = from.right_foot_in_contact_;
      solution_quality_ = from.solution_quality_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public byte getCurrentToolboxState()
   {
      return current_toolbox_state_;
   }

   public void setCurrentToolboxState(byte current_toolbox_state_)
   {
      this.current_toolbox_state_ = current_toolbox_state_;
   }

   public int getJointNameHash()
   {
      return joint_name_hash_;
   }

   public void setJointNameHash(int joint_name_hash_)
   {
      this.joint_name_hash_ = joint_name_hash_;
   }

   public IDLFloatSequence getDesiredJointAngles()
   {
      return desired_joint_angles_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage getDesiredRootPosition()
   {
      return desired_root_position_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage getDesiredRootOrientation()
   {
      return desired_root_orientation_;
   }

   public IDLFloatSequence getDesiredJointVelocities()
   {
      return desired_joint_velocities_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidVector3DMessage getDesiredRootLinearVelocity()
   {
      return desired_root_linear_velocity_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidVector3DMessage getDesiredRootAngularVelocity()
   {
      return desired_root_angular_velocity_;
   }

   public IDLObjectSequence<us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage> getSupportRegion()
   {
      return support_region_;
   }

   public IDLFloatSequence getDesiredJointVelocitiesPublishingPeriod()
   {
      return desired_joint_velocities_publishing_period_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidVector3DMessage getDesiredRootLinearVelocityPublishingPeriod()
   {
      return desired_root_linear_velocity_publishing_period_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidVector3DMessage getDesiredRootAngularVelocityPublishingPeriod()
   {
      return desired_root_angular_velocity_publishing_period_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidPoint3DMessage getDesiredTorsoPosition()
   {
      return desired_torso_position_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidQuaternionMessage getDesiredTorsoOrientation()
   {
      return desired_torso_orientation_;
   }

   public float getComOffset()
   {
      return com_offset_;
   }

   public void setComOffset(float com_offset_)
   {
      this.com_offset_ = com_offset_;
   }

   public boolean getLeftFootInContact()
   {
      return left_foot_in_contact_;
   }

   public void setLeftFootInContact(boolean left_foot_in_contact_)
   {
      this.left_foot_in_contact_ = left_foot_in_contact_;
   }

   public boolean getRightFootInContact()
   {
      return right_foot_in_contact_;
   }

   public void setRightFootInContact(boolean right_foot_in_contact_)
   {
      this.right_foot_in_contact_ = right_foot_in_contact_;
   }

   public double getSolutionQuality()
   {
      return solution_quality_;
   }

   public void setSolutionQuality(double solution_quality_)
   {
      this.solution_quality_ = solution_quality_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("KinematicsToolboxOutputStatus {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("CURRENT_TOOLBOX_STATE_NO_STATUS=");
      builder.append(CURRENT_TOOLBOX_STATE_NO_STATUS);
      builder.append("CURRENT_TOOLBOX_STATE_INITIALIZE_SUCCESSFUL=");
      builder.append(CURRENT_TOOLBOX_STATE_INITIALIZE_SUCCESSFUL);
      builder.append("CURRENT_TOOLBOX_STATE_INITIALIZE_FAILURE_MISSING_RCD=");
      builder.append(CURRENT_TOOLBOX_STATE_INITIALIZE_FAILURE_MISSING_RCD);
      builder.append("CURRENT_TOOLBOX_STATE_RUNNING=");
      builder.append(CURRENT_TOOLBOX_STATE_RUNNING);
      builder.append("current_toolbox_state_=");
      builder.append(current_toolbox_state_);
      builder.append("joint_name_hash_=");
      builder.append(joint_name_hash_);
      builder.append("desired_joint_angles_=");
      builder.append(desired_joint_angles_);
      builder.append("desired_root_position_=");
      builder.append(desired_root_position_);
      builder.append("desired_root_orientation_=");
      builder.append(desired_root_orientation_);
      builder.append("desired_joint_velocities_=");
      builder.append(desired_joint_velocities_);
      builder.append("desired_root_linear_velocity_=");
      builder.append(desired_root_linear_velocity_);
      builder.append("desired_root_angular_velocity_=");
      builder.append(desired_root_angular_velocity_);
      builder.append("support_region_=");
      builder.append(support_region_);
      builder.append("desired_joint_velocities_publishing_period_=");
      builder.append(desired_joint_velocities_publishing_period_);
      builder.append("desired_root_linear_velocity_publishing_period_=");
      builder.append(desired_root_linear_velocity_publishing_period_);
      builder.append("desired_root_angular_velocity_publishing_period_=");
      builder.append(desired_root_angular_velocity_publishing_period_);
      builder.append("desired_torso_position_=");
      builder.append(desired_torso_position_);
      builder.append("desired_torso_orientation_=");
      builder.append(desired_torso_orientation_);
      builder.append("com_offset_=");
      builder.append(com_offset_);
      builder.append("left_foot_in_contact_=");
      builder.append(left_foot_in_contact_);
      builder.append("right_foot_in_contact_=");
      builder.append(right_foot_in_contact_);
      builder.append("solution_quality_=");
      builder.append(solution_quality_);

      builder.append("}");
      return builder.toString();
   }
}