/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC whole-body inverse kinematics module.
This message contains all the information needed to configure the objectives/constraints to apply on
a given 1-DoF joint in the solver.
<p>Source (toolbox_msgs/KinematicsToolboxOneDoFJointMessage):
<pre>{@code
# This message is part of the IHMC whole-body inverse kinematics module.
# This message contains all the information needed to configure the objectives/constraints to apply on 
# a given 1-DoF joint in the solver.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# The is the unique hash code of the joint to be solved for.
# It is used on the solver side to retrieve the desired joint to be controlled.
# See Joint.hashCode() for the computation of a joint hash code.
int32 joint_hash_code
# The is the desired joint position.
float64 desired_position
# Weight used to define the priority for reaching the desired position.
float64 weight}</pre>
*/
public class KinematicsToolboxOneDoFJointMessage implements ROS2Message<KinematicsToolboxOneDoFJointMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::KinematicsToolboxOneDoFJointMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      The is the unique hash code of the joint to be solved for.
      It is used on the solver side to retrieve the desired joint to be controlled.
      See Joint.hashCode() for the computation of a joint hash code.
   */
   private int joint_hash_code_;
   /**
      The is the desired joint position.
   */
   private double desired_position_;
   /**
      Weight used to define the priority for reaching the desired position.
   */
   private double weight_;

   public KinematicsToolboxOneDoFJointMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // joint_hash_code_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // desired_position_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // weight_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeInt(joint_hash_code_);
      buffer.writeDouble(desired_position_);
      buffer.writeDouble(weight_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      joint_hash_code_ = buffer.readInt();
      desired_position_ = buffer.readDouble();
      weight_ = buffer.readDouble();

   }

   @Override
   public void set(KinematicsToolboxOneDoFJointMessage from)
   {
      sequence_id_ = from.sequence_id_;
      joint_hash_code_ = from.joint_hash_code_;
      desired_position_ = from.desired_position_;
      weight_ = from.weight_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public int getJointHashCode()
   {
      return joint_hash_code_;
   }

   public void setJointHashCode(int joint_hash_code_)
   {
      this.joint_hash_code_ = joint_hash_code_;
   }

   public double getDesiredPosition()
   {
      return desired_position_;
   }

   public void setDesiredPosition(double desired_position_)
   {
      this.desired_position_ = desired_position_;
   }

   public double getWeight()
   {
      return weight_;
   }

   public void setWeight(double weight_)
   {
      this.weight_ = weight_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("KinematicsToolboxOneDoFJointMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("joint_hash_code_=");
      builder.append(joint_hash_code_);
      builder.append("desired_position_=");
      builder.append(desired_position_);
      builder.append("weight_=");
      builder.append(weight_);

      builder.append("}");
      return builder.toString();
   }
}