/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (toolbox_msgs/KinematicsPlanningToolboxInputMessage):
<pre>{@code
# This message is part of the IHMC whole-body inverse kinematics module: KinematicsPlanningToolbox.
# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# This is a list of rigid body messages which is used in KinematicsPlanningToolbox.
# It should composed of at least one message. Each message represent the input for solving the trajectory for one rigid-body.
KinematicsPlanningToolboxRigidBodyMessage[] rigid_body_messages

# This is desired key frames for center of mass position and will be used in KinematicsPlanningToolbox.
# In case this message is empty, the kinematics solver will keep center of mass position in its current location.
KinematicsPlanningToolboxCenterOfMassMessage center_of_mass_message

# This is kinematics configuration message and will configure whole body inverse kinematics solver.
# This is optional.
KinematicsToolboxConfigurationMessage kinematics_configuration_message}</pre>
*/
public class KinematicsPlanningToolboxInputMessage implements ROS2Message<KinematicsPlanningToolboxInputMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::KinematicsPlanningToolboxInputMessage_";

   /**
      This message is part of the IHMC whole-body inverse kinematics module: KinematicsPlanningToolbox.
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      This is a list of rigid body messages which is used in KinematicsPlanningToolbox.
      It should composed of at least one message. Each message represent the input for solving the trajectory for one rigid-body.
   */
   private final IDLObjectSequence<toolbox_msgs.KinematicsPlanningToolboxRigidBodyMessage> rigid_body_messages_;
   /**
      This is desired key frames for center of mass position and will be used in KinematicsPlanningToolbox.
      In case this message is empty, the kinematics solver will keep center of mass position in its current location.
   */
   private final toolbox_msgs.KinematicsPlanningToolboxCenterOfMassMessage center_of_mass_message_;
   /**
      This is kinematics configuration message and will configure whole body inverse kinematics solver.
      This is optional.
   */
   private final toolbox_msgs.KinematicsToolboxConfigurationMessage kinematics_configuration_message_;

   public KinematicsPlanningToolboxInputMessage()
   {
      rigid_body_messages_ = new IDLObjectSequence<toolbox_msgs.KinematicsPlanningToolboxRigidBodyMessage>(toolbox_msgs.KinematicsPlanningToolboxRigidBodyMessage.class);
      center_of_mass_message_ = new toolbox_msgs.KinematicsPlanningToolboxCenterOfMassMessage();
      kinematics_configuration_message_ = new toolbox_msgs.KinematicsToolboxConfigurationMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += rigid_body_messages_.calculateSizeBytes(currentAlignment);
      currentAlignment += center_of_mass_message_.calculateSizeBytes(currentAlignment);
      currentAlignment += kinematics_configuration_message_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      rigid_body_messages_.serialize(buffer);
      center_of_mass_message_.serialize(buffer);
      kinematics_configuration_message_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      rigid_body_messages_.deserialize(buffer);
      center_of_mass_message_.deserialize(buffer);
      kinematics_configuration_message_.deserialize(buffer);

   }

   @Override
   public void set(KinematicsPlanningToolboxInputMessage from)
   {
      sequence_id_ = from.sequence_id_;
      rigid_body_messages_.set(from.rigid_body_messages_);
      center_of_mass_message_.set(from.center_of_mass_message_);
      kinematics_configuration_message_.set(from.kinematics_configuration_message_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public IDLObjectSequence<toolbox_msgs.KinematicsPlanningToolboxRigidBodyMessage> getRigidBodyMessages()
   {
      return rigid_body_messages_;
   }

   public toolbox_msgs.KinematicsPlanningToolboxCenterOfMassMessage getCenterOfMassMessage()
   {
      return center_of_mass_message_;
   }

   public toolbox_msgs.KinematicsToolboxConfigurationMessage getKinematicsConfigurationMessage()
   {
      return kinematics_configuration_message_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("KinematicsPlanningToolboxInputMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("rigid_body_messages_=");
      builder.append(rigid_body_messages_);
      builder.append("center_of_mass_message_=");
      builder.append(center_of_mass_message_);
      builder.append("kinematics_configuration_message_=");
      builder.append(kinematics_configuration_message_);

      builder.append("}");
      return builder.toString();
   }
}