/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is used to start and stop recording ROS logs.
This is used both for recording and replaying, see ROS2LogRecord and ROS2LogReplay for more information.
<p>Source (toolbox_msgs/ROS2LogMessage):
<pre>{@code
# This message is used to start and stop recording ROS logs.
# This is used both for recording and replaying, see ROS2LogRecord and ROS2LogReplay for more information.

byte ROS2_LOG_REQUESTED_STATE_START=0
byte ROS2_LOG_REQUESTED_STATE_FINISH=1

# Requested state for the ROS 2 log recorder
byte requested_state 255}</pre>
*/
public class ROS2LogMessage implements ROS2Message<ROS2LogMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::ROS2LogMessage_";

   public static final byte ROS2_LOG_REQUESTED_STATE_START = 0;
   public static final byte ROS2_LOG_REQUESTED_STATE_FINISH = 1;
   /**
      Requested state for the ROS 2 log recorder
   */
   private byte requested_state_;

   public ROS2LogMessage()
   {
      requested_state_ = (byte) 255;

   }

   public ROS2LogMessage(ROS2LogMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // requested_state_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeByte(requested_state_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      requested_state_ = buffer.readByte();

   }

   @Override
   public void set(ROS2LogMessage from)
   {
      requested_state_ = from.requested_state_;

   }

   public byte getRequestedState()
   {
      return requested_state_;
   }

   public void setRequestedState(byte requested_state_)
   {
      this.requested_state_ = requested_state_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ROS2LogMessage {");
      builder.append("ROS2_LOG_REQUESTED_STATE_START=");
      builder.append(ROS2_LOG_REQUESTED_STATE_START);
      builder.append("ROS2_LOG_REQUESTED_STATE_FINISH=");
      builder.append(ROS2_LOG_REQUESTED_STATE_FINISH);
      builder.append("requested_state_=");
      builder.append(requested_state_);

      builder.append("}");
      return builder.toString();
   }
}