/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package toolbox_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Message that carries all the information required to configure the IHMC whole-body trajectory planner.
Main usage is the IHMC WholeBodyTrajectoryToolbox.
<p>Source (toolbox_msgs/WholeBodyTrajectoryToolboxMessage):
<pre>{@code
# Message that carries all the information required to configure the IHMC whole-body trajectory planner.
# Main usage is the IHMC WholeBodyTrajectoryToolbox.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

WholeBodyTrajectoryToolboxConfigurationMessage configuration
WaypointBasedTrajectoryMessage[<=10] end_effector_trajectories
RigidBodyExplorationConfigurationMessage[<=10] exploration_configurations
ReachingManifoldMessage[<=10] reaching_manifolds}</pre>
*/
public class WholeBodyTrajectoryToolboxMessage implements ROS2Message<WholeBodyTrajectoryToolboxMessage>
{
   public static final java.lang.String name = "toolbox_msgs::msg::dds_::WholeBodyTrajectoryToolboxMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private final toolbox_msgs.WholeBodyTrajectoryToolboxConfigurationMessage configuration_;
   private final IDLObjectSequence<toolbox_msgs.WaypointBasedTrajectoryMessage> end_effector_trajectories_;
   private final IDLObjectSequence<toolbox_msgs.RigidBodyExplorationConfigurationMessage> exploration_configurations_;
   private final IDLObjectSequence<toolbox_msgs.ReachingManifoldMessage> reaching_manifolds_;

   public WholeBodyTrajectoryToolboxMessage()
   {
      configuration_ = new toolbox_msgs.WholeBodyTrajectoryToolboxConfigurationMessage();
      end_effector_trajectories_ = new IDLObjectSequence<toolbox_msgs.WaypointBasedTrajectoryMessage>(10, toolbox_msgs.WaypointBasedTrajectoryMessage.class);
      exploration_configurations_ = new IDLObjectSequence<toolbox_msgs.RigidBodyExplorationConfigurationMessage>(10, toolbox_msgs.RigidBodyExplorationConfigurationMessage.class);
      reaching_manifolds_ = new IDLObjectSequence<toolbox_msgs.ReachingManifoldMessage>(10, toolbox_msgs.ReachingManifoldMessage.class);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += configuration_.calculateSizeBytes(currentAlignment);
      currentAlignment += end_effector_trajectories_.calculateSizeBytes(currentAlignment);
      currentAlignment += exploration_configurations_.calculateSizeBytes(currentAlignment);
      currentAlignment += reaching_manifolds_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      configuration_.serialize(buffer);
      end_effector_trajectories_.serialize(buffer);
      exploration_configurations_.serialize(buffer);
      reaching_manifolds_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      configuration_.deserialize(buffer);
      end_effector_trajectories_.deserialize(buffer);
      exploration_configurations_.deserialize(buffer);
      reaching_manifolds_.deserialize(buffer);

   }

   @Override
   public void set(WholeBodyTrajectoryToolboxMessage from)
   {
      sequence_id_ = from.sequence_id_;
      configuration_.set(from.configuration_);
      end_effector_trajectories_.set(from.end_effector_trajectories_);
      exploration_configurations_.set(from.exploration_configurations_);
      reaching_manifolds_.set(from.reaching_manifolds_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public toolbox_msgs.WholeBodyTrajectoryToolboxConfigurationMessage getConfiguration()
   {
      return configuration_;
   }

   public IDLObjectSequence<toolbox_msgs.WaypointBasedTrajectoryMessage> getEndEffectorTrajectories()
   {
      return end_effector_trajectories_;
   }

   public IDLObjectSequence<toolbox_msgs.RigidBodyExplorationConfigurationMessage> getExplorationConfigurations()
   {
      return exploration_configurations_;
   }

   public IDLObjectSequence<toolbox_msgs.ReachingManifoldMessage> getReachingManifolds()
   {
      return reaching_manifolds_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("WholeBodyTrajectoryToolboxMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("configuration_=");
      builder.append(configuration_);
      builder.append("end_effector_trajectories_=");
      builder.append(end_effector_trajectories_);
      builder.append("exploration_configurations_=");
      builder.append(exploration_configurations_);
      builder.append("reaching_manifolds_=");
      builder.append(reaching_manifolds_);

      builder.append("}");
      return builder.toString();
   }
}