# Absolute wall time
time wall_time
# Absolute sim time
time sim_time
# Wall time elapsed since passing the first gate
time wall_time_elapsed
# Sim time elapsed since passing the first gate
time sim_time_elapsed
# How many parts of the task have been accomplished (e.g., gates traversed)
int32 completion_score
# How many damaging falls detected
int32 falls
# Optional message to describe events
string message
