# Number of actions within the sequence
uint16 sequence_size

behavior_msgs/ArmJointAnglesActionDefinitionMessage[<=200] arm_joint_angles_actions

behavior_msgs/BodyPartPoseActionDefinitionMessage[<=200] chest_orientation_actions

behavior_msgs/FootstepPlanActionDefinitionMessage[<=200] footstep_plan_actions

behavior_msgs/SakeHandCommandActionDefinitionMessage[<=200] sake_hand_command_actions

behavior_msgs/SidedBodyPartPoseActionDefinitionMessage[<=200] hand_pose_actions

behavior_msgs/HandWrenchActionDefinitionMessage[<=200] hand_wrench_actions

behavior_msgs/BodyPartPoseActionDefinitionMessage[<=200] pelvis_height_actions

behavior_msgs/SidedBodyPartPoseActionDefinitionMessage[<=200] foot_pose_actions

behavior_msgs/WaitDurationActionDefinitionMessage[<=200] wait_duration_actions

behavior_msgs/WalkActionDefinitionMessage[<=200] walk_actions
