# Number of actions within the sequence
uint16 sequence_size

behavior_msgs/ArmJointAnglesActionStateMessage[<=200] arm_joint_angles_actions

behavior_msgs/ChestOrientationActionStateMessage[<=200] chest_orientation_actions

behavior_msgs/FootstepPlanActionStateMessage[<=200] footstep_plan_actions

behavior_msgs/SakeHandCommandActionStateMessage[<=200] sake_hand_command_actions

behavior_msgs/HandPoseActionStateMessage[<=200] hand_pose_actions

behavior_msgs/HandWrenchActionStateMessage[<=200] hand_wrench_actions

behavior_msgs/PelvisHeightPitchActionStateMessage[<=200] pelvis_height_actions

behavior_msgs/WaitDurationActionStateMessage[<=200] wait_duration_actions

behavior_msgs/WalkActionStateMessage[<=200] walk_actions
