# Parent definition fields
behavior_msgs/ActionNodeDefinitionMessage definition

# Specifies the side of the robot that this message refers to.
byte robot_side 255

# The string value of the legacy grip type
# https://github.com/ihmcrobotics/psyonic-ability-hand-java/blob/main/src/main/java/us/ihmc/abilityhand/AbilityHandLegacyGripCommand.java#L63
string grip_type

# The string value of the legacy grip speed
# https://github.com/ihmcrobotics/psyonic-ability-hand-java/blob/main/src/main/java/us/ihmc/abilityhand/AbilityHandLegacyGripCommand.java#L58
string grip_speed