package actionlib;

public interface TwoIntsActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib/TwoIntsActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nTwoIntsFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  actionlib.TwoIntsFeedback getFeedback();
  void setFeedback(actionlib.TwoIntsFeedback value);
}
