package arm_navigation_msgs;

public interface SyncPlanningSceneGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "arm_navigation_msgs/SyncPlanningSceneGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n# THIS MESSAGE IS FOR INTERNAL COMMUNICATION BETWEEN\n# PLANNING ENVIRONMENT COMPONENTS ONLY\n\n#Full planning scene\nPlanningScene planning_scene\n";
  arm_navigation_msgs.PlanningScene getPlanningScene();
  void setPlanningScene(arm_navigation_msgs.PlanningScene value);
}
