package us.ihmc.avatar.networkProcessor.referenceSpreading;

import java.util.ArrayList;
import java.util.List;

public class ReferenceSpreadingKeyMatrix {
   public static List<String> DEFAULT = new ArrayList<>(List.of(
         "time[sec]", "q_PELVIS_LINK_x", "q_PELVIS_LINK_y", "q_PELVIS_LINK_z",
         "q_PELVIS_LINK_qx", "q_PELVIS_LINK_qy", "q_PELVIS_LINK_qz", "q_PELVIS_LINK_qs",
         "qd_PELVIS_LINK_wX", "qd_PELVIS_LINK_wY", "qd_PELVIS_LINK_wZ", "qd_PELVIS_LINK_x",
         "qd_PELVIS_LINK_y", "qd_PELVIS_LINK_z", "q_PELVIS_LINK_yaw", "q_PELVIS_LINK_pitch",
         "q_PELVIS_LINK_roll", "qd_PELVIS_LINK_world_x", "qd_PELVIS_LINK_world_y",
         "qd_PELVIS_LINK_world_z", "q_LEFT_HIP_Z", "qd_LEFT_HIP_Z", "q_LEFT_HIP_X",
         "qd_LEFT_HIP_X", "q_LEFT_HIP_Y", "qd_LEFT_HIP_Y", "q_LEFT_KNEE_Y", "qd_LEFT_KNEE_Y",
         "q_LEFT_ANKLE_Y", "qd_LEFT_ANKLE_Y", "q_LEFT_ANKLE_X", "qd_LEFT_ANKLE_X",
         "q_RIGHT_HIP_Z", "qd_RIGHT_HIP_Z", "q_RIGHT_HIP_X", "qd_RIGHT_HIP_X",
         "q_RIGHT_HIP_Y", "qd_RIGHT_HIP_Y", "q_RIGHT_KNEE_Y", "qd_RIGHT_KNEE_Y",
         "q_RIGHT_ANKLE_Y", "qd_RIGHT_ANKLE_Y", "q_RIGHT_ANKLE_X", "qd_RIGHT_ANKLE_X",
         "q_SPINE_Z", "qd_SPINE_Z", "q_SPINE_X", "qd_SPINE_X", "q_SPINE_Y", "qd_SPINE_Y",
         "q_RIGHT_SHOULDER_Y", "qd_RIGHT_SHOULDER_Y", "q_RIGHT_SHOULDER_X", "qd_RIGHT_SHOULDER_X",
         "q_RIGHT_SHOULDER_Z", "qd_RIGHT_SHOULDER_Z", "q_RIGHT_ELBOW_Y", "qd_RIGHT_ELBOW_Y",
         "q_RIGHT_WRIST_Z", "qd_RIGHT_WRIST_Z", "q_RIGHT_WRIST_X", "qd_RIGHT_WRIST_X",
         "q_RIGHT_GRIPPER_Z", "qd_RIGHT_GRIPPER_Z", "q_LEFT_SHOULDER_Y", "qd_LEFT_SHOULDER_Y",
         "q_LEFT_SHOULDER_X", "qd_LEFT_SHOULDER_X", "q_LEFT_SHOULDER_Z", "qd_LEFT_SHOULDER_Z",
         "q_LEFT_ELBOW_Y", "qd_LEFT_ELBOW_Y", "q_LEFT_WRIST_Z", "qd_LEFT_WRIST_Z",
         "q_LEFT_WRIST_X", "qd_LEFT_WRIST_X", "q_LEFT_GRIPPER_Z", "qd_LEFT_GRIPPER_Z",
         "filteredWrenchAngularPartXLEFT", "filteredWrenchAngularPartYLEFT",
         "filteredWrenchAngularPartZLEFT", "filteredWrenchLinearPartXLEFT",
         "filteredWrenchLinearPartYLEFT", "filteredWrenchLinearPartZLEFT",
         "filteredWrenchAngularPartXRIGHT", "filteredWrenchAngularPartYRIGHT",
         "filteredWrenchAngularPartZRIGHT", "filteredWrenchLinearPartXRIGHT",
         "filteredWrenchLinearPartYRIGHT", "filteredWrenchLinearPartZRIGHT",
         "RIGHT_GRIPPER_YAW_LINKpositionFeedbackX", "RIGHT_GRIPPER_YAW_LINKpositionFeedbackY",
         "RIGHT_GRIPPER_YAW_LINKpositionFeedbackZ", "RIGHT_GRIPPER_YAW_LINKorientationFeedbackX",
         "RIGHT_GRIPPER_YAW_LINKorientationFeedbackY", "RIGHT_GRIPPER_YAW_LINKorientationFeedbackZ",
         "RIGHT_GRIPPER_YAW_LINKpositionAccelerationX", "RIGHT_GRIPPER_YAW_LINKpositionAccelerationY",
         "RIGHT_GRIPPER_YAW_LINKpositionAccelerationZ", "RIGHT_GRIPPER_YAW_LINKorientationAccelerationX",
         "RIGHT_GRIPPER_YAW_LINKorientationAccelerationY", "RIGHT_GRIPPER_YAW_LINKorientationAccelerationZ",
         "LEFT_GRIPPER_YAW_LINKpositionFeedbackX", "LEFT_GRIPPER_YAW_LINKpositionFeedbackY",
         "LEFT_GRIPPER_YAW_LINKpositionFeedbackZ", "LEFT_GRIPPER_YAW_LINKorientationFeedbackX",
         "LEFT_GRIPPER_YAW_LINKorientationFeedbackY", "LEFT_GRIPPER_YAW_LINKorientationFeedbackZ",
         "LEFT_GRIPPER_YAW_LINKpositionAccelerationX", "LEFT_GRIPPER_YAW_LINKpositionAccelerationY",
         "LEFT_GRIPPER_YAW_LINKpositionAccelerationZ", "LEFT_GRIPPER_YAW_LINKorientationAccelerationX",
         "LEFT_GRIPPER_YAW_LINKorientationAccelerationY", "LEFT_GRIPPER_YAW_LINKorientationAccelerationZ",
         "RIGHT_GRIPPER_YAW_LINKDesiredPositionX", "RIGHT_GRIPPER_YAW_LINKDesiredPositionY",
         "RIGHT_GRIPPER_YAW_LINKDesiredPositionZ", "RIGHT_GRIPPER_YAW_LINKDesiredPositionFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQx", "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQy",
         "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQz", "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQs",
         "RIGHT_GRIPPER_YAW_LINKDesiredOrientationFrame", "RIGHT_GRIPPER_YAW_LINKCurrentPositionX",
         "RIGHT_GRIPPER_YAW_LINKCurrentPositionY", "RIGHT_GRIPPER_YAW_LINKCurrentPositionZ",
         "RIGHT_GRIPPER_YAW_LINKCurrentPositionFrame", "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQx",
         "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQy", "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQz",
         "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQs", "RIGHT_GRIPPER_YAW_LINKCurrentOrientationFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorX", "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorY",
         "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorZ", "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorFrame",
         "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorX", "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorY",
         "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorZ", "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityX", "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityY",
         "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityZ", "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityX", "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityY",
         "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityZ", "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityX", "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityY",
         "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityZ", "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityX", "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityY",
         "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityZ", "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityX", "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityY",
         "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityZ", "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityX", "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityY",
         "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityZ", "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredPositionX", "LEFT_GRIPPER_YAW_LINKDesiredPositionY",
         "LEFT_GRIPPER_YAW_LINKDesiredPositionZ", "LEFT_GRIPPER_YAW_LINKDesiredPositionFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredOrientationQx", "LEFT_GRIPPER_YAW_LINKDesiredOrientationQy",
         "LEFT_GRIPPER_YAW_LINKDesiredOrientationQz", "LEFT_GRIPPER_YAW_LINKDesiredOrientationQs",
         "LEFT_GRIPPER_YAW_LINKDesiredOrientationFrame", "LEFT_GRIPPER_YAW_LINKCurrentPositionX",
         "LEFT_GRIPPER_YAW_LINKCurrentPositionY", "LEFT_GRIPPER_YAW_LINKCurrentPositionZ",
         "LEFT_GRIPPER_YAW_LINKCurrentPositionFrame", "LEFT_GRIPPER_YAW_LINKCurrentOrientationQx",
         "LEFT_GRIPPER_YAW_LINKCurrentOrientationQy", "LEFT_GRIPPER_YAW_LINKCurrentOrientationQz",
         "LEFT_GRIPPER_YAW_LINKCurrentOrientationQs", "LEFT_GRIPPER_YAW_LINKCurrentOrientationFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorX", "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorY",
         "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorZ", "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorFrame",
         "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorX", "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorY",
         "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorZ", "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityX", "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityY",
         "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityZ", "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityX", "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityY",
         "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityZ", "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityX", "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityY",
         "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityZ", "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityX", "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityY",
         "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityZ", "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityFrame"
   ));

   public static List<String> RECORD = new ArrayList<>(List.of(
         "time[sec]", "q_PELVIS_LINK_x", "q_PELVIS_LINK_y", "q_PELVIS_LINK_z",
         "q_PELVIS_LINK_qx", "q_PELVIS_LINK_qy", "q_PELVIS_LINK_qz", "q_PELVIS_LINK_qs",
         "qd_PELVIS_LINK_wX", "qd_PELVIS_LINK_wY", "qd_PELVIS_LINK_wZ", "qd_PELVIS_LINK_x",
         "qd_PELVIS_LINK_y", "qd_PELVIS_LINK_z", "q_PELVIS_LINK_yaw", "q_PELVIS_LINK_pitch",
         "q_PELVIS_LINK_roll", "qd_PELVIS_LINK_world_x", "qd_PELVIS_LINK_world_y",
         "qd_PELVIS_LINK_world_z", "q_LEFT_HIP_Z", "qd_LEFT_HIP_Z", "q_LEFT_HIP_X",
         "qd_LEFT_HIP_X", "q_LEFT_HIP_Y", "qd_LEFT_HIP_Y", "q_LEFT_KNEE_Y", "qd_LEFT_KNEE_Y",
         "q_LEFT_ANKLE_Y", "qd_LEFT_ANKLE_Y", "q_LEFT_ANKLE_X", "qd_LEFT_ANKLE_X",
         "q_RIGHT_HIP_Z", "qd_RIGHT_HIP_Z", "q_RIGHT_HIP_X", "qd_RIGHT_HIP_X",
         "q_RIGHT_HIP_Y", "qd_RIGHT_HIP_Y", "q_RIGHT_KNEE_Y", "qd_RIGHT_KNEE_Y",
         "q_RIGHT_ANKLE_Y", "qd_RIGHT_ANKLE_Y", "q_RIGHT_ANKLE_X", "qd_RIGHT_ANKLE_X",
         "q_SPINE_Z", "qd_SPINE_Z", "q_SPINE_X", "qd_SPINE_X", "q_SPINE_Y", "qd_SPINE_Y",
         "q_RIGHT_SHOULDER_Y", "qd_RIGHT_SHOULDER_Y", "q_RIGHT_SHOULDER_X", "qd_RIGHT_SHOULDER_X",
         "q_RIGHT_SHOULDER_Z", "qd_RIGHT_SHOULDER_Z", "q_RIGHT_ELBOW_Y", "qd_RIGHT_ELBOW_Y",
         "q_RIGHT_WRIST_Z", "qd_RIGHT_WRIST_Z", "q_RIGHT_WRIST_X", "qd_RIGHT_WRIST_X",
         "q_RIGHT_GRIPPER_Z", "qd_RIGHT_GRIPPER_Z", "q_LEFT_SHOULDER_Y", "qd_LEFT_SHOULDER_Y",
         "q_LEFT_SHOULDER_X", "qd_LEFT_SHOULDER_X", "q_LEFT_SHOULDER_Z", "qd_LEFT_SHOULDER_Z",
         "q_LEFT_ELBOW_Y", "qd_LEFT_ELBOW_Y", "q_LEFT_WRIST_Z", "qd_LEFT_WRIST_Z",
         "q_LEFT_WRIST_X", "qd_LEFT_WRIST_X", "q_LEFT_GRIPPER_Z", "qd_LEFT_GRIPPER_Z",
         "filteredWrenchAngularPartXLEFT", "filteredWrenchAngularPartYLEFT",
         "filteredWrenchAngularPartZLEFT", "filteredWrenchLinearPartXLEFT",
         "filteredWrenchLinearPartYLEFT", "filteredWrenchLinearPartZLEFT",
         "filteredWrenchAngularPartXRIGHT", "filteredWrenchAngularPartYRIGHT",
         "filteredWrenchAngularPartZRIGHT", "filteredWrenchLinearPartXRIGHT",
         "filteredWrenchLinearPartYRIGHT", "filteredWrenchLinearPartZRIGHT",
         "RIGHT_GRIPPER_YAW_LINKpositionFeedbackX", "RIGHT_GRIPPER_YAW_LINKpositionFeedbackY",
         "RIGHT_GRIPPER_YAW_LINKpositionFeedbackZ", "RIGHT_GRIPPER_YAW_LINKorientationFeedbackX",
         "RIGHT_GRIPPER_YAW_LINKorientationFeedbackY", "RIGHT_GRIPPER_YAW_LINKorientationFeedbackZ",
         "LEFT_GRIPPER_YAW_LINKpositionFeedbackX", "LEFT_GRIPPER_YAW_LINKpositionFeedbackY",
         "LEFT_GRIPPER_YAW_LINKpositionFeedbackZ", "LEFT_GRIPPER_YAW_LINKorientationFeedbackX",
         "LEFT_GRIPPER_YAW_LINKorientationFeedbackY", "LEFT_GRIPPER_YAW_LINKorientationFeedbackZ",
         "RIGHT_GRIPPER_YAW_LINKDesiredPositionX", "RIGHT_GRIPPER_YAW_LINKDesiredPositionY",
         "RIGHT_GRIPPER_YAW_LINKDesiredPositionZ", "RIGHT_GRIPPER_YAW_LINKDesiredPositionFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQx", "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQy",
         "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQz", "RIGHT_GRIPPER_YAW_LINKDesiredOrientationQs",
         "RIGHT_GRIPPER_YAW_LINKDesiredOrientationFrame", "RIGHT_GRIPPER_YAW_LINKCurrentPositionX",
         "RIGHT_GRIPPER_YAW_LINKCurrentPositionY", "RIGHT_GRIPPER_YAW_LINKCurrentPositionZ",
         "RIGHT_GRIPPER_YAW_LINKCurrentPositionFrame", "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQx",
         "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQy", "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQz",
         "RIGHT_GRIPPER_YAW_LINKCurrentOrientationQs", "RIGHT_GRIPPER_YAW_LINKCurrentOrientationFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorX", "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorY",
         "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorZ", "RIGHT_GRIPPER_YAW_LINKDesiredRotationVectorFrame",
         "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorX", "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorY",
         "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorZ", "RIGHT_GRIPPER_YAW_LINKCurrentRotationVectorFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityX", "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityY",
         "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityZ", "RIGHT_GRIPPER_YAW_LINKDesiredAngularVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityX", "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityY",
         "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityZ", "RIGHT_GRIPPER_YAW_LINKDesiredLinearVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityX", "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityY",
         "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityZ", "RIGHT_GRIPPER_YAW_LINKCurrentAngularVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityX", "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityY",
         "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityZ", "RIGHT_GRIPPER_YAW_LINKCurrentLinearVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityX", "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityY",
         "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityZ", "RIGHT_GRIPPER_YAW_LINKErrorAngularVelocityFrame",
         "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityX", "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityY",
         "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityZ", "RIGHT_GRIPPER_YAW_LINKErrorLinearVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredPositionX", "LEFT_GRIPPER_YAW_LINKDesiredPositionY",
         "LEFT_GRIPPER_YAW_LINKDesiredPositionZ", "LEFT_GRIPPER_YAW_LINKDesiredPositionFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredOrientationQx", "LEFT_GRIPPER_YAW_LINKDesiredOrientationQy",
         "LEFT_GRIPPER_YAW_LINKDesiredOrientationQz", "LEFT_GRIPPER_YAW_LINKDesiredOrientationQs",
         "LEFT_GRIPPER_YAW_LINKDesiredOrientationFrame", "LEFT_GRIPPER_YAW_LINKCurrentPositionX",
         "LEFT_GRIPPER_YAW_LINKCurrentPositionY", "LEFT_GRIPPER_YAW_LINKCurrentPositionZ",
         "LEFT_GRIPPER_YAW_LINKCurrentPositionFrame", "LEFT_GRIPPER_YAW_LINKCurrentOrientationQx",
         "LEFT_GRIPPER_YAW_LINKCurrentOrientationQy", "LEFT_GRIPPER_YAW_LINKCurrentOrientationQz",
         "LEFT_GRIPPER_YAW_LINKCurrentOrientationQs", "LEFT_GRIPPER_YAW_LINKCurrentOrientationFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorX", "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorY",
         "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorZ", "LEFT_GRIPPER_YAW_LINKDesiredRotationVectorFrame",
         "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorX", "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorY",
         "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorZ", "LEFT_GRIPPER_YAW_LINKCurrentRotationVectorFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityX", "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityY",
         "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityZ", "LEFT_GRIPPER_YAW_LINKDesiredAngularVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityX", "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityY",
         "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityZ", "LEFT_GRIPPER_YAW_LINKDesiredLinearVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityX", "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityY",
         "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityZ", "LEFT_GRIPPER_YAW_LINKCurrentAngularVelocityFrame",
         "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityX", "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityY",
         "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityZ", "LEFT_GRIPPER_YAW_LINKCurrentLinearVelocityFrame"
   ));

   public static List<String> DEFAULT_4DOF = new ArrayList<>(List.of(
         "time[sec]", "q_PELVIS_LINK_x", "q_PELVIS_LINK_y", "q_PELVIS_LINK_z",
         "q_PELVIS_LINK_qx", "q_PELVIS_LINK_qy", "q_PELVIS_LINK_qz", "q_PELVIS_LINK_qs",
         "qd_PELVIS_LINK_wX", "qd_PELVIS_LINK_wY", "qd_PELVIS_LINK_wZ", "qd_PELVIS_LINK_x",
         "qd_PELVIS_LINK_y", "qd_PELVIS_LINK_z", "q_PELVIS_LINK_yaw", "q_PELVIS_LINK_pitch",
         "q_PELVIS_LINK_roll", "qd_PELVIS_LINK_world_x", "qd_PELVIS_LINK_world_y",
         "qd_PELVIS_LINK_world_z", "q_LEFT_HIP_Z", "qd_LEFT_HIP_Z", "q_LEFT_HIP_X",
         "qd_LEFT_HIP_X", "q_LEFT_HIP_Y", "qd_LEFT_HIP_Y", "q_LEFT_KNEE_Y", "qd_LEFT_KNEE_Y",
         "q_LEFT_ANKLE_Y", "qd_LEFT_ANKLE_Y", "q_LEFT_ANKLE_X", "qd_LEFT_ANKLE_X",
         "q_RIGHT_HIP_Z", "qd_RIGHT_HIP_Z", "q_RIGHT_HIP_X", "qd_RIGHT_HIP_X",
         "q_RIGHT_HIP_Y", "qd_RIGHT_HIP_Y", "q_RIGHT_KNEE_Y", "qd_RIGHT_KNEE_Y",
         "q_RIGHT_ANKLE_Y", "qd_RIGHT_ANKLE_Y", "q_RIGHT_ANKLE_X", "qd_RIGHT_ANKLE_X",
         "q_SPINE_Z", "qd_SPINE_Z", "q_SPINE_X", "qd_SPINE_X", "q_SPINE_Y", "qd_SPINE_Y",
         "q_RIGHT_SHOULDER_Y", "qd_RIGHT_SHOULDER_Y", "q_RIGHT_SHOULDER_X", "qd_RIGHT_SHOULDER_X",
         "q_RIGHT_SHOULDER_Z", "qd_RIGHT_SHOULDER_Z", "q_RIGHT_ELBOW_Y", "qd_RIGHT_ELBOW_Y",
         "q_LEFT_SHOULDER_Y", "qd_LEFT_SHOULDER_Y",
         "q_LEFT_SHOULDER_X", "qd_LEFT_SHOULDER_X", "q_LEFT_SHOULDER_Z", "qd_LEFT_SHOULDER_Z",
         "q_LEFT_ELBOW_Y", "qd_LEFT_ELBOW_Y",
         "filteredWrenchAngularPartXLEFT", "filteredWrenchAngularPartYLEFT",
         "filteredWrenchAngularPartZLEFT", "filteredWrenchLinearPartXLEFT",
         "filteredWrenchLinearPartYLEFT", "filteredWrenchLinearPartZLEFT",
         "filteredWrenchAngularPartXRIGHT", "filteredWrenchAngularPartYRIGHT",
         "filteredWrenchAngularPartZRIGHT", "filteredWrenchLinearPartXRIGHT",
         "filteredWrenchLinearPartYRIGHT", "filteredWrenchLinearPartZRIGHT",
         "RIGHT_ELBOW_PITCH_LINKpositionFeedbackX", "RIGHT_ELBOW_PITCH_LINKpositionFeedbackY",
         "RIGHT_ELBOW_PITCH_LINKpositionFeedbackZ", "RIGHT_ELBOW_PITCH_LINKorientationFeedbackX",
         "RIGHT_ELBOW_PITCH_LINKorientationFeedbackY", "RIGHT_ELBOW_PITCH_LINKorientationFeedbackZ",
         "RIGHT_ELBOW_PITCH_LINKpositionAccelerationX", "RIGHT_ELBOW_PITCH_LINKpositionAccelerationY",
         "RIGHT_ELBOW_PITCH_LINKpositionAccelerationZ", "RIGHT_ELBOW_PITCH_LINKorientationAccelerationX",
         "RIGHT_ELBOW_PITCH_LINKorientationAccelerationY", "RIGHT_ELBOW_PITCH_LINKorientationAccelerationZ",
         "LEFT_ELBOW_PITCH_LINKpositionFeedbackX", "LEFT_ELBOW_PITCH_LINKpositionFeedbackY",
         "LEFT_ELBOW_PITCH_LINKpositionFeedbackZ", "LEFT_ELBOW_PITCH_LINKorientationFeedbackX",
         "LEFT_ELBOW_PITCH_LINKorientationFeedbackY", "LEFT_ELBOW_PITCH_LINKorientationFeedbackZ",
         "LEFT_ELBOW_PITCH_LINKpositionAccelerationX", "LEFT_ELBOW_PITCH_LINKpositionAccelerationY",
         "LEFT_ELBOW_PITCH_LINKpositionAccelerationZ", "LEFT_ELBOW_PITCH_LINKorientationAccelerationX",
         "LEFT_ELBOW_PITCH_LINKorientationAccelerationY", "LEFT_ELBOW_PITCH_LINKorientationAccelerationZ",
         "RIGHT_ELBOW_PITCH_LINKDesiredPositionX", "RIGHT_ELBOW_PITCH_LINKDesiredPositionY",
         "RIGHT_ELBOW_PITCH_LINKDesiredPositionZ", "RIGHT_ELBOW_PITCH_LINKDesiredPositionFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQx", "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQy",
         "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQz", "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQs",
         "RIGHT_ELBOW_PITCH_LINKDesiredOrientationFrame", "RIGHT_ELBOW_PITCH_LINKCurrentPositionX",
         "RIGHT_ELBOW_PITCH_LINKCurrentPositionY", "RIGHT_ELBOW_PITCH_LINKCurrentPositionZ",
         "RIGHT_ELBOW_PITCH_LINKCurrentPositionFrame", "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQx",
         "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQy", "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQz",
         "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQs", "RIGHT_ELBOW_PITCH_LINKCurrentOrientationFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorX", "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorY",
         "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorZ", "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorFrame",
         "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorX", "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorY",
         "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorZ", "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityX", "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityY",
         "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityZ", "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityX", "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityY",
         "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityZ", "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityX", "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityY",
         "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityZ", "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityX", "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityY",
         "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityZ", "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityX", "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityY",
         "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityZ", "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityX", "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityY",
         "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityZ", "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredPositionX", "LEFT_ELBOW_PITCH_LINKDesiredPositionY",
         "LEFT_ELBOW_PITCH_LINKDesiredPositionZ", "LEFT_ELBOW_PITCH_LINKDesiredPositionFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredOrientationQx", "LEFT_ELBOW_PITCH_LINKDesiredOrientationQy",
         "LEFT_ELBOW_PITCH_LINKDesiredOrientationQz", "LEFT_ELBOW_PITCH_LINKDesiredOrientationQs",
         "LEFT_ELBOW_PITCH_LINKDesiredOrientationFrame", "LEFT_ELBOW_PITCH_LINKCurrentPositionX",
         "LEFT_ELBOW_PITCH_LINKCurrentPositionY", "LEFT_ELBOW_PITCH_LINKCurrentPositionZ",
         "LEFT_ELBOW_PITCH_LINKCurrentPositionFrame", "LEFT_ELBOW_PITCH_LINKCurrentOrientationQx",
         "LEFT_ELBOW_PITCH_LINKCurrentOrientationQy", "LEFT_ELBOW_PITCH_LINKCurrentOrientationQz",
         "LEFT_ELBOW_PITCH_LINKCurrentOrientationQs", "LEFT_ELBOW_PITCH_LINKCurrentOrientationFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorX", "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorY",
         "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorZ", "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorFrame",
         "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorX", "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorY",
         "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorZ", "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityX", "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityY",
         "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityZ", "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityX", "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityY",
         "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityZ", "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityX", "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityY",
         "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityZ", "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityX", "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityY",
         "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityZ", "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityFrame"
   ));

   public static List<String> RECORD_4DOF = new ArrayList<>(List.of(
         "time[sec]", "q_PELVIS_LINK_x", "q_PELVIS_LINK_y", "q_PELVIS_LINK_z",
         "q_PELVIS_LINK_qx", "q_PELVIS_LINK_qy", "q_PELVIS_LINK_qz", "q_PELVIS_LINK_qs",
         "qd_PELVIS_LINK_wX", "qd_PELVIS_LINK_wY", "qd_PELVIS_LINK_wZ", "qd_PELVIS_LINK_x",
         "qd_PELVIS_LINK_y", "qd_PELVIS_LINK_z", "q_PELVIS_LINK_yaw", "q_PELVIS_LINK_pitch",
         "q_PELVIS_LINK_roll", "qd_PELVIS_LINK_world_x", "qd_PELVIS_LINK_world_y",
         "qd_PELVIS_LINK_world_z", "q_LEFT_HIP_Z", "qd_LEFT_HIP_Z", "q_LEFT_HIP_X",
         "qd_LEFT_HIP_X", "q_LEFT_HIP_Y", "qd_LEFT_HIP_Y", "q_LEFT_KNEE_Y", "qd_LEFT_KNEE_Y",
         "q_LEFT_ANKLE_Y", "qd_LEFT_ANKLE_Y", "q_LEFT_ANKLE_X", "qd_LEFT_ANKLE_X",
         "q_RIGHT_HIP_Z", "qd_RIGHT_HIP_Z", "q_RIGHT_HIP_X", "qd_RIGHT_HIP_X",
         "q_RIGHT_HIP_Y", "qd_RIGHT_HIP_Y", "q_RIGHT_KNEE_Y", "qd_RIGHT_KNEE_Y",
         "q_RIGHT_ANKLE_Y", "qd_RIGHT_ANKLE_Y", "q_RIGHT_ANKLE_X", "qd_RIGHT_ANKLE_X",
         "q_SPINE_Z", "qd_SPINE_Z", "q_SPINE_X", "qd_SPINE_X", "q_SPINE_Y", "qd_SPINE_Y",
         "q_RIGHT_SHOULDER_Y", "qd_RIGHT_SHOULDER_Y", "q_RIGHT_SHOULDER_X", "qd_RIGHT_SHOULDER_X",
         "q_RIGHT_SHOULDER_Z", "qd_RIGHT_SHOULDER_Z", "q_RIGHT_ELBOW_Y", "qd_RIGHT_ELBOW_Y",
         "q_LEFT_SHOULDER_Y", "qd_LEFT_SHOULDER_Y",
         "q_LEFT_SHOULDER_X", "qd_LEFT_SHOULDER_X", "q_LEFT_SHOULDER_Z", "qd_LEFT_SHOULDER_Z",
         "q_LEFT_ELBOW_Y", "qd_LEFT_ELBOW_Y",
         "filteredWrenchAngularPartXLEFT", "filteredWrenchAngularPartYLEFT",
         "filteredWrenchAngularPartZLEFT", "filteredWrenchLinearPartXLEFT",
         "filteredWrenchLinearPartYLEFT", "filteredWrenchLinearPartZLEFT",
         "filteredWrenchAngularPartXRIGHT", "filteredWrenchAngularPartYRIGHT",
         "filteredWrenchAngularPartZRIGHT", "filteredWrenchLinearPartXRIGHT",
         "filteredWrenchLinearPartYRIGHT", "filteredWrenchLinearPartZRIGHT",
         "RIGHT_ELBOW_PITCH_LINKpositionFeedbackX", "RIGHT_ELBOW_PITCH_LINKpositionFeedbackY",
         "RIGHT_ELBOW_PITCH_LINKpositionFeedbackZ", "RIGHT_ELBOW_PITCH_LINKorientationFeedbackX",
         "RIGHT_ELBOW_PITCH_LINKorientationFeedbackY", "RIGHT_ELBOW_PITCH_LINKorientationFeedbackZ",
         "LEFT_ELBOW_PITCH_LINKpositionFeedbackX", "LEFT_ELBOW_PITCH_LINKpositionFeedbackY",
         "LEFT_ELBOW_PITCH_LINKpositionFeedbackZ", "LEFT_ELBOW_PITCH_LINKorientationFeedbackX",
         "LEFT_ELBOW_PITCH_LINKorientationFeedbackY", "LEFT_ELBOW_PITCH_LINKorientationFeedbackZ",
         "RIGHT_ELBOW_PITCH_LINKDesiredPositionX", "RIGHT_ELBOW_PITCH_LINKDesiredPositionY",
         "RIGHT_ELBOW_PITCH_LINKDesiredPositionZ", "RIGHT_ELBOW_PITCH_LINKDesiredPositionFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQx", "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQy",
         "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQz", "RIGHT_ELBOW_PITCH_LINKDesiredOrientationQs",
         "RIGHT_ELBOW_PITCH_LINKDesiredOrientationFrame", "RIGHT_ELBOW_PITCH_LINKCurrentPositionX",
         "RIGHT_ELBOW_PITCH_LINKCurrentPositionY", "RIGHT_ELBOW_PITCH_LINKCurrentPositionZ",
         "RIGHT_ELBOW_PITCH_LINKCurrentPositionFrame", "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQx",
         "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQy", "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQz",
         "RIGHT_ELBOW_PITCH_LINKCurrentOrientationQs", "RIGHT_ELBOW_PITCH_LINKCurrentOrientationFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorX", "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorY",
         "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorZ", "RIGHT_ELBOW_PITCH_LINKDesiredRotationVectorFrame",
         "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorX", "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorY",
         "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorZ", "RIGHT_ELBOW_PITCH_LINKCurrentRotationVectorFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityX", "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityY",
         "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityZ", "RIGHT_ELBOW_PITCH_LINKDesiredAngularVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityX", "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityY",
         "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityZ", "RIGHT_ELBOW_PITCH_LINKDesiredLinearVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityX", "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityY",
         "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityZ", "RIGHT_ELBOW_PITCH_LINKCurrentAngularVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityX", "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityY",
         "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityZ", "RIGHT_ELBOW_PITCH_LINKCurrentLinearVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityX", "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityY",
         "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityZ", "RIGHT_ELBOW_PITCH_LINKErrorAngularVelocityFrame",
         "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityX", "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityY",
         "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityZ", "RIGHT_ELBOW_PITCH_LINKErrorLinearVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredPositionX", "LEFT_ELBOW_PITCH_LINKDesiredPositionY",
         "LEFT_ELBOW_PITCH_LINKDesiredPositionZ", "LEFT_ELBOW_PITCH_LINKDesiredPositionFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredOrientationQx", "LEFT_ELBOW_PITCH_LINKDesiredOrientationQy",
         "LEFT_ELBOW_PITCH_LINKDesiredOrientationQz", "LEFT_ELBOW_PITCH_LINKDesiredOrientationQs",
         "LEFT_ELBOW_PITCH_LINKDesiredOrientationFrame", "LEFT_ELBOW_PITCH_LINKCurrentPositionX",
         "LEFT_ELBOW_PITCH_LINKCurrentPositionY", "LEFT_ELBOW_PITCH_LINKCurrentPositionZ",
         "LEFT_ELBOW_PITCH_LINKCurrentPositionFrame", "LEFT_ELBOW_PITCH_LINKCurrentOrientationQx",
         "LEFT_ELBOW_PITCH_LINKCurrentOrientationQy", "LEFT_ELBOW_PITCH_LINKCurrentOrientationQz",
         "LEFT_ELBOW_PITCH_LINKCurrentOrientationQs", "LEFT_ELBOW_PITCH_LINKCurrentOrientationFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorX", "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorY",
         "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorZ", "LEFT_ELBOW_PITCH_LINKDesiredRotationVectorFrame",
         "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorX", "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorY",
         "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorZ", "LEFT_ELBOW_PITCH_LINKCurrentRotationVectorFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityX", "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityY",
         "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityZ", "LEFT_ELBOW_PITCH_LINKDesiredAngularVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityX", "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityY",
         "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityZ", "LEFT_ELBOW_PITCH_LINKDesiredLinearVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityX", "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityY",
         "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityZ", "LEFT_ELBOW_PITCH_LINKCurrentAngularVelocityFrame",
         "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityX", "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityY",
         "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityZ", "LEFT_ELBOW_PITCH_LINKCurrentLinearVelocityFrame"
   ));
}