# This message is part of the IHMC Kinematics Streaming Toolbox module.
# It contains auxiliary information that allows to customize the contact configuration based on user input.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# The contact configuration of the left foot
bool left_foot_in_contact

# The contact configuration of the right foot
bool right_foot_in_contact