#ifndef __system_monitor_msgs__msg__SystemServiceLogRefreshMessage__idl__
#define __system_monitor_msgs__msg__SystemServiceLogRefreshMessage__idl__

module system_monitor_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="system_monitor_msgs::msg::dds_::SystemServiceLogRefreshMessage_")
      struct SystemServiceLogRefreshMessage
      {
        /**
         * The name of the systemd service
         */
        string service_name;
      };
    };
  };
};

#endif
