/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This is a stupid copy of the Float32MultiArray message to get enough array elements
because ihmc-ros2-library defaults unbounded arrays to 100 elements.
Large-capacity Float32MultiArray (1024 elements) for mask polygon data.
<p>Source (perception_msgs/Float32MultiArrayHack):
<pre>{@code
# This is a stupid copy of the Float32MultiArray message to get enough array elements
# because ihmc-ros2-library defaults unbounded arrays to 100 elements.
# Large-capacity Float32MultiArray (1024 elements) for mask polygon data.

std_msgs/MultiArrayLayout   layout        # specification of data layout
float32[<=1024]             data          # array of data
}</pre>
*/
public class Float32MultiArrayHack implements ROS2Message<Float32MultiArrayHack>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::Float32MultiArrayHack_";

   private final std_msgs.MultiArrayLayout layout_; // specification of data layout
   private final IDLFloatSequence data_; // array of data

   public Float32MultiArrayHack()
   {
      layout_ = new std_msgs.MultiArrayLayout();
      data_ = new IDLFloatSequence(0, 1024);

   }

   public Float32MultiArrayHack(Float32MultiArrayHack from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += layout_.calculateSizeBytes(currentAlignment);
      currentAlignment += data_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      layout_.serialize(buffer);
      data_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      layout_.deserialize(buffer);
      data_.deserialize(buffer);

   }

   @Override
   public void set(Float32MultiArrayHack from)
   {
      layout_.set(from.layout_);
      data_.set(from.data_);

   }

   public std_msgs.MultiArrayLayout getLayout()
   {
      return layout_;
   }

   public IDLFloatSequence getData()
   {
      return data_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Float32MultiArrayHack {");
      builder.append("layout_=");
      builder.append(layout_);
      builder.append("data_=");
      builder.append(data_);

      builder.append("}");
      return builder.toString();
   }
}