/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This message is part of the IHMC height map module
<p>Source (perception_msgs/HeightMapMessage):
<pre>{@code
# This message is part of the IHMC height map module

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# X coordinate of the center of the height map
float64 grid_center_x 0.0

# Y coordinate of the center of the height map
float64 grid_center_y 0.0

# Width of the height map in meters
float64 width_in_meters

# Cell size in meters of an individual cell
float64 cell_size_in_meters

# Cells per axis
int32 cells_per_axis

# List of heights, which correspond to the list of keys
byte[<=255000] heights
}</pre>
*/
public class HeightMapMessage implements ROS2Message<HeightMapMessage>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::HeightMapMessage_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      X coordinate of the center of the height map
   */
   private double grid_center_x_;
   /**
      Y coordinate of the center of the height map
   */
   private double grid_center_y_;
   /**
      Width of the height map in meters
   */
   private double width_in_meters_;
   /**
      Cell size in meters of an individual cell
   */
   private double cell_size_in_meters_;
   /**
      Cells per axis
   */
   private int cells_per_axis_;
   /**
      List of heights, which correspond to the list of keys
   */
   private final IDLByteSequence heights_;

   public HeightMapMessage()
   {
      grid_center_x_ = (double) 0.0;
      grid_center_y_ = (double) 0.0;
      heights_ = new IDLByteSequence(255000);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // grid_center_x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // grid_center_y_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // width_in_meters_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // cell_size_in_meters_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // cells_per_axis_
      currentAlignment += heights_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeDouble(grid_center_x_);
      buffer.writeDouble(grid_center_y_);
      buffer.writeDouble(width_in_meters_);
      buffer.writeDouble(cell_size_in_meters_);
      buffer.writeInt(cells_per_axis_);
      heights_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      grid_center_x_ = buffer.readDouble();
      grid_center_y_ = buffer.readDouble();
      width_in_meters_ = buffer.readDouble();
      cell_size_in_meters_ = buffer.readDouble();
      cells_per_axis_ = buffer.readInt();
      heights_.deserialize(buffer);

   }

   @Override
   public void set(HeightMapMessage from)
   {
      sequence_id_ = from.sequence_id_;
      grid_center_x_ = from.grid_center_x_;
      grid_center_y_ = from.grid_center_y_;
      width_in_meters_ = from.width_in_meters_;
      cell_size_in_meters_ = from.cell_size_in_meters_;
      cells_per_axis_ = from.cells_per_axis_;
      heights_.set(from.heights_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public double getGridCenterX()
   {
      return grid_center_x_;
   }

   public void setGridCenterX(double grid_center_x_)
   {
      this.grid_center_x_ = grid_center_x_;
   }

   public double getGridCenterY()
   {
      return grid_center_y_;
   }

   public void setGridCenterY(double grid_center_y_)
   {
      this.grid_center_y_ = grid_center_y_;
   }

   public double getWidthInMeters()
   {
      return width_in_meters_;
   }

   public void setWidthInMeters(double width_in_meters_)
   {
      this.width_in_meters_ = width_in_meters_;
   }

   public double getCellSizeInMeters()
   {
      return cell_size_in_meters_;
   }

   public void setCellSizeInMeters(double cell_size_in_meters_)
   {
      this.cell_size_in_meters_ = cell_size_in_meters_;
   }

   public int getCellsPerAxis()
   {
      return cells_per_axis_;
   }

   public void setCellsPerAxis(int cells_per_axis_)
   {
      this.cells_per_axis_ = cells_per_axis_;
   }

   public IDLByteSequence getHeights()
   {
      return heights_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("HeightMapMessage {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("grid_center_x_=");
      builder.append(grid_center_x_);
      builder.append("grid_center_y_=");
      builder.append(grid_center_y_);
      builder.append("width_in_meters_=");
      builder.append(width_in_meters_);
      builder.append("cell_size_in_meters_=");
      builder.append(cell_size_in_meters_);
      builder.append("cells_per_axis_=");
      builder.append(cells_per_axis_);
      builder.append("heights_=");
      builder.append(heights_);

      builder.append("}");
      return builder.toString();
   }
}