/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (perception_msgs/MeshSelectorBatchResult):
<pre>{@code
# Frame ID of the image
int64 frame_id

# Array of Mesh Selector Batch Items
perception_msgs/MeshSelectorBatchResultItem[] items}</pre>
*/
public class MeshSelectorBatchResult implements ROS2Message<MeshSelectorBatchResult>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::MeshSelectorBatchResult_";

   /**
      Frame ID of the image
   */
   private long frame_id_;
   /**
      Array of Mesh Selector Batch Items
   */
   private final IDLObjectSequence<perception_msgs.MeshSelectorBatchResultItem> items_;

   public MeshSelectorBatchResult()
   {
      items_ = new IDLObjectSequence<perception_msgs.MeshSelectorBatchResultItem>(perception_msgs.MeshSelectorBatchResultItem.class);

   }

   public MeshSelectorBatchResult(MeshSelectorBatchResult from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // frame_id_
      currentAlignment += items_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(frame_id_);
      items_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      frame_id_ = buffer.readLong();
      items_.deserialize(buffer);

   }

   @Override
   public void set(MeshSelectorBatchResult from)
   {
      frame_id_ = from.frame_id_;
      items_.set(from.items_);

   }

   public long getFrameId()
   {
      return frame_id_;
   }

   public void setFrameId(long frame_id_)
   {
      this.frame_id_ = frame_id_;
   }

   public IDLObjectSequence<perception_msgs.MeshSelectorBatchResultItem> getItems()
   {
      return items_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MeshSelectorBatchResult {");
      builder.append("frame_id_=");
      builder.append(frame_id_);
      builder.append("items_=");
      builder.append(items_);

      builder.append("}");
      return builder.toString();
   }
}