/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package perception_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Settings for the YOLOv8DetectionExecutor class
<p>Source (perception_msgs/YOLOv8ExecutorParameters):
<pre>{@code
# Settings for the YOLOv8DetectionExecutor class

ihmc_common_msgs/LatestModificationMessage latest_timestamp_modifiable

# List of the available models
perception_msgs/YOLOv8ModelInfo[<=16] available_yolo_models

# List of models to run
string[<=16] models_to_run

# Settings for each model
perception_msgs/YOLOv8ModelParameters[<=16] model_settings
}</pre>
*/
public class YOLOv8ExecutorParameters implements ROS2Message<YOLOv8ExecutorParameters>
{
   public static final java.lang.String name = "perception_msgs::msg::dds_::YOLOv8ExecutorParameters_";

   private final ihmc_common_msgs.LatestModificationMessage latest_timestamp_modifiable_;
   /**
      List of the available models
   */
   private final IDLObjectSequence<perception_msgs.YOLOv8ModelInfo> available_yolo_models_;
   /**
      List of models to run
   */
   private final IDLStringSequence models_to_run_;
   /**
      Settings for each model
   */
   private final IDLObjectSequence<perception_msgs.YOLOv8ModelParameters> model_settings_;

   public YOLOv8ExecutorParameters()
   {
      latest_timestamp_modifiable_ = new ihmc_common_msgs.LatestModificationMessage();
      available_yolo_models_ = new IDLObjectSequence<perception_msgs.YOLOv8ModelInfo>(0, 16, perception_msgs.YOLOv8ModelInfo.class);
      models_to_run_ = new IDLStringSequence(0);
      model_settings_ = new IDLObjectSequence<perception_msgs.YOLOv8ModelParameters>(0, 16, perception_msgs.YOLOv8ModelParameters.class);

   }

   public YOLOv8ExecutorParameters(YOLOv8ExecutorParameters from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += latest_timestamp_modifiable_.calculateSizeBytes(currentAlignment);
      currentAlignment += available_yolo_models_.calculateSizeBytes(currentAlignment);
      currentAlignment += models_to_run_.calculateSizeBytes(currentAlignment);
      currentAlignment += model_settings_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      latest_timestamp_modifiable_.serialize(buffer);
      available_yolo_models_.serialize(buffer);
      models_to_run_.serialize(buffer);
      model_settings_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      latest_timestamp_modifiable_.deserialize(buffer);
      available_yolo_models_.deserialize(buffer);
      models_to_run_.deserialize(buffer);
      model_settings_.deserialize(buffer);

   }

   @Override
   public void set(YOLOv8ExecutorParameters from)
   {
      latest_timestamp_modifiable_.set(from.latest_timestamp_modifiable_);
      available_yolo_models_.set(from.available_yolo_models_);
      models_to_run_.set(from.models_to_run_);
      model_settings_.set(from.model_settings_);

   }

   public ihmc_common_msgs.LatestModificationMessage getLatestTimestampModifiable()
   {
      return latest_timestamp_modifiable_;
   }

   public IDLObjectSequence<perception_msgs.YOLOv8ModelInfo> getAvailableYoloModels()
   {
      return available_yolo_models_;
   }

   public IDLStringSequence getModelsToRun()
   {
      return models_to_run_;
   }

   public IDLObjectSequence<perception_msgs.YOLOv8ModelParameters> getModelSettings()
   {
      return model_settings_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("YOLOv8ExecutorParameters {");
      builder.append("latest_timestamp_modifiable_=");
      builder.append(latest_timestamp_modifiable_);
      builder.append("available_yolo_models_=");
      builder.append(available_yolo_models_);
      builder.append("models_to_run_=");
      builder.append(models_to_run_);
      builder.append("model_settings_=");
      builder.append(model_settings_);

      builder.append("}");
      return builder.toString();
   }
}