#ifndef __exoskeleton_msgs__msg__ExoStepDataMessage__idl__
#define __exoskeleton_msgs__msg__ExoStepDataMessage__idl__

module exoskeleton_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * This message is part of the IHMC whole-body controller API.
       * This message specifies the position, orientation and side (left or right) of a desired footstep in world frame.
       */
      @TypeCode(type="exoskeleton_msgs::msg::dds_::ExoStepDataMessage_")
      struct ExoStepDataMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Specifies which foot will swing to reach the footstep.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * Specifies the length of the footstep.
         */
        double step_length;
        /**
         * Specifies the height of the footstep.
         */
        double step_height;
        /**
         * Specifies the ending pitch of the footstep.
         */
        double step_pitch;
        /**
         * Contains information on how high the robot should swing its foot.
         * This affects trajectory types TRAJECTORY_TYPE_DEFAULT and TRAJECTORY_TYPE_OBSTACLE_CLEARANCE.
         * If a value smaller then the minimal swing height is chosen (e.g. 0.0) the swing height will be changed to a default value.
         */
        @defaultValue(value=-1.0)
        double swing_height;
        /**
         * The swingDuration is the time a foot is not in ground contact during a step.
         * If the value of this field is invalid (not positive) it will be replaced by a default swing_duration.
         */
        @defaultValue(value=-1.0)
        double swing_duration;
        /**
         * The transferDuration is the time spent with the feet in ground contact before a step.
         * If the value of this field is invalid (not positive) it will be replaced by a default transfer_duration.
         */
        @defaultValue(value=-1.0)
        double transfer_duration;
      };
    };
  };
};

#endif
