#ifndef __exoskeleton_msgs__msg__MetabolicMessage__idl__
#define __exoskeleton_msgs__msg__MetabolicMessage__idl__

module exoskeleton_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the Exoskeleton Metabolic Estimation Interface
       * This message acts as a go-between between Java and Python.
       */
      @TypeCode(type="exoskeleton_msgs::msg::dds_::MetabolicMessage_")
      struct MetabolicMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Current metabolic rate plus the change from the previous metabolic rate
         */
        double metabolic_rate;
        double delta_metabolic_rate;
      };
    };
  };
};

#endif
