# A yaw-pitch-roll is used to represent a 3D orientation by three successive rotations: rotation around the z-axis
# (yaw), then around the y-axis (pitch), and then around the x-axis (roll). The three components yaw, pitch, and
# roll represents the angle for rotation expressed in radians.

# The yaw angle representing the first rotation around the z-axis.
float64 yaw

# The pitch angle representing the second rotation around the y-axis.
float64 pitch

# The roll angle representing the third rotation around the x-axis.
float64 roll