package head_monitor_msgs;

public interface HeadMonitorAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "head_monitor_msgs/HeadMonitorAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeadMonitorActionGoal action_goal\nHeadMonitorActionResult action_result\nHeadMonitorActionFeedback action_feedback\n";
  head_monitor_msgs.HeadMonitorActionGoal getActionGoal();
  void setActionGoal(head_monitor_msgs.HeadMonitorActionGoal value);
  head_monitor_msgs.HeadMonitorActionResult getActionResult();
  void setActionResult(head_monitor_msgs.HeadMonitorActionResult value);
  head_monitor_msgs.HeadMonitorActionFeedback getActionFeedback();
  void setActionFeedback(head_monitor_msgs.HeadMonitorActionFeedback value);
}
