# This message is going to take in data and assign to each muscle channel

uint32 id  #message ID

#arrays for each muscle channel
float32[] frontalis
float32[] ta
float32[] tp
float32[] masseter
float32[] scm
float32[] middlet
float32[] antdeltoid
float32[] mserratusant
float32[] lattriceps
float32[] brachiod
float32[] bicepsbr
float32[] flexcarpu
float32[] flexcarpr
float32[] abductpol
float32[] extdig
float32[] pectmajor
float32[] rectabdomup
float32[] rectabdomlo
float32[] extoblique
float32[] intoblique
float32[] adductors
float32[] soleus
float32[] tibant
float32[] peronous
float32[] medgastro
float32[] latgastro
float32[] bicepsfem
float32[] semitend
float32[] vlo
float32[] vmo
float32[] rectusfem
float32[] pelvicfloor
float32[] uppertrap
float32[] middletrap
float32[] lowertrap
float32[] thoracic
float32[] multifidii
float32[] glutmax
float32[] glutmed
float32[] latdorsi
float32[] infraspin
float32[] cervicalps
