/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package vision_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A 3D bounding box that can be positioned and rotated about its center (6 DOF)
Dimensions of this box are in meters, and as such, it may be migrated to
another package, such as geometry_msgs, in the future.
<p>Source (vision_msgs/BoundingBox3D):
<pre>{@code
# A 3D bounding box that can be positioned and rotated about its center (6 DOF)
# Dimensions of this box are in meters, and as such, it may be migrated to
#   another package, such as geometry_msgs, in the future.

# The 3D position and orientation of the bounding box center
geometry_msgs/Pose center

# The total size of the bounding box, in meters, surrounding the object's center
#   pose.
geometry_msgs/Vector3 size
}</pre>
*/
public class BoundingBox3D implements ROS2Message<BoundingBox3D>
{
   public static final java.lang.String name = "vision_msgs::msg::dds_::BoundingBox3D_";

   /**
      The 3D position and orientation of the bounding box center
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPose3DMessage center_;
   /**
      The total size of the bounding box, in meters, surrounding the object's center
      pose.
   */
   private final us.ihmc.euclid.jros2.messages.EuclidVector3DMessage size_;

   public BoundingBox3D()
   {
      center_ = new us.ihmc.euclid.jros2.messages.EuclidPose3DMessage();
      size_ = new us.ihmc.euclid.jros2.messages.EuclidVector3DMessage();

   }

   public BoundingBox3D(BoundingBox3D from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += center_.calculateSizeBytes(currentAlignment);
      currentAlignment += size_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      center_.serialize(buffer);
      size_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      center_.deserialize(buffer);
      size_.deserialize(buffer);

   }

   @Override
   public void set(BoundingBox3D from)
   {
      center_.set(from.center_);
      size_.set(from.size_);

   }

   public us.ihmc.euclid.jros2.messages.EuclidPose3DMessage getCenter()
   {
      return center_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidVector3DMessage getSize()
   {
      return size_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("BoundingBox3D {");
      builder.append("center_=");
      builder.append(center_);
      builder.append("size_=");
      builder.append(size_);

      builder.append("}");
      return builder.toString();
   }
}