/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package vision_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A 2D bounding box that can be rotated about its center.
All dimensions are in pixels, but represented using floating-point
values to allow sub-pixel precision. If an exact pixel crop is required
for a rotated bounding box, it can be calculated using Bresenham's line
algorithm.
<p>Source (vision_msgs/BoundingBox2D):
<pre>{@code
# A 2D bounding box that can be rotated about its center.
# All dimensions are in pixels, but represented using floating-point
#   values to allow sub-pixel precision. If an exact pixel crop is required
#   for a rotated bounding box, it can be calculated using Bresenham's line
#   algorithm.

# The 2D position (in pixels) and orientation of the bounding box center.
vision_msgs/Pose2D center

# The total size (in pixels) of the bounding box surrounding the object relative
#   to the pose of its center.
float64 size_x
float64 size_y
}</pre>
*/
public class BoundingBox2D implements ROS2Message<BoundingBox2D>
{
   public static final java.lang.String name = "vision_msgs::msg::dds_::BoundingBox2D_";

   /**
      The 2D position (in pixels) and orientation of the bounding box center.
   */
   private final vision_msgs.Pose2D center_;
   /**
      The total size (in pixels) of the bounding box surrounding the object relative
      to the pose of its center.
   */
   private double size_x_;
   private double size_y_;

   public BoundingBox2D()
   {
      center_ = new vision_msgs.Pose2D();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += center_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // size_x_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // size_y_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      center_.serialize(buffer);
      buffer.writeDouble(size_x_);
      buffer.writeDouble(size_y_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      center_.deserialize(buffer);
      size_x_ = buffer.readDouble();
      size_y_ = buffer.readDouble();

   }

   @Override
   public void set(BoundingBox2D from)
   {
      center_.set(from.center_);
      size_x_ = from.size_x_;
      size_y_ = from.size_y_;

   }

   public vision_msgs.Pose2D getCenter()
   {
      return center_;
   }

   public double getSizeX()
   {
      return size_x_;
   }

   public void setSizeX(double size_x_)
   {
      this.size_x_ = size_x_;
   }

   public double getSizeY()
   {
      return size_y_;
   }

   public void setSizeY(double size_y_)
   {
      this.size_y_ = size_y_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("BoundingBox2D {");
      builder.append("center_=");
      builder.append(center_);
      builder.append("size_x_=");
      builder.append(size_x_);
      builder.append("size_y_=");
      builder.append(size_y_);

      builder.append("}");
      return builder.toString();
   }
}