/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package vision_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Defines a 2D detection result.

This is similar to a 2D classification, but includes position information,
allowing a classification result for a specific crop or image point to
to be located in the larger image.
<p>Source (vision_msgs/Detection2D):
<pre>{@code
# Defines a 2D detection result.
#
# This is similar to a 2D classification, but includes position information,
#   allowing a classification result for a specific crop or image point to
#   to be located in the larger image.

std_msgs/Header header

# Class probabilities
ObjectHypothesisWithPose[] results

# 2D bounding box surrounding the object.
BoundingBox2D bbox

# ID used for consistency across multiple detection messages. Detections
# of the same object in different detection messages should have the same id.
# This field may be empty.
string id

# Source data that generated this detection are not a part of the message.
# If you need to access them, use an exact or approximate time synchronizer in
# your code, as this message's header should match the header of the source
# data.
}</pre>
*/
public class Detection2D implements ROS2Message<Detection2D>
{
   public static final java.lang.String name = "vision_msgs::msg::dds_::Detection2D_";

   private final std_msgs.Header header_;
   /**
      Class probabilities
   */
   private final IDLObjectSequence<vision_msgs.ObjectHypothesisWithPose> results_;
   /**
      2D bounding box surrounding the object.
   */
   private final vision_msgs.BoundingBox2D bbox_;
   /**
      ID used for consistency across multiple detection messages. Detections
      of the same object in different detection messages should have the same id.
      This field may be empty.
   */
   private final StringBuilder id_;

   public Detection2D()
   {
      header_ = new std_msgs.Header();
      results_ = new IDLObjectSequence<vision_msgs.ObjectHypothesisWithPose>(vision_msgs.ObjectHypothesisWithPose.class);
      bbox_ = new vision_msgs.BoundingBox2D();
      id_ = new StringBuilder();

   }

   public Detection2D(Detection2D from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += header_.calculateSizeBytes(currentAlignment);
      currentAlignment += results_.calculateSizeBytes(currentAlignment);
      currentAlignment += bbox_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * id_.length()) + 1; // id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      header_.serialize(buffer);
      results_.serialize(buffer);
      bbox_.serialize(buffer);
      buffer.writeString(id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      header_.deserialize(buffer);
      results_.deserialize(buffer);
      bbox_.deserialize(buffer);
      buffer.readString(id_);

   }

   @Override
   public void set(Detection2D from)
   {
      header_.set(from.header_);
      results_.set(from.results_);
      bbox_.set(from.bbox_);
      id_.delete(0, id_.length());
      id_.insert(0, from.id_);

   }

   public std_msgs.Header getHeader()
   {
      return header_;
   }

   public IDLObjectSequence<vision_msgs.ObjectHypothesisWithPose> getResults()
   {
      return results_;
   }

   public vision_msgs.BoundingBox2D getBbox()
   {
      return bbox_;
   }

   public StringBuilder getId()
   {
      return id_;
   }

   public java.lang.String getIdAsString()
   {
      return id_.toString();
   }

   public void setId(java.lang.String s)
   {
      this.id_.delete(0, this.id_.length());
      this.id_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Detection2D {");
      builder.append("header_=");
      builder.append(header_);
      builder.append("results_=");
      builder.append(results_);
      builder.append("bbox_=");
      builder.append(bbox_);
      builder.append("id_=");
      builder.append(id_.toString());

      builder.append("}");
      return builder.toString();
   }
}