/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package vision_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A key value pair that maps an integer class_id to a string class label
in computer vision systems.
<p>Source (vision_msgs/VisionClass):
<pre>{@code
# A key value pair that maps an integer class_id to a string class label
#   in computer vision systems.

# The int value that identifies the class.
# Elements identified with 65535, the maximum uint16 value are assumed
#   to belong to the "UNLABELED" class. For vision pipelines using less
#   than 255 classes the "UNLABELED" is the maximum value in the uint8
#   range.
uint16 class_id

# The name of the class represented by the class_id
string class_name
}</pre>
*/
public class VisionClass implements ROS2Message<VisionClass>
{
   public static final java.lang.String name = "vision_msgs::msg::dds_::VisionClass_";

   /**
      The int value that identifies the class.
      Elements identified with 65535, the maximum uint16 value are assumed
      to belong to the "UNLABELED" class. For vision pipelines using less
      than 255 classes the "UNLABELED" is the maximum value in the uint8
      range.
   */
   private int class_id_;
   /**
      The name of the class represented by the class_id
   */
   private final StringBuilder class_name_;

   public VisionClass()
   {
      class_name_ = new StringBuilder();

   }

   public VisionClass(VisionClass from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // class_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * class_name_.length()) + 1; // class_name_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeUInt16(class_id_);
      buffer.writeString(class_name_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      class_id_ = buffer.readUInt16();
      buffer.readString(class_name_);

   }

   @Override
   public void set(VisionClass from)
   {
      class_id_ = from.class_id_;
      class_name_.delete(0, class_name_.length());
      class_name_.insert(0, from.class_name_);

   }

   public int getClassId()
   {
      return class_id_;
   }

   public void setClassId(int class_id_)
   {
      this.class_id_ = class_id_;
   }

   public StringBuilder getClassName()
   {
      return class_name_;
   }

   public java.lang.String getClassNameAsString()
   {
      return class_name_.toString();
   }

   public void setClassName(java.lang.String s)
   {
      this.class_name_.delete(0, this.class_name_.length());
      this.class_name_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("VisionClass {");
      builder.append("class_id_=");
      builder.append(class_id_);
      builder.append("class_name_=");
      builder.append(class_name_.toString());

      builder.append("}");
      return builder.toString();
   }
}