package control_msgs;

public interface PointHeadActionActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/PointHeadActionActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nPointHeadActionFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  control_msgs.PointHeadActionFeedback getFeedback();
  void setFeedback(control_msgs.PointHeadActionFeedback value);
}
