package move_base_msgs;

public interface MoveBaseResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "move_base_msgs/MoveBaseResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n";
}
