#ifndef __unitree_h_one_msgs__msg__MotorCmd__idl__
#define __unitree_h_one_msgs__msg__MotorCmd__idl__

module unitree_h_one_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_h_one_msgs::msg::dds_::MotorCmd_")
      struct MotorCmd
      {
        octet mode;
        float q;
        float dq;
        float tau;
        float kp;
        float kd;
        unsigned long reserve;
      };
    };
  };
};

#endif
