#ifndef __unitree_h_one_msgs__msg__PressSensorState__idl__
#define __unitree_h_one_msgs__msg__PressSensorState__idl__

module unitree_h_one_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="unitree_h_one_msgs::msg::dds_::PressSensorState_")
      struct PressSensorState
      {
        float pressure[12];
        float temperature[12];
      };
    };
  };
};

#endif
