package us.ihmc.footstepPlanning.steppableRegions;

import us.ihmc.tools.property.*;

/**
 * The JSON file for this property set is located here:
 * ihmc-footstep-planning/src/main/resources/us/ihmc/footstepPlanning/steppableRegions/SteppableRegionCalculatorParameters.json
 *
 * This class was auto generated. Property attributes must be edited in the JSON file,
 * after which this class should be regenerated by running the main. This class uses
 * the generator to assist in the addition, removal, and modification of property keys.
 * It is permissible to forgo these benefits and abandon the generator, in which case
 * you should also move it from the generated-java folder to the java folder.
 *
 * If the constant paths have changed, change them in this file and run the main to regenerate.
 */
public class SteppableRegionCalculatorParameters extends StoredPropertySet implements SteppableRegionCalculatorParametersBasics
{
   public static final StoredPropertyKeyList keys = new StoredPropertyKeyList();

   public static final DoubleStoredPropertyKey normalSearchRadius = keys.addDoubleKey("Normal search radius");
   public static final DoubleStoredPropertyKey minSupportAreaFraction = keys.addDoubleKey("Min support area fraction");
   public static final DoubleStoredPropertyKey minSnapHeightThreshold = keys.addDoubleKey("Min snap height threshold");
   public static final DoubleStoredPropertyKey snapHeightThresholdAtSearchEdge = keys.addDoubleKey("Snap height threshold at search edge");
   public static final DoubleStoredPropertyKey steppingCosineThreshold = keys.addDoubleKey("Stepping cosine threshold");
   public static final DoubleStoredPropertyKey squaredErrorThreshold = keys.addDoubleKey("Squared error threshold");

   /**
    * Loads this property set.
    */
   public SteppableRegionCalculatorParameters()
   {
      this("");
   }

   /**
    * Loads an alternate version of this property set in the same folder.
    */
   public SteppableRegionCalculatorParameters(String versionSuffix)
   {
      this(SteppableRegionCalculatorParameters.class, versionSuffix);
   }

   /**
    * Loads an alternate version of this property set in other folders.
    */
   public SteppableRegionCalculatorParameters(Class<?> classForLoading, String versionSuffix)
   {
      super(keys, classForLoading, SteppableRegionCalculatorParameters.class, versionSuffix);
      load();
   }

   public SteppableRegionCalculatorParameters(StoredPropertySetReadOnly other)
   {
      super(keys, SteppableRegionCalculatorParameters.class, other.getCurrentVersionSuffix());
      set(other);
   }

   public static void main(String[] args)
   {
      StoredPropertySet parameters = new StoredPropertySet(keys, SteppableRegionCalculatorParameters.class);
      parameters.generateJavaFiles();
   }
}
