# Structure for parameters controlling pelvis servo.

float64 pelvis_height # User desired height of the pelvis. 
float64 pelvis_yaw    # User desired yaw angle of the pelvis. 
float64 pelvis_pitch  # User desired pitch angle of the pelvis. 
float64 pelvis_roll   # User desired roll angle of the pelvis. 
float64 com_v0        # User desired horizontal offset of the COM. 
float64 com_v1        # User desired horizontal offset of the COM. 