package us.ihmc.atlas.StepAdjustmentVisualizers;

public enum PushDirection
{
   FORWARD, FORWARD_45, BACKWARD, BACKWARD_45, OUTWARD, FORWARD_30, FORWARD_60//, FORWARD_IN_45, BACKWARD_IN_45, BACKWARD_30, BACKWARD_60, FORWARD_IN_30,  BACKWARD_IN_30
}
