#ifndef __behavior_msgs__msg__AbilityHandActionDefinitionMessage__idl__
#define __behavior_msgs__msg__AbilityHandActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AbilityHandActionDefinitionMessage_")
      struct AbilityHandActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Specifies the side of the robot that this message refers to.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * AbilityHandManager.ControlMode ordinal
         */
        octet control_mode;
        /**
         * Grip to execute, if grip control mode
         */
        octet grip;
        /**
         * Goal positions for the joints
         */
        float goal_positions[6];
        /**
         * Goal positions for the joints
         */
        float goal_velocities[6];
      };
    };
  };
};

#endif
