#ifndef __behavior_msgs__msg__AbilityHandActionDefinitionMessage__idl__
#define __behavior_msgs__msg__AbilityHandActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AbilityHandActionDefinitionMessage_")
      struct AbilityHandActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Specifies the side of the robot that this message refers to.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * AbilityHandManager.ControlMode ordinal
         */
        octet control_mode;
        /**
         * Grip to execute, if grip control mode
         */
        octet grip;
        /**
         * Goal positions for the joints
         */
        float goal_positions[6];
        /**
         * Goal positions for the joints
         */
        float goal_velocities[6];
        /**
         * Success criteria type (enum in AbilityHandActionDefinition)
         */
        octet success_criteria;
        /**
         * +/- tolerance in degrees for each joint position check
         */
        float each_joint_position_tolerance;
        /**
         * Sum all absolute joint movement into one value and check it exceeds this value
         */
        float sufficient_cumulative_joint_movement;
        /**
         * Enable a sinusoidal wiggling of joints if they are unresponsive
         */
        boolean enable_wiggle_on_failure;
        /**
         * When to start wiggling
         */
        float time_to_wiggle;
        /**
         * Timeout regardless of modes, action will cease after this time
         */
        float ultimate_timeout;
      };
    };
  };
};

#endif
