#ifndef __behavior_msgs__msg__ActionSequenceUpdateMessage__idl__
#define __behavior_msgs__msg__ActionSequenceUpdateMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ActionSequenceUpdateMessage_")
      struct ActionSequenceUpdateMessage
      {
        /**
         * Unique identifier of the sequence update used to make sure we got complete data
         */
        unsigned long long sequence_update_uuid;
        /**
         * Number of actions within the sequence
         */
        unsigned long sequence_size;
      };
    };
  };
};

#endif
