#ifndef __behavior_msgs__msg__ActionExecutionStatusMessage__idl__
#define __behavior_msgs__msg__ActionExecutionStatusMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is meant to communicate the status of currently executing actions
       */
      @TypeCode(type="behavior_msgs::msg::dds_::ActionExecutionStatusMessage_")
      struct ActionExecutionStatusMessage
      {
        /**
         * Executing action index
         */
        long action_index;
        /**
         * Nominal execution duration
         */
        double nominal_execution_duration;
        /**
         * Time since execution started
         */
        double elapsed_execution_time;
        /**
         * Total number of footsteps; used for walking actions
         */
        unsigned short total_number_of_footsteps;
        /**
         * Incomplete footsteps; used for walking actions
         */
        unsigned short number_of_incomplete_footsteps;
        /**
         * Current position distance to goal
         */
        double current_position_distance_to_goal;
        /**
         * Start position distance to goal
         */
        double start_position_distance_to_goal;
        /**
         * Position distance to goal tolerance
         */
        double position_distance_to_goal_tolerance;
        /**
         * Current orientation distance to goal
         */
        double current_orientation_distance_to_goal;
        /**
         * Start orientation distance to goal
         */
        double start_orientation_distance_to_goal;
        /**
         * Orientation distance to goal tolerance
         */
        double orientation_distance_to_goal_tolerance;
        /**
         * Linear hand wrench magnitude
         */
        double hand_wrench_magnitude_linear;
      };
    };
  };
};

#endif
