#ifndef __behavior_msgs__msg__ActionSequenceUpdateMessage__idl__
#define __behavior_msgs__msg__ActionSequenceUpdateMessage__idl__

#include "behavior_msgs/msg/./ArmJointAnglesActionStateMessage_.idl"
#include "behavior_msgs/msg/./ChestOrientationActionStateMessage_.idl"
#include "behavior_msgs/msg/./FootstepPlanActionStateMessage_.idl"
#include "behavior_msgs/msg/./HandPoseActionStateMessage_.idl"
#include "behavior_msgs/msg/./HandWrenchActionStateMessage_.idl"
#include "behavior_msgs/msg/./PelvisHeightPitchActionStateMessage_.idl"
#include "behavior_msgs/msg/./SakeHandCommandActionStateMessage_.idl"
#include "behavior_msgs/msg/./WaitDurationActionStateMessage_.idl"
#include "behavior_msgs/msg/./WalkActionStateMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ActionSequenceUpdateMessage_")
      struct ActionSequenceUpdateMessage
      {
        /**
         * Number of actions within the sequence
         */
        unsigned short sequence_size;
        sequence<behavior_msgs::msg::dds::ArmJointAnglesActionStateMessage, 200> arm_joint_angles_actions;
        sequence<behavior_msgs::msg::dds::ChestOrientationActionStateMessage, 200> chest_orientation_actions;
        sequence<behavior_msgs::msg::dds::FootstepPlanActionStateMessage, 200> footstep_plan_actions;
        sequence<behavior_msgs::msg::dds::SakeHandCommandActionStateMessage, 200> sake_hand_command_actions;
        sequence<behavior_msgs::msg::dds::HandPoseActionStateMessage, 200> hand_pose_actions;
        sequence<behavior_msgs::msg::dds::HandWrenchActionStateMessage, 200> hand_wrench_actions;
        sequence<behavior_msgs::msg::dds::PelvisHeightPitchActionStateMessage, 200> pelvis_height_actions;
        sequence<behavior_msgs::msg::dds::WaitDurationActionStateMessage, 200> wait_duration_actions;
        sequence<behavior_msgs::msg::dds::WalkActionStateMessage, 200> walk_actions;
      };
    };
  };
};

#endif
