#ifndef __behavior_msgs__msg__ActionExecutionStatusMessage__idl__
#define __behavior_msgs__msg__ActionExecutionStatusMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is meant to communicate the status of currently executing actions
       */
      @TypeCode(type="behavior_msgs::msg::dds_::ActionExecutionStatusMessage_")
      struct ActionExecutionStatusMessage
      {
        /**
         * Executing action index
         */
        long action_index;
        /**
         * Nominal execution duration
         */
        double nominal_execution_duration;
        /**
         * Time since execution started
         */
        double elapsed_execution_time;
        /**
         * Total number of footsteps; used for walking actions
         */
        unsigned short total_number_of_footsteps;
        /**
         * Incomplete footsteps; used for walking actions
         */
        unsigned short number_of_incomplete_footsteps;
        /**
         * Translation current distance to goal
         */
        double translation_current_distance_to_goal;
        /**
         * Translation start distance to goal
         */
        double translation_start_distance_to_goal;
        /**
         * Orientation current distance to goal
         */
        double orientation_current_distance_to_goal;
        /**
         * Orientation start distance to goal
         */
        double orientation_start_distance_to_goal;
      };
    };
  };
};

#endif
