#ifndef __behavior_msgs__msg__ActionSequenceUpdateMessage__idl__
#define __behavior_msgs__msg__ActionSequenceUpdateMessage__idl__

#include "behavior_msgs/msg/./ArmJointAnglesActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./BodyPartPoseActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./FootstepPlanActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./HandWrenchActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./SakeHandCommandActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./SidedBodyPartPoseActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./WaitDurationActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./WalkActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ActionSequenceUpdateMessage_")
      struct ActionSequenceUpdateMessage
      {
        /**
         * Number of actions within the sequence
         */
        unsigned short sequence_size;
        sequence<behavior_msgs::msg::dds::ArmJointAnglesActionDefinitionMessage, 200> arm_joint_angles_actions;
        sequence<behavior_msgs::msg::dds::BodyPartPoseActionDefinitionMessage, 200> chest_orientation_actions;
        sequence<behavior_msgs::msg::dds::FootstepPlanActionDefinitionMessage, 200> footstep_plan_actions;
        sequence<behavior_msgs::msg::dds::SakeHandCommandActionDefinitionMessage, 200> sake_hand_command_actions;
        sequence<behavior_msgs::msg::dds::SidedBodyPartPoseActionDefinitionMessage, 200> hand_pose_actions;
        sequence<behavior_msgs::msg::dds::HandWrenchActionDefinitionMessage, 200> hand_wrench_actions;
        sequence<behavior_msgs::msg::dds::BodyPartPoseActionDefinitionMessage, 200> pelvis_height_actions;
        sequence<behavior_msgs::msg::dds::SidedBodyPartPoseActionDefinitionMessage, 200> foot_pose_actions;
        sequence<behavior_msgs::msg::dds::WaitDurationActionDefinitionMessage, 200> wait_duration_actions;
        sequence<behavior_msgs::msg::dds::WalkActionDefinitionMessage, 200> walk_actions;
      };
    };
  };
};

#endif
