#ifndef __behavior_msgs__msg__ActionsExecutionStatusMessage__idl__
#define __behavior_msgs__msg__ActionsExecutionStatusMessage__idl__

#include "behavior_msgs/msg/./ActionExecutionStatusMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is meant to communicate the status of currently executing actions
       */
      @TypeCode(type="behavior_msgs::msg::dds_::ActionsExecutionStatusMessage_")
      struct ActionsExecutionStatusMessage
      {
        /**
         * This message contains a list of action status messages
         */
        sequence<behavior_msgs::msg::dds::ActionExecutionStatusMessage> action_status_list;
      };
    };
  };
};

#endif
