#ifndef __behavior_msgs__msg__ActionInformationMessage__idl__
#define __behavior_msgs__msg__ActionInformationMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ActionInformationMessage_")
      struct ActionInformationMessage
      {
        /**
         * Index of the action within the sequence
         */
        unsigned long action_index;
      };
    };
  };
};

#endif
