#ifndef __behavior_msgs__msg__ActionSequenceStateMessage__idl__
#define __behavior_msgs__msg__ActionSequenceStateMessage__idl__

#include "behavior_msgs/msg/./ActionSequenceDefinitionMessage_.idl"
#include "behavior_msgs/msg/./BehaviorTreeNodeStateMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ActionSequenceStateMessage_")
      struct ActionSequenceStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::ActionSequenceDefinitionMessage definition;
      };
    };
  };
};

#endif
