#ifndef __behavior_msgs__msg__AI2RActionFailureMessage__idl__
#define __behavior_msgs__msg__AI2RActionFailureMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Quaternion_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * For use by external AI to modify the behavior tree and operate behaviors
       */
      @TypeCode(type="behavior_msgs::msg::dds_::AI2RActionFailureMessage_")
      struct AI2RActionFailureMessage
      {
        /**
         * Name of the action that has failed
         */
        string action_name;
        /**
         * Type of the action
         */
        string action_type;
        /**
         * Reference frame of the action
         */
        string action_frame;
        /**
         * Position tolerance for the action [m]
         */
        double position_tolerance;
        /**
         * Orientation tolerance for the action [deg]
         */
        double orientation_tolerance;
        /**
         * Error in position for the action
         */
        geometry_msgs::msg::dds::Point position_error;
        /**
         * Error in orientation for the action
         */
        geometry_msgs::msg::dds::Quaternion orientation_error;
        /**
         * Last commanded position (in action_frame) for the action
         */
        geometry_msgs::msg::dds::Point desired_position;
        /**
         * Last commanded orientation (in action_frame) for the action
         */
        geometry_msgs::msg::dds::Quaternion desired_orientation;
      };
    };
  };
};

#endif
