#ifndef __behavior_msgs__msg__AI2RNavigationMessage__idl__
#define __behavior_msgs__msg__AI2RNavigationMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AI2RNavigationMessage_")
      struct AI2RNavigationMessage
      {
        /**
         * Goto action - Reference frame for the action
         */
        string reference_frame_name;
        /**
         * Goto action - The distance to the frame
         */
        double distance_to_frame;
      };
    };
  };
};

#endif
