#ifndef __behavior_msgs__msg__AI2RReceiveObjectMessage__idl__
#define __behavior_msgs__msg__AI2RReceiveObjectMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AI2RReceiveObjectMessage_")
      struct AI2RReceiveObjectMessage
      {
        /**
         * Reference frame (object) to receive
         */
        string object_name;
        /**
         * Which hand to receive the object
         */
        @defaultValue(value=255)
        octet side;
        /**
         * The maximum distance hand-object allowed to trigger grasping
         */
        double distance_to_object;
      };
    };
  };
};

#endif
