#ifndef __behavior_msgs__msg__AI2RCommandMessage__idl__
#define __behavior_msgs__msg__AI2RCommandMessage__idl__

#include "behavior_msgs/msg/./AI2RHandPoseAdaptationMessage_.idl"
#include "behavior_msgs/msg/./AI2RNavigationMessage_.idl"
#include "behavior_msgs/msg/./AI2RReceiveObjectMessage_.idl"
#include "behavior_msgs/msg/./AI2RScanMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AI2RCommandMessage_")
      struct AI2RCommandMessage
      {
        /**
         * Behavior to execute (checkpoint to jump to in the pre-loaded behavior collection)
         */
        string behavior_to_execute;
        boolean adapting_behavior;
        behavior_msgs::msg::dds::AI2RHandPoseAdaptationMessage hand_pose_adaptation;
        behavior_msgs::msg::dds::AI2RNavigationMessage navigation;
        behavior_msgs::msg::dds::AI2RReceiveObjectMessage receive_object;
        behavior_msgs::msg::dds::AI2RScanMessage scan;
      };
    };
  };
};

#endif
