#ifndef __behavior_msgs__msg__AI2RNavigationMessage__idl__
#define __behavior_msgs__msg__AI2RNavigationMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {
      /**
       * SPATIAL RELATION TYPE
       */
      const octet DEFAULT =
      0;

      const octet FRONT =
      1;

      const octet BEHIND =
      2;

      const octet LEFT =
      3;

      const octet RIGHT =
      4;


      @TypeCode(type="behavior_msgs::msg::dds_::AI2RNavigationMessage_")
      struct AI2RNavigationMessage
      {
        /**
         * The type of spatial relation with the secondary reference object as defined above
         */
        octet spatial_relation;
        /**
         * Point of view object. Secondary reference frame (object) used as the point of view that defines the spatial relation with the object
         */
        string pov_object;
        /**
         * Target reference frame (object) to go to
         */
        string target_object;
        /**
         * The distance to the reference frame (located at the object's centroid)
         */
        double distance_to_object;
        /**
         * The minimum distance to the obstacles considered in body path planning
         */
        double obstacle_clearance;
      };
    };
  };
};

#endif
