#ifndef __behavior_msgs__msg__AI2RPickUpObjectMessage__idl__
#define __behavior_msgs__msg__AI2RPickUpObjectMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AI2RPickUpObjectMessage_")
      struct AI2RPickUpObjectMessage
      {
        /**
         * Reference frame (object) to pick up
         */
        string object_name;
      };
    };
  };
};

#endif
