#ifndef __behavior_msgs__msg__AI2RScanMessage__idl__
#define __behavior_msgs__msg__AI2RScanMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AI2RScanMessage_")
      struct AI2RScanMessage
      {
        sequence<string, 200> object_names;
      };
    };
  };
};

#endif
