#ifndef __behavior_msgs__msg__AI2RHandPoseAdaptationMessage__idl__
#define __behavior_msgs__msg__AI2RHandPoseAdaptationMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Quaternion_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::AI2RHandPoseAdaptationMessage_")
      struct AI2RHandPoseAdaptationMessage
      {
        /**
         * Name of the action to adapt
         */
        string action_name;
        /**
         * Hand Pose action - Reference frame for the action
         */
        string reference_frame_name;
        /**
         * Hand Pose action - The position of the hand specified in reference_frame_name
         */
        geometry_msgs::msg::dds::Point new_position;
        /**
         * Hand Pose action - The orientation of the hand specified in reference_frame_name
         */
        geometry_msgs::msg::dds::Quaternion new_orientation;
      };
    };
  };
};

#endif
