#ifndef __behavior_msgs__msg__ArmActionDefinitionMessage__idl__
#define __behavior_msgs__msg__ArmActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ArmActionDefinitionMessage_")
      struct ArmActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Specifies the side of the robot that this message refers to.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * Whether the action is defined in jointspace (true) or taskspace (false)
         */
        boolean defined_in_jointspace;
        /**
         * Taskspace trajectory mode: 0 = single pose, 1 = screw primitive
         */
        octet taskspace_trajectory_mode;
        /**
         * The trajectory duration
         */
        double trajectory_duration;
        /**
         * Preset arm configuration
         */
        octet preset;
        /**
         * Joint angles
         */
        double joint_angles[7];
        /**
         * Name of the frame the this action is expressed in
         */
        string parent_frame_name;
        /**
         * Transform that expresses the hand pose in the parent frame
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage transform_to_parent;
        /**
         * Whether the rigid body is controlled in jointspace (true) or hybrid (false) during single-point taskspace execution
         */
        boolean joint_space_control;
        /**
         * Whether maintaining the rigid body controlled in world after the action is complete
         */
        boolean hold_pose_in_world;
        /**
         * Screw primitive fields
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage screw_axis_pose;
        double translation;
        double rotation;
        double max_linear_velocity;
        double max_angular_velocity;
        double linear_position_weight;
        double angular_position_weight;
        double jointspace_weight;
        double position_error_tolerance;
        double orientation_error_tolerance;
      };
    };
  };
};

#endif
