#ifndef __behavior_msgs__msg__ArmJointAnglesActionDefinitionMessage__idl__
#define __behavior_msgs__msg__ArmJointAnglesActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ArmJointAnglesActionDefinitionMessage_")
      struct ArmJointAnglesActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Specifies the side of the robot that this message refers to.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * Preset arm configuration
         */
        long preset;
        /**
         * Joint angles
         */
        double joint_angles[7];
        /**
         * Duration of the trajectory
         */
        double trajectory_duration;
      };
    };
  };
};

#endif
