#ifndef __behavior_msgs__msg__BasicNodeStateMessage__idl__
#define __behavior_msgs__msg__BasicNodeStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeDefinitionMessage_.idl"
#include "behavior_msgs/msg/./BehaviorTreeNodeStateMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::BasicNodeStateMessage_")
      struct BasicNodeStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeDefinitionMessage definition;
      };
    };
  };
};

#endif
