#ifndef __behavior_msgs__msg__BehaviorTreeSceneObjectStateMessage__idl__
#define __behavior_msgs__msg__BehaviorTreeSceneObjectStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeSceneObjectDefinitionMessage_.idl"
#include "behavior_msgs/msg/./PersistentDetectionStatusMessage_.idl"
#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
#include "geometry_msgs/msg/./Point_.idl"
#include "ihmc_common_msgs/msg/./LatestModificationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      const octet DOOR_TYPE_UNKNOWN =
      0;

      const octet DOOR_TYPE_PUSH =
      1;

      const octet DOOR_TYPE_PULL =
      2;


      /**
       * A behavior tree scene object
       * Table approach
       */
      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorTreeSceneObjectStateMessage_")
      struct BehaviorTreeSceneObjectStateMessage
      {
        /**
         * The timestamp and modifier ID of the latest modification to this object's data fields
         */
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_modification_to_data;
        /**
         * The object's unique ID
         */
        unsigned long id;
        behavior_msgs::msg::dds::BehaviorTreeSceneObjectDefinitionMessage definition;
        /**
         * Persistent detection associated with this object
         */
        behavior_msgs::msg::dds::PersistentDetectionStatusMessage persistent_detection;
        /**
         * Transform of the object frame to world frame
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage transform_to_world;
        /**
         * Whether the object is valid
         */
        boolean valid;
        /**
         * Whether the object is frozen
         */
        boolean frozen;
        /**
         * Used only for door panel
         */
        behavior_msgs::msg::dds::PersistentDetectionStatusMessage door_panel_detection;
        /**
         * Number of points in the latch post detection capsule
         */
        unsigned long latch_post_points;
        /**
         * Number of points in the hinge side recess detection capsule
         */
        unsigned long hinge_recess_points;
        /**
         * The open angle of the door hinge (0 = closed, Zup yaw)
         */
        float door_open_angle;
        /**
         * Door type as defined above
         */
        octet door_type;
        /**
         * Hinge side from the view of the robot
         */
        octet hinge_side;
        unsigned long left_table_points;
        unsigned long right_table_points;
        geometry_msgs::msg::dds::Point left_capsule_center;
        geometry_msgs::msg::dds::Point right_capsule_center;
      };
    };
  };
};

#endif
