#ifndef __behavior_msgs__msg__BehaviorTreeSceneStateMessage__idl__
#define __behavior_msgs__msg__BehaviorTreeSceneStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeSceneObjectStateMessage_.idl"
#include "behavior_msgs/msg/./PersistentDetectionStatusMessage_.idl"
#include "ihmc_common_msgs/msg/./LatestModificationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * The state of the behavior tree scene
       */
      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorTreeSceneStateMessage_")
      struct BehaviorTreeSceneStateMessage
      {
        /**
         * The timestamp and modifier ID of the latest modification to the list of objects
         */
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_modification_to_list;
        /**
         * Scene objects
         */
        sequence<behavior_msgs::msg::dds::BehaviorTreeSceneObjectStateMessage, 100> objects;
        /**
         * Persistent detections tracked in the scene
         */
        sequence<behavior_msgs::msg::dds::PersistentDetectionStatusMessage, 100> persistent_detections;
      };
    };
  };
};

#endif
