#ifndef __behavior_msgs__msg__BehaviorTreeSceneObjectDefinitionMessage__idl__
#define __behavior_msgs__msg__BehaviorTreeSceneObjectDefinitionMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorTreeSceneObjectDefinitionMessage_")
      struct BehaviorTreeSceneObjectDefinitionMessage
      {
        /**
         * Object type: YOLO only, FoundationPose, or specific heurustic
         */
        octet object_type;
        /**
         * YOLO model name to use
         */
        string yolo_model_name;
        /**
         * Class name to use for the object
         */
        string yolo_class_name;
        /**
         * FoundationPose object type (IsaacROSFoundationPoseObject enum ordinal)
         */
        octet foundation_pose_object_type;
      };
    };
  };
};

#endif
