#ifndef __behavior_msgs__msg__BehaviorActionStateMessage__idl__
#define __behavior_msgs__msg__BehaviorActionStateMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorActionStateMessage_")
      struct BehaviorActionStateMessage
      {
        /**
         * The action's unique ID
         */
        unsigned long id;
        /**
         * The action's index in the sequence
         */
        unsigned short action_index;
        /**
         * If the action is next for execution
         */
        boolean is_next_for_execution;
        /**
         * If the action is to be executed concurrently
         */
        boolean is_to_be_executed_concurrently;
      };
    };
  };
};

#endif
