#ifndef __behavior_msgs__msg__BehaviorTreeNodeStateMessage__idl__
#define __behavior_msgs__msg__BehaviorTreeNodeStateMessage__idl__

#include "ihmc_common_msgs/msg/./InstantMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      const octet RUNNING =
      0;

      const octet FAILURE =
      1;

      const octet SUCCESS =
      2;

      const octet NOT_TICKED =
      3;


      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorTreeNodeStateMessage_")
      struct BehaviorTreeNodeStateMessage
      {
        /**
         * The current status of the node
         */
        octet status;
        /**
         * The instant the node was last ticked
         */
        ihmc_common_msgs::msg::dds::InstantMessage last_tick_instant;
      };
    };
  };
};

#endif
