#ifndef __behavior_msgs__msg__BehaviorTreeStateMessage__idl__
#define __behavior_msgs__msg__BehaviorTreeStateMessage__idl__

#include "behavior_msgs/msg/./AI2RNodeStateMessage_.idl"
#include "behavior_msgs/msg/./AbilityHandActionStateMessage_.idl"
#include "behavior_msgs/msg/./ActionSequenceStateMessage_.idl"
#include "behavior_msgs/msg/./ArmActionStateMessage_.idl"
#include "behavior_msgs/msg/./BasicNodeStateMessage_.idl"
#include "behavior_msgs/msg/./BehaviorTreeRootNodeStateMessage_.idl"
#include "behavior_msgs/msg/./BuildingExplorationStateMessage_.idl"
#include "behavior_msgs/msg/./CheckPointNodeStateMessage_.idl"
#include "behavior_msgs/msg/./ConditionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./DoorTraversalStateMessage_.idl"
#include "behavior_msgs/msg/./FallbackNodeStateMessage_.idl"
#include "behavior_msgs/msg/./GotoNodeStateMessage_.idl"
#include "behavior_msgs/msg/./HandWrenchActionStateMessage_.idl"
#include "behavior_msgs/msg/./LegActionStateMessage_.idl"
#include "behavior_msgs/msg/./NeckActionStateMessage_.idl"
#include "behavior_msgs/msg/./PelvisActionStateMessage_.idl"
#include "behavior_msgs/msg/./SakeHandCommandActionStateMessage_.idl"
#include "behavior_msgs/msg/./SceneActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./ScrewPrimitiveActionStateMessage_.idl"
#include "behavior_msgs/msg/./SpineActionStateMessage_.idl"
#include "behavior_msgs/msg/./WaitDurationActionStateMessage_.idl"
#include "behavior_msgs/msg/./WalkActionStateMessage_.idl"
#include "ihmc_common_msgs/msg/./LatestModificationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      /**
       * Used to minimize bandwidth, nodes that are send
       * without their full data.
       */
      const octet PARTIAL_DATA =
      0;

      const octet ROOT_NODE =
      1;

      const octet BASIC_NODE =
      2;

      const octet ACTION_SEQUENCE =
      3;

      const octet FALLBACK_NODE =
      4;

      const octet CONDITION_NODE =
      5;

      const octet GOTO_NODE =
      6;

      const octet CHECKPOINT_NODE =
      7;

      const octet SCENE_ACTION =
      8;

      const octet AI2R_NODE =
      9;

      const octet DOOR_TRAVERSAL =
      10;

      const octet BUILDING_EXPLORATION =
      11;

      const octet NECK_ACTION =
      12;

      const octet SPINE_ACTION =
      13;

      const octet WALK_ACTION =
      14;

      const octet SAKE_HAND_COMMAND_ACTION =
      15;

      const octet ABILITY_HAND_ACTION =
      16;

      const octet ARM_ACTION =
      17;

      const octet HAND_WRENCH_ACTION =
      18;

      const octet SCREW_PRIMITIVE_ACTION =
      19;

      const octet PELVIS_ACTION =
      20;

      const octet WAIT_DURATION_ACTION =
      21;

      const octet LEG_ACTION =
      22;


      /**
       * Gives the current state of the complete collection of behavior tree nodes.
       * Publishing all behavior tree nodes in one message can simplify synchronization and
       * reduce the complexity of logic in figuring out when nodes are currently under
       * consideration.
       */
      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorTreeStateMessage_")
      struct BehaviorTreeStateMessage
      {
        /**
         * Monotonically increasing message ID that matches the CRDTInfo update number
         */
        unsigned long long sequence_id;
        /**
         * The ID to assign to the next instantiated node
         */
        unsigned long next_id;
        /**
         * The timestamp and modifier ID of the most recent time the root node was replaced or removed
         */
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_modification_to_root_reference;
        /**
         * The timestamp and modifier ID of the latest modification of the tree data fields
         */
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_modification_to_data;
        /**
         * A depth first ordered list of types.
         */
        sequence<octet, 1000> behavior_tree_types;
        /**
         * A depth first ordered list of node indexes.
         * The index is of that node in it's respective list for
         * it's type.
         */
        sequence<unsigned long, 1000> behavior_tree_indices;
        sequence<behavior_msgs::msg::dds::BasicNodeStateMessage, 300> partial_data_nodes;
        sequence<behavior_msgs::msg::dds::BehaviorTreeRootNodeStateMessage, 1> root_nodes;
        sequence<behavior_msgs::msg::dds::BasicNodeStateMessage, 120> basic_nodes;
        sequence<behavior_msgs::msg::dds::ActionSequenceStateMessage, 120> action_sequences;
        sequence<behavior_msgs::msg::dds::FallbackNodeStateMessage, 120> fallback_nodes;
        sequence<behavior_msgs::msg::dds::ConditionNodeStateMessage, 120> condition_nodes;
        sequence<behavior_msgs::msg::dds::GotoNodeStateMessage, 120> goto_nodes;
        sequence<behavior_msgs::msg::dds::CheckPointNodeStateMessage, 120> checkpoint_nodes;
        sequence<behavior_msgs::msg::dds::SceneActionNodeStateMessage, 120> scene_actions;
        sequence<behavior_msgs::msg::dds::AI2RNodeStateMessage, 1> ai2r_nodes;
        sequence<behavior_msgs::msg::dds::DoorTraversalStateMessage, 120> door_traversals;
        sequence<behavior_msgs::msg::dds::BuildingExplorationStateMessage, 120> building_explorations;
        sequence<behavior_msgs::msg::dds::NeckActionStateMessage, 120> neck_actions;
        sequence<behavior_msgs::msg::dds::SpineActionStateMessage, 120> spine_actions;
        sequence<behavior_msgs::msg::dds::WalkActionStateMessage, 120> walk_actions;
        sequence<behavior_msgs::msg::dds::SakeHandCommandActionStateMessage, 120> sake_hand_command_actions;
        sequence<behavior_msgs::msg::dds::AbilityHandActionStateMessage, 120> ability_hand_actions;
        sequence<behavior_msgs::msg::dds::ArmActionStateMessage, 120> arm_actions;
        sequence<behavior_msgs::msg::dds::HandWrenchActionStateMessage, 120> hand_wrench_actions;
        sequence<behavior_msgs::msg::dds::ScrewPrimitiveActionStateMessage, 120> screw_primitive_actions;
        sequence<behavior_msgs::msg::dds::PelvisActionStateMessage, 120> pelvis_actions;
        sequence<behavior_msgs::msg::dds::WaitDurationActionStateMessage, 120> wait_duration_actions;
        sequence<behavior_msgs::msg::dds::LegActionStateMessage, 120> leg_actions;
      };
    };
  };
};

#endif
