#ifndef __behavior_msgs__msg__BehaviorTreeNodeStateMessage__idl__
#define __behavior_msgs__msg__BehaviorTreeNodeStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeLogMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorTreeNodeStateMessage_")
      struct BehaviorTreeNodeStateMessage
      {
        /**
         * The node's unique ID
         */
        unsigned long id;
        /**
         * A node is active if it lies on the path of the current tree tick.
         */
        boolean is_active;
        /**
         * Recent log messages
         */
        sequence<behavior_msgs::msg::dds::BehaviorTreeLogMessage, 50> recent_log_messages;
      };
    };
  };
};

#endif
