#ifndef __behavior_msgs__msg__BehaviorActionDefinitionMessage__idl__
#define __behavior_msgs__msg__BehaviorActionDefinitionMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::BehaviorActionDefinitionMessage_")
      struct BehaviorActionDefinitionMessage
      {
        /**
         * Human readable description of what the action does
         */
        sequence<string, 1> description;
        /**
         * Execute with next action
         */
        boolean execute_with_next_action;
      };
    };
  };
};

#endif
