#ifndef __behavior_msgs__msg__BodyPartPoseStatusMessage__idl__
#define __behavior_msgs__msg__BodyPartPoseStatusMessage__idl__

#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::BodyPartPoseStatusMessage_")
      struct BodyPartPoseStatusMessage
      {
        /**
         * Name of the frame the this action is expressed in
         */
        sequence<string, 1000> parent_frame;
        /**
         * Transform that expresses the pelvis pose in the parent frame
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage transform_to_parent;
        /**
         * Specifies whether the action is next and concurrent with other actions
         */
        boolean next_and_concurrent;
      };
    };
  };
};

#endif
