#ifndef __behavior_msgs__msg__BuildingExplorationDefinitionMessage__idl__
#define __behavior_msgs__msg__BuildingExplorationDefinitionMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::BuildingExplorationDefinitionMessage_")
      struct BuildingExplorationDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeDefinitionMessage definition;
      };
    };
  };
};

#endif
