#ifndef __behavior_msgs__msg__CheckpointNodeDefinitionMessage__idl__
#define __behavior_msgs__msg__CheckpointNodeDefinitionMessage__idl__

#include "behavior_msgs/msg/./LeafNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::CheckpointNodeDefinitionMessage_")
      struct CheckpointNodeDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::LeafNodeDefinitionMessage definition;
      };
    };
  };
};

#endif
