#ifndef __behavior_msgs__msg__CheckPointNodeDefinitionMessage__idl__
#define __behavior_msgs__msg__CheckPointNodeDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::CheckPointNodeDefinitionMessage_")
      struct CheckPointNodeDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
      };
    };
  };
};

#endif
