#ifndef __behavior_msgs__msg__ChestOrientationActionMessage__idl__
#define __behavior_msgs__msg__ChestOrientationActionMessage__idl__

#include "behavior_msgs/msg/./ActionInformationMessage_.idl"
#include "ihmc_common_msgs/msg/./YawPitchRollMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ChestOrientationActionMessage_")
      struct ChestOrientationActionMessage
      {
        /**
         * Used for syncing action sequences
         */
        behavior_msgs::msg::dds::ActionInformationMessage action_information;
        /**
         * The orientation as a yaw-pitch-roll
         */
        ihmc_common_msgs::msg::dds::YawPitchRollMessage orientation;
        /**
         * The trajectory duration
         */
        double trajectory_duration;
      };
    };
  };
};

#endif
