#ifndef __behavior_msgs__msg__ConditionNodeDefinitionMessage__idl__
#define __behavior_msgs__msg__ConditionNodeDefinitionMessage__idl__

#include "behavior_msgs/msg/./LeafNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      const octet COUNTER_TYPE =
      0;

      const octet LLM_TYPE =
      1;


      /**
       * COUNTER TYPE
       * LLM TYPE
       */
      @TypeCode(type="behavior_msgs::msg::dds_::ConditionNodeDefinitionMessage_")
      struct ConditionNodeDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::LeafNodeDefinitionMessage definition;
        /**
         * The type of condtion as defined above
         */
        octet type;
        /**
         * The number of times to fail before passing
         */
        unsigned long count_to;
        /**
         * Whether to reset the context on each run
         */
        boolean reset_context_each_run;
        /**
         * Whether to generate behavior state information and add it to the prompt
         */
        boolean inject_behavior_state;
        /**
         * Whether to generate environment state information and add it to the prompt
         */
        boolean inject_environment_state;
        /**
         * The prompt given once at the very beginning
         */
        string<10000> system;
        /**
         * The prompt defining how to make the boolean decision
         */
        string<10000> prompt;
      };
    };
  };
};

#endif
