#ifndef __behavior_msgs__msg__ConditionNodeStateMessage__idl__
#define __behavior_msgs__msg__ConditionNodeStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeStateMessage_.idl"
#include "behavior_msgs/msg/./ConditionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::ConditionNodeStateMessage_")
      struct ConditionNodeStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::ConditionNodeDefinitionMessage definition;
      };
    };
  };
};

#endif
