#ifndef __behavior_msgs__msg__ConditionNodeStateMessage__idl__
#define __behavior_msgs__msg__ConditionNodeStateMessage__idl__

#include "behavior_msgs/msg/./ConditionNodeDefinitionMessage_.idl"
#include "behavior_msgs/msg/./LeafNodeStateMessage_.idl"
#include "geometry_msgs/msg/./Vector3_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * COUNTER TYPE
       * LLM TYPE
       * PROXIMITY TYPE
       * SHAPE CONTAINS TYPE
       */
      @TypeCode(type="behavior_msgs::msg::dds_::ConditionNodeStateMessage_")
      struct ConditionNodeStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::LeafNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::ConditionNodeDefinitionMessage definition;
        /**
         * The current count of the counter
         */
        unsigned long count;
        /**
         * A request to reset the LLM's context now
         */
        boolean request_reset_context;
        /**
         * The positional vector from frame B to frame A in world frame
         */
        geometry_msgs::msg::dds::Vector3 b_to_a;
        /**
         * Whether frame A is present
         */
        boolean frame_a_is_present;
        /**
         * Whether frame B is present
         */
        boolean frame_b_is_present;
        boolean frame_is_contained;
        unsigned long number_of_points_contained;
        float average_hue;
        float average_saturation;
        float average_value;
      };
    };
  };
};

#endif
