#ifndef __behavior_msgs__msg__ConditionNodeDefinitionMessage__idl__
#define __behavior_msgs__msg__ConditionNodeDefinitionMessage__idl__

#include "behavior_msgs/msg/./LeafNodeDefinitionMessage_.idl"
#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      const octet COUNTER_TYPE =
      0;

      const octet LLM_TYPE =
      1;

      const octet PROXIMITY_TYPE =
      2;

      const octet SHAPE_CONTAINS =
      3;

      const octet ALWAYS_FAIL =
      4;

      const octet ALWAYS_SUCCEED =
      5;

      const octet XYZ =
      0;

      const octet XY =
      1;

      const octet Z =
      2;

      const octet CONTAINS_FRAME =
      0;

      const octet CONTAINS_POINTS =
      1;


      /**
       * COUNTER TYPE
       * LLM TYPE
       * PROXIMITY TYPE
       * SHAPE CONTAINS TYPE
       */
      @TypeCode(type="behavior_msgs::msg::dds_::ConditionNodeDefinitionMessage_")
      struct ConditionNodeDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::LeafNodeDefinitionMessage definition;
        /**
         * The type of condition as defined above
         */
        octet type;
        /**
         * The number of times to fail before passing
         */
        unsigned long count_to;
        /**
         * Whether to reset the context on each run
         */
        boolean reset_context_each_run;
        /**
         * Whether to generate behavior state information and add it to the prompt
         */
        boolean inject_behavior_state;
        /**
         * Whether to generate environment state information and add it to the prompt
         */
        boolean inject_environment_state;
        /**
         * If a response match indicates success, else a match indicates failure
         */
        boolean match_is_success;
        /**
         * The prompt given once at the very beginning
         */
        string<10000> system;
        /**
         * The prompt defining how to make the boolean decision
         */
        string<10000> prompt;
        /**
         * A regular expression, where if it matches, the execution failed
         */
        string<10000> response_matcher;
        /**
         * The type of distance condition as defined above
         */
        octet distance_type;
        /**
         * Name of frame A
         */
        string frame_name_a;
        /**
         * Name of frame B
         */
        string frame_name_b;
        /**
         * The minimum distance between the two frames
         */
        double min_distance;
        /**
         * The maximum distance between the two frames
         */
        double max_distance;
        /**
         * Timeout for waiting for the condition to be satisfied
         */
        double timeout;
        /**
         * The type of shape contains condition as defined above
         */
        octet contains_type;
        /**
         * Name of the frame the the shape's pose is expressed in
         */
        string shape_parent_frame_name;
        /**
         * Transform that expresses the pose of the shape in the parent frame
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage shape_transform_to_parent;
        /**
         * Radius of the sphere used for checking containment
         */
        float sphere_radius;
        /**
         * Name of frame to check for containment
         */
        string frame_name;
        /**
         * Minimum number of points in the shape
         */
        unsigned long min_points;
      };
    };
  };
};

#endif
