#ifndef __behavior_msgs__msg__ConditionNodeStateMessage__idl__
#define __behavior_msgs__msg__ConditionNodeStateMessage__idl__

#include "behavior_msgs/msg/./ConditionNodeDefinitionMessage_.idl"
#include "behavior_msgs/msg/./LeafNodeStateMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * COUNTER TYPE
       * LLM TYPE
       */
      @TypeCode(type="behavior_msgs::msg::dds_::ConditionNodeStateMessage_")
      struct ConditionNodeStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::LeafNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::ConditionNodeDefinitionMessage definition;
        /**
         * The current count of the counter
         */
        unsigned long count;
        /**
         * A request to reset the LLM's context now
         */
        boolean request_reset_context;
      };
    };
  };
};

#endif
