#ifndef __behavior_msgs__msg__DoorTraversalStateMessage__idl__
#define __behavior_msgs__msg__DoorTraversalStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeStateMessage_.idl"
#include "behavior_msgs/msg/./DoorTraversalDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::DoorTraversalStateMessage_")
      struct DoorTraversalStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::DoorTraversalDefinitionMessage definition;
      };
    };
  };
};

#endif
