#ifndef __behavior_msgs__msg__EZGripperActionStateMessage__idl__
#define __behavior_msgs__msg__EZGripperActionStateMessage__idl__

#include "behavior_msgs/msg/./ActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./EZGripperActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::EZGripperActionStateMessage_")
      struct EZGripperActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::ActionNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::EZGripperActionDefinitionMessage definition;
      };
    };
  };
};

#endif
