#ifndef __behavior_msgs__msg__FallbackNodeDefinitionMessage__idl__
#define __behavior_msgs__msg__FallbackNodeDefinitionMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::FallbackNodeDefinitionMessage_")
      struct FallbackNodeDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeDefinitionMessage definition;
        /**
         * The ID of the action to retry
         */
        unsigned long goto_action_id;
      };
    };
  };
};

#endif
