#ifndef __behavior_msgs__msg__FootstepPlanActionStateMessage__idl__
#define __behavior_msgs__msg__FootstepPlanActionStateMessage__idl__

#include "behavior_msgs/msg/./ActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./FootstepPlanActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./FootstepPlanActionFootstepStateMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::FootstepPlanActionStateMessage_")
      struct FootstepPlanActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::ActionNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::FootstepPlanActionDefinitionMessage definition;
        /**
         * The footsteps, with a maximum of 50
         */
        sequence<behavior_msgs::msg::dds::FootstepPlanActionFootstepStateMessage, 50> footsteps;
        /**
         * Total number of footsteps; used for walking actions
         */
        unsigned short total_number_of_footsteps;
        /**
         * Incomplete footsteps; used for walking actions
         */
        unsigned short number_of_incomplete_footsteps;
      };
    };
  };
};

#endif
