#ifndef __behavior_msgs__msg__FootPoseActionStateMessage__idl__
#define __behavior_msgs__msg__FootPoseActionStateMessage__idl__

#include "behavior_msgs/msg/./ActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./FootPoseActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::FootPoseActionStateMessage_")
      struct FootPoseActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::ActionNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::FootPoseActionDefinitionMessage definition;
      };
    };
  };
};

#endif
