#ifndef __behavior_msgs__msg__FootstepPlanActionDefinitionMessage__idl__
#define __behavior_msgs__msg__FootstepPlanActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./BehaviorActionDefinitionMessage_.idl"
#include "behavior_msgs/msg/./FootstepActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::FootstepPlanActionDefinitionMessage_")
      struct FootstepPlanActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::BehaviorActionDefinitionMessage action_definition;
        /**
         * Name of the parent frame the footsteps are expressed in
         */
        sequence<string, 1000> parent_frame;
        /**
         * The footsteps, with a maximum of 50
         */
        sequence<behavior_msgs::msg::dds::FootstepActionDefinitionMessage, 50> footsteps;
        /**
         * Swing duration
         */
        double swing_duration;
        /**
         * Transfer duration
         */
        double transfer_duration;
      };
    };
  };
};

#endif
