#ifndef __behavior_msgs__msg__FootstepPlanActionDefinitionMessage__idl__
#define __behavior_msgs__msg__FootstepPlanActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
#include "behavior_msgs/msg/./FootstepPlanActionFootstepDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::FootstepPlanActionDefinitionMessage_")
      struct FootstepPlanActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Name of the parent frame the footsteps are expressed in
         */
        string parent_frame_name;
        /**
         * Swing duration
         */
        double swing_duration;
        /**
         * Transfer duration
         */
        double transfer_duration;
        /**
         * Is using the footstep planner or manually placing
         */
        boolean is_manually_placed;
        /**
         * The footsteps, with a maximum of 50
         */
        sequence<behavior_msgs::msg::dds::FootstepPlanActionFootstepDefinitionMessage, 50> footsteps;
        /**
         * Planning goal pose X in the parent frame
         */
        double goal_x_in_parent;
        /**
         * Planning goal pose Y in the parent frame
         */
        double goal_y_in_parent;
        /**
         * Planning goal pose Yaw in the parent frame
         */
        double goal_yaw_in_parent;
        /**
         * Left goal foot X to the goal pose
         */
        double left_goal_foot_x_to_gizmo;
        /**
         * Left goal foot Y to the goal pose
         */
        double left_goal_foot_y_to_gizmo;
        /**
         * Left goal foot Yaw to the goal pose
         */
        double left_goal_foot_yaw_to_gizmo;
        /**
         * Right goal foot X to the goal pose
         */
        double right_goal_foot_x_to_gizmo;
        /**
         * Right goal foot Y to the goal pose
         */
        double right_goal_foot_y_to_gizmo;
        /**
         * Right goal foot Yaw to the goal pose
         */
        double right_goal_foot_yaw_to_gizmo;
      };
    };
  };
};

#endif
