#ifndef __behavior_msgs__msg__FootstepPlanActionStateBasicsMessage__idl__
#define __behavior_msgs__msg__FootstepPlanActionStateBasicsMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::FootstepPlanActionStateBasicsMessage_")
      struct FootstepPlanActionStateBasicsMessage
      {
        /**
         * Total number of footsteps; used for walking actions
         */
        unsigned short total_number_of_footsteps;
        /**
         * Incomplete footsteps; used for walking actions
         */
        unsigned short number_of_incomplete_footsteps;
      };
    };
  };
};

#endif
