#ifndef __behavior_msgs__msg__HandConfigurationActionMessage__idl__
#define __behavior_msgs__msg__HandConfigurationActionMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::HandConfigurationActionMessage_")
      struct HandConfigurationActionMessage
      {
        boolean unused_placeholder_field;
      };
    };
  };
};

#endif
