#ifndef __behavior_msgs__msg__HandConfigurationActionDescriptionMessage__idl__
#define __behavior_msgs__msg__HandConfigurationActionDescriptionMessage__idl__

#include "behavior_msgs/msg/./ActionInformationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::HandConfigurationActionDescriptionMessage_")
      struct HandConfigurationActionDescriptionMessage
      {
        /**
         * Used for syncing action sequences
         */
        behavior_msgs::msg::dds::ActionInformationMessage action_information;
        /**
         * Specifies the side of the robot that this message refers to.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * The grip type
         */
        unsigned long grip;
        /**
         * Whether the next action can be executed at the same time of this one
         */
        boolean execute_with_next_action;
      };
    };
  };
};

#endif
