#ifndef __behavior_msgs__msg__LeafNodeDefinitionMessage__idl__
#define __behavior_msgs__msg__LeafNodeDefinitionMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      /**
       * Value of execute after node ID when we have a name but still need to find the ID
       */
      const long long INVALID =
      -1;

      /**
       * Value of execute after node ID when this leaf is set to execute after the previous node
       */
      const long long EXECUTE_AFTER_PREVIOUS =
      -2;

      /**
       * Value of execute after node ID when this leaf is set to execute after the beginning of the sequence
       */
      const long long EXECUTE_AFTER_BEGINNING =
      -3;


      @TypeCode(type="behavior_msgs::msg::dds_::LeafNodeDefinitionMessage_")
      struct LeafNodeDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeDefinitionMessage definition;
        /**
         * The ID of the node to execute after or one of the invalid, previous, or beginning constants
         */
        long long execute_after_node_id;
      };
    };
  };
};

#endif
