#ifndef __behavior_msgs__msg__LeafNodeStateMessage__idl__
#define __behavior_msgs__msg__LeafNodeStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeStateMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::LeafNodeStateMessage_")
      struct LeafNodeStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeStateMessage state;
        /**
         * The action's unique ID
         */
        unsigned long id;
        /**
         * If the action is next for execution
         */
        boolean is_next_for_execution;
        /**
         * If the node is able to execution
         */
        boolean can_execute;
        /**
         * If the node is currently executing
         */
        boolean is_executing;
        /**
         * If the node had a failure during it's last execution
         */
        boolean failed;
      };
    };
  };
};

#endif
