#ifndef __behavior_msgs__msg__LerobotInferenceOperationMessage__idl__
#define __behavior_msgs__msg__LerobotInferenceOperationMessage__idl__

#include "ihmc_common_msgs/msg/./LatestModificationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A message for remotely operationg the lerobot policies
       */
      @TypeCode(type="behavior_msgs::msg::dds_::LerobotInferenceOperationMessage_")
      struct LerobotInferenceOperationMessage
      {
        /**
         * Allows the user to operate the inference of visuomotor policies
         */
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_timestamp_modifiable;
        /**
         * Monotonically increasing, number of updates of robot thread
         */
        unsigned long sequence_id;
        /**
         * Whether the inference and action output to IK streaming is active
         */
        boolean running;
        /**
         * Whether to enable controlling the robot instead of just previewing
         */
        boolean control_robot;
        /**
         * Frequency of status from python side
         */
        double python_status_frequency;
        /**
         * Message received from python
         */
        string python_status_message;
        /**
         * Number of output actions received from policy
         */
        unsigned long received_actions;
      };
    };
  };
};

#endif
