#ifndef __behavior_msgs__msg__MimicActionDefinitionMessage__idl__
#define __behavior_msgs__msg__MimicActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      const octet POLICY_TRANSITION =
      0;

      const octet EXIT_POLICY =
      1;

      const octet EXECUTE_POLICY =
      2;


      @TypeCode(type="behavior_msgs::msg::dds_::MimicActionDefinitionMessage_")
      struct MimicActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * The type of action as defined above
         */
        octet mimic_action_type;
        /**
         * The name of the mimic file
         */
        string mimic_file_name;
        /**
         * Wait time in seconds after the policy has been exited
         */
        double wait_time_exit_policy;
      };
    };
  };
};

#endif
