#ifndef __behavior_msgs__msg__MinimalFootstepMessage__idl__
#define __behavior_msgs__msg__MinimalFootstepMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Quaternion_.idl"
#include "ihmc_common_msgs/msg/./Point2DMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::MinimalFootstepMessage_")
      struct MinimalFootstepMessage
      {
        /**
         * Specifies which foot will swing to reach the footstep.
         * Field default value 255
         */
        octet robot_side;
        /**
         * Specifies the position of the footstep (sole frame) in world frame.
         */
        geometry_msgs::msg::dds::Point position;
        /**
         * Specifies the orientation of the footstep (sole frame) in world frame.
         */
        geometry_msgs::msg::dds::Quaternion orientation;
        /**
         * Support polygon
         */
        sequence<ihmc_common_msgs::msg::dds::Point2DMessage, 16> support_polygon;
        /**
         * Description of the footstep
         */
        string description;
      };
    };
  };
};

#endif
