#ifndef __behavior_msgs__msg__NeckActionStateMessage__idl__
#define __behavior_msgs__msg__NeckActionStateMessage__idl__

#include "behavior_msgs/msg/./ActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./NeckActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::NeckActionStateMessage_")
      struct NeckActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::ActionNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::NeckActionDefinitionMessage definition;
      };
    };
  };
};

#endif
