#ifndef __behavior_msgs__msg__NeckActionDefinitionMessage__idl__
#define __behavior_msgs__msg__NeckActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::NeckActionDefinitionMessage_")
      struct NeckActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Neck pitch angle
         */
        double pitch;
        /**
         * Neck yaw angle
         */
        double yaw;
        /**
         * Duration of the trajectory
         */
        double trajectory_duration;
      };
    };
  };
};

#endif
