#ifndef __behavior_msgs__msg__PelvisHeightActionMessage__idl__
#define __behavior_msgs__msg__PelvisHeightActionMessage__idl__

#include "behavior_msgs/msg/./ActionInformationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::PelvisHeightActionMessage_")
      struct PelvisHeightActionMessage
      {
        /**
         * Used for syncing action sequences
         */
        behavior_msgs::msg::dds::ActionInformationMessage action_information;
        /**
         * Duration of the trajectory
         */
        double trajectory_duration;
        /**
         * Z height in world frame
         */
        double height_in_world;
      };
    };
  };
};

#endif
