#ifndef __behavior_msgs__msg__PelvisHeightOrientationActionStateMessage__idl__
#define __behavior_msgs__msg__PelvisHeightOrientationActionStateMessage__idl__

#include "behavior_msgs/msg/./ActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./PelvisHeightOrientationActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::PelvisHeightOrientationActionStateMessage_")
      struct PelvisHeightOrientationActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::ActionNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::PelvisHeightOrientationActionDefinitionMessage definition;
      };
    };
  };
};

#endif
