#ifndef __behavior_msgs__msg__PelvisHeightOrientationActionDefinitionMessage__idl__
#define __behavior_msgs__msg__PelvisHeightOrientationActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::PelvisHeightOrientationActionDefinitionMessage_")
      struct PelvisHeightOrientationActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Name of the frame the this action is expressed in
         */
        string parent_frame_name;
        /**
         * Transform that expresses the pelvis pose in the parent frame
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage pelvis_transform_to_parent;
        /**
         * Duration of the trajectory
         */
        double trajectory_duration;
      };
    };
  };
};

#endif
