#ifndef __behavior_msgs__msg__RoomExplorationStateMessage__idl__
#define __behavior_msgs__msg__RoomExplorationStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorTreeNodeStateMessage_.idl"
#include "behavior_msgs/msg/./RoomExplorationDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::RoomExplorationStateMessage_")
      struct RoomExplorationStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::BehaviorTreeNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::RoomExplorationDefinitionMessage definition;
      };
    };
  };
};

#endif
