#ifndef __behavior_msgs__msg__SakeHandCommandActionDefinitionMessage__idl__
#define __behavior_msgs__msg__SakeHandCommandActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::SakeHandCommandActionDefinitionMessage_")
      struct SakeHandCommandActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Specifies the side of the robot that this message refers to.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * Desired angle between the fingers from 0 to 210 degrees (specified in radians)
         */
        double hand_open_angle;
        /**
         * Torque limit specified as fingertip grip force. Valid up to 29 Newtons. Safe value is 8.7 N.
         */
        double fingertip_grip_force_limit;
      };
    };
  };
};

#endif
