#ifndef __behavior_msgs__msg__SceneActionDefinitionMessage__idl__
#define __behavior_msgs__msg__SceneActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
#include "behavior_msgs/msg/./BehaviorTreeSceneObjectDefinitionMessage_.idl"
#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
#include "perception_msgs/msg/./YOLOv8ModelParameters_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      const octet SETUP_OBJECT =
      0;

      const octet FREEZE_OBJECT =
      1;

      const octet DELETE_OBJECT =
      2;

      const octet CLEAR_SCENE =
      3;

      const octet FREEZE_SCENE =
      4;

      const octet CONFIGURE_PERSISTENT_DETECTIONS =
      5;

      const octet CONFIGURE_YOLO =
      6;

      const octet CONFIGURE_FOUNDATION_POSE =
      7;


      /**
       * Setup, freeze, delete object:
       * Configure persistent detections:
       * Configure YOLO:
       * Configure FoundationPose:
       */
      @TypeCode(type="behavior_msgs::msg::dds_::SceneActionDefinitionMessage_")
      struct SceneActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * The type of action as defined above
         */
        octet scene_action_type;
        /**
         * Definition of the object to setup
         */
        behavior_msgs::msg::dds::BehaviorTreeSceneObjectDefinitionMessage scene_object_definition;
        /**
         * If this action can't do what it needs to do in this amount of time, give up.
         */
        float timeout;
        /**
         * Filter for persistent detection history size
         */
        unsigned short minimum_history_size;
        /**
         * The nominal object pose for behavior previewing
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage nominal_object_pose;
        float pose_filter_alpha;
        float acceptance_confidence;
        float stability_frequency;
        float history_duration;
        /**
         * YOLO models that should be enabled at this point (by available index)
         */
        sequence<unsigned short, 10> enabled_yolo_models;
        /**
         * Pararmeters of the enabled YOLO models
         */
        sequence<perception_msgs::msg::dds::YOLOv8ModelParameters, 10> yolo_model_parameters;
        /**
         * FoundationPose models that should be enabled at this point
         */
        sequence<octet, 10> enabled_foundation_pose_models;
      };
    };
  };
};

#endif
