#ifndef __behavior_msgs__msg__VLAOperationMessage__idl__
#define __behavior_msgs__msg__VLAOperationMessage__idl__

#include "geometry_msgs/msg/./Pose_.idl"
#include "ihmc_common_msgs/msg/./LatestModificationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A message for remotely operating the VLA policies
       */
      @TypeCode(type="behavior_msgs::msg::dds_::VLAOperationMessage_")
      struct VLAOperationMessage
      {
        ihmc_common_msgs::msg::dds::LatestModificationMessage latest_timestamp_modifiable;
        /**
         * Monotonically increasing, number of updates of robot thread
         */
        unsigned long sequence_id;
        /**
         * Whether the inference and action output to IK streaming is active
         */
        boolean running;
        /**
         * Whether to enable controlling the robot instead of just previewing
         */
        boolean control_robot;
        /**
         * The latest action hand poses
         */
        geometry_msgs::msg::dds::Pose action_hand_poses[2];
        /**
         * The latest action forearm poses
         */
        geometry_msgs::msg::dds::Pose action_forearm_poses[2];
        /**
         * Status message from robot thread to show to the operator
         */
        string status_message;
      };
    };
  };
};

#endif
