#ifndef __behavior_msgs__msg__WaitDurationActionMessage__idl__
#define __behavior_msgs__msg__WaitDurationActionMessage__idl__

#include "behavior_msgs/msg/./ActionInformationMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::WaitDurationActionMessage_")
      struct WaitDurationActionMessage
      {
        /**
         * Used for syncing action sequences
         */
        behavior_msgs::msg::dds::ActionInformationMessage action_information;
        /**
         * Wait duration
         */
        double wait_duration;
      };
    };
  };
};

#endif
