#ifndef __behavior_msgs__msg__WaitDurationActionStateMessage__idl__
#define __behavior_msgs__msg__WaitDurationActionStateMessage__idl__

#include "behavior_msgs/msg/./ActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./WaitDurationActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::WaitDurationActionStateMessage_")
      struct WaitDurationActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::ActionNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::WaitDurationActionDefinitionMessage definition;
      };
    };
  };
};

#endif
