#ifndef __behavior_msgs__msg__WalkActionFootstepStateMessage__idl__
#define __behavior_msgs__msg__WalkActionFootstepStateMessage__idl__

module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::WalkActionFootstepStateMessage_")
      struct WalkActionFootstepStateMessage
      {
        boolean unused_placeholder_field;
      };
    };
  };
};

#endif
