#ifndef __behavior_msgs__msg__WalkActionDefinitionMessage__idl__
#define __behavior_msgs__msg__WalkActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
#include "behavior_msgs/msg/./WalkActionFootstepDefinitionMessage_.idl"
#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Pose_.idl"
#include "ihmc_common_msgs/msg/./PrimitiveDataVectorMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {
      /**
       * Quick footstep planner
       */
      const octet QUICK =
      0;

      /**
       * Turn walk turn planner
       */
      const octet TURN_WALK_TURN =
      1;

      /**
       * A star planner
       */
      const octet A_STAR =
      2;


      @TypeCode(type="behavior_msgs::msg::dds_::WalkActionDefinitionMessage_")
      struct WalkActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        /**
         * Name of the parent frame the footsteps are expressed in
         */
        string parent_frame_name;
        /**
         * Swing duration
         */
        double swing_duration;
        /**
         * Transfer duration
         */
        double transfer_duration;
        /**
         * OVERRIDE (0) or QUEUE (1)
         */
        octet execution_mode;
        /**
         * Is using the footstep planner or manually placing
         */
        boolean is_manually_placed;
        /**
         * Pose waypoints to hit along the way (may be none)
         */
        sequence<geometry_msgs::msg::dds::Pose, 40> waypoints;
        /**
         * The footsteps, with a maximum of 50
         */
        sequence<behavior_msgs::msg::dds::WalkActionFootstepDefinitionMessage, 50> footsteps;
        /**
         * The position to which the goal stance is aligned
         */
        geometry_msgs::msg::dds::Point goal_stance_point;
        /**
         * The point that the robot should be facing in the goal stance
         */
        geometry_msgs::msg::dds::Point goal_focal_point;
        /**
         * Left goal foot X to the goal pose
         */
        double left_goal_foot_x_to_gizmo;
        /**
         * Left goal foot Y to the goal pose
         */
        double left_goal_foot_y_to_gizmo;
        /**
         * Left goal foot Yaw to the goal pose
         */
        double left_goal_foot_yaw_to_gizmo;
        /**
         * Right goal foot X to the goal pose
         */
        double right_goal_foot_x_to_gizmo;
        /**
         * Right goal foot Y to the goal pose
         */
        double right_goal_foot_y_to_gizmo;
        /**
         * Right goal foot Yaw to the goal pose
         */
        double right_goal_foot_yaw_to_gizmo;
        /**
         * Initial stance side when planning
         */
        octet planner_initial_stance_side;
        /**
         * The type of planner as defined above
         */
        octet planner;
        /**
         * Whether to walk, turning first, matching the goal orientation
         */
        boolean planner_walk_with_goal_orientation;
        /**
         * Whether to use the body path planner or not
         */
        boolean planner_plan_with_body_path;
        /**
         * The footstep planner parameters
         */
        ihmc_common_msgs::msg::dds::PrimitiveDataVectorMessage planner_parameters;
        /**
         * Quick footstep planner parameters
         */
        boolean quick_waypoint_only;
        boolean use_rrt_path_planner;
        double obstacle_clearance_radius;
        double quick_hip_width;
        double quick_step_length;
        double quick_next_pelvis_yaw_limit;
        double quick_inward_limit;
        double quick_outward_limit;
        double quick_step_angle_limit;
        double quick_swing_time_distance_lower;
        double quick_swing_time_distance_upper;
        double quick_min_swing_time;
        double quick_max_swing_time;
      };
    };
  };
};

#endif
