#ifndef __behavior_msgs__msg__WalkActionStateMessage__idl__
#define __behavior_msgs__msg__WalkActionStateMessage__idl__

#include "behavior_msgs/msg/./BehaviorActionStateMessage_.idl"
#include "behavior_msgs/msg/./WalkActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::WalkActionStateMessage_")
      struct WalkActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::BehaviorActionStateMessage action_state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::WalkActionDefinitionMessage definition;
      };
    };
  };
};

#endif
