#ifndef __behavior_msgs__msg__WalkActionDefinitionMessage__idl__
#define __behavior_msgs__msg__WalkActionDefinitionMessage__idl__

#include "behavior_msgs/msg/./ActionNodeDefinitionMessage_.idl"
#include "behavior_msgs/msg/./FootstepPlanActionDefinitionBasicsMessage_.idl"
#include "controller_msgs/msg/./RigidBodyTransformMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::WalkActionDefinitionMessage_")
      struct WalkActionDefinitionMessage
      {
        /**
         * Parent definition fields
         */
        behavior_msgs::msg::dds::ActionNodeDefinitionMessage definition;
        behavior_msgs::msg::dds::FootstepPlanActionDefinitionBasicsMessage definition_basics;
        /**
         * Transform that expresses the walk gizmo pose in the parent frame
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage transform_to_parent;
        /**
         * Left goal foot transform to the walk gizmo
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage left_goal_foot_transform_to_gizmo;
        /**
         * Right goal foot transform to the walk gizmo
         */
        controller_msgs::msg::dds::RigidBodyTransformMessage right_goal_foot_transform_to_gizmo;
      };
    };
  };
};

#endif
