#ifndef __behavior_msgs__msg__WalkActionStateMessage__idl__
#define __behavior_msgs__msg__WalkActionStateMessage__idl__

#include "behavior_msgs/msg/./ActionNodeStateMessage_.idl"
#include "behavior_msgs/msg/./WalkActionDefinitionMessage_.idl"
module behavior_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="behavior_msgs::msg::dds_::WalkActionStateMessage_")
      struct WalkActionStateMessage
      {
        /**
         * Parent state fields
         */
        behavior_msgs::msg::dds::ActionNodeStateMessage state;
        /**
         * Definition
         */
        behavior_msgs::msg::dds::WalkActionDefinitionMessage definition;
        /**
         * Total number of footsteps; used for walking actions
         */
        unsigned short total_number_of_footsteps;
        /**
         * Incomplete footsteps; used for walking actions
         */
        unsigned short number_of_incomplete_footsteps;
      };
    };
  };
};

#endif
