package control_msgs;

public interface JointTrajectoryFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/JointTrajectoryFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\n";
}
