#ifndef __isaac_ros_tensor_list_interfaces__msg__TensorShape__idl__
#define __isaac_ros_tensor_list_interfaces__msg__TensorShape__idl__

module isaac_ros_tensor_list_interfaces
{
  module msg
  {
    module dds
    {

      @TypeCode(type="isaac_ros_tensor_list_interfaces::msg::dds_::TensorShape_")
      struct TensorShape
      {
        /**
         * Rank of the tensor
         */
        octet rank;
        /**
         * Number of elements in each dimension
         */
        sequence<unsigned long> dims;
      };
    };
  };
};

#endif
