#ifndef __isaac_ros_tensor_list_interfaces__msg__Tensor__idl__
#define __isaac_ros_tensor_list_interfaces__msg__Tensor__idl__

#include "isaac_ros_tensor_list_interfaces/msg/./TensorShape_.idl"
module isaac_ros_tensor_list_interfaces
{
  module msg
  {
    module dds
    {

      @TypeCode(type="isaac_ros_tensor_list_interfaces::msg::dds_::Tensor_")
      struct Tensor
      {
        /**
         * Name of the tensor
         */
        string name;
        /**
         * Shape information for tensor
         */
        isaac_ros_tensor_list_interfaces::msg::dds::TensorShape shape;
        /**
         * Data type for tensor
         * Use the following values to represent these data types:
         * -  1: "int8"
         * -  2: "uint8"
         * -  3: "int16"
         * -  4: "uint16"
         * -  5: "int32"
         * -  6: "uint32"
         * -  7: "int64"
         * -  8: "uint64"
         * -  9: "float32"
         * - 10: "float64"
         */
        long data_type;
        /**
         * Strides of tensor (byte size for each dimension)
         */
        sequence<unsigned long long> strides;
        /**
         * Data buffer
         */
        sequence<octet> data;
      };
    };
  };
};

#endif
