# OPTIONAL: This contains any differences the user would like 
# to apply to the current planning scene.  This will not
# affect the current state of any other node
PlanningScene planning_scene_diff

# OPTINAL: Diff uses ordered collision operations instead of allowed_collision_matrix
arm_navigation_msgs/OrderedCollisionOperations operations
---
# This includes the current planning scene and any changes applied from the 
# diff
PlanningScene planning_scene

						   
				   
