# This message returns the current robot state from a node that has information
# about the current state of the robot

---

# The returned robot_state contains the current state of the robot
arm_navigation_msgs/RobotState robot_state

# Integer error code corresponding to the first check that was violated
# The message contains both the returned error code value and a set 
# of possible error codes
arm_navigation_msgs/ArmNavigationErrorCodes error_code
