
# Number of actions within the sequence
uint16 sequence_size

behavior_msgs/ArmJointAnglesActionMessage[] arm_joint_angles_actions

behavior_msgs/BodyPartPoseActionMessage[] chest_orientation_actions

behavior_msgs/FootstepPlanActionMessage[] footstep_plan_actions

behavior_msgs/SakeHandCommandActionMessage[] sake_hand_command_actions

behavior_msgs/SidedBodyPartPoseActionMessage[] hand_pose_actions

behavior_msgs/HandWrenchActionMessage[] hand_wrench_actions

behavior_msgs/BodyPartPoseActionMessage[] pelvis_height_actions

behavior_msgs/WaitDurationActionMessage[] wait_duration_actions

behavior_msgs/WalkActionMessage[] walk_actions


