
# Number of actions within the sequence
uint16 sequence_size

behavior_msgs/ArmJointAnglesActionMessage[] arm_joint_angles_actions

behavior_msgs/ChestOrientationActionMessage[] chest_orientation_actions

behavior_msgs/FootstepActionMessage[] footstep_actions

behavior_msgs/HandConfigurationActionMessage[] hand_configuration_actions

behavior_msgs/HandPoseActionMessage[] hand_pose_actions

behavior_msgs/HandWrenchActionMessage[] hand_wrench_actions

behavior_msgs/PelvisHeightActionMessage[] pelvis_height_actions

behavior_msgs/WaitDurationActionMessage[] wait_duration_actions

behavior_msgs/WalkActionMessage[] walk_actions


