package nav_msgs;

public interface GetMapResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "nav_msgs/GetMapResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\nnav_msgs/OccupancyGrid map\n";
  nav_msgs.OccupancyGrid getMap();
  void setMap(nav_msgs.OccupancyGrid value);
}
