package nav_msgs;

public interface GetMapActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "nav_msgs/GetMapActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nGetMapFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  nav_msgs.GetMapFeedback getFeedback();
  void setFeedback(nav_msgs.GetMapFeedback value);
}
