#ifndef __quadruped_msgs__msg__QuadrupedRequestedSteppingStateMessage__idl__
#define __quadruped_msgs__msg__QuadrupedRequestedSteppingStateMessage__idl__

module quadruped_msgs
{
  module msg
  {
    module dds
    {
      const octet REQUEST_STAND =
      0;

      const octet REQUEST_STEP =
      1;

      const octet REQUEST_SOLE_WAYPOINT =
      2;


      /**
       * This message is part of the IHMC quadruped controller API.
       * This message is used to switch the control scheme between different stepping modes.
       */
      @TypeCode(type="quadruped_msgs::msg::dds_::QuadrupedRequestedSteppingStateMessage_")
      struct QuadrupedRequestedSteppingStateMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Specifies the which state the controller should transition into.
         */
        @defaultValue(value=255)
        octet quadruped_stepping_requested_event;
      };
    };
  };
};

#endif
