#ifndef __quadruped_msgs__msg__QuadrupedBodyOrientationMessage__idl__
#define __quadruped_msgs__msg__QuadrupedBodyOrientationMessage__idl__

#include "ihmc_common_msgs/msg/./SO3TrajectoryMessage_.idl"
module quadruped_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       * This message commands the controller to move in taskspace the body to the desired orientation while going through the specified trajectory points.
       * A Hermite based curve (third order) is used to interpolate the orientations.
       * This message allows controlling the body orientation without interfering with position that will still be controlled to maintain the current desired capture point position.
       * To execute a normal trajectory to reach a desired body orientation, set only one trajectory point with zero velocity and its time to be equal to the desired trajectory time.
       */
      @TypeCode(type="quadruped_msgs::msg::dds_::QuadrupedBodyOrientationMessage_")
      struct QuadrupedBodyOrientationMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * If true, the times are expressed in absolute time relative to the robot start
         */
        @defaultValue(value=True)
        boolean is_expressed_in_absolute_time;
        /**
         * Indicates if the given trajectory should be considered an "absolute" orientation or an "offset" orientation
         */
        @defaultValue(value=True)
        boolean is_an_offset_orientation;
        /**
         * The orientation trajectory information.
         */
        ihmc_common_msgs::msg::dds::SO3TrajectoryMessage so3_trajectory;
      };
    };
  };
};

#endif
