#ifndef __quadruped_msgs__msg__QuadrupedBodyPathPlanMessage__idl__
#define __quadruped_msgs__msg__QuadrupedBodyPathPlanMessage__idl__

#include "ihmc_common_msgs/msg/./EuclideanTrajectoryPointMessage_.idl"
module quadruped_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       * This message commands the quadruped planner to execute a path composed of the given sequence of waypoints.
       * A waypoint represents a desired (x, y, yaw) position which the robot should pass through.
       * A Hermite based curve (third order) is used to interpolate the waypoints.
       */
      @TypeCode(type="quadruped_msgs::msg::dds_::QuadrupedBodyPathPlanMessage_")
      struct QuadrupedBodyPathPlanMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * If true, the times are expressed in absolute time relative to the robot start
         */
        @defaultValue(value=True)
        boolean is_expressed_in_absolute_time;
        /**
         * List of body path waypoint
         */
        sequence<ihmc_common_msgs::msg::dds::EuclideanTrajectoryPointMessage, 50> body_path_points;
      };
    };
  };
};

#endif
