/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This is part of the IHMC Common message package.
<p>Source (ihmc_common_msgs/Ellipsoid3DMessage):
<pre>{@code
# This is part of the IHMC Common message package.

# Pose of the ellipsoid, see Ellipsoid3D
geometry_msgs/Pose pose

# Radii of the ellipsoid, see Ellipsoid3D
geometry_msgs/Vector3 radii}</pre>
*/
public class Ellipsoid3DMessage implements ROS2Message<Ellipsoid3DMessage>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::Ellipsoid3DMessage_";

   /**
      Pose of the ellipsoid, see Ellipsoid3D
   */
   private final us.ihmc.euclid.jros2.messages.EuclidPose3DMessage pose_;
   /**
      Radii of the ellipsoid, see Ellipsoid3D
   */
   private final us.ihmc.euclid.jros2.messages.EuclidVector3DMessage radii_;

   public Ellipsoid3DMessage()
   {
      pose_ = new us.ihmc.euclid.jros2.messages.EuclidPose3DMessage();
      radii_ = new us.ihmc.euclid.jros2.messages.EuclidVector3DMessage();

   }

   public Ellipsoid3DMessage(Ellipsoid3DMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += pose_.calculateSizeBytes(currentAlignment);
      currentAlignment += radii_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      pose_.serialize(buffer);
      radii_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      pose_.deserialize(buffer);
      radii_.deserialize(buffer);

   }

   @Override
   public void set(Ellipsoid3DMessage from)
   {
      pose_.set(from.pose_);
      radii_.set(from.radii_);

   }

   public us.ihmc.euclid.jros2.messages.EuclidPose3DMessage getPose()
   {
      return pose_;
   }

   public us.ihmc.euclid.jros2.messages.EuclidVector3DMessage getRadii()
   {
      return radii_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("Ellipsoid3DMessage {");
      builder.append("pose_=");
      builder.append(pose_);
      builder.append("radii_=");
      builder.append(radii_);

      builder.append("}");
      return builder.toString();
   }
}