/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
An instantaneous point on the time-line.
Corresponds to java.time.Instant. Read about it:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Instant.html
<p>Source (ihmc_common_msgs/InstantMessage):
<pre>{@code
# An instantaneous point on the time-line.
# Corresponds to java.time.Instant. Read about it:
# https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Instant.html

# Seconds elapsed since the standard Java epoch of 1970-01-01T00:00:00Z
int64 seconds_since_epoch
# Additional nanoseconds which will always be between 0 and 999,999,999
int64 additional_nanos}</pre>
*/
public class InstantMessage implements ROS2Message<InstantMessage>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::InstantMessage_";

   /**
      Seconds elapsed since the standard Java epoch of 1970-01-01T00:00:00Z
   */
   private long seconds_since_epoch_;
   /**
      Additional nanoseconds which will always be between 0 and 999,999,999
   */
   private long additional_nanos_;

   public InstantMessage()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // seconds_since_epoch_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // additional_nanos_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(seconds_since_epoch_);
      buffer.writeLong(additional_nanos_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      seconds_since_epoch_ = buffer.readLong();
      additional_nanos_ = buffer.readLong();

   }

   @Override
   public void set(InstantMessage from)
   {
      seconds_since_epoch_ = from.seconds_since_epoch_;
      additional_nanos_ = from.additional_nanos_;

   }

   public long getSecondsSinceEpoch()
   {
      return seconds_since_epoch_;
   }

   public void setSecondsSinceEpoch(long seconds_since_epoch_)
   {
      this.seconds_since_epoch_ = seconds_since_epoch_;
   }

   public long getAdditionalNanos()
   {
      return additional_nanos_;
   }

   public void setAdditionalNanos(long additional_nanos_)
   {
      this.additional_nanos_ = additional_nanos_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("InstantMessage {");
      builder.append("seconds_since_epoch_=");
      builder.append(seconds_since_epoch_);
      builder.append("additional_nanos_=");
      builder.append(additional_nanos_);

      builder.append("}");
      return builder.toString();
   }
}