/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
This is part of the IHMC Common message package.
Notifies the user that a MessageCollection has been received.
This is used to know when the controller is ready to start collecting the actual collection of messages.
<p>Source (ihmc_common_msgs/MessageCollectionNotification):
<pre>{@code
# This is part of the IHMC Common message package.
# Notifies the user that a MessageCollection has been received.
# This is used to know when the controller is ready to start collecting the actual collection of messages.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

# This is the sequence ID of the MessageCollection that has just been received.
uint32 message_collection_sequence_id}</pre>
*/
public class MessageCollectionNotification implements ROS2Message<MessageCollectionNotification>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::MessageCollectionNotification_";

   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   /**
      This is the sequence ID of the MessageCollection that has just been received.
   */
   private int message_collection_sequence_id_;

   public MessageCollectionNotification()
   {
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4); // message_collection_sequence_id_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeInt(message_collection_sequence_id_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      message_collection_sequence_id_ = buffer.readInt();

   }

   @Override
   public void set(MessageCollectionNotification from)
   {
      sequence_id_ = from.sequence_id_;
      message_collection_sequence_id_ = from.message_collection_sequence_id_;

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public int getMessageCollectionSequenceId()
   {
      return message_collection_sequence_id_;
   }

   public void setMessageCollectionSequenceId(int message_collection_sequence_id_)
   {
      this.message_collection_sequence_id_ = message_collection_sequence_id_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MessageCollectionNotification {");
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("message_collection_sequence_id_=");
      builder.append(message_collection_sequence_id_);

      builder.append("}");
      return builder.toString();
   }
}