/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
Use this message for the robot to speak.
<p>Source (ihmc_common_msgs/TextToSpeechPacket):
<pre>{@code
# Use this message for the robot to speak.

string FOOTSTEP_COMPLETED = "Finished Taking Footstep"
string FINISHED_WALKING = "Finished walking"
string WALKING_ABORTED = "walking aborted"
string STARTING_CONTROLLER = "starting controller"
string WALKING = "walking"
string MOVING_LEFT_ARM = "moving the left arm"
string MOVING_RIGHT_ARM = "moving the right arm"
string NETWORKPROCESSOR_ONLINE = "Reestablished Connection To The Network Processor"

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint64 sequence_id

bool speak_packet false
bool beep true
string text_to_speak}</pre>
*/
public class TextToSpeechPacket implements ROS2Message<TextToSpeechPacket>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::TextToSpeechPacket_";

   public static final String FOOTSTEP_COMPLETED = "Finished Taking Footstep";
   public static final String FINISHED_WALKING = "Finished walking";
   public static final String WALKING_ABORTED = "walking aborted";
   public static final String STARTING_CONTROLLER = "starting controller";
   public static final String WALKING = "walking";
   public static final String MOVING_LEFT_ARM = "moving the left arm";
   public static final String MOVING_RIGHT_ARM = "moving the right arm";
   public static final String NETWORKPROCESSOR_ONLINE = "Reestablished Connection To The Network Processor";
   /**
      Unique ID used to identify this message, should preferably be consecutively increasing.
   */
   private long sequence_id_;
   private boolean speak_packet_;
   private boolean beep_;
   private final StringBuilder text_to_speak_;

   public TextToSpeechPacket()
   {
      speak_packet_ = (boolean) false;
      beep_ = (boolean) true;
      text_to_speak_ = new StringBuilder();

   }

   public TextToSpeechPacket(TextToSpeechPacket from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // sequence_id_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // speak_packet_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // beep_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * text_to_speak_.length()) + 1; // text_to_speak_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeLong(sequence_id_);
      buffer.writeBoolean(speak_packet_);
      buffer.writeBoolean(beep_);
      buffer.writeString(text_to_speak_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      sequence_id_ = buffer.readLong();
      speak_packet_ = buffer.readBoolean();
      beep_ = buffer.readBoolean();
      buffer.readString(text_to_speak_);

   }

   @Override
   public void set(TextToSpeechPacket from)
   {
      sequence_id_ = from.sequence_id_;
      speak_packet_ = from.speak_packet_;
      beep_ = from.beep_;
      text_to_speak_.delete(0, text_to_speak_.length());
      text_to_speak_.insert(0, from.text_to_speak_);

   }

   public long getSequenceId()
   {
      return sequence_id_;
   }

   public void setSequenceId(long sequence_id_)
   {
      this.sequence_id_ = sequence_id_;
   }

   public boolean getSpeakPacket()
   {
      return speak_packet_;
   }

   public void setSpeakPacket(boolean speak_packet_)
   {
      this.speak_packet_ = speak_packet_;
   }

   public boolean getBeep()
   {
      return beep_;
   }

   public void setBeep(boolean beep_)
   {
      this.beep_ = beep_;
   }

   public StringBuilder getTextToSpeak()
   {
      return text_to_speak_;
   }

   public java.lang.String getTextToSpeakAsString()
   {
      return text_to_speak_.toString();
   }

   public void setTextToSpeak(java.lang.String s)
   {
      this.text_to_speak_.delete(0, this.text_to_speak_.length());
      this.text_to_speak_.insert(0, s);
   }

   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("TextToSpeechPacket {");
      builder.append("FOOTSTEP_COMPLETED=");
      builder.append(FOOTSTEP_COMPLETED);
      builder.append("FINISHED_WALKING=");
      builder.append(FINISHED_WALKING);
      builder.append("WALKING_ABORTED=");
      builder.append(WALKING_ABORTED);
      builder.append("STARTING_CONTROLLER=");
      builder.append(STARTING_CONTROLLER);
      builder.append("WALKING=");
      builder.append(WALKING);
      builder.append("MOVING_LEFT_ARM=");
      builder.append(MOVING_LEFT_ARM);
      builder.append("MOVING_RIGHT_ARM=");
      builder.append(MOVING_RIGHT_ARM);
      builder.append("NETWORKPROCESSOR_ONLINE=");
      builder.append(NETWORKPROCESSOR_ONLINE);
      builder.append("sequence_id_=");
      builder.append(sequence_id_);
      builder.append("speak_packet_=");
      builder.append(speak_packet_);
      builder.append("beep_=");
      builder.append(beep_);
      builder.append("text_to_speak_=");
      builder.append(text_to_speak_.toString());

      builder.append("}");
      return builder.toString();
   }
}