/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package ihmc_common_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
A yaw-pitch-roll is used to represent a 3D orientation by three successive rotations: rotation around the z-axis
(yaw), then around the y-axis (pitch), and then around the x-axis (roll). The three components yaw, pitch, and
roll represents the angle for rotation expressed in radians.
<p>Source (ihmc_common_msgs/YawPitchRollMessage):
<pre>{@code
# A yaw-pitch-roll is used to represent a 3D orientation by three successive rotations: rotation around the z-axis
# (yaw), then around the y-axis (pitch), and then around the x-axis (roll). The three components yaw, pitch, and
# roll represents the angle for rotation expressed in radians.

# The yaw angle representing the first rotation around the z-axis.
float64 yaw

# The pitch angle representing the second rotation around the y-axis.
float64 pitch

# The roll angle representing the third rotation around the x-axis.
float64 roll}</pre>
*/
public class YawPitchRollMessage implements ROS2Message<YawPitchRollMessage>
{
   public static final java.lang.String name = "ihmc_common_msgs::msg::dds_::YawPitchRollMessage_";

   /**
      The yaw angle representing the first rotation around the z-axis.
   */
   private double yaw_;
   /**
      The pitch angle representing the second rotation around the y-axis.
   */
   private double pitch_;
   /**
      The roll angle representing the third rotation around the x-axis.
   */
   private double roll_;

   public YawPitchRollMessage()
   {
   }

   public YawPitchRollMessage(YawPitchRollMessage from)
   {
      this();
      set(from);
   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // yaw_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // pitch_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // roll_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeDouble(yaw_);
      buffer.writeDouble(pitch_);
      buffer.writeDouble(roll_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      yaw_ = buffer.readDouble();
      pitch_ = buffer.readDouble();
      roll_ = buffer.readDouble();

   }

   @Override
   public void set(YawPitchRollMessage from)
   {
      yaw_ = from.yaw_;
      pitch_ = from.pitch_;
      roll_ = from.roll_;

   }

   public double getYaw()
   {
      return yaw_;
   }

   public void setYaw(double yaw_)
   {
      this.yaw_ = yaw_;
   }

   public double getPitch()
   {
      return pitch_;
   }

   public void setPitch(double pitch_)
   {
      this.pitch_ = pitch_;
   }

   public double getRoll()
   {
      return roll_;
   }

   public void setRoll(double roll_)
   {
      this.roll_ = roll_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("YawPitchRollMessage {");
      builder.append("yaw_=");
      builder.append(yaw_);
      builder.append("pitch_=");
      builder.append(pitch_);
      builder.append("roll_=");
      builder.append(roll_);

      builder.append("}");
      return builder.toString();
   }
}