package us.ihmc.quadrupedRobotics.parameters;

public enum QuadrupedJointName
{
   /* Neck joints */
   NEAR_NECK_YAW,
   NEAR_NECK_PITCH,
   NEAR_NECK_ROLL,

   /* Head joints */
   FAR_NECK_YAW,
   FAR_NECK_PITCH,
   FAR_NECK_ROLL,

   /* Leg joints */
   FRONT_LEFT_HIP_ROLL,
   FRONT_LEFT_HIP_PITCH,
   FRONT_LEFT_KNEE_PITCH,
   FRONT_LEFT_ANKLE_PITCH,
   FRONT_RIGHT_HIP_ROLL,
   FRONT_RIGHT_HIP_PITCH,
   FRONT_RIGHT_KNEE_PITCH,
   FRONT_RIGHT_ANKLE_PITCH,
   HIND_LEFT_HIP_ROLL,
   HIND_LEFT_HIP_PITCH,
   HIND_LEFT_KNEE_PITCH,
   HIND_LEFT_ANKLE_PITCH,
   HIND_RIGHT_HIP_ROLL,
   HIND_RIGHT_HIP_PITCH,
   HIND_RIGHT_KNEE_PITCH,
   HIND_RIGHT_ANKLE_PITCH;
}
