# This is a message that holds time interval details.
#
# The time interval is defined by:
#  * the time at the beginning of the interval, and
#  * the duration of the interval.
#
# The time interval information allow us to compute the beginning of
# the reference state and control.

# This represents the time at the beginning of the interval
float64 time

# This represents the duration of the interval
float64 duration