# This message is part of the IHMC quadruped footstep planning module.

float64 NO_VALUE_DOUBLE = -11.1

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint32 sequence_id

float64 maximum_step_reach -11.1
float64 maximum_step_length -11.1
float64 minimum_step_length -11.1
float64 maximum_step_width -11.1
float64 minimum_step_width -11.1
float64 minimum_step_yaw -11.1
float64 maximum_step_yaw -11.1
float64 maximum_step_change_z -11.1
float64 body_ground_clearance -11.1
float64 distance_heuristic_weight -11.1
float64 yaw_weight -11.1
float64 x_gait_weight -11.1
float64 cost_per_step -11.1
float64 step_up_weight -11.1
float64 step_down_weight -11.1
float64 heuristics_weight -11.1
float64 min_x_clearance_from_foot -11.1
float64 min_y_clearance_from_foot -11.1
float64 max_walking_speed_multiplier -11.1
float64 projection_inside_distance_for_expansion -11.1
float64 projection_inside_distance_for_post_processing -11.1
float64 minimum_surface_incline_radians -11.1
float64 cliff_height_to_avoid -11.1
float64 minimum_distance_from_cliff_bottoms -11.1
float64 minimum_distance_from_cliff_tops -11.1
