# This message is part of the IHMC whole-body controller API.
# This message will request a calibration the wrist force sensors to the IHMC controller (does not do hardware calibration).
# It is strongly suggested to perform the calibration when the hands are not moving nor interacting with the environment.

# Unique ID used to identify this message, should preferably be consecutively increasing.
uint32 sequence_id
