# This message represents a rigid body transform as a translation and rotation matrix

# Translation X
float64 x
# Translation Y
float64 y
# Translation Z
float64 z

# Rotation matrix
float64 m00

# Rotation matrix
float64 m01

# Rotation matrix
float64 m02

# Rotation matrix
float64 m10

# Rotation matrix
float64 m11

# Rotation matrix
float64 m12

# Rotation matrix
float64 m20

# Rotation matrix
float64 m21

# Rotation matrix
float64 m22
