package us.ihmc.commonWalkingControlModules.controllerCore.command;

public enum ControllerCoreCommandType
{
   TASKSPACE, POINT, ORIENTATION, JOINTSPACE, MOMENTUM,
   PRIVILEGED_CONFIGURATION, VIRTUAL_WRENCH,
   EXTERNAL_WRENCH, PLANE_CONTACT_STATE,
   JOINT_ACCELERATION_INTEGRATION,
   COMMAND_LIST
}
