package arm_navigation_msgs;

public interface MakeStaticCollisionMapActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "arm_navigation_msgs/MakeStaticCollisionMapActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nMakeStaticCollisionMapGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  arm_navigation_msgs.MakeStaticCollisionMapGoal getGoal();
  void setGoal(arm_navigation_msgs.MakeStaticCollisionMapGoal value);
}
