package pr2_common_action_msgs;

public interface ArmMoveIKResult extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "pr2_common_action_msgs/ArmMoveIKResult";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#result definition\n\n";
}
