/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer */

#ifndef _Included_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer
#define _Included_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer
#ifdef __cplusplus
extern "C" {
#endif
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nPointsPerPlane
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nPointsPerPlane 4L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nSupportVectorsPerPoint
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nSupportVectorsPerPoint 4L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nPlanes
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nPlanes 4L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nWrench
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nWrench 6L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nRho
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_nRho 64L
/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer
 * Method:    initializeNative
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_initializeNative
  (JNIEnv *, jobject, jint);

JNIEXPORT void initializeNative(int);
/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer
 * Method:    resetActiveSet
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_resetActiveSet
  (JNIEnv *, jobject);

JNIEXPORT void resetActiveSet();
/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer
 * Method:    solveNative
 * Signature: ([D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_ActiveSetQPMomentumOptimizer_solveNative
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

JNIEXPORT int solveNative(
		double* A, double* b, double* C,
		double* Jp, double* pp,
		double* Js, double* ps, double* Ws,
		double* WRho, double* Lambda,
		double* WRhoSmoother,
		double* rhoPrevMean, double* WRhoCoPPenalty,
		double* QRho, double* c, double* rhoMin,
		double* vd, double* rho);
#ifdef __cplusplus
}
#endif
#endif
