/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative */

#ifndef _Included_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
#define _Included_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
#ifdef __cplusplus
extern "C" {
#endif
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_NUMBER_OF_SUPPORT_VECTORS
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_NUMBER_OF_SUPPORT_VECTORS 4L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_MAX_NUMBER_OF_CONTACTS
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_MAX_NUMBER_OF_CONTACTS 2L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_n
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_n 6L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_m
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_m 8L
/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_initialize
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
 * Method:    getPhiBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_getPhiBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
 * Method:    getXiBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_getXiBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
 * Method:    getRhoBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_getRhoBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
 * Method:    solveNative
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_solveNative
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative
 * Method:    getOptValNative
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_LeeGoswamiForceOptimizerNative_getOptValNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
