/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative */

#ifndef _Included_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
#define _Included_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
#ifdef __cplusplus
extern "C" {
#endif
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nSupportVectors
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nSupportVectors 3L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nPointsPerContact
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nPointsPerContact 4L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nContacts
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nContacts 4L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_wrenchLength
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_wrenchLength 6L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nDoF
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nDoF 34L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nNull
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_nNull 4L
#undef us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_rhoSize
#define us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_rhoSize 48L
/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_initialize
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getABuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getABuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getbBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getbBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getCBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getCBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getJsBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getJsBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getpsBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getpsBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getWsBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getWsBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getLambdaBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getLambdaBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getQBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getQBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getcBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getcBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getNBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getNBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getzBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getzBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getrhoMinBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getrhoMinBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getrhoBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getrhoBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getvdBuffer
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getvdBuffer
  (JNIEnv *, jclass);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    solveNative
 * Signature: (D)I
 */
JNIEXPORT jint JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_solveNative
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative
 * Method:    getOptValNative
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_us_ihmc_commonWalkingControlModules_controlModules_nativeOptimization_MomentumOptimizerNative_getOptValNative
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
