package actionlib;

public interface TestRequestActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib/TestRequestActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nTestRequestFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  actionlib.TestRequestFeedback getFeedback();
  void setFeedback(actionlib.TestRequestFeedback value);
}
