package actionlib;

public interface TwoIntsActionGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib/TwoIntsActionGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalID goal_id\nTwoIntsGoal goal\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalID getGoalId();
  void setGoalId(actionlib_msgs.GoalID value);
  actionlib.TwoIntsGoal getGoal();
  void setGoal(actionlib.TwoIntsGoal value);
}
