%flist=strsplit('simple1DQpTest.QPS TAME.QPS HS21.QPS HS35.QPS ZECEVIC2.QPS HS35MOD.QPS HS76.QPS HS52.QPS HS51.QPS HS53.QPS HS268.QPS S268.QPS LOTSCHD.QPS GENHS28.QPS HS118.QPS QPCBLEND.QPS CVXQP2_S.QPS CVXQP1_S.QPS CVXQP3_S.QPS DUALC2.QPS QPCBOEI2.QPS PRIMALC2.QPS DUALC1.QPS PRIMALC1.QPS DUALC5.QPS PRIMALC5.QPS DUALC8.QPS PRIMALC8.QPS DUAL4.QPS QPCSTAIR.QPS QPCBOEI1.QPS GOULDQP2.QPS');
%flist=strsplit('DUAL1.QPS PRIMAL1.QPS MOSARQP2.QPS','GOULDQP3.QPS') 
flist=strsplit('CVXQP3_M.QPS AUG3DQP.QPS PRIMAL4.QPS KSIP.QPS PRIMAL3.QPS AUG3DCQP.QPS AUG3D.QPS AUG3DC.QPS')

flist={'DUALC1.QPS'};
for s=flist
    qpsName=s{:}
    yamlName=[qpsName(1:end-4) '.yaml'];
    processedObj=ReadMpsAdapter(qpsName, yamlName);
end