/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/AI2RReceiveObjectMessage):
<pre>{@code
# Reference frame (object) to receive
string object_name

# Which hand to receive the object
byte side 255

# The maximum distance hand-object allowed to trigger grasping
float64 distance_to_object}</pre>
*/
public class AI2RReceiveObjectMessage implements ROS2Message<AI2RReceiveObjectMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::AI2RReceiveObjectMessage_";

   /**
      Reference frame (object) to receive
   */
   private final StringBuilder object_name_;
   /**
      Which hand to receive the object
   */
   private byte side_;
   /**
      The maximum distance hand-object allowed to trigger grasping
   */
   private double distance_to_object_;

   public AI2RReceiveObjectMessage()
   {
      object_name_ = new StringBuilder();
      side_ = (byte) 255;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * object_name_.length()) + 1; // object_name_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // side_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // distance_to_object_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeString(object_name_);
      buffer.writeByte(side_);
      buffer.writeDouble(distance_to_object_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      buffer.readString(object_name_);
      side_ = buffer.readByte();
      distance_to_object_ = buffer.readDouble();

   }

   @Override
   public void set(AI2RReceiveObjectMessage from)
   {
      object_name_.delete(0, object_name_.length());
      object_name_.insert(0, from.object_name_);
      side_ = from.side_;
      distance_to_object_ = from.distance_to_object_;

   }

   public StringBuilder getObjectName()
   {
      return object_name_;
   }

   public java.lang.String getObjectNameAsString()
   {
      return object_name_.toString();
   }

   public void setObjectName(java.lang.String s)
   {
      this.object_name_.delete(0, this.object_name_.length());
      this.object_name_.insert(0, s);
   }
   public byte getSide()
   {
      return side_;
   }

   public void setSide(byte side_)
   {
      this.side_ = side_;
   }

   public double getDistanceToObject()
   {
      return distance_to_object_;
   }

   public void setDistanceToObject(double distance_to_object_)
   {
      this.distance_to_object_ = distance_to_object_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AI2RReceiveObjectMessage {");
      builder.append("object_name_=");
      builder.append(object_name_.toString());
      builder.append("side_=");
      builder.append(side_);
      builder.append("distance_to_object_=");
      builder.append(distance_to_object_);

      builder.append("}");
      return builder.toString();
   }
}