/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/AI2RScanMessage):
<pre>{@code
string[<=200] object_names}</pre>
*/
public class AI2RScanMessage implements ROS2Message<AI2RScanMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::AI2RScanMessage_";

   private final IDLStringSequence object_names_;

   public AI2RScanMessage()
   {
      object_names_ = new IDLStringSequence(0);

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += object_names_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      object_names_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      object_names_.deserialize(buffer);

   }

   @Override
   public void set(AI2RScanMessage from)
   {
      object_names_.set(from.object_names_);

   }

   public IDLStringSequence getObjectNames()
   {
      return object_names_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("AI2RScanMessage {");
      builder.append("object_names_=");
      builder.append(object_names_);

      builder.append("}");
      return builder.toString();
   }
}