/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/ArmActionDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/ActionNodeDefinitionMessage definition

# Specifies the side of the robot that this message refers to.
byte robot_side 255

# Name of the frame the this action is expressed in
string parent_frame_name

# Transform that expresses the hand pose in the parent frame
controller_msgs/RigidBodyTransformMessage transform_to_parent

# Whether the rigid body is controlled in jointspace (true) or taskspace (false)
bool joint_space_control

# Whether to use predefined joint angles
bool use_predefined_joint_angles

# Preset arm configuration
byte preset

# Joint angles
float64[7] joint_angles

# The trajectory duration
float64 trajectory_duration

# Whether maintaining the rigid body controlled in world after the action is complete
bool hold_pose_in_world

float64 linear_position_weight

float64 angular_position_weight

float64 jointspace_weight

float64 position_error_tolerance

float64 orientation_error_tolerance
}</pre>
*/
public class ArmActionDefinitionMessage implements ROS2Message<ArmActionDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::ArmActionDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.ActionNodeDefinitionMessage definition_;
   /**
      Specifies the side of the robot that this message refers to.
   */
   private byte robot_side_;
   /**
      Name of the frame the this action is expressed in
   */
   private final StringBuilder parent_frame_name_;
   /**
      Transform that expresses the hand pose in the parent frame
   */
   private final controller_msgs.RigidBodyTransformMessage transform_to_parent_;
   /**
      Whether the rigid body is controlled in jointspace (true) or taskspace (false)
   */
   private boolean joint_space_control_;
   /**
      Whether to use predefined joint angles
   */
   private boolean use_predefined_joint_angles_;
   /**
      Preset arm configuration
   */
   private byte preset_;
   /**
      Joint angles
   */
   private final double[] joint_angles_;
   /**
      The trajectory duration
   */
   private double trajectory_duration_;
   /**
      Whether maintaining the rigid body controlled in world after the action is complete
   */
   private boolean hold_pose_in_world_;
   private double linear_position_weight_;
   private double angular_position_weight_;
   private double jointspace_weight_;
   private double position_error_tolerance_;
   private double orientation_error_tolerance_;

   public ArmActionDefinitionMessage()
   {
      definition_ = new behavior_msgs.ActionNodeDefinitionMessage();
      robot_side_ = (byte) 255;
      parent_frame_name_ = new StringBuilder();
      transform_to_parent_ = new controller_msgs.RigidBodyTransformMessage();
      joint_space_control_ = (boolean) false;
      use_predefined_joint_angles_ = (boolean) false;
      joint_angles_ = new double[7];
      hold_pose_in_world_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // robot_side_
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * parent_frame_name_.length()) + 1; // parent_frame_name_
      currentAlignment += transform_to_parent_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // joint_space_control_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // use_predefined_joint_angles_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // preset_
      currentAlignment += (7 * 8) + CDRBuffer.alignment(currentAlignment, (7 * 8)); // joint_angles_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // trajectory_duration_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hold_pose_in_world_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // linear_position_weight_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // angular_position_weight_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // jointspace_weight_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // position_error_tolerance_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // orientation_error_tolerance_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeByte(robot_side_);
      buffer.writeString(parent_frame_name_);
      transform_to_parent_.serialize(buffer);
      buffer.writeBoolean(joint_space_control_);
      buffer.writeBoolean(use_predefined_joint_angles_);
      buffer.writeByte(preset_);
      for (int i = 0; i < joint_angles_.length; ++i)
      {
         buffer.writeDouble(joint_angles_[i]);
      }
      buffer.writeDouble(trajectory_duration_);
      buffer.writeBoolean(hold_pose_in_world_);
      buffer.writeDouble(linear_position_weight_);
      buffer.writeDouble(angular_position_weight_);
      buffer.writeDouble(jointspace_weight_);
      buffer.writeDouble(position_error_tolerance_);
      buffer.writeDouble(orientation_error_tolerance_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      robot_side_ = buffer.readByte();
      buffer.readString(parent_frame_name_);
      transform_to_parent_.deserialize(buffer);
      joint_space_control_ = buffer.readBoolean();
      use_predefined_joint_angles_ = buffer.readBoolean();
      preset_ = buffer.readByte();
      for (int i = 0; i < joint_angles_.length; ++i)
      {
         joint_angles_[i] = buffer.readDouble();
      }
      trajectory_duration_ = buffer.readDouble();
      hold_pose_in_world_ = buffer.readBoolean();
      linear_position_weight_ = buffer.readDouble();
      angular_position_weight_ = buffer.readDouble();
      jointspace_weight_ = buffer.readDouble();
      position_error_tolerance_ = buffer.readDouble();
      orientation_error_tolerance_ = buffer.readDouble();

   }

   @Override
   public void set(ArmActionDefinitionMessage from)
   {
      definition_.set(from.definition_);
      robot_side_ = from.robot_side_;
      parent_frame_name_.delete(0, parent_frame_name_.length());
      parent_frame_name_.insert(0, from.parent_frame_name_);
      transform_to_parent_.set(from.transform_to_parent_);
      joint_space_control_ = from.joint_space_control_;
      use_predefined_joint_angles_ = from.use_predefined_joint_angles_;
      preset_ = from.preset_;
      for (int i = 0; i < joint_angles_.length; ++i)
      {
         joint_angles_[i] = from.joint_angles_[i];
      }
      trajectory_duration_ = from.trajectory_duration_;
      hold_pose_in_world_ = from.hold_pose_in_world_;
      linear_position_weight_ = from.linear_position_weight_;
      angular_position_weight_ = from.angular_position_weight_;
      jointspace_weight_ = from.jointspace_weight_;
      position_error_tolerance_ = from.position_error_tolerance_;
      orientation_error_tolerance_ = from.orientation_error_tolerance_;

   }

   public behavior_msgs.ActionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public byte getRobotSide()
   {
      return robot_side_;
   }

   public void setRobotSide(byte robot_side_)
   {
      this.robot_side_ = robot_side_;
   }

   public StringBuilder getParentFrameName()
   {
      return parent_frame_name_;
   }

   public java.lang.String getParentFrameNameAsString()
   {
      return parent_frame_name_.toString();
   }

   public void setParentFrameName(java.lang.String s)
   {
      this.parent_frame_name_.delete(0, this.parent_frame_name_.length());
      this.parent_frame_name_.insert(0, s);
   }
   public controller_msgs.RigidBodyTransformMessage getTransformToParent()
   {
      return transform_to_parent_;
   }

   public boolean getJointSpaceControl()
   {
      return joint_space_control_;
   }

   public void setJointSpaceControl(boolean joint_space_control_)
   {
      this.joint_space_control_ = joint_space_control_;
   }

   public boolean getUsePredefinedJointAngles()
   {
      return use_predefined_joint_angles_;
   }

   public void setUsePredefinedJointAngles(boolean use_predefined_joint_angles_)
   {
      this.use_predefined_joint_angles_ = use_predefined_joint_angles_;
   }

   public byte getPreset()
   {
      return preset_;
   }

   public void setPreset(byte preset_)
   {
      this.preset_ = preset_;
   }

   public double[] getJointAngles()
   {
      return joint_angles_;
   }

   public double getTrajectoryDuration()
   {
      return trajectory_duration_;
   }

   public void setTrajectoryDuration(double trajectory_duration_)
   {
      this.trajectory_duration_ = trajectory_duration_;
   }

   public boolean getHoldPoseInWorld()
   {
      return hold_pose_in_world_;
   }

   public void setHoldPoseInWorld(boolean hold_pose_in_world_)
   {
      this.hold_pose_in_world_ = hold_pose_in_world_;
   }

   public double getLinearPositionWeight()
   {
      return linear_position_weight_;
   }

   public void setLinearPositionWeight(double linear_position_weight_)
   {
      this.linear_position_weight_ = linear_position_weight_;
   }

   public double getAngularPositionWeight()
   {
      return angular_position_weight_;
   }

   public void setAngularPositionWeight(double angular_position_weight_)
   {
      this.angular_position_weight_ = angular_position_weight_;
   }

   public double getJointspaceWeight()
   {
      return jointspace_weight_;
   }

   public void setJointspaceWeight(double jointspace_weight_)
   {
      this.jointspace_weight_ = jointspace_weight_;
   }

   public double getPositionErrorTolerance()
   {
      return position_error_tolerance_;
   }

   public void setPositionErrorTolerance(double position_error_tolerance_)
   {
      this.position_error_tolerance_ = position_error_tolerance_;
   }

   public double getOrientationErrorTolerance()
   {
      return orientation_error_tolerance_;
   }

   public void setOrientationErrorTolerance(double orientation_error_tolerance_)
   {
      this.orientation_error_tolerance_ = orientation_error_tolerance_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("ArmActionDefinitionMessage {");
      builder.append("definition_=");
      builder.append(definition_);
      builder.append("robot_side_=");
      builder.append(robot_side_);
      builder.append("parent_frame_name_=");
      builder.append(parent_frame_name_.toString());
      builder.append("transform_to_parent_=");
      builder.append(transform_to_parent_);
      builder.append("joint_space_control_=");
      builder.append(joint_space_control_);
      builder.append("use_predefined_joint_angles_=");
      builder.append(use_predefined_joint_angles_);
      builder.append("preset_=");
      builder.append(preset_);
      builder.append("joint_angles_=");
      builder.append(java.util.Arrays.toString(joint_angles_));
      builder.append("trajectory_duration_=");
      builder.append(trajectory_duration_);
      builder.append("hold_pose_in_world_=");
      builder.append(hold_pose_in_world_);
      builder.append("linear_position_weight_=");
      builder.append(linear_position_weight_);
      builder.append("angular_position_weight_=");
      builder.append(angular_position_weight_);
      builder.append("jointspace_weight_=");
      builder.append(jointspace_weight_);
      builder.append("position_error_tolerance_=");
      builder.append(position_error_tolerance_);
      builder.append("orientation_error_tolerance_=");
      builder.append(orientation_error_tolerance_);

      builder.append("}");
      return builder.toString();
   }
}