/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/MimicActionStateMessage):
<pre>{@code
# Parent state fields
behavior_msgs/ActionNodeStateMessage state

# Definition
behavior_msgs/MimicActionDefinitionMessage definition
}</pre>
*/
public class MimicActionStateMessage implements ROS2Message<MimicActionStateMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::MimicActionStateMessage_";

   /**
      Parent state fields
   */
   private final behavior_msgs.ActionNodeStateMessage state_;
   /**
      Definition
   */
   private final behavior_msgs.MimicActionDefinitionMessage definition_;

   public MimicActionStateMessage()
   {
      state_ = new behavior_msgs.ActionNodeStateMessage();
      definition_ = new behavior_msgs.MimicActionDefinitionMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += state_.calculateSizeBytes(currentAlignment);
      currentAlignment += definition_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      state_.serialize(buffer);
      definition_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      state_.deserialize(buffer);
      definition_.deserialize(buffer);

   }

   @Override
   public void set(MimicActionStateMessage from)
   {
      state_.set(from.state_);
      definition_.set(from.definition_);

   }

   public behavior_msgs.ActionNodeStateMessage getState()
   {
      return state_;
   }

   public behavior_msgs.MimicActionDefinitionMessage getDefinition()
   {
      return definition_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("MimicActionStateMessage {");
      builder.append("state_=");
      builder.append(state_);
      builder.append("definition_=");
      builder.append(definition_);

      builder.append("}");
      return builder.toString();
   }
}