/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/PelvisActionDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/ActionNodeDefinitionMessage definition

# Name of the frame the this action is expressed in
string parent_frame_name

# Transform that expresses the pelvis pose in the parent frame
controller_msgs/RigidBodyTransformMessage pelvis_transform_to_parent

# Duration of the trajectory
float64 trajectory_duration}</pre>
*/
public class PelvisActionDefinitionMessage implements ROS2Message<PelvisActionDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::PelvisActionDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.ActionNodeDefinitionMessage definition_;
   /**
      Name of the frame the this action is expressed in
   */
   private final StringBuilder parent_frame_name_;
   /**
      Transform that expresses the pelvis pose in the parent frame
   */
   private final controller_msgs.RigidBodyTransformMessage pelvis_transform_to_parent_;
   /**
      Duration of the trajectory
   */
   private double trajectory_duration_;

   public PelvisActionDefinitionMessage()
   {
      definition_ = new behavior_msgs.ActionNodeDefinitionMessage();
      parent_frame_name_ = new StringBuilder();
      pelvis_transform_to_parent_ = new controller_msgs.RigidBodyTransformMessage();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * parent_frame_name_.length()) + 1; // parent_frame_name_
      currentAlignment += pelvis_transform_to_parent_.calculateSizeBytes(currentAlignment);
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // trajectory_duration_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeString(parent_frame_name_);
      pelvis_transform_to_parent_.serialize(buffer);
      buffer.writeDouble(trajectory_duration_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      buffer.readString(parent_frame_name_);
      pelvis_transform_to_parent_.deserialize(buffer);
      trajectory_duration_ = buffer.readDouble();

   }

   @Override
   public void set(PelvisActionDefinitionMessage from)
   {
      definition_.set(from.definition_);
      parent_frame_name_.delete(0, parent_frame_name_.length());
      parent_frame_name_.insert(0, from.parent_frame_name_);
      pelvis_transform_to_parent_.set(from.pelvis_transform_to_parent_);
      trajectory_duration_ = from.trajectory_duration_;

   }

   public behavior_msgs.ActionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public StringBuilder getParentFrameName()
   {
      return parent_frame_name_;
   }

   public java.lang.String getParentFrameNameAsString()
   {
      return parent_frame_name_.toString();
   }

   public void setParentFrameName(java.lang.String s)
   {
      this.parent_frame_name_.delete(0, this.parent_frame_name_.length());
      this.parent_frame_name_.insert(0, s);
   }
   public controller_msgs.RigidBodyTransformMessage getPelvisTransformToParent()
   {
      return pelvis_transform_to_parent_;
   }

   public double getTrajectoryDuration()
   {
      return trajectory_duration_;
   }

   public void setTrajectoryDuration(double trajectory_duration_)
   {
      this.trajectory_duration_ = trajectory_duration_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("PelvisActionDefinitionMessage {");
      builder.append("definition_=");
      builder.append(definition_);
      builder.append("parent_frame_name_=");
      builder.append(parent_frame_name_.toString());
      builder.append("pelvis_transform_to_parent_=");
      builder.append(pelvis_transform_to_parent_);
      builder.append("trajectory_duration_=");
      builder.append(trajectory_duration_);

      builder.append("}");
      return builder.toString();
   }
}