/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/SpineActionDefinitionMessage):
<pre>{@code
# Parent definition fields
behavior_msgs/ActionNodeDefinitionMessage definition

# Name of the frame the this action is expressed in
string parent_frame_name

# Duration of the trajectory
float64 trajectory_duration

# Whether the action is jointspace only
bool jointspace_only

# Jointspace values
float64[3] joint_angles

# Transform that expresses the chest pose in the parent frame
controller_msgs/RigidBodyTransformMessage chest_transform_to_parent

# Whether maintaining the rigid body controlled in world after the action is complete
bool hold_pose_in_world}</pre>
*/
public class SpineActionDefinitionMessage implements ROS2Message<SpineActionDefinitionMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::SpineActionDefinitionMessage_";

   /**
      Parent definition fields
   */
   private final behavior_msgs.ActionNodeDefinitionMessage definition_;
   /**
      Name of the frame the this action is expressed in
   */
   private final StringBuilder parent_frame_name_;
   /**
      Duration of the trajectory
   */
   private double trajectory_duration_;
   /**
      Whether the action is jointspace only
   */
   private boolean jointspace_only_;
   /**
      Jointspace values
   */
   private final double[] joint_angles_;
   /**
      Transform that expresses the chest pose in the parent frame
   */
   private final controller_msgs.RigidBodyTransformMessage chest_transform_to_parent_;
   /**
      Whether maintaining the rigid body controlled in world after the action is complete
   */
   private boolean hold_pose_in_world_;

   public SpineActionDefinitionMessage()
   {
      definition_ = new behavior_msgs.ActionNodeDefinitionMessage();
      parent_frame_name_ = new StringBuilder();
      jointspace_only_ = (boolean) false;
      joint_angles_ = new double[3];
      chest_transform_to_parent_ = new controller_msgs.RigidBodyTransformMessage();
      hold_pose_in_world_ = (boolean) false;

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += definition_.calculateSizeBytes(currentAlignment);
      currentAlignment += 4 + CDRBuffer.alignment(currentAlignment, 4) + (1 * parent_frame_name_.length()) + 1; // parent_frame_name_
      currentAlignment += 8 + CDRBuffer.alignment(currentAlignment, 8); // trajectory_duration_
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // jointspace_only_
      currentAlignment += (3 * 8) + CDRBuffer.alignment(currentAlignment, (3 * 8)); // joint_angles_
      currentAlignment += chest_transform_to_parent_.calculateSizeBytes(currentAlignment);
      currentAlignment += 1 + CDRBuffer.alignment(currentAlignment, 1); // hold_pose_in_world_

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      definition_.serialize(buffer);
      buffer.writeString(parent_frame_name_);
      buffer.writeDouble(trajectory_duration_);
      buffer.writeBoolean(jointspace_only_);
      for (int i = 0; i < joint_angles_.length; ++i)
      {
         buffer.writeDouble(joint_angles_[i]);
      }
      chest_transform_to_parent_.serialize(buffer);
      buffer.writeBoolean(hold_pose_in_world_);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      definition_.deserialize(buffer);
      buffer.readString(parent_frame_name_);
      trajectory_duration_ = buffer.readDouble();
      jointspace_only_ = buffer.readBoolean();
      for (int i = 0; i < joint_angles_.length; ++i)
      {
         joint_angles_[i] = buffer.readDouble();
      }
      chest_transform_to_parent_.deserialize(buffer);
      hold_pose_in_world_ = buffer.readBoolean();

   }

   @Override
   public void set(SpineActionDefinitionMessage from)
   {
      definition_.set(from.definition_);
      parent_frame_name_.delete(0, parent_frame_name_.length());
      parent_frame_name_.insert(0, from.parent_frame_name_);
      trajectory_duration_ = from.trajectory_duration_;
      jointspace_only_ = from.jointspace_only_;
      for (int i = 0; i < joint_angles_.length; ++i)
      {
         joint_angles_[i] = from.joint_angles_[i];
      }
      chest_transform_to_parent_.set(from.chest_transform_to_parent_);
      hold_pose_in_world_ = from.hold_pose_in_world_;

   }

   public behavior_msgs.ActionNodeDefinitionMessage getDefinition()
   {
      return definition_;
   }

   public StringBuilder getParentFrameName()
   {
      return parent_frame_name_;
   }

   public java.lang.String getParentFrameNameAsString()
   {
      return parent_frame_name_.toString();
   }

   public void setParentFrameName(java.lang.String s)
   {
      this.parent_frame_name_.delete(0, this.parent_frame_name_.length());
      this.parent_frame_name_.insert(0, s);
   }
   public double getTrajectoryDuration()
   {
      return trajectory_duration_;
   }

   public void setTrajectoryDuration(double trajectory_duration_)
   {
      this.trajectory_duration_ = trajectory_duration_;
   }

   public boolean getJointspaceOnly()
   {
      return jointspace_only_;
   }

   public void setJointspaceOnly(boolean jointspace_only_)
   {
      this.jointspace_only_ = jointspace_only_;
   }

   public double[] getJointAngles()
   {
      return joint_angles_;
   }

   public controller_msgs.RigidBodyTransformMessage getChestTransformToParent()
   {
      return chest_transform_to_parent_;
   }

   public boolean getHoldPoseInWorld()
   {
      return hold_pose_in_world_;
   }

   public void setHoldPoseInWorld(boolean hold_pose_in_world_)
   {
      this.hold_pose_in_world_ = hold_pose_in_world_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("SpineActionDefinitionMessage {");
      builder.append("definition_=");
      builder.append(definition_);
      builder.append("parent_frame_name_=");
      builder.append(parent_frame_name_.toString());
      builder.append("trajectory_duration_=");
      builder.append(trajectory_duration_);
      builder.append("jointspace_only_=");
      builder.append(jointspace_only_);
      builder.append("joint_angles_=");
      builder.append(java.util.Arrays.toString(joint_angles_));
      builder.append("chest_transform_to_parent_=");
      builder.append(chest_transform_to_parent_);
      builder.append("hold_pose_in_world_=");
      builder.append(hold_pose_in_world_);

      builder.append("}");
      return builder.toString();
   }
}