/*
 * This class was automatically generated by jros2.
 * Do not modify this file directly.
 */
package behavior_msgs;

import us.ihmc.fastddsjava.cdr.CDRBuffer;
import us.ihmc.fastddsjava.cdr.idl.*;
import us.ihmc.jros2.ROS2Message;

/**
<p>Source (behavior_msgs/StatusLogMessage):
<pre>{@code
# Log level
uint16 log_level

# Log message
int8[] log_message}</pre>
*/
public class StatusLogMessage implements ROS2Message<StatusLogMessage>
{
   public static final java.lang.String name = "behavior_msgs::msg::dds_::StatusLogMessage_";

   /**
      Log level
   */
   private short log_level_;
   /**
      Log message
   */
   private final IDLByteSequence log_message_;

   public StatusLogMessage()
   {
      log_message_ = new IDLByteSequence();

   }

   @Override
   public int calculateSizeBytes(int currentAlignment)
   {
      int initialAlignment = currentAlignment;

      currentAlignment += 2 + CDRBuffer.alignment(currentAlignment, 2); // log_level_
      currentAlignment += log_message_.calculateSizeBytes(currentAlignment);

      return currentAlignment - initialAlignment;
   }

   @Override
   public void serialize(CDRBuffer buffer)
   {
      buffer.writeShort(log_level_);
      log_message_.serialize(buffer);

   }

   @Override
   public void deserialize(CDRBuffer buffer)
   {
      log_level_ = buffer.readShort();
      log_message_.deserialize(buffer);

   }

   @Override
   public void set(StatusLogMessage from)
   {
      log_level_ = from.log_level_;
      log_message_.set(from.log_message_);

   }

   public short getLogLevel()
   {
      return log_level_;
   }

   public void setLogLevel(short log_level_)
   {
      this.log_level_ = log_level_;
   }

   public IDLByteSequence getLogMessage()
   {
      return log_message_;
   }


   @Override
   public java.lang.String toString()
   {
      java.lang.StringBuilder builder = new java.lang.StringBuilder();
      builder.append("StatusLogMessage {");
      builder.append("log_level_=");
      builder.append(log_level_);
      builder.append("log_message_=");
      builder.append(log_message_);

      builder.append("}");
      return builder.toString();
   }
}