package actionlib_tutorials;

public interface AveragingAction extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib_tutorials/AveragingAction";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nAveragingActionGoal action_goal\nAveragingActionResult action_result\nAveragingActionFeedback action_feedback\n";
  actionlib_tutorials.AveragingActionGoal getActionGoal();
  void setActionGoal(actionlib_tutorials.AveragingActionGoal value);
  actionlib_tutorials.AveragingActionResult getActionResult();
  void setActionResult(actionlib_tutorials.AveragingActionResult value);
  actionlib_tutorials.AveragingActionFeedback getActionFeedback();
  void setActionFeedback(actionlib_tutorials.AveragingActionFeedback value);
}
