package actionlib_tutorials;

public interface AveragingGoal extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib_tutorials/AveragingGoal";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n#goal definition\nint32 samples\n";
  int getSamples();
  void setSamples(int value);
}
