package actionlib_tutorials;

public interface FibonacciActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "actionlib_tutorials/FibonacciActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nFibonacciFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  actionlib_tutorials.FibonacciFeedback getFeedback();
  void setFeedback(actionlib_tutorials.FibonacciFeedback value);
}
