% Produced by CVXGEN, 2013-01-17 15:52:18 +0000.
% CVXGEN is Copyright (C) 2006-2012 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2012 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
Phi = params.Phi;
epsilon_f = params.epsilon_f;
xi = params.xi;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable rho(8, 1);

  minimize(quad_form(Phi*rho - xi, eye(6)) + epsilon_f*epsilon_f*quad_form(rho, eye(8)));
  subject to
    rho >= 0;
cvx_end
vars.rho = rho;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
