module us{
module ihmc{
module robotDataLogger{
	
	struct CameraAnnouncement
	{	
		string name;
		long id;
	};
	
	struct ModelFileDescription{
		boolean hasModel;
		string name;
		string modelLoaderClass;
		sequence<string, 255> resourceDirectories;
		
		long modelFileSize;
		
		boolean hasResourceZip;
		long resourceZipSize;
	};
		
		
	struct Announcement
	{
		string identifier;
		
		octet dataIP[4];
		short dataPort;
		
		string name;
		string hostName;
		sequence<CameraAnnouncement, 127> cameras;
		ModelFileDescription modelFileDescription;
		
		boolean log;
	};
};
};
};