module us{
module ihmc{
module robotDataLogger{
	struct YoRegistryDefinition
	{
		short parent;
		string name;
	};
	
	enum YoType
	{
		DoubleYoVariable,
		BooleanYoVariable,
		IntegerYoVariable,
		LongYoVariable,
		EnumYoVariable
	};
	
	enum JointType
	{
		SiXDoFJoint,
		OneDoFJoint
	};
	
	
	struct YoVariableDefinition
	{
		string name;
		YoType type;
		short registry;
		short enumType;
		boolean allowNullValues;
	};
	
	struct JointDefinition
	{
		string name;
		JointType type;
		
	};
	
	struct AppearanceDefinitionMessage
	{
		double r;
		double g;
		double b;
		
		double transparency;
	};
	
	struct GraphicObjectMessage
	{
		short type;
		string name;
		
		sequence<short, 128> yoVariableIndex;
		sequence<double, 128> constants;
		AppearanceDefinitionMessage appearance;
		string listName;
	};
	
	struct EnumType
	{
		string name;
		sequence<string, 128> enumValues;
	};
	
	struct Handshake
	{
		double dt;
		sequence<YoRegistryDefinition, 1024> registries;
		sequence<YoVariableDefinition, 32767> variables;
		sequence<JointDefinition, 128> joints;
		sequence<GraphicObjectMessage, 2048> graphicObjects;
		sequence<GraphicObjectMessage, 2048> artifacts;
		sequence<EnumType, 1024> enumTypes;
	};

};
};
};