name: Trigger dependent CI

on:
  push:
    branches: [develop]

jobs:
  trigger:
    uses: ihmcrobotics/ihmc-actions/.github/workflows/trigger-dependents.yml@main
    secrets:
      ROSIE_PERSONAL_ACCESS_TOKEN: ${{ secrets.ROSIE_PERSONAL_ACCESS_TOKEN }}
      DEPENDENCY_GRAPH: ${{ secrets.DEPENDENCY_GRAPH }}
    with:
      source-repo: ihmc-open-robotics-software
