#ifndef __controller_msgs__msg__ArmDesiredAccelerationsMessage__idl__
#define __controller_msgs__msg__ArmDesiredAccelerationsMessage__idl__

#include "controller_msgs/msg/./DesiredAccelerationsMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * This message is part of the IHMC whole-body controller API.
       * This message gives the user the option to bypass IHMC feedback controllers for the arm joints by sending desired arm joint accelerations.
       * One needs experience in control when activating the bypass as it can result in unexpected behaviors for unreasonable accelerations.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ArmDesiredAccelerationsMessage_")
      struct ArmDesiredAccelerationsMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Specifies the side of the robot that will execute the command.
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * The desired joint acceleration information.
         */
        controller_msgs::msg::dds::DesiredAccelerationsMessage desired_accelerations;
      };
    };
  };
};

#endif
