#ifndef __controller_msgs__msg__AtlasElectricMotorAutoEnableFlagPacket__idl__
#define __controller_msgs__msg__AtlasElectricMotorAutoEnableFlagPacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Atlas specific message.
       */
      @TypeCode(type="controller_msgs::msg::dds_::AtlasElectricMotorAutoEnableFlagPacket_")
      struct AtlasElectricMotorAutoEnableFlagPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        boolean should_auto_enable;
      };
    };
  };
};

#endif
