#ifndef __controller_msgs__msg__AtlasDesiredPumpPSIPacket__idl__
#define __controller_msgs__msg__AtlasDesiredPumpPSIPacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Send a request to change the desired PSI of the Atlas hydraulic pump.
       */
      @TypeCode(type="controller_msgs::msg::dds_::AtlasDesiredPumpPSIPacket_")
      struct AtlasDesiredPumpPSIPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        /**
         * The desired hydraulic pump PSI.
         */
        long desired_pump_psi;
      };
    };
  };
};

#endif
