#ifndef __controller_msgs__msg__BehaviorControlModeResponsePacket__idl__
#define __controller_msgs__msg__BehaviorControlModeResponsePacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet STOP =
      0;

      const octet PAUSE =
      1;

      const octet RESUME =
      2;


      /**
       * This message is part of the IHMC humanoid behavior module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::BehaviorControlModeResponsePacket_")
      struct BehaviorControlModeResponsePacket
      {
        @defaultValue(value=255)
        octet behavior_control_mode_enum_request;
      };
    };
  };
};

#endif
