#ifndef __controller_msgs__msg__BehaviorControlModePacket__idl__
#define __controller_msgs__msg__BehaviorControlModePacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet STOP =
      0;

      const octet PAUSE =
      1;

      const octet RESUME =
      2;


      /**
       * This message is part of the IHMC humanoid behavior module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::BehaviorControlModePacket_")
      struct BehaviorControlModePacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        @defaultValue(value=255)
        octet behavior_control_mode_enum_request;
      };
    };
  };
};

#endif
