#ifndef __controller_msgs__msg__BodyPathPlanStatisticsMessage__idl__
#define __controller_msgs__msg__BodyPathPlanStatisticsMessage__idl__

#include "controller_msgs/msg/./VisibilityMapMessage_.idl"
#include "controller_msgs/msg/./VisibilityMapWithNavigableRegionMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      const long NO_PLAN_ID =
      -1;


      /**
       * This message is part of the IHMC footstep planning module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::BodyPathPlanStatisticsMessage_")
      struct BodyPathPlanStatisticsMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=-1)
        long plan_id;
        sequence<controller_msgs::msg::dds::VisibilityMapWithNavigableRegionMessage, 25> navigable_regions;
        controller_msgs::msg::dds::VisibilityMapMessage inter_regions_map;
        controller_msgs::msg::dds::VisibilityMapMessage start_visibility_map;
        controller_msgs::msg::dds::VisibilityMapMessage goal_visibility_map;
      };
    };
  };
};

#endif
