#ifndef __controller_msgs__msg__BoundingBoxesPacket__idl__
#define __controller_msgs__msg__BoundingBoxesPacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::BoundingBoxesPacket_")
      struct BoundingBoxesPacket
      {
        sequence<long> bounding_boxes_x_coordinates;
        sequence<long> bounding_boxes_y_coordinates;
        sequence<long> bounding_boxes_widths;
        sequence<long> bounding_boxes_heights;
        sequence<string> labels;
      };
    };
  };
};

#endif
