#ifndef __controller_msgs__msg__BoundingBox3DMessage__idl__
#define __controller_msgs__msg__BoundingBox3DMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::BoundingBox3DMessage_")
      struct BoundingBox3DMessage
      {
        geometry_msgs::msg::dds::Point min_point;
        geometry_msgs::msg::dds::Point max_point;
      };
    };
  };
};

#endif
