#ifndef __controller_msgs__msg__ComPositionPacket__idl__
#define __controller_msgs__msg__ComPositionPacket__idl__

#include "geometry_msgs/msg/./Point_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC quadruped controller API.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ComPositionPacket_")
      struct ComPositionPacket
      {
        geometry_msgs::msg::dds::Point position;
      };
    };
  };
};

#endif
