#ifndef __controller_msgs__msg__ControllerReleaseGoalMessage__idl__
#define __controller_msgs__msg__ControllerReleaseGoalMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Input message for the PDVelocityBasedGoalReacher.
       * This tells the goal reacher to stop trying to walk to a goal.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ControllerReleaseGoalMessage_")
      struct ControllerReleaseGoalMessage
      {
        boolean release_goal;
      };
    };
  };
};

#endif
