#ifndef __controller_msgs__msg__ControllerWaypointStatusMessage__idl__
#define __controller_msgs__msg__ControllerWaypointStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Published by the PDVelocityBasedGoalReacher when it begins walking toward a waypoint
       * or when it reaches a waypoint.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ControllerWaypointStatusMessage_")
      struct ControllerWaypointStatusMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long long sequence_id;
        /**
         * The waypoint goal pose associated with this event.
         */
        double goal_x_position;
        double goal_y_position;
        double goal_yaw;
        /**
         * Number of waypoints remaining in the queue after this event (not counting the waypoint
         * described by this message).
         */
        long waypoints_remaining;
        /**
         * True if the robot just started walking toward this waypoint.
         * False if the robot just reached this waypoint.
         */
        boolean is_started;
      };
    };
  };
};

#endif
