#ifndef __controller_msgs__msg__ControllerWalkToGoalStatusMessage__idl__
#define __controller_msgs__msg__ControllerWalkToGoalStatusMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Status message for the PDVelocityBasedGoalReacher.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ControllerWalkToGoalStatusMessage_")
      struct ControllerWalkToGoalStatusMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long long sequence_id;
        /**
         * Current pose for the robot to reach.
         */
        double current_goal_x_position;
        double current_goal_y_position;
        double current_goal_yaw;
        geometry_msgs::msg::dds::Point current_position;
        boolean is_reached;
      };
    };
  };
};

#endif
