#ifndef __controller_msgs__msg__ContinuousStepGeneratorStatusMessage__idl__
#define __controller_msgs__msg__ContinuousStepGeneratorStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Current status of various CSG parameters
       */
      @TypeCode(type="controller_msgs::msg::dds_::ContinuousStepGeneratorStatusMessage_")
      struct ContinuousStepGeneratorStatusMessage
      {
        boolean is_walking;
        boolean are_velocities_normalized;
        double current_forward_velocity;
        double current_lateral_velocity;
        double current_turn_velocity;
        double current_swing_height;
        double current_swing_duration;
        double current_transfer_duration;
        double current_max_step_length_forwards;
        double current_max_step_length_backwards;
        double current_max_step_width;
        double current_min_step_width;
        double current_default_step_width;
        double current_turn_max_angle_inward;
        double current_turn_max_angle_outward;
        boolean are_steps_adjustable;
        boolean snapping_to_heightmap;
        boolean accounting_for_ground_drift;
      };
    };
  };
};

#endif
