#ifndef __controller_msgs__msg__DesiredWalkingSpeedPacket__idl__
#define __controller_msgs__msg__DesiredWalkingSpeedPacket__idl__

#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC fast walking controller API.
       * This message sets the desired walking and turning speed.
       * This message may initiate or stop walking.
       */
      @TypeCode(type="controller_msgs::msg::dds_::DesiredWalkingSpeedPacket_")
      struct DesiredWalkingSpeedPacket
      {
        /**
         * Define the desired 3D linear velocity to be reached.
         */
        geometry_msgs::msg::dds::Vector3 desired_speed;
        /**
         * Define the desired turning velocity
         */
        double turning_speed;
      };
    };
  };
};

#endif
