#ifndef __controller_msgs__msg__DetectedFacesPacket__idl__
#define __controller_msgs__msg__DetectedFacesPacket__idl__

#include "geometry_msgs/msg/./Point_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::DetectedFacesPacket_")
      struct DetectedFacesPacket
      {
        sequence<string> ids;
        sequence<geometry_msgs::msg::dds::Point> positions;
      };
    };
  };
};

#endif
