#ifndef __controller_msgs__msg__EnableHPUCommandMessage__idl__
#define __controller_msgs__msg__EnableHPUCommandMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::EnableHPUCommandMessage_")
      struct EnableHPUCommandMessage
      {
        /**
         * True to enable hydaulic power unit (HPU) and false to turn HPU off immediately (not graceful)
         */
        boolean enable_hpu;
      };
    };
  };
};

#endif
