#ifndef __controller_msgs__msg__EnableHPUStatusMessage__idl__
#define __controller_msgs__msg__EnableHPUStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::EnableHPUStatusMessage_")
      struct EnableHPUStatusMessage
      {
        /**
         * True if hydaulic power unit (HPU) is enabled and false if it is turned off
         */
        boolean hpu_enabled;
      };
    };
  };
};

#endif
