#ifndef __controller_msgs__msg__EStopMasterGainStatusMessage__idl__
#define __controller_msgs__msg__EStopMasterGainStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A message for allowing operator to observe the status of various startup/shutdown variables often required for robot operation
       */
      @TypeCode(type="controller_msgs::msg::dds_::EStopMasterGainStatusMessage_")
      struct EStopMasterGainStatusMessage
      {
        /**
         * Current SOFT-E-STOP value
         */
        boolean is_estopped;
        /**
         * Is robot faulted
         */
        boolean robot_is_faulted;
        /**
         * Is robot servod
         */
        boolean robot_is_servod;
        /**
         * Is robot calibrated
         */
        boolean robot_is_calibrated;
        /**
         * Is publishing ROS commands to robot enabled
         */
        boolean publishing_to_robot_is_enabled;
        /**
         * Are the actuators enabled
         */
        boolean actuators_are_enabled;
        /**
         * The current master gain
         */
        double current_master_gain;
      };
    };
  };
};

#endif
