#ifndef __controller_msgs__msg__EStopMasterGainCommandMessage__idl__
#define __controller_msgs__msg__EStopMasterGainCommandMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * A message for sending necessary startup, shutdown, and high-level operational command variables to the robot
       */
      @TypeCode(type="controller_msgs::msg::dds_::EStopMasterGainCommandMessage_")
      struct EStopMasterGainCommandMessage
      {
        /**
         * Auto startup and shutdown
         */
        boolean request_startup;
        boolean request_shutdown;
        boolean execute_startup_shutdown;
        /**
         * SOFT-E-STOP to set
         */
        boolean estop;
        boolean execute_estop;
        /**
         * AvatarLowLevelOutputProcessor masterGain variable to set
         */
        double desired_master_gain;
        boolean execute_master_gain;
        /**
         * True if this is a request to servo the robot
         * This is used to enable and ramp up/down the robot's controller gains, to go into freeze or stand prep
         */
        boolean servo_robot;
        boolean execute_servo_robot;
        /**
         * True if this is a request to immediately zero the gains which can be violent and dangerous
         */
        boolean unservo_quickly;
        boolean execute_unservo_quickly;
        /**
         * Enable publishing of ROS commands to the robot
         */
        boolean enable_publishing_to_robot;
        boolean execute_enable_publishing_to_robot;
        /**
         * Clear robot faults
         */
        boolean clear_faults;
        boolean execute_clear_faults;
        /**
         * Calibrate robot
         */
        boolean calibrate_robot;
        boolean execute_calibrate_robot;
        /**
         * Enable all actuators
         */
        boolean enable_actuators;
        boolean execute_enable_actuators;
      };
    };
  };
};

#endif
