#ifndef __controller_msgs__msg__EtherSnacksSakeHandCommandMessage__idl__
#define __controller_msgs__msg__EtherSnacksSakeHandCommandMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      @TypeCode(type="controller_msgs::msg::dds_::EtherSnacksSakeHandCommandMessage_")
      struct EtherSnacksSakeHandCommandMessage
      {
        @defaultValue(value=255)
        octet robot_side;
        double desired_position;
        double torque_limit;
        boolean torque_on;
      };
    };
  };
};

#endif
