#ifndef __controller_msgs__msg__ExoskeletonBehaviorStatePacket__idl__
#define __controller_msgs__msg__ExoskeletonBehaviorStatePacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is used to switch the control scheme between force and position control.
       * WARNING: When in position control, the IHMC balance algorithms will be disabled and it is up to the user to ensure stability.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ExoskeletonBehaviorStatePacket_")
      struct ExoskeletonBehaviorStatePacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        octet exoskeleton_behavior_state;
      };
    };
  };
};

#endif
