#ifndef __controller_msgs__msg__ExoskeletonBehaviorStatePacket__idl__
#define __controller_msgs__msg__ExoskeletonBehaviorStatePacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::ExoskeletonBehaviorStatePacket_")
      struct ExoskeletonBehaviorStatePacket
      {
        octet exoskeleton_behavior_state;
      };
    };
  };
};

#endif
