#ifndef __controller_msgs__msg__ExternalForceEstimationOutputStatus__idl__
#define __controller_msgs__msg__ExternalForceEstimationOutputStatus__idl__

#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC external force estimation module.
       * It provides the result from the estimator
       */
      @TypeCode(type="controller_msgs::msg::dds_::ExternalForceEstimationOutputStatus_")
      struct ExternalForceEstimationOutputStatus
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Estimated external force in world frame
         */
        sequence<geometry_msgs::msg::dds::Vector3, 10> estimated_external_forces;
      };
    };
  };
};

#endif
