#ifndef __controller_msgs__msg__FlatGroundPlanarRegionParametersMessage__idl__
#define __controller_msgs__msg__FlatGroundPlanarRegionParametersMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message sets the parameters of the FlatGroundPlanarRegionPublisher
       */
      @TypeCode(type="controller_msgs::msg::dds_::FlatGroundPlanarRegionParametersMessage_")
      struct FlatGroundPlanarRegionParametersMessage
      {
        /**
         * Enables/Disables the FlatGroundPlanarRegionPublisher module
         */
        boolean enable;
      };
    };
  };
};

#endif
