#ifndef __controller_msgs__msg__FootstepPlannerLatticeMapMessage__idl__
#define __controller_msgs__msg__FootstepPlannerLatticeMapMessage__idl__

#include "controller_msgs/msg/./FootstepPlannerLatticeNodeMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC footstep planning module.
       * This message is sent from the planner in order to visualize and debug planner progress
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepPlannerLatticeMapMessage_")
      struct FootstepPlannerLatticeMapMessage
      {
        /**
         * This is the ID of the planning request which this message corresponds to
         */
        unsigned long plan_id;
        /**
         * List of cells that the planner has explored
         */
        sequence<controller_msgs::msg::dds::FootstepPlannerLatticeNodeMessage, 10000> lattice_nodes;
      };
    };
  };
};

#endif
