#ifndef __controller_msgs__msg__FootstepPlannerLatticeNodeMessage__idl__
#define __controller_msgs__msg__FootstepPlannerLatticeNodeMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * This message is part of the IHMC footstep planning module.
       * This message is sent from the planner in order to visualize and debug planner progress
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepPlannerLatticeNodeMessage_")
      struct FootstepPlannerLatticeNodeMessage
      {
        /**
         * X index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.FootstepNode for more information
         */
        long x_index;
        /**
         * Y index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.FootstepNode for more information
         */
        long y_index;
        /**
         * Yaw index of the cell
         */
        long yaw_index;
        /**
         * Robot side of the cell
         */
        octet robot_side;
        long node_index;
      };
    };
  };
};

#endif
