#ifndef __controller_msgs__msg__FootstepPlannerCellMessage__idl__
#define __controller_msgs__msg__FootstepPlannerCellMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC footstep planning module.
       * This message is sent from the planner in order to visualize and debug planner progress
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepPlannerCellMessage_")
      struct FootstepPlannerCellMessage
      {
        /**
         * X index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.DiscreteFootstep for more information
         */
        long x_index;
        /**
         * Y index of the cell. See us.ihmc.footstepPlanning.graphSearch.graph.DiscreteFootstep for more information
         */
        long y_index;
      };
    };
  };
};

#endif
