#ifndef __controller_msgs__msg__FootstepNodeDataMessage__idl__
#define __controller_msgs__msg__FootstepNodeDataMessage__idl__

#include "controller_msgs/msg/./FootstepPlannerLatticeNodeMessage_.idl"
#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Quaternion_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      /**
       * Node rejection reasons. See BipedalFootstepPlannerNodeRejectionReason
       */
      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_HIGH_OR_LOW =
      0;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_LOW_AND_FORWARD_WHEN_PITCHED =
      1;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_FORWARD_AND_DOWN =
      2;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_WIDE_AND_DOWN =
      3;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_FAR =
      4;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_FAR_AND_HIGH =
      5;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_WIDE_AND_HIGH =
      6;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_NOT_WIDE_ENOUGH =
      7;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_IN_PLACE =
      8;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_NOT_ENOUGH_AREA =
      9;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_COULD_NOT_SNAP =
      10;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_SURFACE_NORMAL_TOO_STEEP_TO_SNAP =
      11;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_TOO_MUCH_PENETRATION_AFTER_WIGGLE =
      12;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_NOT_LONG_ENOUGH =
      13;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_TOO_WIDE =
      14;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_OBSTACLE_BLOCKING_BODY =
      15;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_OBSTACLE_HITTING_BODY =
      16;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_AT_CLIFF_BOTTOM =
      17;

      const octet BIPEDAL_FOOTSTEP_PLANNER_NODE_REJECTION_REASON_STEP_YAWS_TOO_MUCH =
      18;


      /**
       * This message is part of the IHMC footstep planning module.
       * This message is sent from the planner in order to visualize and debug planner progress
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepNodeDataMessage_")
      struct FootstepNodeDataMessage
      {
        /**
         * Specifies snap transform translation. NaN if snap was unsuccessful
         */
        geometry_msgs::msg::dds::Point position;
        /**
         * Specifies the snap rotation. NaN if snap unsuccessful.
         */
        geometry_msgs::msg::dds::Quaternion orientation;
        /**
         * ID of parent node. This should reference the index of this node in a FootstepNodeDataList
         */
        @defaultValue(value=-1)
        long parent_node_id;
        controller_msgs::msg::dds::FootstepPlannerLatticeNodeMessage footstep_node;
        /**
         * Node rejection reason. 255 if node was accepted
         */
        @defaultValue(value=255)
        octet bipedal_footstep_planner_node_rejection_reason;
      };
    };
  };
};

#endif
