#ifndef __controller_msgs__msg__FootstepPlannerOccupancyMapMessage__idl__
#define __controller_msgs__msg__FootstepPlannerOccupancyMapMessage__idl__

#include "controller_msgs/msg/./FootstepPlannerCellMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC footstep planning module.
       * This message is sent from the planner in order to visualize and debug planner progress
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepPlannerOccupancyMapMessage_")
      struct FootstepPlannerOccupancyMapMessage
      {
        /**
         * This is the ID of the planning request which this message corresponds to
         */
        unsigned long sequence_id;
        /**
         * List of cells that the planner has explored
         */
        sequence<controller_msgs::msg::dds::FootstepPlannerCellMessage, 10000> occupied_cells;
      };
    };
  };
};

#endif
