#ifndef __controller_msgs__msg__FootstepNodeDataListMessage__idl__
#define __controller_msgs__msg__FootstepNodeDataListMessage__idl__

#include "controller_msgs/msg/./FootstepNodeDataMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC footstep planning module.
       * This message is sent from the planner in order to visualize and debug planner progress
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepNodeDataListMessage_")
      struct FootstepNodeDataListMessage
      {
        /**
         * This is the ID of the planning request which this message corresponds to
         */
        unsigned long sequence_id;
        /**
         * List of all footstep node data. Index 0 should hold the start node
         */
        sequence<controller_msgs::msg::dds::FootstepNodeDataMessage> node_data;
      };
    };
  };
};

#endif
