#ifndef __controller_msgs__msg__FootstepPlanRequestPacket__idl__
#define __controller_msgs__msg__FootstepPlanRequestPacket__idl__

#include "controller_msgs/msg/./FootstepDataMessage_.idl"
#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet FOOTSTEP_PLAN_REQUEST_TYPE_START_SEARCH =
      0;

      const octet FOOTSTEP_PLAN_REQUEST_TYPE_STOP_SEARCH =
      1;

      const octet FOOTSTEP_PLAN_REQUEST_TYPE_UPDATE_START =
      2;


      /**
       * (Obsolete) This message is part of the old IHMC footstep planning module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepPlanRequestPacket_")
      struct FootstepPlanRequestPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        controller_msgs::msg::dds::FootstepDataMessage start_footstep;
        double theta_start;
        @defaultValue(value=1.0)
        double max_sub_optimality;
        sequence<controller_msgs::msg::dds::FootstepDataMessage> goals;
        @defaultValue(value=255)
        octet footstep_plan_request_type;
      };
    };
  };
};

#endif
