#ifndef __controller_msgs__msg__FootstepPathPlanPacket__idl__
#define __controller_msgs__msg__FootstepPathPlanPacket__idl__

#include "controller_msgs/msg/./FootstepDataMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * (Obsolete) This message is part of the old IHMC footstep planning module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::FootstepPathPlanPacket_")
      struct FootstepPathPlanPacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        boolean goals_valid;
        controller_msgs::msg::dds::FootstepDataMessage start;
        sequence<controller_msgs::msg::dds::FootstepDataMessage> original_goals;
        sequence<controller_msgs::msg::dds::FootstepDataMessage> path_plan;
        sequence<boolean> footstep_unknown;
        double sub_optimality;
        @defaultValue(value=inf)
        double path_cost;
      };
    };
  };
};

#endif
