#ifndef __controller_msgs__msg__FusedSensorHeadPointCloudMessage__idl__
#define __controller_msgs__msg__FusedSensorHeadPointCloudMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::FusedSensorHeadPointCloudMessage_")
      struct FusedSensorHeadPointCloudMessage
      {
        /**
         * Which segment
         */
        unsigned long segment_index;
        /**
         * Compressed point cloud data
         * Sized specifically for our current primary sensor head streaming
         * 22220 * 4 * 4
         */
        sequence<octet, 355520> scan;
      };
    };
  };
};

#endif
