#ifndef __controller_msgs__msg__HandJointAnglePacket__idl__
#define __controller_msgs__msg__HandJointAnglePacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * Message used to report the current joint angles for the fingers of a hand.
       */
      @TypeCode(type="controller_msgs::msg::dds_::HandJointAnglePacket_")
      struct HandJointAnglePacket
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=255)
        octet robot_side;
        sequence<double> joint_angles;
        boolean connected;
        boolean calibrated;
      };
    };
  };
};

#endif
