#ifndef __controller_msgs__msg__HandContactListMessage__idl__
#define __controller_msgs__msg__HandContactListMessage__idl__

#include "controller_msgs/msg/./HandContactMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::HandContactListMessage_")
      struct HandContactListMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Defines the list of footstep to perform.
         */
        sequence<controller_msgs::msg::dds::HandContactMessage, 2> hand_contact_list;
      };
    };
  };
};

#endif
