#ifndef __controller_msgs__msg__HeatMapPacket__idl__
#define __controller_msgs__msg__HeatMapPacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::HeatMapPacket_")
      struct HeatMapPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        sequence<float> data;
        long width;
        long height;
        string name;
      };
    };
  };
};

#endif
