#ifndef __controller_msgs__msg__HeightQuadTreeLeafMessage__idl__
#define __controller_msgs__msg__HeightQuadTreeLeafMessage__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height quad tree module
       */
      @TypeCode(type="controller_msgs::msg::dds_::HeightQuadTreeLeafMessage_")
      struct HeightQuadTreeLeafMessage
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        float center_x;
        float center_y;
        float height;
      };
    };
  };
};

#endif
