#ifndef __controller_msgs__msg__HeightQuadTreeToolboxRequestMessage__idl__
#define __controller_msgs__msg__HeightQuadTreeToolboxRequestMessage__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height quad tree module
       */
      @TypeCode(type="controller_msgs::msg::dds_::HeightQuadTreeToolboxRequestMessage_")
      struct HeightQuadTreeToolboxRequestMessage
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        boolean request_clear_quad_tree;
        boolean request_quad_tree_update;
      };
    };
  };
};

#endif
