#ifndef __controller_msgs__msg__HeightMapMessage__idl__
#define __controller_msgs__msg__HeightMapMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height map module
       */
      @TypeCode(type="controller_msgs::msg::dds_::HeightMapMessage_")
      struct HeightMapMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=-1.0)
        double xy_resolution;
        @defaultValue(value=-1.0)
        double grid_size_xy;
        sequence<long, 30000> x_cells;
        sequence<long, 30000> y_cells;
        sequence<float, 30000> heights;
      };
    };
  };
};

#endif
