#ifndef __controller_msgs__msg__HeightQuadTreeLeafMessage__idl__
#define __controller_msgs__msg__HeightQuadTreeLeafMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height quad tree module
       */
      @TypeCode(type="controller_msgs::msg::dds_::HeightQuadTreeLeafMessage_")
      struct HeightQuadTreeLeafMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        float center_x;
        float center_y;
        float height;
      };
    };
  };
};

#endif
