#ifndef __controller_msgs__msg__HeightQuadTreeToolboxRequestMessage__idl__
#define __controller_msgs__msg__HeightQuadTreeToolboxRequestMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC height quad tree module
       */
      @TypeCode(type="controller_msgs::msg::dds_::HeightQuadTreeToolboxRequestMessage_")
      struct HeightQuadTreeToolboxRequestMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        boolean request_clear_quad_tree;
        boolean request_quad_tree_update;
      };
    };
  };
};

#endif
