#ifndef __controller_msgs__msg__ImageMessage__idl__
#define __controller_msgs__msg__ImageMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::ImageMessage_")
      struct ImageMessage
      {
        /**
         * This message can be used as a general image.
         * Each component of the data which of length is same with width * height is an integer value describing color with the conventional RGB.
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        long width;
        long height;
        sequence<long> rgbdata;
      };
    };
  };
};

#endif
