#ifndef __controller_msgs__msg__JointOfflineMessage__idl__
#define __controller_msgs__msg__JointOfflineMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       * This message notifies the controller of a joint going offline, which causes the controller to go into an emergency fall-prevention mode.
       */
      @TypeCode(type="controller_msgs::msg::dds_::JointOfflineMessage_")
      struct JointOfflineMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Hash-code of the joints which are offline. Joints that are currently offline and not included in this list are re-enabled.
         * The hash-code is computed from OneDoFJoint#hashcode().
         */
        sequence<long, 6> joint_offline_hash_codes;
        /**
         * Nominal left foot contact points (in sole frame) given the set of offline joints
         */
        sequence<geometry_msgs::msg::dds::Point, 4> nominal_left_foot_contact_points_2d;
        /**
         * Nominal right foot contact points (in sole frame) given the set of offline joints
         */
        sequence<geometry_msgs::msg::dds::Point, 4> nominal_right_foot_contact_points_2d;
        /**
         * The time to delay this command on the controller side before being executed.
         */
        double execution_delay_time;
      };
    };
  };
};

#endif
