#ifndef __controller_msgs__msg__KinematicsPlanningToolboxOutputStatus__idl__
#define __controller_msgs__msg__KinematicsPlanningToolboxOutputStatus__idl__

#include "controller_msgs/msg/./KinematicsToolboxOutputStatus_.idl"
#include "controller_msgs/msg/./WholeBodyTrajectoryMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet KINEMATICS_PLANNING_RESULT_OPTIMAL_SOLUTION =
      0;

      const octet KINEMATICS_PLANNING_RESULT_EXCEED_JOINT_VELOCITY_LIMIT =
      1;

      const octet KINEMATICS_PLANNING_RESULT_UNREACHABLE_KEYFRAME =
      2;


      @TypeCode(type="controller_msgs::msg::dds_::KinematicsPlanningToolboxOutputStatus_")
      struct KinematicsPlanningToolboxOutputStatus
      {
        /**
         * This message is part of the IHMC whole-body inverse kinematics module.
         * This output status will be converted into the WholeBodyTrajectoryMessage.
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        @defaultValue(value=-1)
        long plan_id;
        /**
         * List of times for each key frames.
         * The length of this should be same with the length of the configurations.
         */
        sequence<double> key_frame_times;
        /**
         * List of configurations for each key frames.
         */
        sequence<controller_msgs::msg::dds::KinematicsToolboxOutputStatus> robot_configurations;
        /**
         * Solution quality.
         * The total summation of the all solution quality for each key frames.
         */
        @defaultValue(value=-1.0)
        double solution_quality;
        /**
         * Suggested message to send to the IHMC walking controller to request the robot to go through the key frames.
         */
        controller_msgs::msg::dds::WholeBodyTrajectoryMessage suggested_controller_message;
      };
    };
  };
};

#endif
