#ifndef __controller_msgs__msg__LidarScanParametersMessage__idl__
#define __controller_msgs__msg__LidarScanParametersMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Message used for simulated LIDAR
       */
      @TypeCode(type="controller_msgs::msg::dds_::LidarScanParametersMessage_")
      struct LidarScanParametersMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        long long timestamp;
        float sweep_yaw_max;
        float sweep_yaw_min;
        float height_pitch_max;
        float height_pitch_min;
        float time_increment;
        float scan_time;
        float min_range;
        float max_range;
        long points_per_sweep;
        long scan_height;
      };
    };
  };
};

#endif
