#ifndef __controller_msgs__msg__LocalizationPacket__idl__
#define __controller_msgs__msg__LocalizationPacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Message part of the localization module
       */
      @TypeCode(type="controller_msgs::msg::dds_::LocalizationPacket_")
      struct LocalizationPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        boolean reset;
        boolean toggle;
      };
    };
  };
};

#endif
