#ifndef __controller_msgs__msg__ManipulationAbortedStatus__idl__
#define __controller_msgs__msg__ManipulationAbortedStatus__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       * This message is sent by the controller to notify the user that the current manipulation task has been aborted.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ManipulationAbortedStatus_")
      struct ManipulationAbortedStatus
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
      };
    };
  };
};

#endif
