#ifndef __controller_msgs__msg__MasterGainScaleControllerStatusMessage__idl__
#define __controller_msgs__msg__MasterGainScaleControllerStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::MasterGainScaleControllerStatusMessage_")
      struct MasterGainScaleControllerStatusMessage
      {
        /**
         * Whether the robot's gains are currently active in holding the controller's desireds
         */
        boolean is_robot_servoed;
      };
    };
  };
};

#endif
