#ifndef __controller_msgs__msg__MasterGainScaleControllerCommandMessage__idl__
#define __controller_msgs__msg__MasterGainScaleControllerCommandMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::MasterGainScaleControllerCommandMessage_")
      struct MasterGainScaleControllerCommandMessage
      {
        /**
         * True if this is a request to servo the robot
         * This is used to enable and ramp up the robot's controller gains, to go into freeze or stand prep
         */
        boolean servo_robot;
        /**
         * True is this is a request to immediately zero the gains which can be violent and dangerous
         * This will also turn off the HPU
         */
        boolean unservo_immediately;
        /**
         * True if this is a request to slowly ramp down the robot's controller gains to zero, in prepration for robot shutdown
         * This will also turn off the HPU at the end
         */
        boolean unservo_slowly;
      };
    };
  };
};

#endif
