#ifndef __controller_msgs__msg__MultiContactBalanceStatus__idl__
#define __controller_msgs__msg__MultiContactBalanceStatus__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC multi-contact controller API.
       * Published by the IHMC controller, this message carries minimal information relative
       * to the balance status of the robot.
       * All the information here is expressed in the world frame.
       */
      @TypeCode(type="controller_msgs::msg::dds_::MultiContactBalanceStatus_")
      struct MultiContactBalanceStatus
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * This is the measured position in world of the robot's capture point. Only x and y coordinates are relevant.
         */
        geometry_msgs::msg::dds::Point capture_point_2d;
        /**
         * This is the measured position in world of the robot's center of mass.
         */
        geometry_msgs::msg::dds::Point center_of_mass_3d;
        /**
         * List of contact points in world-frame.
         */
        sequence<geometry_msgs::msg::dds::Point, 16> contact_points_in_world;
        /**
         * (Optional) List of the contact surface normals in world frame. If provided these are used to solve generalized support region.
         */
        sequence<geometry_msgs::msg::dds::Vector3, 16> surface_normals_in_world;
        /**
         * List of the rigid-bodies in contact. This list's size and ordering corresponds to contact_point_in_world and surface_normals_in_world.
         */
        sequence<long, 16> support_rigid_body_ids;
      };
    };
  };
};

#endif
