#ifndef __controller_msgs__msg__MultisenseParameterPacket__idl__
#define __controller_msgs__msg__MultisenseParameterPacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::MultisenseParameterPacket_")
      struct MultisenseParameterPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        boolean initialize;
        double gain;
        double motor_speed;
        boolean led_enable;
        boolean flash_enable;
        double duty_cycle;
        boolean auto_exposure;
        boolean auto_white_balance;
      };
    };
  };
};

#endif
