#ifndef __controller_msgs__msg__ObjectCarryMessage__idl__
#define __controller_msgs__msg__ObjectCarryMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::ObjectCarryMessage_")
      struct ObjectCarryMessage
      {
        boolean pickup_object;
      };
    };
  };
};

#endif
