#ifndef __controller_msgs__msg__ObjectCarryMessage__idl__
#define __controller_msgs__msg__ObjectCarryMessage__idl__

#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      @TypeCode(type="controller_msgs::msg::dds_::ObjectCarryMessage_")
      struct ObjectCarryMessage
      {
        /**
         * Specifies the side of the robot carrying the object
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * If true, will increase mass in the hand
         */
        boolean is_picking_up;
        /**
         * Mass of the object being picked up
         */
        double object_mass;
        /**
         * World-frame offset from hand control frame to bag com
         */
        geometry_msgs::msg::dds::Vector3 hand_to_bag_com_offset;
      };
    };
  };
};

#endif
