#ifndef __controller_msgs__msg__PIDGainsMessage__idl__
#define __controller_msgs__msg__PIDGainsMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * this represents the gains for a PID controller
       */
      @TypeCode(type="controller_msgs::msg::dds_::PIDGainsMessage_")
      struct PIDGainsMessage
      {
        double kp;
        double kd;
        double ki;
        double zeta;
      };
    };
  };
};

#endif
