#ifndef __controller_msgs__msg__PilotInterfacePacket__idl__
#define __controller_msgs__msg__PilotInterfacePacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::PilotInterfacePacket_")
      struct PilotInterfacePacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        long behaviour_state;
        long requested_behavior_state;
        long desired_step_type;
        long desired_step_length_type;
        long desired_step_stairs_type;
        boolean desired_step_continous_walk;
        long desired_steps_to_take;
        boolean execute_behavior;
        long desired_slope_step_type;
        long current_pilot_state;
      };
    };
  };
};

#endif
