#ifndef __controller_msgs__msg__PilotAlarmPacket__idl__
#define __controller_msgs__msg__PilotAlarmPacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::PilotAlarmPacket_")
      struct PilotAlarmPacket
      {
        double beep_rate;
        double enable_tone;
      };
    };
  };
};

#endif
