#ifndef __controller_msgs__msg__PlanarVelocityPacket__idl__
#define __controller_msgs__msg__PlanarVelocityPacket__idl__

#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC quadruped controller API.
       */
      @TypeCode(type="controller_msgs::msg::dds_::PlanarVelocityPacket_")
      struct PlanarVelocityPacket
      {
        geometry_msgs::msg::dds::Vector3 velocity;
      };
    };
  };
};

#endif
