#ifndef __controller_msgs__msg__PointCloudWorldPacket__idl__
#define __controller_msgs__msg__PointCloudWorldPacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is obsolete
       */
      @TypeCode(type="controller_msgs::msg::dds_::PointCloudWorldPacket_")
      struct PointCloudWorldPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        long long timestamp;
        sequence<float> ground_quad_tree_support;
        sequence<float> decaying_world_scan;
        float default_ground_height;
      };
    };
  };
};

#endif
