#ifndef __controller_msgs__msg__QuadrupedSteppingStateChangeMessage__idl__
#define __controller_msgs__msg__QuadrupedSteppingStateChangeMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet STAND =
      0;

      const octet STEP =
      1;

      const octet SOLE_WAYPOINT =
      2;


      /**
       * This message is part of the IHMC quadruped controller API.
       * This message notifies the user of a change in the stepping controller state.
       * This message's primary use is to signal a requested state change is completed.
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuadrupedSteppingStateChangeMessage_")
      struct QuadrupedSteppingStateChangeMessage
      {
        /**
         * Specifies the controller's state prior to transition.
         */
        @defaultValue(value=255)
        octet initial_quadruped_stepping_state_enum;
        /**
         * Specifies the state the controller has transitioned into.
         */
        @defaultValue(value=255)
        octet end_quadruped_stepping_state_enum;
      };
    };
  };
};

#endif
