#ifndef __controller_msgs__msg__QuadrupedGroundPlaneMessage__idl__
#define __controller_msgs__msg__QuadrupedGroundPlaneMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC quadruped controller API.
       * This message contains the controller's estimate of the ground plane.
       * It is defined by an origin and a normal
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuadrupedGroundPlaneMessage_")
      struct QuadrupedGroundPlaneMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        geometry_msgs::msg::dds::Point region_origin;
        geometry_msgs::msg::dds::Vector3 region_normal;
      };
    };
  };
};

#endif
