#ifndef __controller_msgs__msg__QuadrupedTeleopDesiredPose__idl__
#define __controller_msgs__msg__QuadrupedTeleopDesiredPose__idl__

#include "geometry_msgs/msg/./Pose_.idl"
module __controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC quadruped controller API.
       * This message sends a desired body pose to the body teleop module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuadrupedTeleopDesiredPose_")
      struct QuadrupedTeleopDesiredPose
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        geometry_msgs::msg::dds::Pose pose;
        double pose_shift_time;
      };
    };
  };
};

#endif