#ifndef __controller_msgs__msg__QuadrupedSupportPlanarRegionParametersMessage__idl__
#define __controller_msgs__msg__QuadrupedSupportPlanarRegionParametersMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message sets the parameters of the BipedalSupportPlanarRegionPublisher
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuadrupedSupportPlanarRegionParametersMessage_")
      struct QuadrupedSupportPlanarRegionParametersMessage
      {
        /**
         * Enables the QuadrupedSupportPlanarRegionPublish module
         */
        boolean enable;
        /**
         * The support planar region is set to be a square at each of the feet.
         * This value specifies the half length of the side of teh square.
         */
        @defaultValue(value=1.0)
        double support_region_size;
      };
    };
  };
};

#endif
