#ifndef __controller_msgs__msg__QuixSideStepSwingOutMessage__idl__
#define __controller_msgs__msg__QuixSideStepSwingOutMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuixSideStepSwingOutMessage_")
      struct QuixSideStepSwingOutMessage
      {
        boolean side_step_in_swing_out;
      };
    };
  };
};

#endif
