#ifndef __controller_msgs__msg__QuixCrutchMessage__idl__
#define __controller_msgs__msg__QuixCrutchMessage__idl__

#include "controller_msgs/msg/./FlatStepTypeMessage_.idl"
#include "controller_msgs/msg/./QuixMotionStateMessage_.idl"
#include "controller_msgs/msg/./QuixSideStepDirectionMessage_.idl"
#include "controller_msgs/msg/./QuixSlopeStepTypeMessage_.idl"
#include "controller_msgs/msg/./QuixStairsStepTypeMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the Quix controller API.
       * This message is used to allow the crutch to communicate a desired change in behavior.
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuixCrutchMessage_")
      struct QuixCrutchMessage
      {
        unsigned long sequence_id;
        boolean user_enable;
        boolean rewiggle;
        boolean start_behavior;
        controller_msgs::msg::dds::QuixMotionStateMessage requested_motion_state;
        boolean execute_behavior;
        boolean continuous_walking;
        controller_msgs::msg::dds::FlatStepTypeMessage flat_step_type;
        controller_msgs::msg::dds::QuixStairsStepTypeMessage stairs_step_type;
        controller_msgs::msg::dds::QuixSideStepDirectionMessage side_step_direction;
        controller_msgs::msg::dds::QuixSlopeStepTypeMessage slope_step_type;
        @defaultValue(value=255)
        octet force_swing_side;
      };
    };
  };
};

#endif
