#ifndef __controller_msgs__msg__QuixSideStepDirectionMessage__idl__
#define __controller_msgs__msg__QuixSideStepDirectionMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * This message is part of the Quix controller API.
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuixSideStepDirectionMessage_")
      struct QuixSideStepDirectionMessage
      {
        @defaultValue(value=255)
        octet step_direction;
      };
    };
  };
};

#endif
