#ifndef __controller_msgs__msg__QuixUrgentUserInfoMessage__idl__
#define __controller_msgs__msg__QuixUrgentUserInfoMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet EMPTY =
      0;

      const octet ESTOP_PRESSED =
      1;

      const octet MOTOR_OVER_TEMP =
      2;

      const octet LOW_BATTERY =
      3;


      /**
       * This message is part of the Quix controller API.
       * This message is used to notify the crutch display of some important system state that might otherwise be hard to recognize.
       */
      @TypeCode(type="controller_msgs::msg::dds_::QuixUrgentUserInfoMessage_")
      struct QuixUrgentUserInfoMessage
      {
        unsigned long sequence_id;
        octet urgent_user_info_name;
      };
    };
  };
};

#endif
