#ifndef __controller_msgs__msg__ReinitializeStateEstimatorMessage__idl__
#define __controller_msgs__msg__ReinitializeStateEstimatorMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       * This message is used to request an initialization fo the state estimator.
       */
      @TypeCode(type="controller_msgs::msg::dds_::ReinitializeStateEstimatorMessage_")
      struct ReinitializeStateEstimatorMessage
      {
        boolean request_reinitialize;
      };
    };
  };
};

#endif
