#ifndef __controller_msgs__msg__RLModelSelectionMessage__idl__
#define __controller_msgs__msg__RLModelSelectionMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message represents the command to switch to a desired policy
       */
      @TypeCode(type="controller_msgs::msg::dds_::RLModelSelectionMessage_")
      struct RLModelSelectionMessage
      {
        /**
         * Desired model to be used, wrt array position
         */
        octet desired_model;
        boolean execute_desired_model;
      };
    };
  };
};

#endif
