#ifndef __controller_msgs__msg__RLPolicyState__idl__
#define __controller_msgs__msg__RLPolicyState__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message represents the current policy and available policies for RL
       */
      @TypeCode(type="controller_msgs::msg::dds_::RLPolicyState_")
      struct RLPolicyState
      {
        /**
         * Current model being used, wrt array of available models
         */
        octet current_model;
        /**
         * Array of available models to choose from, with the number of models in the array
         */
        octet num_available_models;
        sequence<string, 16> available_models;
      };
    };
  };
};

#endif
