#ifndef __controller_msgs__msg__SakeHandDesiredCommandMessage__idl__
#define __controller_msgs__msg__SakeHandDesiredCommandMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * Message for commanding the Sake hands to perform various predefined grasps.
       * Also allows for custom grasps with set positions/torques
       */
      @TypeCode(type="controller_msgs::msg::dds_::SakeHandDesiredCommandMessage_")
      struct SakeHandDesiredCommandMessage
      {
        /**
         * Specifies the side of the robot of the hand being referred to
         */
        @defaultValue(value=255)
        octet robot_side;
        /**
         * Request the gripper to perform a calibration sequence
         */
        boolean request_calibration;
        /**
         * Request to reset the gripper error state after overheating
         */
        boolean request_reset_errors;
        /**
         * The desired dynamixel position, in radians
         */
        double gripper_desired_position;
        /**
         * The dynamixel torque limit setting in achieving the desired position
         * 0: dynamixel will not apply any force and will not achieve desired position
         * 300: A reasonable normal value
         * 1023: dynamixel max torque which will quickly overheat the motor
         */
        long raw_gripper_torque_limit;
        /**
         * Keeping the torque off when not needed can help keep the hand's temperature down
         */
        boolean torque_on;
      };
    };
  };
};

#endif
