#ifndef __controller_msgs__msg__SakeHandStatusMessage__idl__
#define __controller_msgs__msg__SakeHandStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * Message used to report the current joint angles for the fingers of the sake gripper.
       */
      @TypeCode(type="controller_msgs::msg::dds_::SakeHandStatusMessage_")
      struct SakeHandStatusMessage
      {
        /**
         * Specifies the side of the robot of the hand being referred to
         */
        @defaultValue(value=255)
        octet robot_side;
        double temperature;
        /**
         * The current dynamixel position, normalized to the gripper range of motion
         * 0.0 (fingers touching) -> 1.0 (open 210 degrees between fingers)
         */
        double normalized_current_position;
        /**
         * The current dynamixel torque
         * 0.0: dynamixel will not apply any force and will not achieve desired position
         * 0.3: A reasonable normal value
         * 1.0: dynamixel max torque which will quickly overheat the motor
         */
        double normalized_current_torque;
        double normalized_desired_position;
        double normalized_torque_limit;
        boolean is_calibrated;
        boolean needs_reset;
      };
    };
  };
};

#endif
