#ifndef __controller_msgs__msg__SCSListenerPacket__idl__
#define __controller_msgs__msg__SCSListenerPacket__idl__

#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of IHMC Simulation Construction Set.
       * Notifies the user when the simulation has stopped.
       */
      @TypeCode(type="controller_msgs::msg::dds_::SCSListenerPacket_")
      struct SCSListenerPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        @defaultValue(value=True)
        boolean is_stopped;
      };
    };
  };
};

#endif
