#ifndef __controller_msgs__msg__SimpleCoactiveBehaviorDataPacket__idl__
#define __controller_msgs__msg__SimpleCoactiveBehaviorDataPacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC humanoid behavior module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::SimpleCoactiveBehaviorDataPacket_")
      struct SimpleCoactiveBehaviorDataPacket
      {
        string key;
        double value;
      };
    };
  };
};

#endif
