#ifndef __controller_msgs__msg__SimulatedLidarScanPacket__idl__
#define __controller_msgs__msg__SimulatedLidarScanPacket__idl__

#include "controller_msgs/msg/./LidarScanParametersMessage_.idl"
#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::SimulatedLidarScanPacket_")
      struct SimulatedLidarScanPacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        sequence<float> ranges;
        long sensor_id;
        controller_msgs::msg::dds::LidarScanParametersMessage lidar_scan_parameters;
      };
    };
  };
};

#endif
