#ifndef __controller_msgs__msg__SpatialVectorMessage__idl__
#define __controller_msgs__msg__SpatialVectorMessage__idl__

#include "geometry_msgs/msg/./Vector3_.idl"
#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Represents a 6D vector composed of a 3D anuglar vector and a 3D linear vector.
       */
      @TypeCode(type="controller_msgs::msg::dds_::SpatialVectorMessage_")
      struct SpatialVectorMessage
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        geometry_msgs::msg::dds::Vector3 angular_part;
        geometry_msgs::msg::dds::Vector3 linear_part;
      };
    };
  };
};

#endif
