#ifndef __controller_msgs__msg__StereoVisionPointCloudMessage__idl__
#define __controller_msgs__msg__StereoVisionPointCloudMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Should disappear for the ROS equivalent.
       */
      @TypeCode(type="controller_msgs::msg::dds_::StereoVisionPointCloudMessage_")
      struct StereoVisionPointCloudMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        long long robot_timestamp;
        sequence<float, 600000> point_cloud;
        sequence<long, 200000> colors;
      };
    };
  };
};

#endif
