#ifndef __controller_msgs__msg__StereoVisionPointCloudMessage__idl__
#define __controller_msgs__msg__StereoVisionPointCloudMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Should disappear for the ROS equivalent.
       */
      @TypeCode(type="controller_msgs::msg::dds_::StereoVisionPointCloudMessage_")
      struct StereoVisionPointCloudMessage
      {
        long long robot_timestamp;
        sequence<float> point_cloud;
        sequence<long> colors;
      };
    };
  };
};

#endif
