#ifndef __controller_msgs__msg__TriggerKickMessage__idl__
#define __controller_msgs__msg__TriggerKickMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      const octet ROBOT_SIDE_LEFT =
      0;

      const octet ROBOT_SIDE_RIGHT =
      1;


      /**
       * This message is part of the IHMC whole-body controller API.
       * This message is used to trigger a donkey (back) kick. The robot should be in an appropriate position to execute the kick.
       */
      @TypeCode(type="controller_msgs::msg::dds_::TriggerKickMessage_")
      struct TriggerKickMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Specifies the side of the robot that will execute the kick.
         */
        octet robot_side;
        /**
         * The height at which the kick should be targeted.
         */
        double kick_height;
        /**
         * The impulse with which the kick should be executed.
         */
        double kick_impulse;
        /**
         * The target distance from the robot to where the kick should be aimed.
         */
        double kick_target_distance;
        /**
         * A boolean for tracking whether a kick has been requested.
         */
        boolean trigger_kick_request;
        /**
         * Weight distribution before the kick. 1.0 means all weight on the kicking foot. Default is 0.5.
         */
        double prekick_weight_distribution;
      };
    };
  };
};

#endif
