#ifndef __controller_msgs__msg__TriggerKickMessage__idl__
#define __controller_msgs__msg__TriggerKickMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       * This message is used to trigger a donkey (back) kick. The robot should be in an appropriate position to execute the kick.
       */
      @TypeCode(type="controller_msgs::msg::dds_::TriggerKickMessage_")
      struct TriggerKickMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
      };
    };
  };
};

#endif
