#ifndef __controller_msgs__msg__UIConnectedPacket__idl__
#define __controller_msgs__msg__UIConnectedPacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::UIConnectedPacket_")
      struct UIConnectedPacket
      {
        boolean unused_placeholder_field;
      };
    };
  };
};

#endif
