#ifndef __controller_msgs__msg__ValkyrieFootstepPlanningStatus__idl__
#define __controller_msgs__msg__ValkyrieFootstepPlanningStatus__idl__

#include "controller_msgs/msg/./FootstepDataListMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {
      /**
       * Planner is actively planning. If any other status is indicated, the planner has terminated
       */
      const octet STATUS_PLANNING =
      0;

      /**
       * A solution was found that reaches the goal
       */
      const octet STATUS_FOUND_SOLUTION =
      1;

      /**
       * The timeout was reached and the planner did not find valid solution
       */
      const octet STATUS_TIMED_OUT =
      2;

      /**
       * Planner exhaustively searched all possibilities and could not find a plan
       */
      const octet STATUS_NO_SOLUTION_EXISTS =
      3;

      /**
       * The goal steps in the request packet are not valid
       */
      const octet STATUS_INVALID_GOAL =
      4;


      @TypeCode(type="controller_msgs::msg::dds_::ValkyrieFootstepPlanningStatus_")
      struct ValkyrieFootstepPlanningStatus
      {
        /**
         * ID that matches the plan_id of the active request packet
         */
        @defaultValue(value=-1)
        long plan_id;
        /**
         * Current planner status
         */
        @defaultValue(value=255)
        octet planner_status;
        /**
         * Contains the current best solution, i.e. lowest cost + heuristic
         * If the planner found a solution, this contains the solution path
         */
        controller_msgs::msg::dds::FootstepDataListMessage footstep_data_list;
      };
    };
  };
};

#endif
