#ifndef __controller_msgs__msg__ValkyrieFootstepPlanningActionPacket__idl__
#define __controller_msgs__msg__ValkyrieFootstepPlanningActionPacket__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      /**
       * Halts active plan
       */
      const octet PLANNING_ACTION_HALT =
      0;

      /**
       * Returns default planner parameters
       */
      const octet PLANNING_ACTION_REQUEST_PARAMETERS =
      1;


      @TypeCode(type="controller_msgs::msg::dds_::ValkyrieFootstepPlanningActionPacket_")
      struct ValkyrieFootstepPlanningActionPacket
      {
        @defaultValue(value=255)
        octet planner_action;
      };
    };
  };
};

#endif
