#ifndef __controller_msgs__msg__VehiclePosePacket__idl__
#define __controller_msgs__msg__VehiclePosePacket__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Quaternion_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      @TypeCode(type="controller_msgs::msg::dds_::VehiclePosePacket_")
      struct VehiclePosePacket
      {
        /**
         * Old message used for the VRC? Needs to be revised, maybe deleted?
         */
        geometry_msgs::msg::dds::Point position;
        geometry_msgs::msg::dds::Quaternion orientation;
        long index;
      };
    };
  };
};

#endif
