#ifndef __controller_msgs__msg__VehiclePosePacket__idl__
#define __controller_msgs__msg__VehiclePosePacket__idl__

#include "geometry_msgs/msg/./Point_.idl"
#include "geometry_msgs/msg/./Quaternion_.idl"
#include "std_msgs/msg/./Header_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * Old message used for the VRC? Needs to be revised, maybe deleted?
       */
      @TypeCode(type="controller_msgs::msg::dds_::VehiclePosePacket_")
      struct VehiclePosePacket
      {
        /**
         * As of March 2018, the header for this message is only use for its sequence ID.
         */
        std_msgs::msg::dds::Header header;
        geometry_msgs::msg::dds::Point position;
        geometry_msgs::msg::dds::Quaternion orientation;
        long index;
      };
    };
  };
};

#endif
