#ifndef __controller_msgs__msg__VisibilityMapMessage__idl__
#define __controller_msgs__msg__VisibilityMapMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC footstep planning module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::VisibilityMapMessage_")
      struct VisibilityMapMessage
      {
        /**
         * unique id of the map
         */
        unsigned long map_id;
        /**
         * start point for the connection
         */
        sequence<geometry_msgs::msg::dds::Point> source_points;
        /**
         * target point for the connection
         */
        sequence<geometry_msgs::msg::dds::Point> target_points;
      };
    };
  };
};

#endif
