#ifndef __controller_msgs__msg__VisibilityMapWithNavigableRegionMessage__idl__
#define __controller_msgs__msg__VisibilityMapWithNavigableRegionMessage__idl__

#include "controller_msgs/msg/./PlanarRegionMessage_.idl"
#include "controller_msgs/msg/./VisibilityClusterMessage_.idl"
#include "controller_msgs/msg/./VisibilityMapMessage_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC footstep planning module.
       */
      @TypeCode(type="controller_msgs::msg::dds_::VisibilityMapWithNavigableRegionMessage_")
      struct VisibilityMapWithNavigableRegionMessage
      {
        controller_msgs::msg::dds::PlanarRegionMessage home_region;
        controller_msgs::msg::dds::VisibilityClusterMessage home_region_cluster;
        controller_msgs::msg::dds::VisibilityMapMessage visibility_map_in_world;
        sequence<controller_msgs::msg::dds::VisibilityClusterMessage, 25> obstacle_clusters;
      };
    };
  };
};

#endif
