#ifndef __controller_msgs__msg__WalkingControllerFailureStatusMessage__idl__
#define __controller_msgs__msg__WalkingControllerFailureStatusMessage__idl__

#include "geometry_msgs/msg/./Vector3_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC whole-body controller API.
       * The controller will send this message when detecting a fall.
       */
      @TypeCode(type="controller_msgs::msg::dds_::WalkingControllerFailureStatusMessage_")
      struct WalkingControllerFailureStatusMessage
      {
        /**
         * Specifies the estimated falling direction in 2D
         */
        geometry_msgs::msg::dds::Vector3 falling_direction;
      };
    };
  };
};

#endif
