#ifndef __controller_msgs__msg__WalkingStatusMessage__idl__
#define __controller_msgs__msg__WalkingStatusMessage__idl__

module controller_msgs
{
  module msg
  {
    module dds
    {
      /**
       * The robot has begun its initial transfer/sway at the start of a walking plan.
       */
      const octet STARTED =
      0;

      /**
       * The robot has finished its final transfer/sway at the end of a walking plan.
       */
      const octet COMPLETED =
      1;

      /**
       * A walking abort has been requested by the controller.
       */
      const octet ABORT_REQUESTED =
      2;

      /**
       * The robot is back to standing on a break waiting for either an un-pause command or new footsteps.
       */
      const octet PAUSED =
      3;

      /**
       * The robot is resuming the series of footsteps that were paused.
       */
      const octet RESUMED =
      4;


      /**
       * This message is part of the IHMC whole-body controller API.
       * The controller sends this message to notify the user of the status of walking.
       */
      @TypeCode(type="controller_msgs::msg::dds_::WalkingStatusMessage_")
      struct WalkingStatusMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Status of walking.
         */
        @defaultValue(value=255)
        octet walking_status;
      };
    };
  };
};

#endif
