#ifndef __controller_msgs__msg__WholeBodyContactStateMessage__idl__
#define __controller_msgs__msg__WholeBodyContactStateMessage__idl__

#include "geometry_msgs/msg/./Point_.idl"
module controller_msgs
{
  module msg
  {
    module dds
    {

      /**
       * This message is part of the IHMC multi-contact controller API.
       */
      @TypeCode(type="controller_msgs::msg::dds_::WholeBodyContactStateMessage_")
      struct WholeBodyContactStateMessage
      {
        /**
         * Unique ID used to identify this message, should preferably be consecutively increasing.
         */
        unsigned long sequence_id;
        /**
         * Hash codes of contacting bodies
         */
        sequence<long> contacting_bodies_hash_codes;
        /**
         * List of contact positions for each rigid body, expressed in RigidBody.getParentJoint().getFrameAfterJoint()
         */
        sequence<geometry_msgs::msg::dds::Point> contact_point_positions;
      };
    };
  };
};

#endif
