package us.ihmc.footstepPlanning;

import us.ihmc.tools.property.*;

/**
 * The JSON file for this property set is located here:
 * ihmc-footstep-planning/src/main/resources/us/ihmc/footstepPlanning/MonteCarloFootstepPlannerParameters.json
 *
 * This class was auto generated. Property attributes must be edited in the JSON file,
 * after which this class should be regenerated by running the main. This class uses
 * the generator to assist in the addition, removal, and modification of property keys.
 * It is permissible to forgo these benefits and abandon the generator, in which case
 * you should also move it from the generated-java folder to the java folder.
 *
 * If the constant paths have changed, change them in this file and run the main to regenerate.
 */
public class MonteCarloFootstepPlannerParameters extends StoredPropertySet implements MonteCarloFootstepPlannerParametersBasics
{
   public static final StoredPropertyKeyList keys = new StoredPropertyKeyList();

   public static final IntegerStoredPropertyKey numberOfIterations = keys.addIntegerKey("Number of iterations");
   public static final IntegerStoredPropertyKey numberOfSimulations = keys.addIntegerKey("Number of simulations");
   public static final DoubleStoredPropertyKey timeoutDuration = keys.addDoubleKey("Timeout duration");

   /**
    * Loads this property set.
    */
   public MonteCarloFootstepPlannerParameters()
   {
      this("");
   }

   /**
    * Loads an alternate version of this property set in the same folder.
    */
   public MonteCarloFootstepPlannerParameters(String versionSuffix)
   {
      this(MonteCarloFootstepPlannerParameters.class, versionSuffix);
   }

   /**
    * Loads an alternate version of this property set in other folders.
    */
   public MonteCarloFootstepPlannerParameters(Class<?> classForLoading, String versionSuffix)
   {
      super(keys, classForLoading, MonteCarloFootstepPlannerParameters.class, versionSuffix);
      load();
   }

   public MonteCarloFootstepPlannerParameters(StoredPropertySetReadOnly other)
   {
      super(keys, MonteCarloFootstepPlannerParameters.class, other.getCurrentVersionSuffix());
      set(other);
   }

   public static void main(String[] args)
   {
      StoredPropertySet parameters = new StoredPropertySet(keys, MonteCarloFootstepPlannerParameters.class);
      parameters.generateJavaFiles();
   }
}
