package control_msgs;

public interface PointHeadActionFeedback extends org.ros.internal.message.Message {
  static final java.lang.String _TYPE = "control_msgs/PointHeadActionFeedback";
  static final java.lang.String _DEFINITION = "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\nHeader header\nactionlib_msgs/GoalStatus status\nPointHeadFeedback feedback\n";
  std_msgs.Header getHeader();
  void setHeader(std_msgs.Header value);
  actionlib_msgs.GoalStatus getStatus();
  void setStatus(actionlib_msgs.GoalStatus value);
  control_msgs.PointHeadFeedback getFeedback();
  void setFeedback(control_msgs.PointHeadFeedback value);
}
